### ISSUE TITLE
getShortestPaths doesn't include states guarded by conditions

### ISSUE THREAD

**Issue by MicheleBertoli** [davidkpiano/xstate#100]
Follows the discussion in [#49](https://github.com/MicheleBertoli/react-automata/issues/49).

## Description:

When a state is guarded by a condition, `getShortestPaths` doesn't include it in the array of paths.

For example:

```js
const statechart = {
  initial: 'a',
  states: {
    a: {
      on: {
        EVENT: {
          b: {
            cond: extState => extState.shouldPass,
          },
        },
      },
    },
    b: {},
  },
}
const machine = Machine(statechart)
const paths = getShortestPaths(machine)
```

## Expected result:

```js
// { '"a"': [{ state: 'b', event: 'EVENT' }] }
```

## Actual result:

```js
// { '"a"': [] }
```

## Potential fix:

A potential fix could be adding a second `extendedState` parameter to `getShortestPaths` so that the returned paths take into account the state and the conditions are evaluated.

Alternatively, the output could include the condition as well:

```js
// { '"a"': [{ state: 'b', event: 'EVENT', cond: ??? }] }
```

**Comment by MicheleBertoli** [comment]
💯

**Comment by hally9k** [comment]
@davidkpiano - Should we open a seperate issue for the afore mentioned challenge?

**Comment by davidkpiano** [comment]
Yes, please.

**Comment by PickleyD** [comment]
Was a separate issue raised for the above? Unable to find it

**Comment by Nickersoft** [comment]
Just ran into this as well – was this ever fully addressed?
