### ISSUE TITLE
Highlight transition line on hover in visualizer

### ISSUE THREAD

**Issue by Nohac** [davidkpiano/xstate#1009]
**Description**
If there are a lot of transitions overlapping in the visualizer, it's impossible to know where the transition ends up. It would be nice if the transition line would be highlighted on mouse hover.

![states](https://i.imgur.com/Gthfszs.png)

**Comment by davidkpiano** [comment]
This will be fixed in the next update.

**Comment by davidkpiano** [comment]
Closing as the visualizer is being redone.
