### ISSUE TITLE
Suggestion about tools that could help

### ISSUE THREAD

**Issue by sneko** [davidkpiano/xstate#101]
Hi @davidkpiano!

I was watching some of your videos because I was trying to find a library to manage routing in Vue.js through Finite State Machines. For now, I didn't find a good and maintained one that would be well-integrated to this framework but I keep looking for.

On the other hand, I wanted to tell you that I already used statecharts through JS apps. And I have some suggestions that could help you:

- I was using Qt Creator with their SCXML plugin to define grafically my statecharts. That's free :)
- Then, I was able to export this file as SCXML one
- I was using the SCION library in JavaScript to parse the SCXML and broadcast events inside my FSM (https://github.com/jbeard4/SCION)

I don't know if you have heard about these tools or if it's too late to integrate SCION in xstate... but I hope it will be useful to your progress.

Thomas

EDIT: Note that both tools are managing nested states, history... They are really powerful 😀

**Comment by davidkpiano** [comment]
Hey @sneko - SCXML compatibility and integration is what we're currently working on - and it's almost done!

When that's done, you'll be able to use Qt Creator the exact same way with `xstate`, or any other tools that work with SCXML.

There are many key differences between SCION and `xstate` however, including the representation of states (hierarchical object-based vs. arrays), and that `xstate` is meant to be a _superset_ of SCXML - we plan to support more than just core SCXML functionality, but also other ideas discussed in the original paper, such as parametric states and activities.

Also, `xstate` is meant to be interpreter-agnostic, leaving you to use any interpreter you desire, or make your own.

So keep a lookout for SCXML compatibility 🔜 !
