### ISSUE TITLE
Can't get pure() actions to work

### ISSUE THREAD

**Issue by semopz** [davidkpiano/xstate#1014]
**Description**
Using `pure()` in xstate 4.7.8 seems to just throw errors or log warnings. Tried using it in event `actions` and state node `entry` and get the same result.

Got usage instructions from [a discussion](https://spectrum.chat/statecharts/general/conditional-raise-inside-a-declared-action~c4531b4c-b5f1-406f-9294-abce524660cb) that I didn't want to hijack.

**Expected Result**
When I return an `assign()` action from `pure()`, I expect the context to be updated accordingly.

**Actual Result**
Following warning is raised and context does not get updated:
>Warning: No implementation found for action type 'xstate.assign' 

**Reproduction**
https://codesandbox.io/s/xstate-typescript-template-qzzhm
**Additional context**
 xstate 4.7.8

**Comment by davidkpiano** [comment]
Please keep in mind that `pure()` is still being developed and not part of public API yet. I'll look into this.

**Comment by Andarist** [comment]
Seems like the problem is that returned actions from `pure` are not resolved. It should be an easy fix.

**Comment by davidkpiano** [comment]
Cannot reproduce with latest XState (4.16.2)
