### ISSUE TITLE
es modules/web versions of @xstate/test & @xstate/graph

### ISSUE THREAD

**Issue by ZempTime** [davidkpiano/xstate#1025]
**Description**
Would like es/web exports for `@xstate/graph` and `@xstate/test` so I could:

```
import { createModel } from "@xstate/test";
```

**Expected Result**
I expected to be able to pull these in without needing to modify testing config.

**Actual Result**
<img width="1542" alt="Screen Shot 2020-02-25 at 9 40 32 AM" src="https://user-images.githubusercontent.com/3596468/75262967-ea9a5700-57b2-11ea-87c5-60bdd94ff9c1.png">

**Reproduction**
You can see the exact replication/setup here:
* https://github.com/ZempTime/dwight-job-application
* `yarn && yarn test`

**Comment by davidkpiano** [comment]
I would accept a PR for this, if you could 🙏

**Comment by ZempTime** [comment]
I got graph building on a local branch. How should I handle the shared config across packages? cc @Andarist . Here's a list of approaches I can think of:

* Keep it in root of monorepo & pull it in
* Separate it out into it's own package [example](https://github.com/open-wc/open-wc/tree/master/packages/building-rollup)
* duplicate across all places (core, graph, test)

Would one of these be preferred, or would something else work better?

**Comment by Andarist** [comment]
For now, just duplicate it. V5 branch has already a completely new build setup using [preconstruct](http://preconstruct.tools/), so most likely your work will be removed (sorry!) when we merge back master to the next branch - that setup should have it already covered. 

Are you interested purely in ESM builds or do you want to consume them somehow in browsers **without** a bundler?

**Comment by ZempTime** [comment]
Will do. I'm mainly interested in ESM builds. However, I do on occasion go straight to the browser without a bundler, but never for real production. That'd get occasional use from me, but it's certainly not something I'd genuinely request.
