### ISSUE TITLE
xstate/fsm: state.changed is undefined when service first starts

### ISSUE THREAD

**Issue by mreinstein** [davidkpiano/xstate#1029]
Setup code:

```javascript
const m = createMachine({
  initialState: 'init',
  ...rest of  typical machine definition here ...
})
const s = interpret(m).start()

s.subscribe(state => {
        console.log('state:', state.value, ' changed:', state.changed);
})

setTimeout(function () {  s.send('SOME_EVENT') }, 2000)
```

I see this in the console:
```
state: init   changed: undefined
state: init   changed: false

// 2 seconds-ish later:
state: some_new_state   changed: true

**Comment by mreinstein** [comment]
I'm thinking this is related to #826 , like we're not setting the changed value as expected when we run the initial state's entry callback

**Comment by davidkpiano** [comment]
This is expected. The very first state can't be considered changed or unchanged from some previous state (which does not exist)... and `undefined` represents that it does not exist.

**Comment by davidkpiano** [comment]
Although... are you seeing two `init` updates in the console? Can you share a reproducible code example? That might be a different bug.

**Comment by mreinstein** [comment]
> are you seeing two init updates in the console

It's possible I mangled the example in my attempt to keep the setup code as simple as possible.

I'll construct a working example right now to validate that this extra `init` update is really happening. I'll post here with whatever I find.

**Comment by mreinstein** [comment]
test.js
```javascript
import { createMachine, interpret } from '@xstate/fsm'


const m = createMachine({
    initial: 'uninitialized',
    states: {
        uninitialized: {
                entry: function () {
                        console.log('I run :) ')
                },
                on: {
                  SOME_EVENT: 'some_new_state'
                }
        },
        some_new_state: {  }
    }
})

const s = interpret(m).start()


s.subscribe(state => {
        console.log('state:', state.value, ' changed:', state.changed)
})

setTimeout(function () {  s.send('SOME_EVENT') }, 2000)
```

output:
```bash
➜ node -r esm test.js
I run :)
state: uninitialized  changed: undefined
state: some_new_state  changed: true
➜
```

looks right to me! I must have mangled the example. Sorry about that!
