### ISSUE TITLE
Complex typing

### ISSUE THREAD

**Issue by madsbuch** [davidkpiano/xstate#1034]
**Description**
After integrating xstate into our project we have experienced a quite significant editor slowdown. After having upgraded to typescript version 3.8.2 we have also started to get type erros / warnings about these matters.

![Screenshot from 2020-02-28 12-00-32](https://user-images.githubusercontent.com/1612807/75583339-34d53f80-5a22-11ea-9a46-e63fc0aa4d74.png)

**Expected Result**
We would, ideally, expect no difference to the editor / compilation speed.

**Actual Result**
Slowdown to the editor.

**Reproduction**
To come, currently this is meant as a heads up and a chance to discuss typing.

**Additional context**

* `"skipLibCheck": true`
* Visual Studio Code 
* Typescript 3.8.2

We use xstate in a reasonably sized application. Developer productivity is a concern, and it seems that typescript has been a bit too liberal on the type constructs they allow with speed as the trade off.

We use other libraries (cough, style components) that also expose complex type constructions. Individually, this might not be a problem, but it doesn't take many of these libraries to impact the overall editor experience.

**Comment by davidkpiano** [comment]
Thanks for reporting. We're currently working on V5 and types will be overhauled and simplified, which should (hopefully) mitigate these issues. Using `skipLibCheck: true` is a good idea.

Also, it seems that others downgrading TS to an earlier 3.7.* version alleviated the problem, as a workaround.

For reference, TypeScript has an arbitrary limit (50 I believe) for recursive types, which causes this error. https://stackoverflow.com/questions/60265325/using-recursive-type-alias-in-generic-results-in-error

**Comment by davidkpiano** [comment]
We'll track this here: https://github.com/davidkpiano/xstate/issues/1015#issuecomment-592508668
