### ISSUE TITLE
Feature request: conditional action (qol)

### ISSUE THREAD

**Issue by MrNovado** [davidkpiano/xstate#1036]
# Request

Now, I know there are conditions and actions already, but the thing is they might be really awkward to use when in order to check a condition you have to make the same'ish amount of work needed to make an action. 

Like, for an actor in a game, in order to make a proper move, you'll have to find a desirable spot first and then check if it's free to move to, concluding the conditional check. But since actions are decoupled from conditions, you will have to find a desirable spot again (which we already did, but the action has no clue about, and we couldn't buffer our findings anywhere) and then message a parent with the selected spot.

**TL;DR**: Actions and conditions are decoupled, making it awkward to use them sometimes. Additionally, conditional-guards could not be used to restrict the context of execution (with typescript) in any way, leaving the action completely clue-less about the current state, forcing it to recalculate and re-check everything anew.

What I'm asking here is maybe just a sugar-coating/optimization for an already existing feature.
I imagine it looking something like that:
```javascript
on: {
    "": [
       { target: "x", condAction: (context) => context?.x ? send({ type: "x", x: context.x }) : false  },
       { target: "y", condAction: (context) => context?.y ? sendParent({ type: "y", y: context.y }) : false  },
       { target: "z", condAction: (context) => context?.z ? assign({ z: context.z + 1 }) : false  },
       ...
    ]
}
```

Basically, conditional-action-expression returns `action | false`.
The addition of this feature should not produce any breaking changes. This is purely QoL.

# Example

I've been tinkering with the tic-tac-toe game for a while now:
https://github.com/MrNovado/xstate-playground/tree/master/src/feature/TicTacToe
https://mrnovado.github.io/xstate-playground/#/x-tictactoe

And one of my actors has this list of transitions:
https://github.com/MrNovado/xstate-playground/blob/master/src/feature/TicTacToe/Actor.declarative.ts#L162
```javascript
PLAY: [
  {
    // 1. Win: If the player has two in a row,
    // they can place a third to get three in a row.
    actions: "win",
    cond: "checkMy2InARow",
  },
  {
    // 2. Block: If the opponent has two in a row,
    // the player must play the third themselves to block
    // the opponent.
    actions: "block",
    cond: "checkOpponent2InARow",
  },
  {
    // 3. Fork: Create an opportunity where the player
    // has two ways to win (two non-blocked lines of 2).
    actions: "fork",
    cond: "checkMyFork",
  },
...
]
```

Now, `fork` here is the heaviest amongst actions and requires us to find an intersection of 2 rows.
In order to check if such an intersection exists (`checkMyFork`):
- we have to find all rows/columns/diagonals, with only our symbol in one of their cells
- find the first intersection, which should be a non-taken spot

If such an intersection does not exist for us - we'll move further down the list of available tactics.
But if such an intersection does indeed exists, - we'll transition to an action `fork` where we must do the same work finding an intersection all over again.

Of course, there is a workaround for that. You may try to remodel your state in such a way, so you store the result of a condition in a buffer first and __then__ you check on them.
https://github.com/MrNovado/xstate-playground/blob/master/src/feature/TicTacToe/Actor.declarative.2.ts#L143

Which will look something like this:
```javascript
context: {
    buffer:
        | null
        | { type: "win"; combination: number[] }
        | { type: "blockWin"; combination: number[] }
        | { type: "fork"; intersection: number }
        | { type: "blockFork"; intersection: number }
        | { type: "takeCenter" }
        | { type: "takeOppositeCornter"; corner: number }
        | { type: "takeCorner" }
        | { type: "takeEmptySide" };
},
...,
fork: {
  id: "fork",
  initial: "check",
  states: {
    check: {
      entry: "assignMyFork",
      on: {
        "": [
          {
            cond: ({ buffer }) => buffer ? .type === "fork",
            target: "act",
          },
          {
            target: "#blockFork",
          },
        ],
      },
    },
    act: {
      on: {
        "": {
          target: "#awaitingTurn",
          actions: "fork",
        },
      },
    },
  },
},
```
Instead of making the same work twice, only `assignMyFork` now makes the needed computation.
Which works, but actions now have to reason about the buffer in order to make a message:
https://github.com/MrNovado/xstate-playground/blob/master/src/feature/TicTacToe/Actor.declarative.2.ts#L284
```javascript
fork: sendParent(({ buffer }: DeclarativePerfectActorContext) => {
  switch (buffer?.type) {
    case "fork": {
      return {
        type: "TURN_MADE",
        selectedIndex: buffer.intersection,
      };
    }
    default:
      return {
        type: "UNKNOWN_STATE",
          origin: "declarativePerfectActor2",
          message: "fork is invoked, but buffer is not there!",
      };
  }
}, DELAY),
```

If only there was a way to restrict the context, make a condition-check and plan an action all in one go.

Thoughts?

---

P.S. I absolutely LOVE and ADORE this tool, but its API (especially when it comes to TS) feels underbaked. `spawn` and `sendParent` type-definitions seems completely broken at the moment (there are already issues for that though if I remember correctly). I would very much hope for a much more restrictive and opinionated API, which will not let you make a mistake, but currently, type-inference is all over the place. Still, even with just JS, this tool is a huge help with almost anything. Thank you!

**Comment by davidkpiano** [comment]
Thanks! Yeah, the typing can be stronger - a lot of the things we do in XState push the limit of TypeScript (we need dependent types!) but version 5 will simplify and restrict the types so that the TS experience is better.

I'm going to merge this issue with the pre-existing request: https://github.com/davidkpiano/xstate/issues/990

In short, conditional actions are a good idea, SCXML-compatible, and will be supported, either in 4.8 or 5.0.
