### ISSUE TITLE
[Feature] Add 'target' to send actions

### ISSUE THREAD

**Issue by mpolichette** [davidkpiano/xstate#105]
## Bug or feature request?
Feature Request
## Description:

SCXML specifies an attribute `target` on send events.  
> The unique identifier of the message target that the platform should send the event to. See 6.2.4 The Target of Send for details.

I find this especially useful for reusable state charts or parallel machines (or even specifying specific targets for reusable send actions).

## Potential implementation:
This is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)
Changes are very minimal:
1. add an additional argument to [`SendAction`](https://github.com/davidkpiano/xstate/blob/master/src/types.ts#L193) and [`SendActionOptions`](https://github.com/davidkpiano/xstate/blob/master/src/types.ts#L198) and 
2. Make sure to pass it through in the [send action](https://github.com/davidkpiano/xstate/blob/master/src/actions.ts#L84) definition.
```javascript
import { actions } from 'xstate';
// ...
actions.send('someEvent', {  target: 'someTarget' })
//
// {
//   type: 'xstate.send',
//   event: { type: 'someEvent' },
//   target: 'someTarget'
// }
```

**Comment by davidkpiano** [comment]
I think this is a good idea and `xstate` can handle whether the event should be handled or not, based on the `target`.

One thing I'd change is that the target should always be an ID, since it's not relative to anything, so `{ target: '#someTarget' }`.

Also for SCXML's `targetexpr` we can support:

```js
target: (fullState, event) => {
  // return an ID
}
```

**Comment by mpolichette** [comment]
Hmm... I'm not sure I follow.   

My understanding is that an `action.target` is not necessarily a StateNode... even in the [SCXML docs](https://www.w3.org/TR/scxml/#SendTargets) it seems like targets could be *anything* 
> In most cases, the format of the target depends on the type of the target  ...

In my case, I want to use action targets to identify an external service.

**Comment by davidkpiano** [comment]
Ah okay, that makes sense. So it's just metadata then?

**Comment by mpolichette** [comment]
Hah, yes, for my need I think that would work fine... are those semantics right?  

Just checking my understanding... would something like what I described be a `event.target` or an `action.target` in state chart land?

In my case, the metadata approach would work fine, I'd feel free to close the issue w/ that resolution.

**Comment by davidkpiano** [comment]
The event can have any metadata, so that's up to you. Same with actions. Both `.target`s are what you define it as.

But in SCXML, an event `target` would be an event intended for a particular statechart/state, to my understanding.

**Comment by davidkpiano** [comment]
This is now in `master` and will be released in 4.0. It is to be used in conjunction with the `invoke: ...` syntax.

**Comment by xlozinguez** [comment]
@davidkpiano it seems the typing doesn't allow for this second options argument in the send method... I'll look into it and eventually publish a PR once I confirm

**Comment by davidkpiano** [comment]
This only refers to the `send(...)` action creator (pure function), not the `interpreter.send(...)` dispatcher (impure method).

**Comment by xlozinguez** [comment]
oh that makes more sense. Thanks for clarifying! It was quite late when I was attempting this 😁
