### ISSUE TITLE
Todo example routing not working correctly

### ISSUE THREAD

**Issue by allforabit** [davidkpiano/xstate#1050]
**Description**
The example todo app doesn't restore it's router state correctly. 

**Expected Result**
The todo app should jump to the correct state after refreshing the page.

**Actual Result**
It just jumps to the initial `all` state, even if you are on one of the other routes (e.g. `complete`).

**Reproduction**
It can be seen in the linked code sandbox: https://codesandbox.io/s/xstate-todomvc-33wr94qv1 This page will not go to `completed` correctly: https://33wr94qv1.csb.app/#/completed

**Additional context**
I've fixed it here by firing an event on component load: https://codesandbox.io/s/xstate-todomvc-mhr7k. You can see it jumps to `completed` correctly: https://mhr7k.csb.app/#/completed

**Comment by davidkpiano** [comment]
Great, fixed! Thanks!
