### ISSUE TITLE
Invokes and entry actions not called when starting from an explicit state

### ISSUE THREAD

**Issue by knordman** [davidkpiano/xstate#1053]
**Description**
When a service is started from an explicit state, by passing that to the `start` interpreter method, e.g. `service.start("here-i-wanna-go")` or ` service.start(State.from("here-i-wanna-go"))` no entry actions or invokes are called. 

**Expected Result**
Entry actions and invokes called when starting from an explicit state. E.g. `service.start()` would be the same as passing `service.start('initial')` if `initial` is the initial state of the machine. 

**Actual Result**
Entry actions and invokes are not called. 

**Reproduction**
- [CodeSandbox](https://codesandbox.io/s/cold-forest-p5sjp)

**Additional context**
"xstate": "4.8.0"

**Comment by davidkpiano** [comment]
This might be an invalid use-case. The actions to execute (from `entry` etc.) should be present in the starting state passed to `.start(state)`. Here, you're just passing a state with _no_ actions.

If your use-case is rehydrating from a state, you should be saving the actual state observed, which does include those actions.

What is your use-case here?

**Comment by knordman** [comment]
Thanks for the reply. My use case is connected to rehydration. This is part of a node backend serivce: a microservice orchestrator taking as input a statechart and then executing the "pipeline" defined by that statechart. So far my "pipelines" are mostly sequential states using invokes and actions from a pre-defined "library": works great with the `withConfig` machine option. 

So what I'm trying to do is to start that pipeline from any state not just from the initial state. The typings for `start` indicate that `start` may also take a simple string, so yes that was my erroneous assumption that it would work like that. 

Is there any good way to create an initial state manually, or is the JSON format that one gets when persisting the state an internal format that may change?

**Comment by knordman** [comment]
I came to the conclusion that the best and simplest way to achieve what I want, is just to have a machine factory that can set the `initial` property of the machine as needed :slightly_smiling_face:
