### ISSUE TITLE
@xstate/react/lib/fsm missing TypeState support

### ISSUE THREAD

**Issue by osdiab** [davidkpiano/xstate#1059]
**Description**
It just sets the `TypeState` to `any`, which I didn't expect

**Expected Result**
Don't throw away the `TypeState` generic so that it can be used in the component without a typecast

**Actual Result**
`state.context` isn't narrowed by `value` because `useState` passes `any` as the typestate generic

**Reproduction**
- [CodeSandbox template (React)](https://codesandbox.io/s/competent-kirch-9vhgm)

**Comment by osdiab** [comment]
Additionally: the FSM implementation of `StateMachine.State` just sets `value: string`, which means that the typestate is ignored again and narrowing with the `useMachine` hook fails again.

**Comment by davidkpiano** [comment]
I'd accept a PR for this. cc. @Andarist

**Comment by Andarist** [comment]
`@xstate/react/lib/fsm` has exposed TS types. From what I understand this is about those types not working as expected - it's hard for me to relate to it because the provided repro case doesn't contain a faulty code (it refers to `xstate` and not `@xstate/fsm`). Could you prepare a one showcasing your issue?

**Comment by osdiab** [comment]
@Andarist oops looks like i needed to save or something to get it to reflect properly, is it good now?

https://codesandbox.io/s/competent-kirch-9vhgm

**Comment by Andarist** [comment]
I've prepared a fix for this: https://github.com/davidkpiano/xstate/pull/1061 . Keep in mind that to narrow down typestates you would have to use `.matches()`, you can't do that with a simple comparison of the `.value` property.
