### ISSUE TITLE
assign doesn't support ensuring Context matches TypeState

### ISSUE THREAD

**Issue by osdiab** [davidkpiano/xstate#1060]
**Description**
Currently xstate supports changing state in an action using `assign`. This works great, but it is implemented in a way that ensures that if you provided a `TypeState`, it may mutate the context in a way that defies the `TypeState` definition.

If you pass a callback to `assign`, it correctly provides a `TypeState`-narrowed version of `Context` as an argument based on the origin state, but because the callback assumes you want to do a partial merge to context, using `Partial<Ctx>` as the return type, it means that you can replace the context with a value that actually defies what the `TypeState` parameter says the shape of the object will be (it will accept any return value so long as it's `Partial<Ctx>` and merge it blindly).

**Expected Result**
That's fine for convenience but if I want to actually make sure my program is type safe, I'd like the return type of the assign function to constrain me to the shape of the destination `TypeState`.

@davidkpiano rightly pointed out that doing that with the partial merge syntax is probably impossible - which is because that behavior is inherently type-unsafe to begin with, blindly merging objects and hoping they match any arbitrary constraint on the context type.

So what that means is a syntax or alternative to `assign` that forces me to implement the transformation from the past context + event data to the next context, much like any normal reducer pattern / the `useState` hook would force me to do anyway.

So long as that "replace" version of `assign` forces a shape matching the proper `TypeState` (which should be easily parameterized given that the `on` block already has the destination state annotated), then I can get TypeScript to force me to provide a valid context value.

**Actual Result**
I can cause TypeScript to be mistyped with a bad assign, turning the type checker against me (debugging scenario: TypeScript says this value should be some type, so I trust it!! (little did I know that the types were lying, in fact it was something else and I'm sent the wrong direction debugging or stop trusting my TypeScript types)

**Reproduction**
Will do in a little bit

**Additional context**
I can force myself to do this by explicitly typing the return value of the `assign` callback to be the proper `TypeState` object, but it's wordy and repetitive to have to do that by hand every time.

**Comment by davidkpiano** [comment]
Moving this to a more general discussion, since this is not yet a feature of XState: https://github.com/davidkpiano/xstate/discussions/2322
