### ISSUE TITLE
Document that respond is in actions

### ISSUE THREAD

**Issue by knobo** [davidkpiano/xstate#1062]
**Description**
I don't know if this is intentional, but I had to get respond from actions.
``` js
import { Machine, assign, actions } from 'xstate';
const respond = actions.respond;
```
There was nothing about this in the docs.
From the docs I would expect that it would be possible to import respond directly from xstate.
Like this:
``` js
import { Machine, assign, respond } from 'xstate';
```

**Comment by davidkpiano** [comment]
Can you make a PR for this?

**Comment by knobo** [comment]
Should I add something more?

**Comment by knobo** [comment]
It is a bit confusing that some actions can be imported directly from `xstate`, but other has to come from `actions`

**Comment by davidkpiano** [comment]
> It is a bit confusing that some actions can be imported directly from xstate, but other has to come from actions

Most of these are intentional, but we'll fix `respond` coming from the main import instead.

In the future, action imports will look like:

```js
import { send, respond, log } from 'xstate/actions';
```
