### ISSUE TITLE
Typescript: support async function types in invoke service src

### ISSUE THREAD

**Issue by haywirez** [davidkpiano/xstate#1063]
As a follow up to #988, I think it'd be great to support `async` functions in invoke `src` types.

**Comment by Andarist** [comment]
Isnt `src: () => async function(){}` working already?

**Comment by davidkpiano** [comment]
> Isnt src: () => async function(){} working already?

I don't believe this works if the `async function` is a callback function rather than a promise.

**Comment by haywirez** [comment]
> > Isnt src: () => async function(){} working already?
> 
> I don't believe this works if the `async function` is a callback function rather than a promise.

Aren't all async functions promises?

**Comment by davidkpiano** [comment]
> Aren't all async functions promises?

No:

<img width="233" alt="Screen Shot 2020-03-15 at 11 58 46 AM" src="https://user-images.githubusercontent.com/1093738/76705163-600f8e00-66b4-11ea-9cfc-f025d72a4f34.png">

**Comment by Andarist** [comment]
Truth to be told - both works: https://codesandbox.io/s/determined-morse-nxm9j?file=/src/index.js , but the preferred way should be:
```js
asyncFn: async (context, event) => { /* implementation */ }
```

I also can't find any problem with TS in this regard:
https://codesandbox.io/s/small-glade-nbikr?file=/src/index.ts

@haywirez Could you prepare a repro case of your problem?

**Comment by davidkpiano** [comment]
Closing as this is supported.
