### ISSUE TITLE
Invoked child service not initialized correctly when used with useMachine

### ISSUE THREAD

**Issue by allforabit** [davidkpiano/xstate#1067]
**Description**
When using the `useMachine` hook to create a service in a parent component and then passing down an invoked child service (using `current.children`) the sub interpretor doesn't seem to be initialized correctly in all cases and so the `useService` hook in the sub component doesn't always work. This only happens if the invoked service is in the initial state of the parent machine. If it's in another state it works as expected.

**Expected Result**
The child component should be able to use the service by using `useService`.

**Actual Result**
The child component `useService` hook returns null for the current value instead of a state.

**Reproduction**

https://codesandbox.io/s/invoked-sub-machine-issue-v1gwl

**Comment by davidkpiano** [comment]
This is fixed in the latest XState and `@xstate/react` 1.0.0-rc3, which will be released soon. Please use those versions.

**Comment by allforabit** [comment]
Ah great thanks very much @davidkpiano!
