### ISSUE TITLE
`data` function is executed before machine enters final state.

### ISSUE THREAD

**Issue by RafalFilipek** [davidkpiano/xstate#1079]
**Description**
`data` function is executed before machine enters final state.

**Expected Result**
`data` function should be executed after machine enters final state.

**Reproduction**
https://codesandbox.io/s/vibrant-chandrasekhar-v8q61

**Additional context**
Maybe this behavior is expected. I'm trying to validate output data here. But it is impossible if this function is executed earlier.

Thanks

**Comment by RafalFilipek** [comment]
Is there any other way to send such data? Right now I have to fill whole context object to avoid errors while reading nested objects. 

Thanks

**Comment by Andarist** [comment]
Please be patient, you have opened your issue **yesterday** - we all have lives and are doing this in our free time, getting an answer might take a couple of days (and that's normal).

I'll look into this in the following days to see what's going on.

**Comment by RafalFilipek** [comment]
@Andarist Sorry if my comment sound this way. I was just wondering if there is any quick workaround that you are aware of. It was not my intention to rush anyone.
Thank you for your help and have a nice day :)

**Comment by davidkpiano** [comment]
@RafalFilipek No workaround yet; you can set a small delay to go to the final state, although that might not be the ideal solution.

**Comment by wesselvdv** [comment]
I am having exactly the same issue, and it's quite blocking :-( I tried to use master to see if that fixes it, but I am still seeing that it's executed before the machine enters final state?
