### ISSUE TITLE
Passing in an incomplete "current state" sometimes yields wrong results

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#108]
## Description:

If you pass in an invalid configuration to transition, xstate seems to gloss over the fact that it's invalid and tries a bit too hard.  It should throw an error condition if the 'current state' is not a state that adheres to the state machine.

For example, if you mention a state in the current state, but it actually has substates, it should be well defined what is happening:  Do you infer that you've already entered the substates' initial states?

If you have a state machine, a parallel root, with regions A, B, C. then currentState `"A"` is not valid, or at least it does not yield the same results as `{A: 'A1', B: 'B1', C: 'C1'}` where A1, B1, C1 are the initial states of A, B, C respectively.

## Expected result:

Throw an error in some cases, document other cases, or gloss over in a more correct manner:

```
machine.transition('A', 'E')
machine.transition({A: 'A1'}, 'E')
machine.transition({A: 'A1', B: 'B1', C: 'C1'}, 'E')
```

All of the above should either work, or the first two should throw an error saying that B and C are not specified.

## Actual result:

Some states are deemed not to be entered and don't get to receive events that they should, if they're omitted from the current state.

machine.transition('A', 'E')  // {A: A2, B: B1, C: C1}
machine.transition({A: 'A1'}, 'E') // {A: A2, B: B2, C: C2} (correct)
machine.transition({A: 'A1', B: 'B1', C: 'C1'}, 'E')   // {A: A2, B: B2, C: C2} (correct)

**Comment by davidkpiano** [comment]
@mogsie Can you add tests for this?

**Comment by davidkpiano** [comment]
Ping @mogsie 🙏
