### ISSUE TITLE
Invoke service is not subscribed 

### ISSUE THREAD

**Issue by BharadwajMP** [davidkpiano/xstate#1081]
**Description**

I have a login state machine,
const loginMachine: Machine = {
  id: 'login',
  context,
  initial: 'autoLogin',
  states: {
    autoLogin: {
      invoke: {
        src: 'tryAutoLogin'
      },
      on: {
        SUCCESS: {
          target: 'loggedIn'
        },
        FAILURE: {
          target: 'loggedOut'
        }
      }
    },
    loggedOut: {
      entry: ['errorMsg'],
      on: {
        SUBMIT: [
          {
            target: 'loading'
          }
        ]
      }
    },
    loggedIn: {
      on: {
        LOGGED_OUT: {
          target: 'loggedOut'
        }
      }
    },
    requestError: {
      on: {
        SUBMIT: 'loading'
      }
    },
    loading: {
      invoke: {
        src: 'requestLogin'
      },
      on: {
        SUCCESS: {
          target: 'loggedIn',
          actions: ['assignUser']
        },
        FAILURE: {
          target: 'requestError'
        }
      }
    }
  }
}

When user triggers SUBMIT event, a transition to loading state occurs and requestLogin should be triggered always. requestLogin return an observable of type SUCCESS or FAILURE. 

**Expected Result**
requestLogin must resolve to SUCCESS or FAILURE

**Actual Result**
requestLogin resolves to SUCCESS or FAILURE only first time and later doesn't resolve to any state and gets stuck in loading state. Debugging shows that the HTTP request to the backend is cancelled because no one subscribes to it but xstate must subscribe to it if I'm not wrong because it works the first time.

**Comment by davidkpiano** [comment]
Please put your code in a CodeSandbox to demonstrate the failure. I'll reopen this when that is done.
