### ISSUE TITLE
Visualizer does not show activities

### ISSUE THREAD

**Issue by qtiki** [davidkpiano/xstate#1089]
**Description**

The visualizer does not show state activities at all.

**Expected Result**

The visualizer should show activities in a similar manner as invoked services.

**Reproduction**

https://xstate.js.org/viz/?gist=d114ffd788befbe352abddcf3819194b

**Comment by davidkpiano** [comment]
Please post visualizer questions in http://github.com/statecharts/xstate-viz/issues/new

**Comment by qtiki** [comment]
Ah okay I've copied the issue there. I didn't realize the visualizer issues go to another repository as there are some with the `🔬 visualizer` tag open in this one as well: #997, #912, #834 and #683
