### ISSUE TITLE
How to determine the allowed events from the current state?

### ISSUE THREAD

**Issue by klvnptr** [davidkpiano/xstate#1091]
Hello

First of all thanks for this fantastic package. I was wondering how to deremine the allowed events to be sent when I'm in a certain state? To check if the state machine will respond to a certain event in the current state.

Thanks so much,
Peter

**Comment by Andarist** [comment]
There is `nextEvents` property which currently serves this purpose.

**Comment by davidkpiano** [comment]
See here: https://xstate.js.org/docs/guides/states.html#state-nextevents

**Comment by James-E-A** [comment]
Now deprecated...

```js
actor.subscribe((snapshot) => {
	let currentState = snapshot.value;
	// https://stately.ai/docs/migration#statenextevents-has-been-removed
	let nextEvents = Array.from(new Set(snapshot._nodes.flatMap((sn) => sn.ownEvents)));
	console.debug("%s: %s", JSON.stringify(currentState), JSON.stringify(nextEvents));
});
```
