### ISSUE TITLE
Toggle component name need to be fixed

### ISSUE THREAD

**Issue by ahmdtalat** [davidkpiano/xstate#1093]
**Description**
xstate-vue-todo-mvc not working due to component name.

**Expected Result**
The Todo app will work just fine

**Actual Result**
Can't import Toggle from @component/toggle/Toggle

**Comment by davidkpiano** [comment]
Can you please create a reproduction? Or better yet, make a PR?

**Comment by ahmdtalat** [comment]
I made a [PR](https://github.com/AleksejDix/xstate-vue-todo-mvc/pull/1) to this [repo](https://github.com/AleksejDix/xstate-vue-todo-mvc).
I think this where it happens.

**Comment by davidkpiano** [comment]
Ah okay, so it's for a different repo. We'll track it there.
