### ISSUE TITLE
Feature req: Straight forward way to forward event to other actions or chain actions

### ISSUE THREAD

**Issue by jaqmol** [davidkpiano/xstate#1097]
## Description

There seems to be no straight forward (or no documented) way to forward events to other actions or chain actions, without losing the original event's properties.

### raise(...)

https://xstate.js.org/docs/guides/actions.html#raise-action
Raise is not useful because it drops all event properties of the previous event.

### forwardTo(...)

https://xstate.js.org/docs/guides/actions.html#forward-to-action
"Forward To Action" is documented as forwarding to services only, not actions. It might be a good idea to change the header of the documentation section to "Forward To Service".

### send(...)

Send is not useful because it drops all event properties of the previous event.

## Conclusion

Either none of the above mentioned methods seems useful to actually forward events with all their data and properties to other actions, or the documentation is not mentioning a hidden usage option that could cover this use-case, or the documentation is not simple enough to dicsover.

## Expectations

1. A method to actually forward complete events with all properties and data from one action to another.
2. This method should sport a facility to modify the event before forwarding to other action.

## Example:

```typescript
/* ... */
  ACT_ONE: {
    actions: [
      assign<Context, EventObject&ActOneEvent>({
        /* ... */
      }),
      forwardToAction<Context, EventObject&ActOneEvent, EventObject&ActTwoEvent>(
        'ACT_TWO', // Action name analog to send(...)
        // Optional event modification function:
        (Context, EventObject&ActOneEvent) :EventObject&ActTwoEvent => {
          /* THIS FUNCTION IS OPTIONAL. IF NOT PRESENT, EVENT IS JUST FORWARDED AS IS TO ACT_TWO */
        }
      ),
    ]
  },
  ACT_TWO: {
    actions: [
      assign<Context, EventObject&ActTwoEvent>({
        /* ... */
      }),
    ]
  },
/* ... */
```

**Comment by jaqmol** [comment]
I just discovered in an example of another issue that the `send(..)` function has a hidden overload option and can used like:

```typescript
  send((_, anyEvent: EventObject) => ({
    type: 'ACT_TWO',
    actTwoProp: (anyEvent as EventObject&ActOneEvent).actOneProp,
  })),
```

After a couple of minutes of digging I even found it mentioned in the documentation:

> The event argument passed to send(event) can be:
> 
> - A string event, e.g., send('TOGGLE')
> - An event object, e.g., send({ type: 'TOGGLE', payload: ... })
> - **An event expression, which is a function that takes in the current context and event that triggered the send() action, and returns an event object:**

It would have been nice to find all the overloads of the send function mentioned in the table directly at the beginning of the documentation section, expressed in wording that follows JavaScript or TypeScript naming conventions / lingo. The term "expression" is definitely not used understandably in this context. 

> Argument | Type | Description
> -- | -- | --
> event | string or event object or **event expression** | The event to send to the specified options.to (or self)
> options? | send options (see below) | Options for sending the event.

**In general I must admit that the lingo used in the XState documentation is sometimes in it's own way to communicate the issue in a straight forward way.**

**Comment by davidkpiano** [comment]
> In general I must admit that the lingo used in the XState documentation is sometimes in it's own way to communicate the issue in a straight forward way.

The "lingo" comes mainly from the SCXML spec: https://www.w3.org/TR/scxml

**Comment by jaqmol** [comment]
Thanks for the reply. What do you think about the section header:

> forwardTo(...)
>
> https://xstate.js.org/docs/guides/actions.html#forward-to-action
> "Forward To Action" is documented as forwarding to services only, not actions. It might be a good idea to change the header of the documentation section to "Forward To Service". 

I'm asking to find out if I'm having another issue concerning my understanding of the SCXML lingo.
