### ISSUE TITLE
Interpreter.start does not assign meta into state 

### ISSUE THREAD

**Issue by anttiahola** [davidkpiano/xstate#1105]
**Description**
If you serialise state into JSON and start a new interpreter from that state the `meta` is preserved, but if you start interpreter from a string value of state, the state does not contain the expected `meta`.
```
const m1 = interpret(fsm).start(JSON.parse(mystate))
const m2 = interpret(fsm).start("mystate")

//m1 contains the meta related to state "mystate", but m2 does not. 
```

**Expected Result**
When starting the interpreter from a string value of, the result state should contain the state's `meta`.

**Actual Result**
Meta is empty object `{}`

**Reproduction**
The call `State.from(initialState, this.machine.context)` does not contain meta, hence the result cannot contain it either. See:
https://github.com/davidkpiano/xstate/blob/9e11131883ac8f49159486103a113c4c22b5c4c9/packages/core/src/interpreter.ts#L413

**Additional context**
v. 4.8.0

**Comment by davidkpiano** [comment]
I'm confused - if you call `interpret(fsm).start("someStringState")`, of course it won't have metadata, because you're only providing the state value, and not the entire state.

**Comment by anttiahola** [comment]
Well, I disagree on the idea of meta being part of dynamic state. Just like the documentation says about meta: 
> meta: any static meta data defined on the meta property of the state node 

Since meta is static and part of the machine definition, I think it should be made available when I call `interpret(fsm).start("someStringState")`. Of course I can use `fsm.getStateNode("someStringState").meta` as a workaround, but it would be cleaner to have it available without the workaround.
