### ISSUE TITLE
exit action is not triggered on child machine

### ISSUE THREAD

**Issue by piojablonski** [davidkpiano/xstate#1109]
**Description**
Child machine runs using invoke on parent machine. Child machine has exit action defined. 

**Expected Result**
I expect child machine exit action to trigger after it reaches it final state

**Actual Result**
Exit action on child machine is not fired

**Reproduction**
```javascript
const childMachine = Machine({
  entry: () => { console.log('entry') },
  exit: () => { console.log('exit') },
  initial: 'a',
  states: {
    a: {
      type: 'final'
    }
  }
})

const parentMachine = Machine({
  initial: 'active',
  states: {
    active: {
      invoke: {
        src: childMachine,
        onDone: 'finished'
      }
    },
    finished: {
      type: 'final'
    }
  }
})
```
https://xstate.js.org/viz/?gist=5ebf91269382bbd3e0bc66c62643a2fa

**Comment by Andarist** [comment]
I can confirm that this should be fired as per [`exitInterpreter` procedure](https://www.w3.org/TR/scxml/#exitInterpreter)

**Comment by piojablonski** [comment]
I tried to do a workaround by using an "a" state exit hook, unfortunately id doesn't work etiher.
```javascript
const childMachine = Machine({
  entry: () => { console.log('entry') },
  
  // this is not trigerred
  exit: () => { console.log('exit') },
  initial: 'a',
  states: {

    a: {
      type: 'final',
      
        // this is not triggered either
      exit: () => { console.log('"a" state exit')}
    }
  }
})

```

**Comment by Andarist** [comment]
Im looking into fixing this and while this is on fact defined behavior in SCXML Im wondering - what is your exact real life use case for this? Im trying to think through what unexpected things this change might cause for people.

**Comment by davidkpiano** [comment]
Related to #1111?

**Comment by Andarist** [comment]
Not quite - when looking at #1111 resolution. This is about what we were discussing today - aligning with SCXML spec by calling onExit handlers for canceled/finalized machines. I hope to get this done this week.

**Comment by chromakode** [comment]
Just bumped into this too. Here's my example use case: a child machine that acquires microphone access using `getUserMedia`. I want to trigger an action when the machine is destroyed so I can release the microphone access.
