### ISSUE TITLE
onDone not triggered for parallel states

### ISSUE THREAD

**Issue by renerbaffa** [davidkpiano/xstate#1111]
**Description**
I was studying parallel states and more specifically trying out the example in the documentation (https://xstate.js.org/docs/guides/final.html#parallel-states). The `onDone` function does not get fired when children states get into the final state.

This issue might be related to https://github.com/davidkpiano/xstate/issues/335?

**Expected Result**
As the example in the documentation, `onDone` should be fired when the children get into the final state.

**Actual Result**
`onDone` is not fired when the children get into the final state.

**Reproduction**
https://codesandbox.io/s/nifty-ganguly-8bnei

**Additional context**
Latest version of xstate (4.8.0)

**Comment by davidkpiano** [comment]
Try doing it in a child `parallel` state, rather than directly on the machine.

**Comment by renerbaffa** [comment]
It works only for the first parallel child moving to a final state.
The second `onDone` is also not being fired:

https://codesandbox.io/s/infallible-haze-h73e2

You can change the order of events sent to see it.

In any case, if that `onDone` in the machine level does not work, how would you fill up `data` to pass context to the parent?

**Comment by renerbaffa** [comment]
what would be the direction here?

**Comment by knobo** [comment]
I have the same problem.

**Comment by knobo** [comment]
Wrapping the whole thing in as a child state worked. But it's a bug anyway.

**Comment by davidkpiano** [comment]
Looking into this now.

**Comment by knobo** [comment]
I was fetching all resources needed by a webpage before displaying it.
It works for me to do it as I did, by wrapping it as a child state. I don't have to have this fixed now, but it should be documented. Because it took me some time to figure this out.

**Comment by Andarist** [comment]
@davidkpiano maybe we could also add a dev-only working when we find `onDone` defined on the root? As it can't work (because the machine is determined by then, like you have said) then we could just surface misusage to the user early.

**Comment by renerbaffa** [comment]
My use-case is similar to @knobo. Fetching from different sources and moving on with the parent state afterwards. `service.onDone(...)` worked as pointed out.
I liked the idea of adding this use-case in the documentation. Would have saved me some time 😅

**Comment by justin0mcateer** [comment]
Well, I just ran into this problem. I see there were nice warnings added in the v4 docs, but the seem to have been lost in the transition to v5. Neither the pages on parallel or final states which both address 'onDone' mention the fact that onDone cannot be used at the root level.
