### ISSUE TITLE
Delayed self transition on parallel state is always treated as internal transition.

### ISSUE THREAD

**Issue by piojablonski** [davidkpiano/xstate#1118]
**Description**
Delayed self transition on parallel state is treated as internal transition even with `internal: false`. In effect it doesn't reenter itself and doesn't trigger entry/exit actions.

**Expected Result**
I expect an event `log` to be fired every second.

**Actual Result**
Event `log` is fired only once, when the machine initializes.

**Reproduction**
https://xstate.js.org/viz/?gist=d1ffc68cc1d29a9eb24e14b53be365b3

**Additional context**
XState 4.8.0

**Comment by Andarist** [comment]
As far as I can tell by checking this quickly - it works correctly: https://codesandbox.io/s/quizzical-field-f45v6?file=/src/index.js . There might be some bug in the visualizer though.

**Comment by davidkpiano** [comment]
The visualizer is using an older version of XState (4.6).

**Comment by piojablonski** [comment]
Thanks, indeed it works correctly on version 4.8, I tested it only on the visualizer.
