### ISSUE TITLE
State type should be used in the Config type

### ISSUE THREAD

**Issue by chancestrickland** [davidkpiano/xstate#1120]
**Description**
The `StateMachine.Config` interface should accept a third generic for our state type, which should then be provided when used in the `createMachine` function. I think. I have declared my own module and haven't had any issues, but if there are any reasons this wasn't set up this way originally let me know. Happy to submit a PR with a fix otherwise.

```ts
declare module "@xstate/fsm" {
  export namespace StateMachine {
    // ...
    interface Config<
      TContext extends object,
      TEvent extends EventObject,
      TState extends Typestate<TContext> = any
    > {
      id?: string;
      initial: string;
      context?: TContext;
      states: {
        [key in TState["value"]]: {
          on?: {
            [K in TEvent["type"]]?: SingleOrArray<
              Transition<
                TContext,
                TEvent extends {
                  type: K;
                }
                  ? TEvent
                  : never
              >
            >
          };
          exit?: SingleOrArray<Action<TContext, TEvent>>;
          entry?: SingleOrArray<Action<TContext, TEvent>>;
        }
      };
    }
    // ...
  }
  // ...
  export function createMachine<
    TContext extends object,
    TEvent extends EventObject = EventObject,
    TState extends Typestate<TContext> = any
  >(
    // hi! now we know some stuff!
    fsmConfig: StateMachine.Config<TContext, TEvent, TState>,
    options?: {
      actions?: StateMachine.ActionMap<TContext, TEvent>;
    }
  ): StateMachine.Machine<TContext, TEvent, TState>;
  // ...
}

```

Using the state type provides helpful intellisense when defining the state chart transitions! 

**Expected Result**
Providing a state type to `createMachine` should help find errors when defining our state chart.

**Actual Result**
Without any knowledge of the state object type, we might forget context keys or leave old state definitions in our chart that we no longer need.

**Reproduction**
See `machine.ts` for a simple state chart working blissfully with the additional state type knowledge: https://codesandbox.io/s/xstatefsm-type-fix-9p3zz?file=/src/machine.ts

**Additional context**
Using @xstate/fsm 1.3.0

**Comment by davidkpiano** [comment]
Want to create/discuss in a PR? 🙏
