### ISSUE TITLE
Feature request & question: dynamically import machines?

### ISSUE THREAD

**Issue by geekox86** [davidkpiano/xstate#1123]
Greetings all and thanks for the wonderful project.

I am wondering about the recommended strategies to scale larger state machines.
In particular, how can we load child machines on demand and destroy them when not needed, with optionally saving their final states for later.

I could not see in the definition of InvokeCreator an option to return a Promise<StateMachine>, so that I can use a dynamic import statement.

My assumption, and correct me if I am wrong please, that if I invoke a service in a state and later I exit this state, then the invoked service is destroyed, i.e. left for the garbage collector.
Is my understanding correct?

Thank you very much.

**Comment by davidkpiano** [comment]
Yes, the invoked service should be destroyed once you exit the state.

You can invoke promises: https://xstate.js.org/docs/guides/communication.html#invoking-promises

**Comment by geekox86** [comment]
@davidkpiano Hi David. Thanks for the prompt response.

So basically I can invoke a promise that dynamically loads the child machine and then when the promise is resolved I can invoke the loaded machine, i.e. a double invoke.

If my understanding is correct then, I just need a syntactical sugar to make it easy to reuse this approach. Any suggestions?

**Comment by davidkpiano** [comment]
Err, okay now that I understand it more clearly, that's probably not what you'd want to do.

Try invoking a callback instead. You would use a strategy like:

```
src: (ctx, e) => (callback, receive) => {
  asyncGetDynamicMachine(/* ... */).then(machine => {
    const service = interpret(machine).start();

    receive(event => {
      service.send(event);
    });
  });
}
```

Sending back up to the parent gets a bit more complicated, since we don't have direct access to the service here (but that's changing in V5). However, you can still use `callback` as normal to sort of do this with a custom action:

```js
interpret(machine.withConfig({
  sendToParent: (ctx, e, { action }) => {
    callback(action.event)
  }
})

// usage
entry: [{ type: 'sendToParent', event: 'SOME_EVENT' }]
```

You're going to have to get a little creative here; it's a unique use-case, and V5 will have better patterns for solving this.

**Comment by geekox86** [comment]
Thank you again for taking the time to respond to our questions. This is really helpful in quickly adopting Xstate.

This is what have got so far. What do you think?

```ts
import { createMachine } from 'xstate'

const loadMachine = (resolver: () => Promise<any>) =>
    createMachine(
        {
            context: {
                resolver,
                state: null
            },
            initial: 'loading',
            states: {
                loading: {
                    invoke: {
                        src: 'load',
                        onDone: 'loaded',
                        onError: 'error'
                    }
                },
                loaded: {
                    invoke: {
                        src: 'state',
                        onDone: 'done',
                        onError: 'error'
                    }
                },
                done: {
                    type: 'final'
                },
                error: {
                    type: 'final'
                }
            }
        },
        {
            services: {
                load: async context =>
                    resolver().then(({ default: state }) => context.state = state),
                state: context => context.state!
            }
        }
    )

export { loadMachine }
```

And then it can be used like this:
```ts
import { createMachine, interpret } from 'xstate'
import { loadMachine } from '@/LoadMachine'

const appState = createMachine(
    {
        strict: true,
        initial: 'x',
        states: {
            x: {
                invoke: {
                    src: 'dynamicMachine',
                    onDone: 'y',
                    onError: 'z'
                }
            },
            y: { type: 'final' },
            z: { type: 'final' }
        }
    },
    {
        services: {
            dynamicMachine: loadMachine(() => import('@/DynamicMachine'))
        }
    }
)

interpret(appState)
    .onTransition(state => console.log(state))
    .start()
```

Btw., what is the difference between `createMachine` and `Machine`?

**Comment by geekox86** [comment]
Also, now when `appMachine` exists state `x`, will the invoked `dynamicMachine` be left for garbage collection?

**Comment by geekox86** [comment]
Where can I read more about v5?

**Comment by geekox86** [comment]
For sending events up to parent, how about adding a wildcard '*' event in the wrapper machine of `loadMachine` that catches all sent events from the dynamic machine and forward them to the intended parent using `sendParent`. I just need to use practically unique names for existing events to avoid collisions.

**Comment by davidkpiano** [comment]
This is problematic: 

```js
context.machine = machine
```

Don't mutate `context`.

**Comment by geekox86** [comment]
@davidkpiano Yes, thank you for pointing that out. Where can I read more about v5?
