### ISSUE TITLE
CDN url broken 

### ISSUE THREAD

**Issue by pat123456** [davidkpiano/xstate#1136]
Hello,
The [https://unpkg.com/@xstate/vue/dist/xstate-vue.min.js](https://unpkg.com/@xstate/vue/dist/xstate-vue.min.js) url is broken, no "dist" folder ?

**Comment by chriscalo** [comment]
I think all that's needed is a new deployment to npm and unpkg will mirror it.

**Comment by chriscalo** [comment]
Is it much work to get a new version deployed to npm?

**Comment by chriscalo** [comment]
This seems to now be fixed after the 4.11.0 release.
