### ISSUE TITLE
TypeError: choose is not a function 

### ISSUE THREAD

**Issue by AlbertoLopSie** [davidkpiano/xstate#1140]
**Description**

Trying to run the sample code at https://xstate.js.org/docs/guides/actions.html#choose-action throws an `TypeError: choose is not a function `  error

**Expected Result**
It should run fine

**Actual Result**

**Reproduction**
Just try to run a project with the sample code in de [documentation](https://xstate.js.org/docs/guides/actions.html#choose-action)

**Additional context**

**Comment by CodingDive** [comment]
Make sure you are using XState `4.9.1`. Check your `yarn.lock` that you are on the correct version. It's working fine for me.

**Comment by davidkpiano** [comment]
If you can still reproduce this with `4.9.1` I expect a CodeSandbox (links are in the issue template) showing the issue.
