### ISSUE TITLE
pure action is not exported from `actions`

### ISSUE THREAD

**Issue by cellog** [davidkpiano/xstate#1147]
**Description**

the `pure` action creator appears to be exported from `xstate/lib/actions`, but contrary to the docs, is not exported from `actions` when imported this way:

```ts
import { actions } from "xstate";
const { pure } = actions;
```

**Expected Result**

pure should exist as documented

**Actual Result**

can be worked around, but does not import as documented

**Reproduction**

- [CodeSandbox template (JavaScript)](https://codesandbox.io/s/xstate-example-template-m4ckv)
- [CodeSandbox template (TypeScript)](https://codesandbox.io/s/xstate-typescript-template-s9kz8)
- ⚛︎ [CodeSandbox template (React)](https://codesandbox.io/s/xstate-react-template-3t2tg)
- ⚛︎ [CodeSandbox template (React + TypeScript)](https://codesandbox.io/s/xstate-react-typescript-template-wjdvn)
- 💚 [CodeSandbox template (Vue + Composition API)](https://codesandbox.io/s/xstate-vue-template-composition-api-1n23l)
- [XState Visualizer](https://xstate.js.org/viz/)

**Additional context**

4.9.0

**Comment by davidkpiano** [comment]
Please try 4.9.1
