### ISSUE TITLE
Improve contribution documentation for implementing xstate in other frameworks

### ISSUE THREAD

**Issue by EddyVinck** [davidkpiano/xstate#1149]
## Feature request
Improve the documentation for future (unofficial) implementations of `xstate`

## Description:
New frameworks come and go. I can't imagine having an official version of XState for every library or framework out there (although [@xstate/svelte would be great!](https://twitter.com/Veinq_/status/1245082165215444998)) as it would be too much of a burden to maintain. 

I'm personally not deep into state machine material yet (or Svelte for that matter), so if I'm considering to build an unofficial implementation of `xstate` I might make some (potentially not so 
obvious) mistakes. 

It would be very valuable if there was documentation to guide people on implementing XState for their favorite library or framework.  

If anyone knows a good example of these kinds of docs that might be worth commenting. 

## (Feature) Potential implementation:

**Required!** If you would like to see a feature or enhancement make its way to xstate, please describe:

Just some ideas:
- Potentially a thorough explanation of an existing `xstate` implementation, like `xstate/react`
- A tutorial where a new offical `xstate` implementation is being created for a currently unsupported library or framework. This could make the hardest part of creating an `xstate` implementation easier to explain if the process of creating the implementation is documented.

**Comment by davidkpiano** [comment]
Added to Roadmap
