### ISSUE TITLE
Chosen actions are not applied if it's pure or assign

### ISSUE THREAD

**Issue by saadshahd** [davidkpiano/xstate#1152]
**Description**
I'm trying to use the new choose action creator but the chosen actions don't get applied if they are pure or assign.

Only log and send work with me.

**Expected Result**
The child assign action of the choose to be invoked

**Actual Result**
The child assign action of the choose didn't get invoked.

**Reproduction**

- [CodeSandbox (JavaScript)](https://codesandbox.io/s/quizzical-sunset-exs80)

**Additional context**
XState Version: 4.9.1

**Comment by davidkpiano** [comment]
Given your current code, you shouldn't be using `choose(...)` at all. What is your use-case for using `choose(...)`?

**Comment by saadshahd** [comment]
> Given your current code, you shouldn't be using `choose(...)` at all. What is your use-case for using `choose(...)`?

@davidkpiano Thanks for the awesome library.

The code is just a simple example of using the `choose(...)`. in the real work example, I am trying to trigger a different set of actions based on the state of a parallel machine.

**Comment by saadshahd** [comment]
But however, even if semantically my use-case doesn't make sense. Based on the docs I think my snippet of code should work differently. Am I right?

**Comment by Andarist** [comment]
@saadshahd yes, it should work - I've located the problem, gonna prepare a PR with the fix soon.

**Comment by Andarist** [comment]
Here you go: https://github.com/davidkpiano/xstate/pull/1153

**Comment by saadshahd** [comment]
@davidkpiano below is a chunk my real-world use case, I would really appreciate if you looked and suggested some refactoring.

```js
const machine = Machine({
  id: 'collection-room',
  type: 'parallel',
  context: {
    loopInterval: null,
    video: {
      url: '',
      timestamp: 0
    }
  },

  on: {
    SET_VIDEO_TIME_WITH_MODE: {
      actions: ['setVideoTimestampWithMode']
    },
  },

  states: {
    videoMode: {
      id: 'videoMode',
      initial: 'manual',

      states: {
        manual: {
          on: {
            ENTER_LOOP: 'loop'
          }
        },

        loop: {
          exit: 'clearLoopInterval',
          on: {
            ENTER_MANUAL: 'manual'
          }
        }
      }
    },

    activating: {
      id: 'activating',
      initial: 'empty',

      on: {
        CHANGE: [
          { target: 'activating.empty', cond: 'isActiveBaseEmpty' },
          { target: 'activating.start', cond: 'isActiveBaseStart' },
          { target: 'activating.end', cond: 'isActiveBaseEnd' },
          { target: 'activating.full' }
        ]
      },

      entry: [
        ...
        'setLoopIntervalFromActiveWithMode'
      ],

      states: {
        empty: {},
        full: {
          entry: [...]
        },
        start: {
          entry: [...]
        },
        end: {
          entry: [...]
        }
      }
    }
  }
}, {
  actions: {
    setVideoTimestampWithMode: choose([
      {
        cond: 'isManual',
        actions: ['setVideoTimestamp', 'checkActive', 'redirect']
      },
      {
        cond: 'isLoop',
        actions: ['setVideoTimestamp']
      }
    ]),

    setLoopIntervalFromActiveWithMode: choose([
      {
        cond: 'isManual',
        actions: ['clearLoopInterval']
      },
      {
        cond: 'isLoop',
        actions: ['setLoopIntervalFromActive']
      }
    ])
  }
});
```
I see now that I could easily get rid of `setVideoTimestampWithMode` by decalring the `SET_VIDEO_TIME_WITH_MODE` event on the video mode state nodes instead of the rool level.catch((err) => {}) 
But I still can't figure out what could I do better to get rid of `setLoopIntervalFromActiveWithMode`.

Thanks in advance.
