### ISSUE TITLE
runtime exception when used with next.js

### ISSUE THREAD

**Issue by tylerthehaas** [davidkpiano/xstate#1158]
**Description**
runtime exception is thrown when used with next.js

**Expected Result**
to be able to run when used in a next.js app

**Actual Result**
runtime exception thrown see attached image.

**Reproduction**
https://github.com/tylerthehaas/nextjs-xstate

**Additional context**
![image](https://user-images.githubusercontent.com/11150235/80056368-45b1a700-84e1-11ea-8f54-8d40d4f6b3b6.png)

**Comment by davidkpiano** [comment]
Could not reproduce (thanks for the CodeSandbox example): https://codesandbox.io/s/github/tylerthehaas/nextjs-xstate
