### ISSUE TITLE
Transient Transitions issue in @xstate/fsm

### ISSUE THREAD

**Issue by abinavseelan** [davidkpiano/xstate#1159]
**Description**

[Transient Transitions](https://xstate.js.org/docs/guides/transitions.html#transient-transitions) seem to not trigger when using `@xstate/fsm`.

Have linked below a repro codesandbox using the example from the docs.

_On a side-note, thank you so much for putting together this package._ ❤️ 

**Expected Result**

Transient transitions allow state changes to occur without an event.

**Actual Result**

No transition occurs and state machine is stuck on initial step.

**Reproduction**

https://codesandbox.io/s/distracted-lederberg-t52tj?file=/src/index.js

**Comment by davidkpiano** [comment]
Thanks for the report, but transient transitions (and microtransitions, raised events, etc. in general) are currently not supported in `@xstate/fsm`. 

This is where you would want to either reach for `xstate`, or manually send a null event: `send('')`.
