### ISSUE TITLE
Problems using xstate with Vuex + Nuxt.js

### ISSUE THREAD

**Issue by lorlab** [davidkpiano/xstate#116]
Hi! I am having trouble using xstate in a Vuex store using Nuxt.js. I have used xstate in Vuex before without problems, but together with Nuxt.js I am getting errors.

If I export my Vuex store in the classic way as described by Nuxt.js docs:

```
import Vuex from 'vuex'
import authMachine from './authMachine'

const createStore = () => {
  return new Vuex.Store({
    state: {
      stateMachine: authMachine,
      authorization: authMachine.initialState.value
    }
    ...
  })
}

export default createStore
```
I get `TypeError - Converting circular structure to JSON`

If I export the Vuex store in the modules way as described by Nuxt.js docs:

```
import authMachine from './authMachine'

export const state = () => ({
  stateMachine: authMachine,
  authorization: authMachine.initialState.value
})
...
```
I get  `RangeError - Maximum call stack size exceeded `

`authMachine` simply exports a machine:

```
import { Machine } from 'xstate'

export default Machine({
  key: 'auth',
  strict: true,
  initial: 'uninitialized',
  states: {
    uninitialized: {
      on: {
        LOGIN: 'loggedIn',
        LOGOUT: 'loggedOut'
      }
    },
    loggedIn: {
      on: { LOGOUT: 'loggedOut' },
      onEntry: ['login']
    },
    loggedOut: {
      on: { LOGIN: 'loggedIn' },
      onEntry: ['logout']
    }
  }
})
```

Any ideas?
Thanks!

**Comment by davidkpiano** [comment]
Why is it converting it to JSON? The machine, by its nature, will have circular structures (`loggedIn` -> `loggedOut` -> `loggedIn`).

This doesn't seem to be a problem with `xstate`, but rather with Vuex trying to convert the machine to JSON. 

To solve this, do _not_ put the machine on the `store` - there's no reason for it to be there, since it's just a function. You can and should define it and reference it externally.

Hope that helps!

**Comment by lorlab** [comment]
Thanks! It makes perfect sense to just reference the machine externally, I don't know why I wanted to save a reference in the store.
By the way, I think the reason it's converting the machine to JSON is because since nuxt initializes the store on the server, it needs a way to pass it to the client.
