### ISSUE TITLE
Viz don't work

### ISSUE THREAD

**Issue by 11111000000** [davidkpiano/xstate#1166]
**Description**
<ExtViz / > don't work

**Expected Result**
working ExtViz

**Actual Result**
render errors when I try to use lastest master. Provided example also don't start properly...

**Reproduction**
yarn
cd packages/xstate-viz/example
yarn start

**Comment by davidkpiano** [comment]
It's not meant for public consumption until I actually release it publicly.

**Comment by 11111000000** [comment]
@davidkpiano  How can I help you?
