### ISSUE TITLE
Something changed between 3.2.1 and 3.3.0

### ISSUE THREAD

**Issue by AnimaLupi** [davidkpiano/xstate#117]
## Bug or feature request?
Bug (or beaking change)

## Description:
When using parallel states with substates, transition using dot notation works on 3.2.1 but breaks on 3.3.0. Maybe it's due to a changed getStatePath or similar?

I'll provide link to 3.2.1 version and 3.3.0 so behavior can be seen:

[3.2.1](https://codepen.io/AnimaLupi/pen/oyXBrw)

[3.3.0](https://codepen.io/AnimaLupi/pen/bKdqGz)

Sorry for the long and apparently redundant configs, I did cut already most of the stuff away...

Thank you!

Andrea

**Comment by davidkpiano** [comment]
Can you write a test? What's breaking, and what's the expected behavior?

**Comment by AnimaLupi** [comment]
Hello David,

Basically in 3.2.1 the transition happens as expected, while in 3.3.0 I get an error in console (it can be seen on the pens linked above).

I'll try to write a test asap.

**Comment by AnimaLupi** [comment]
Hello again @davidkpiano ,

I wrote a pull request  (#119) with the test.

Hope it helps.

Thank you!

**Comment by AnimaLupi** [comment]
Hello @davidkpiano , I updated to the version including your fix. The test passes, but I noticed that by adding another substate leads to same error.
Maybe I'm doing things wrong (as I was doing for history states) but I hope the config is right...
I've created a pull request (#125) with the updated test, hope it helps.
Thank you!

**Comment by AnimaLupi** [comment]
Hi again @davidkpiano, please ignore what I wrote above. Actually the state broke in my app for some other reason I'm investigating (i.e. now it works!) and the test I wrote breaks just because I forgot to add the newly added state in the assert condition... my bad!
Excuse me again! (Now I'm also back to try to understand how to make those history states work... :-) )

**Comment by davidkpiano** [comment]
@AnimaLupi Can you do me a huge favor and reduce the statechart in the failing test to as minimal as possible to reduce the error? Makes it difficult to debug otherwise.

**Comment by AnimaLupi** [comment]
@davidkpiano Sure, I've made a pull request (#126) with a smaller config (it's probably 1/4 of what was before, I tried not to cut it too much as to provide at least 2 substates everywhere).
Thanks!
