### ISSUE TITLE
React hooks loose StateSchema types

### ISSUE THREAD

**Issue by amir-zahedi** [davidkpiano/xstate#1177]
**Feature request description**
React hooks do not allow StateSchema generic types to be passed and always pass any to StateMachine<TContext, any, TEvent>

**Current Behaviour**
StateSchema is always typed to any in useMachine and useService hooks, resulting in the state object coming back as not being typed.

**Expected Result**
A generic type to be exposed by the hooks for the StateSchema

**Reproduction**

- [Code Sandbox example](https://codesandbox.io/s/shy-haze-2rjxv?file=/src/index.tsx) 
Please see lines 41 through 50

**Comment by davidkpiano** [comment]
Typestates don't use the StateSchema. Please see https://codesandbox.io/s/floral-shadow-8qoy3?file=/src/index.tsx

The StateSchema is only useful for constructing the machine, and that information is not needed after the machine is constructed.

**Comment by amir-zahedi** [comment]
Thanks @davidkpiano. That's what I was looking for.
