### ISSUE TITLE
Typescript error in compound child state

### ISSUE THREAD

**Issue by impleri** [davidkpiano/xstate#1179]
**Description**

Typescript does not seem to like a child state node having a final state and a defined initial state. However, removing the initial property fixes the TS error (though it then causes the machine to be invalid). Also, omitting the schema from 

**Expected Result**

A child compound node that contains a final node without TS error.

**Actual Result**

The error given by typescript is that the final node's type is invalid.

**Reproduction**

https://codesandbox.io/s/type-iniitial-ts-repro-rjik8

I'm running 4.9.1 within a create-react-app project. I suspect it has to do with the tsconfig.

**Comment by impleri** [comment]
Workaround: Turn off `strictNullChecks` in tsconfig.

**Comment by davidkpiano** [comment]
Not sure what's going on (lots of type indirection here) but if you defined your schema as this:

```ts
interface OwnStateSchema {
  states: {
    inactive: {
      states: {
        pristine: {};
        starting: {};
        ready: {}
      }
    };
    active: {}
  };
}
```

There is no issue. Please check against this.

**Comment by impleri** [comment]
Except that causes another TS error: `Type 'OwnStateSchema' does not satisfy the constraint 'StateSchema<any>'.`. It's why I've added more explicit typings. The repro has been updated with the above schema and his the typing error.

**Comment by davidkpiano** [comment]
When you nest states, you need to add them in the `states` property:

```ts
interface OwnStateSchema {
  states: {
    active: {};
    inactive: {
      states: {
        pristine: {};
        starting: {};
        ready: {};
      }
    };
  };
}

```
