### ISSUE TITLE
Potential type inference bug with send actions event expression

### ISSUE THREAD

**Issue by artoale** [davidkpiano/xstate#1190]
**Description**
Using typescript, when within a transition definition I use a `send` using the event expression, typescript fails to compile if the type of event returned by the expression is not the same as the type of the event that caused the transition

**Expected Result**
Another valid event should be acceptable

**Actual Result**
Typescript fails to compile with error: 

```
Argument of type '(_: any, evt: { type: "PED_COUNTDOWN"; duration: number; }) => { type: "TIMER"; }' is not assignable to parameter of type '"PED_COUNTDOWN" | { type: "PED_COUNTDOWN"; duration: number; } | ExprWithMeta<any, { type: "PED_COUNTDOWN"; duration: number; }, { type: "PED_COUNTDOWN"; duration: number; }>'.
  Type '(_: any, evt: { type: "PED_COUNTDOWN"; duration: number; }) => { type: "TIMER"; }' is not assignable to type 'ExprWithMeta<any, { type: "PED_COUNTDOWN"; duration: number; }, { type: "PED_COUNTDOWN"; duration: number; }>'.
    Property 'duration' is missing in type '{ type: "TIMER"; }' but required in type '{ type: "PED_COUNTDOWN"; duration: number; }' .ts(2345)
```

**Reproduction**
Slight modification of the "Using with typescript" guide
See line 63 at the [code sandbox](https://codesandbox.io/s/festive-chandrasekhar-vxtqc?file=/src/index.ts)

**Additional Context**
The bug is not manifest if you replace the returned event with the same event type as the one that triggered the transition (in this case `"PED_COUNTDOWN"`), which makes me think the generic type used to describe the return value and the parameter are the same, where in fact they shouldn't? Sorry, I'm not a typescript expert, just guessing :)

**Comment by davidkpiano** [comment]
I believe this was fixed recently in #1178 - we'll cut a release soon.
