### ISSUE TITLE
Xstate with typescript: state.value is always reported as a string even if it can be an object

### ISSUE THREAD

**Issue by overtune** [davidkpiano/xstate#1191]
**Description**
When using Xstate with React I sometimes find the need to pass properties of `state.value` when it is an object to child components. There are no problem doing this in javascript with nullchecks, but I can't manage to get Typescript to allow this.
The Typescript compiler gives the error: `Property 'X' does not exist on type 'string'`.

**Expected Result**
When typing the state like this:
```javascript
interface LightStateSchema {
  states: {
    green: {};
    yellow: {};
    red: {
      states: {
        walk: {};
        wait: {};
        stop: {};
      };
    };
  };
}
```
I think code like this should work:
```javascript
{state.value.red && <RedComponent redState={state.value.red} />}
```

**Actual Result**
Instead typscript gives the error:
`Property 'red' does not exist on type 'string'`

**Reproduction**
Here is a Codesandbox which more or less just use the typescript example from: https://xstate.js.org/docs/guides/typescript.html  
On line 104 typescript gives the error:
https://codesandbox.io/s/intelligent-water-81rzj?file=/src/App.tsx:2061-2132

**Additional context**
Xstate 4.9.1
@xstate-react 0.8.1

Not sure if this is a bug in the Xstate typescript implementation, or if I havn't understood how to type the state in Xstate.

**Comment by FredyC** [comment]
I am just curious what is your use case behind passing pretty much internal structures of the machine around. I mean with your interface, only one property will be ever-present and you would have to do checking which one. Doesn't that kinda beat the purpose of the state machine?

```ts
interface RedComponentProps {
  redState: {
    walk: {};
    wait: {};
    stop: {};
  };
}
```

What about passing a whole `service` instead and then with `useService` in child component you can easily do `current.matches` and work with it as intended.

I don't know, just my opinion as it feels you are complicating it for yourself.

**Comment by overtune** [comment]
The most common usecase I have is when using Styled components.
Lets say I have a statemachine which describes an input (which handles focus/validity/pristine/toched states of the input):
https://xstate.js.org/viz/?gist=a0352e44d41ddcb36cd533a28720ca8b

Then I would like to pass some of these props directly to the styled components so they can set their style accordingly.

For example I might have an label (styled) component, which could reuse the same interface as the validity state:
```javascript
<Label validity={state.value.validity}>Label</Label>
```

Instead of having to do something like this:
```javascript
const invalid = state.matches("validity.valid");

<Label invalid={invalid}>Label</Label>
```

The second example would be really messy if I would like to pass a childstate that could have more than just 2 different values/states.

**Comment by davidkpiano** [comment]
Two things:

1. Prefer using `state.matches(...)`, your use-case is what that is for:

```js
const valid = state.matches({ validity: 'valid' });
```

2. If you're set on using `state.value` directly, understand that `state.value` is typed to `string | StateValueMap` and coerce the type appropriately:

```ts
(state.value as Record<string, string>).validity
```
