### ISSUE TITLE
state.matches does not accept valid parent value when using typestates

### ISSUE THREAD

**Issue by njdancer** [davidkpiano/xstate#1195]
**Description**
When using typestates, the parentStateValue accepted by state.matches is constrained to only valid states of the machine(as specified in the typestate) whereas the documentation indicates this function should also be used to determine if a state is a subset of the given state.

**Expected Result**
state.matches should accept any state that is a valid parent of the states provided in typestate.

**Actual Result**
state.matches returns error. ```Argument of type '\"draft\"' is not assignable to parameter of type \"draft.editing\" | \"draft.submitted\" | ...```

**Reproduction**
https://codesandbox.io/s/xstate-typestate-matches-repro-09be7?file=/src/index.tsx

**Additional context**
Not quite sure what the solution is here. AFAIK string literals are opaque to tsc so not sure how you would be able to infer all the valid parent states when only being provided complete child states. If this means what i'm asking for is impossible then that's fine. Mostly just wanting to make sure i'm using typestates correctly. I did try explicitly adding the parent states I was using to the typestate which seems to work around this issue, however i'm unsure of the implications of this as the state machine can never really be in one of those states. Seems like the best strategy from my perspective but interested in your thoughts.

**Comment by davidkpiano** [comment]
Regardless of the string literals, the behavior here is correct. In the CodeSandbox, you are trying to match `"active"` with `"active.test"`, which is not a match, since `"active.test"` is more specific than `"active"` (since `"active"` can mean `"active.anything"` which does not match `"active.test"`).

The right thing to do here is to be more explicit about your typestates:

```ts
type ToggleState =
  | { value: "inactive"; context: ToggleContext }
  | { value: 'active' | { active: 'test' }; context: ToggleContext };
```

Note to self: should add in the documentation that string representation of states for compound typestates (e.g., `"foo.bar"`) should not be allowed.

**Comment by njdancer** [comment]
Ahh ok. That makes sense. Thanks for the example.

Does this mean that a typestate can only specify the context type for a top level state?

Would be happy to submit a PR to update the typestate example in the docs to include a compound state if you’d be willing to accept.

In any case, thanks for the great library.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davidkpiano** [comment]
> Does this mean that a typestate can only specify the context type for a top level state?

Context is for the entire machine; not sure what you mean by this.

**Comment by njdancer** [comment]
Isn’t the benefit of typestates vs stateschema that the typestate allows you to narrow the type of the context based on which state the machine is in?

Looking at your example, you seem to be specifying that “active” and “active.test” should both have a context of shape ToggleContext, or in other words, that any substate of the top level state “active” should have ToggleContext. You’ve also stated that you shouldn’t be able to represent compound states in a typestate, so If I wanted an extra field to exist in the context only when the state is “active.test”, I’m not sure how I would achieve this.

Apologies if I’ve completely misunderstood something.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davidkpiano** [comment]
You shouldn't represent _string_ compound states, e.g., `value: "active.test"` would be invalid. But yes, you can narrow down context:

```ts
type ToggleState = 
  | { type: 'active'; context: ToggleContext }
  | { type: { active: 'test' }; context: ToggleContext & { something: true } }
```

**Comment by njdancer** [comment]
Thanks for your explanations. I've tried updating the typescript documentation to be more explicit about some of these things and have created #1208 for you to review.

Regarding the behaviour of ```state.matches```, I've taken on board your comment about using the object syntax for compound states and I think ultimately the answer to my original question is that a typestate needs to explicitly model all states including the parent of any compound states, which is more than fine. From additional testing though, It seems that when you use the object syntax inside the typestate you are forced to use the object syntax with ```state.matches``` as well, which is also fine, but if true, I'd like to add this to the documentation as well. I've updated the code sandbox to demonstrate this.

https://codesandbox.io/s/xstate-typestate-matches-repro-5881n

Specifically, when using the following typestate,

```ts
type ToggleState =
  | {
      value: "inactive" | "active";
      context: ToggleContext & { test: undefined };
    }
  | { value: { active: "test" }; context: ToggleContext & { test: string } };
```

these are compiled without error:

```ts
current.matches("active");
current.matches("inactive");
current.matches({ active: "test" });
```

and this receives the error ```Argument of type '"active.test"' is not assignable to parameter of type '"inactive" | "active" | { active: "test"; }'```

```ts
current.matches("active.test");
```

Sorry to waste more of your time if I'm misunderstanding this still, but if I'm correct, let me know and I'll push an update to the PR.
