### ISSUE TITLE
[4.10: TypeScript] Typed actions throw type errors 

### ISSUE THREAD

**Issue by CodingDive** [davidkpiano/xstate#1198]
**Description**
Hello everybody, 
I just upgraded to version 4.10 ready to fix my `send` types. I'm so happy about this release! Thank you so much for introducing the third generic `toSendEvent`. I oftentimes had to go for `<any, any>` as a workaround and am so glad to finally change those. 🖤 

When defining an assign action within the configuration object, TypeScript goes nuts.

```typescript
actions: {
  assignCard: assign<MContext, SubmitEvent>({
    card: (_, event) => event.data.name
  })
}
```

I got the same error when passing the action to `machine.withConfig()`.

**Expected Result**
No type error should be thrown.

**Actual Result**
TypeScript error pyramid of death 😬 

![image](https://user-images.githubusercontent.com/28842311/82574757-dbdff800-9b87-11ea-8df8-547af796ce63.png)

**Reproduction**
https://codesandbox.io/s/xstate-bug-typed-assign-action-in-configuration-object-5pc63?file=/src/index.tsx:1858-1981

**Additional context**

```
@xstate/react: 0.8.1,
xstate: 4.10.0
```

**Comment by davidkpiano** [comment]
Workaround:

```ts
    actions: {
      assignCard: assign<MContext, any>({
        card: (_, event) => (event as SubmitEvent).data.name
      })
    }
```

**Comment by CodingDive** [comment]
`(event as SubmitEvent).data.name`
I didn't know this worked in TypeScript 😲

**Comment by FredyC** [comment]
Or a different workaround, imo slightly nicer :)

```ts
actions: {
  assignCard: assign<MContext, SubmitEvent>({
    card: (_, event) => event.data.name
  }) as any
}
```

**Comment by davidkpiano** [comment]
> I assume this will get better in V5?

That's the goal

**Comment by CodingDive** [comment]
Will this be only fixed when V5 hits? I have 100+ type errors because of this and am contemplating if it's worth to fix them with the described workaround.

I was hoping to upgrade to 4.10 not only to fix my `send` types but also because the `pure` and `choose` actions were not available in the machine configuration object in 4.9.1.

**Comment by FredyC** [comment]
@CodingDive I've extended my workaround and I basically have all my actions declared in a separate file, exporting them in a single object, and then in machine config I can do just this. It's easy to find later and remove.

```ts
{
  actions: myMachineActions as any
}
```

**Comment by CodingDive** [comment]
This is the point in time where I regret having quite a few inline-actions 😁

**Comment by davidkpiano** [comment]
The main problem is that TypeScript often has a hard time inferring object values when it can be one of many things. Looking into a few ways to remedy this at the TS level.

**Comment by CodingDive** [comment]
It also seems to behave non-deterministic. It would sometimes show 0 errors then list quite a few when recompiling without changing anything.

Another TypeScript related problem is that when one of the machines has a type error, it also shows errors when spawning the machine. If an actor is spawned by three machines but also has a type error, it would sometimes print 4 errors. One for the machine that actually has the type errors and in the 3 parents when spawning the machine. I can't remember this happening with < 4.10 but I also wasn't on the latest TypeScript back then.

**Comment by FokkeZB** [comment]
@davidkpiano I ran into this as well and while trying to find a good workaround, I actually wonder if it wouldn't be more accurate for actions to not depend on the transition events calling them, as different actions may share the same actions.

I'd expect `assign()` to be a generic accepting `<Context, { expectedProp: number }>` so that the action defines what props transition events must have to be allowed to call this action.

**Comment by davidkpiano** [comment]
@FokkeZB Can you share a code example of the problem you're running into?

> I'd expect `assign()` to be a generic accepting `<Context, { expectedProp: number }>` so that the action defines what props transition events must have to be allowed to call this action.

That's an interesting idea. Would have to explore how to best do that at the type level.

**Comment by Andarist** [comment]
Note that you can already sort-of do this:
```
<Context, Extract<Events, { expectedProp: number }>>
```

I don't think we should support this out of the box - current types are already complex and this would only raise the complexity. Offloading this to the user space is also a more robust solution as one could write any type matcher on their own, instead of us enforcing a specific type of such matcher.

**Comment by FokkeZB** [comment]
@Andarist I like that pattern, as with that you indicate you don't care what events call the action, as long as they have certain props. You could even do the same for `Context` if we'd have typing of what it may look like for each state, just like we do for `Events`.

@davidkpiano it's not so much of a problem, but a way to think about types. We've run into this with GraphQL where initially we'd use the generated types for queries in presentational components. That may make sense initially, but ultimately breaks you up. Types for output and input should be duplicated as it shouldn't be of a component/function's concern where the data comes from (and what additional props might be passed along), but just define what it **needs**.

**Comment by davidkpiano** [comment]
This problem can now be mitigated using `createModel`: https://xstate.js.org/docs/guides/models.html#typescript 📖 

It will be improved in v5.
