### ISSUE TITLE
guard evaluated before exit and transition actions

### ISSUE THREAD

**Issue by czabaj** [davidkpiano/xstate#1199]
**Description**
I have a real word example. User enters a PIN, if she fails enter the pin for >= `maxFailedAttemptsCount`, she must authenticate with login and password. `failedAttemptsCount` is persisted, so if she forcefully terminates the app and open it again, the app skips PIN authentication as well. I defined it like this:

```
pin: {
  on: {
    '': [
      { cond: 'pinNotSet', target: 'password' },
      {
        cond: { type: 'maxPinFailedAttemptsReached', maxFailedAttemptsCount: 5 },
        actions: ['notifyMaxFailedPinAttemptsReached', 'removeStoredSecrets'],
        target: 'password',
      },
    ],
      SUCCESS: 'userAuthenticated',
      FAIL: { actions: ['incrementPinFailedAttemptsCount'] },
      USE_OTHER_LOGIN_METHOD: { actions: ['removeStoredSecrets'], target: 'password' },
  },
},
password: {
  on: {
    SUCCESS: 'userAuthenticated',
  },
},
```

This flow checks `maxPinFailedAttemptsReached` in transient transition. It counts with `failedAttemptsCount` which is increment upon `FAIL` event transition. I assumed that `failedAttemptsCount` will be incremented before `maxPinFailedAttemptsReached` guard evaluation, but this is not true. Current behaviour is described in [Actions docs](https://xstate.js.org/docs/guides/actions.html#actions) which states

> Actions are not immediately triggered. Instead, the State object returned from machine.transition(...) will declaratively provide an array of .actions that an interpreter can then execute.

Thus actions are executed after transition ends. This is more like feature than bug, but it is highly counter-intuitive. It would be more meaningful for me if `exit` and `event` actions would be executed before transition, or, more precisely, if _actions would be executed before transient transition evaluation_.

**Expected Result**
`exit` and `event` actions are executed before transient transition evaluation.

**Actual Result**
All actions are executed after transition and subsequent transient transition finishes, thus quards in transient transition evaluates data not updated by event and exit actions.

EDIT

Complete example of login machine.

```
const loginMachine = {
  id: 'login',
  initial: 'biometric',
  states: {
    biometric: {
      on: {
        '': { cond: 'biometricNotSet', target: 'pin' },
        SUCCESS: 'userAuthenticated',
        USE_OTHER_LOGIN_METHOD: 'pin',
      },
    },
    pin: {
      on: {
        '': [
          { cond: 'pinNotSet', target: 'password' },
          {
            cond: 'maxPinFailedAttemptsReached',
            actions: ['notifyMaxFailedPinAttemptsReached', 'removeStoredSecrets'],
            target: 'password',
          },
        ],
        SUCCESS: 'userAuthenticated',
        FAIL: { actions: ['incrementPinFailedAttemptsCount'] },
        USE_OTHER_LOGIN_METHOD: { actions: ['removeStoredSecrets'], target: 'password' },
      },
    },
    password: {
      on: {
        SUCCESS: 'userAuthenticated',
      },
    },
    userAuthenticated: {
      entry: ['resetPinFailedAttemptsCount'],
      type: 'final' as 'final',
    },
  },
  onDone: '#appStart.setupPin',
};

```

**Comment by davidkpiano** [comment]
I know it might seem counter-intuitive, but it is the SCXML spec behavior and XState will not deviate from that, so no, it will not change.

Think of guarded transitions as saying "if the `cond` passes, _select this transition_, meaning transition to this `target` and execute these `actions`". The actions should not be executed if the transition isn't taken.

So the logic you actually want is:

> When max attempts are reached, execute these actions and transition to the password state. Otherwise, just execute those actions.

Notice how you had to specify that you needed to execute those actions _twice_. This is explicit, and a good practice IMO. Map that out into your logic:

```js
  on: {
    '': [
      { cond: 'pinNotSet', target: 'password' },
      {
        cond: { type: 'maxPinFailedAttemptsReached', maxFailedAttemptsCount: 5 },
        actions: ['notifyMaxFailedPinAttemptsReached', 'removeStoredSecrets'],
        target: 'password',
      },
      {
        actions: ['notifyMaxFailedPinAttemptsReached', 'removeStoredSecrets'],
      }
    ]
  }
```

You can even DRY up the actions:

```js
const doMaxFailedActions = ['notifyMaxFailedPinAttemptsReached', 'removeStoredSecrets'];

// ...
      {
        cond: { type: 'maxPinFailedAttemptsReached', maxFailedAttemptsCount: 5 },
        actions: doMaxFailedActions,
        target: 'password',
      },
      { actions: doMaxFailedActions }
// ...
```

Or you can even create your own helper in userland:

```js
const executeActionsRegardless = (cond, actions, target) => {
  return [
    { cond, actions, target },
    { actions }
  ];
}

// ...
on: {
  '': [
    { cond: 'pinNotSet', target: 'password' },
    ...executeActionsRegardless('maxReached', doMaxFailedActions, 'password')
  ]
}
```

In general, XState's behavior should not deviate from the SCXML spec. And you can also treat XState as a lower-level target for your logic, which can be represented in a higher-level way (like the previous example).

Hope that helps!
