### ISSUE TITLE
onDone event name is undefined when invoked Observable completes

### ISSUE THREAD

**Issue by stefanoslig** [davidkpiano/xstate#1205]
**Description**
onDone event name is undefined when invoked Observable completes. You can reproduce it easily if in the https://codesandbox.io/s/xstate-react-reddit-example-with-actors-lj9cs?file=/src/subredditMachine.js you replace the "fetch" method with an "of({})" 

**Reproduction**
![image](https://user-images.githubusercontent.com/6942946/82803232-74c08d00-9e80-11ea-8aec-0d0f99bfffea.png)

![image](https://user-images.githubusercontent.com/6942946/82803209-696d6180-9e80-11ea-8880-6fcbcd4344c3.png)

**Comment by davidkpiano** [comment]
This is as intended:

> Observables can be invoked, which is expected to send events (strings or objects) to the parent machine, yet not receive events (uni-directional).

You're not sending an event, you're sending an empty object.

https://xstate.js.org/docs/guides/communication.html#invoking-observables
