### ISSUE TITLE
[TypeScript] Should StateSchema be typed with Record<string, unknown> instead of {} ?

### ISSUE THREAD

**Issue by RomainLanz** [davidkpiano/xstate#1206]
Hi there! 👋 

With the rule [@typescript-eslint/ban-types](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/ban-types.md) added lately to ESLint [the TypeScript code example](https://xstate.js.org/docs/guides/typescript.html#using-typescript) given in the documentation triggers an error.

```ts
interface LightStateSchema {
  states: {
    green: {};
    yellow: {};
    red: {
      states: {
        walk: {};
        wait: {};
        stop: {};
      };
    };
  };
}
```

This will trigger the rule because "we should" avoid using `{}` as a type.

```
error  Don't use `{}` as a type. `{}` actually means "any non-nullish value".
```

Should we update the documentation to use `Record<string, unknown>` instead?

**Comment by RomainLanz** [comment]
In fact, when using the [Typestates](https://xstate.js.org/docs/guides/typescript.html#typestates) system there's no error like the one above.

I believe we can close this since it's fixed with the new syntax.

**Comment by davidkpiano** [comment]
Since it's a lint rule issue that's easily worked around, yes we can go ahead and close this.

**Comment by andriworld** [comment]
I didn't immediately understand how to migrate to Typestates, so I went with a solution like this:

```ts
import { StateNodeConfig } from 'xstate'

type LightStateNodeConfig = StateNodeConfig<Context, Record<string, never>, LightStateEvent>

interface LightStateSchema {
  states: {
    green: LightStateNodeConfig;
    yellow: LightStateNodeConfig;
    red: {
      states: {
        walk: LightStateNodeConfig;
        wait: LightStateNodeConfig;
        stop: LightStateNodeConfig;
      };
    };
  };
}
```

This has the advantage of type-checking your state configs.
