### ISSUE TITLE
useService performance recommendations

### ISSUE THREAD

**Issue by alexreardon** [davidkpiano/xstate#1209]
I'm trying to find a good way to use xstate at scale with good performance.

I create a machine fairly high in my react tree

```js
const [state, send, service] = useMachine(machine);
```

I put the `service` on the react `<ServiceContext.Provider value={service}>` so that other components can also talk to the service

```js
const [state, send, service] = useService(service);
```

My trouble is that in order for `state` to be updated in everything with `useService`, they are re-rendered.

```js
const [state, send, service] = useService(service);
//     ^^^^^
```

I often have components that care about some state transitions, but not others. But right now each one has to render every time.

I'm looking for a good way to solve this.

### Some ideas:

1. Use more nested machines (in user land)
2. Create some sort of selector mechanism so I only re-render components that need to (in user land). This would involve creating a wrapping component for each useService which does some memoization
3. Something else?

**Comment by davidkpiano** [comment]
I'm thinking something like this can help for now:

```jsx
function usePartial(service, selector) {
  const [partialContext, setPartialContext] = useState(selector(service.state.context));

  useEffect(() => {
    const { unsubscribe } = service.subscribe(state => {
      if (!state.changed) return;

      setPartialContext(selector(state.context));
    });

    return () => unsubscribe();
  }, []);

  return partialContext;
}
```

**Comment by alexreardon** [comment]
So:

> 2. Create some sort of selector mechanism

👍

**Comment by JackCA** [comment]
I've written a slightly modified typescript version that uses `state` instead of `context` as the argument:

```typescript
export function usePartial<
  TContext,
  TSchema,
  TEvent extends EventObject,
  TSelectorValue
>(
  service: Interpreter<TContext, TSchema, TEvent>,
  selector: (state: State<TContext, TEvent, TSchema>) => TSelectorValue
): TSelectorValue {
  const [partialContext, setPartialContext] = useState(selector(service.state))

  useEffect(() => {
    const { unsubscribe } = service.subscribe(state => {
      if (state.changed !== true) return

      setPartialContext(selector(state))
    })

    return (): void => unsubscribe()
  }, [selector, service])

  return partialContext
}
```

**Comment by JackCA** [comment]
I've written a slightly modified typescript version that uses `state` instead of `context` as the argument:

``` typescript
export function usePartial<
  TContext,
  TSchema,
  TEvent extends EventObject,
  TSelectorValue
>(
  service: Interpreter<TContext, TSchema, TEvent>,
  selector: (state: State<TContext, TEvent, TSchema>) => TSelectorValue
): TSelectorValue {
  const [partialState, setPartialState] = useState(selector(service.state))

  useEffect(() => {
    const { unsubscribe } = service.subscribe(state => {
      if (state.changed !== true) return

      setPartialState(selector(state))
    })

    return (): void => unsubscribe()
  }, [selector, service])

  return partialState
}
```

**Comment by nazmifeeroz** [comment]
this code is interesting and looks legit.
I tried it out, but i still getting re-renders from other child components not related to the context changed.

it seems that anything under the same context provider still gets re-rendered.

maybe i missed something out?
do you mind creating a sandbox i could refer to?

**Comment by davidkpiano** [comment]
@nazmifeeroz Chances are the rerenders are _not_ due to XState, but other things in React. Try using `React.memo(...)`.
