### ISSUE TITLE
Docs History Typo

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#121]
Bug

## Description:
Small typo in the history machine code example (line 2) in docs at http://davidkpiano.github.io/xstate/docs/#/guides/history.

## Expected result:
`initial: 'fanOff'`

## Actual result:
`initial: 'off'`

**Comment by avaragado** [comment]
Also the paragraph after the chart uses `on` and `off`. I guess these were changed to `fanOn` and `fanOff` to avoid confusion with the magic word `on` in chart configs, and a few instances were accidentally missed.

**Comment by davidkpiano** [comment]
Thanks, would you mind making a PR for this in the `gh-pages` branch?
