### ISSUE TITLE
Add validation to xState visualizer

### ISSUE THREAD

**Issue by ShMcK** [davidkpiano/xstate#122]
**Feature Request**

It would be great if the xState visualizer  ran validation on the object passed in and returned helpful warnings if something goes wrong.

Currently, any invalid machine causes the visualizer to crash. To see this, open the [demo](https://musing-rosalind-2ce8e7.netlify.com/) and change any state name to "other", hit save.

---

### Validation Suggestions
I've included an incomplete list of possible warnings and how they may be determined:

##### Not a valid JSON object
catch if `JSON.stringify(JSON.parse(state))` fails

##### No matching state found for "stateName"
The parser could first run through the possible states keys and validate them against those included as `on` keys

##### `onEnter` key passed in, did you mean `onEntry`?
Catch invalid state keys, and use fuzzy matching to return a helpful message

##### No `initial` key supplied for state
Catch if object is missing a valid `initial` key

---

Alternatively, it may be helpful to use a parser like [PEG.js](https://pegjs.org/), which could provide the exact line and character position of the error.

**Comment by davidkpiano** [comment]
This is a great starting point, thanks! TypeScript will catch many of these but I think that it would be good for `xstate` to have static analysis in development mode, with verbose warnings/errors for the developer.

**Comment by avaragado** [comment]
TypeScript will catch errors only if the developer is using TypeScript. I'm using Flow, and many developers won't be using any static typing at all. Development-mode static analysis would be great.

Some more suggestions:

- State id definitions must not have the `#` prefix, only state id references
- State references must refer to state reachable from there (eg not parent states)
- Missing `target` property where one is required

**Comment by gewoonwoutje** [comment]
Typescript as input in the visualizer would also be great!
