### ISSUE TITLE
[React] Event cannot be send to child invoked machine

### ISSUE THREAD

**Issue by FredyC** [davidkpiano/xstate#1235]
**Description**
According to [the example in docs](https://xstate.js.org/docs/guides/communication.html#sending-events), it should be possible to sent events to the invoked machine. 

**Expected Result**
Sending events to invoked child machines should work.

**Actual Result**
It works nicely with pure `xstate`

https://codesandbox.io/s/dazzling-cohen-5jf9e?file=/src/index.js

However, with React and `useMachine` the send action seems to be ignored.

https://codesandbox.io/s/admiring-dhawan-jj14k?file=/src/App.js

Note, that I have `@xstate/react` built from the latest master in my local development and nothing changes. This problem doesn't seem to be related to running actions in effect as default.

**Comment by FredyC** [comment]
Looking at the current code, I am failing to see where is it supposed to be handling other actions that don't use `asEffect` or `asLayoutEffect`.

The line 176 is clearly an only spot working with `currentState.actions` where it filters those that are supposed to be executed in effect. Are the other actions ignored?

https://github.com/davidkpiano/xstate/blob/2119a1d958380a8f8c12bf71b946d80ec757c4d7/packages/xstate-react/src/useMachine.ts#L171-L200

**Comment by FredyC** [comment]
Oh wow, this is somewhat silly. There is no actual bug. The CodeSandbox failing example is most likely related to effect actions. In local development, my problem turned out to be a simple typo in the event name 😅 

I wonder, why is the check for missing events hidden behind "strict" mode? Once I have enabled it I am getting correct error. Till then it's just silently ignoring the sent event.

**Comment by Andarist** [comment]
> Looking at the current code, I am failing to see where is it supposed to be handling other actions that don't use asEffect or asLayoutEffect.

Yes, other actions should be executed like normal. Provided codesandbox is not using this version of `@xstate/react` and it's broken in regards to invoked machines - this is supposed to get fixed/changed when `asEffect` stuff gets released.

> I wonder, why is the check for missing events hidden behind "strict" mode? Once I have enabled it I am getting correct error. Till then it's just silently ignoring the sent event.

Technically it's valid to send any event to a machine - unknown will just get ignored. You should rely on a type system to disallow "invalid" events and not this runtime check.

**Comment by FredyC** [comment]
> Technically it's valid to send any event to a machine - unknown will just get ignored. You should rely on a type system to disallow "invalid" events and not this runtime check.

I am absolutely using TypeScript and it surely helps in most cases, but frankly, when talking in terms of communication between services, it's not exactly possible to have it strongly typed. Especially when you identify service by a string and it's configured when consuming that machine. I am hoping this will get somehow improved with V5, but it's very hard to rely on that.

**Comment by Andarist** [comment]
> Is the strict mode even documented somewhere? I basically stumbled upon it when debugging through the code.

I don't think it is - we might even remove it in v5. It's not set in stone yet, but we've talked about it. I think we should remove it and validate this at all times behind a dev flag, or not validate at all. There is a slight problem with `*` matcher - using it once within your machine would immediately make your machine non-strict as it would have to accept any event.

**Comment by FredyC** [comment]
Personally, I never used "*" so far yet, it feels like a poor model design to use that in my opinion. Perhaps it could be excluded from checks? It sounds like a bad idea to remove "strict" only to avoid this edge case. Alternatively, it could warn if you use "*" and tell you to disable "strict" mode.

**Comment by davidkpiano** [comment]
Closing this issue as invalid (since you solved it 😅 )

Feel free to open another issue/discussion for strict mode considerations.

**Comment by FredyC** [comment]
There is already discussion about strict mode: https://github.com/davidkpiano/xstate/discussions/1248

But I believe that after taking care of https://github.com/davidkpiano/xstate/issues/1250 the strict mode won't be necessary.
