### ISSUE TITLE
[React] asEffect and asLayoutEffect are not re-exported

### ISSUE THREAD

**Issue by rlaffers** [davidkpiano/xstate#1268]
**Description**
According to [@xstate/react docs](https://xstate.js.org/docs/packages/xstate-react/#aseffect-action), it should be possible to import **asEffect** and **asLayoutEffect** functions. However, they are not available for import.
```javascript
import { asEffect, asLayoutEffect } from '@xstate/react'
```

**Expected Result**
```javascript
typeof asEffect === 'function' // true
typeof asLayoutEffect === 'function' // true
```

**Actual Result**
```javascript
typeof asEffect === 'undefined' // true
typeof asLayoutEffect === 'undefined' // true
```

**Reproduction**
https://codesandbox.io/s/aged-worker-yjb6i?file=/src/index.js

**Additional context**
Versions:
xstate@4.10.0
@xstate/react@1.0.0-rc.5

**Comment by pex** [comment]
When is this fix going to be released?

**Comment by davidkpiano** [comment]
> When is this fix going to be released?

Soon!
