### ISSUE TITLE
xState visualizer not supporting internal transitions

### ISSUE THREAD

**Issue by ShMcK** [davidkpiano/xstate#128]
**Bug**

xState visualizer doesn't seem to be supporting internal transitions.

##### Steps To Reproduce: 

Copy the [internal transition example code](http://davidkpiano.github.io/xstate/docs/#/guides/internal) and paste it into the [visualizer](https://bit.ly/xstate-viz).

**Comment by elijah-schow** [comment]
I also encountered this issue exporting a deeply nested statechart from [sketch.systems](https://sketch.systems/) to the visualizer.

**Comment by davidkpiano** [comment]
Add the `initial: 'direction'` property to the top-level state to visualize it. I'll fix the docs.
