### ISSUE TITLE
package built wrong

### ISSUE THREAD

**Issue by sec0ndhand** [davidkpiano/xstate#13]
When referencing the package using the import statement:
import { Machine } from 'xstate'

It says it can't find xstate.  If I open the npm package.json found here:
node_modules/xstate/package.json

and change line 5 to this:
"main": "dist/xstate.js",

That error goes away.  Maybe there is a better fix, but hopefully that gives you enough info, here is the package.json after I changed it:
[package copy.txt](https://github.com/davidkpiano/xstate/files/1279678/package.copy.txt)

.  Thanks!

**Comment by BrockReece** [comment]
Hey @sec0ndhand, 
 
The latest release [v1.0.3](https://github.com/davidkpiano/xstate/releases/tag/v1.0.3), should have fixed this issue. #11

**Comment by davidkpiano** [comment]
Yep, please let me know if it works now.

**Comment by SuperManEver** [comment]
@davidkpiano still doesn't work for me. I tried to install more latest version of node. thought this is the case. then loaded 1.0.3, built and dropped into 'node_module' this didn't help either. I got following

![image](https://user-images.githubusercontent.com/2178264/30395014-4cc0be4c-98de-11e7-9a4b-4852d23d542a.png)

**Comment by davidkpiano** [comment]
@SuperManEver Just made some changes to 1.1.0, please reinstall and see if it works now.

**Comment by davidkpiano** [comment]
Closing - I'll reopen if you run into further issues.
