### ISSUE TITLE
Visualizer crashes when adding entry action with incorrect conditional

### ISSUE THREAD

**Issue by adiun** [davidkpiano/xstate#1307]
**Description**
When adding an `entry` action with an incorrect conditional, the entire visualizer goes blank with an error in the console. E.g. when adding the `entry` block here:

```
readyToEnd: {
  entry: { 
    target: 'ended',
    cond: hitFinalIdx
  },
  on: {
    APPEND: {
      target: 'ended',
      cond: hitFinalIdx
    }
  }
}
```

**Expected Result**
See an error shown in the form of a toast (not destructive)

**Actual Result**

```
StateChartAction.js:100 Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at sn (StateChartAction.js:100)
    at Qi (react-dom.production.min.js:3274)
    at ka (react-dom.production.min.js:3899)
    at Vo (react-dom.production.min.js:5514)
    at zo (react-dom.production.min.js:5536)
    at Ns (react-dom.production.min.js:5958)
    at ws (react-dom.production.min.js:5925)
    at Cs (react-dom.production.min.js:5860)
    at Zo (react-dom.production.min.js:5787)
    at sa (react-dom.production.min.js:3497)
sn @ main.2b5d9a5b.chunk.js:1
Qi @ 2.06c6d969.chunk.js:1
ka @ 2.06c6d969.chunk.js:1
Vo @ 2.06c6d969.chunk.js:1
zo @ 2.06c6d969.chunk.js:1
Ns @ 2.06c6d969.chunk.js:1
ws @ 2.06c6d969.chunk.js:1
Cs @ 2.06c6d969.chunk.js:1
Zo @ 2.06c6d969.chunk.js:1
sa @ 2.06c6d969.chunk.js:1
(anonymous) @ 2.06c6d969.chunk.js:1
t.update @ 2.06c6d969.chunk.js:1
(anonymous) @ 2.06c6d969.chunk.js:1
e.process @ 2.06c6d969.chunk.js:1
e.schedule @ 2.06c6d969.chunk.js:1
send @ 2.06c6d969.chunk.js:1
i.id @ 2.06c6d969.chunk.js:1
Promise.then (async)
t.spawnPromise @ 2.06c6d969.chunk.js:1
t.exec @ 2.06c6d969.chunk.js:1
t.execute @ 2.06c6d969.chunk.js:1
t.update @ 2.06c6d969.chunk.js:1
(anonymous) @ 2.06c6d969.chunk.js:1
e.process @ 2.06c6d969.chunk.js:1
e.initialize @ 2.06c6d969.chunk.js:1
t.start @ 2.06c6d969.chunk.js:1
(anonymous) @ 2.06c6d969.chunk.js:1
fo @ 2.06c6d969.chunk.js:1
(anonymous) @ 2.06c6d969.chunk.js:1
u @ 2.06c6d969.chunk.js:1
p @ 2.06c6d969.chunk.js:1
P.port1.onmessage @ 2.06c6d969.chunk.js:1
```

**Reproduction**

https://xstate.js.org/viz/?gist=814d4a8c857ab5d323b6ad1fcc83e2c0
Gist: https://gist.github.com/adiun/814d4a8c857ab5d323b6ad1fcc83e2c0

**Additional context**

**Comment by hamzazaidi** [comment]
I am running in to the same issue, i am trying to update the visualizer with the following gist and its crashing
https://gist.github.com/hamzazaidi/e6da36a2d49ea4657717309b06444252

**Comment by EdmundsEcho** [comment]
@adiun  Thank you for posting this bug.  I spent several hours debugging this one before reading yoru post.  I knew it was my mistake, but the error messages were truly impossible for me to work through (the state-machine is part of a large bundle).  It took me all of 2 minutes to at least isolate the source of the bug after having read your post.  Best regards, - E

**Comment by davidkpiano** [comment]
> I spent several hours debugging this one 

Please reach out in the issues, discussions, or gitter.im/statecharts or spectrum.chat/statecharts if you find yourself spending too long on an issue 🙏
