### ISSUE TITLE
[3.3.2] Transition to self wrongly stops activity

### ISSUE THREAD

**Issue by avaragado** [davidkpiano/xstate#131]
When in a state with a current activity, and you transition to the same state (_without_ setting `internal: true`), the activity is wrongly reported as stopped.

Example machine: ([Codesandbox: see console](https://codesandbox.io/s/6lnkqxy25k))

```js
const { Machine } = require("xstate");

const machine = Machine({
    key: "test",
    initial: "test",
    states: {
        test: {
            activities: ["ACTIVITY"],
            on: {
                NEXT: [
                    {
                        // internal: true,
                        target: "test",
                    },
                ],
            },
        },
    },
});

const log = (ix, state) => {
    console.log(`${ix}\n\n${JSON.stringify(state, null, 4)}\n\n`);
};

log(1, machine.initialState);

log(2, machine.transition(machine.initialState, "NEXT"));
```

With 3.3.2, this is the output:

```

1

{
    "value": "test",
    "actions": [
        {
            "type": "xstate.start",
            "activity": "ACTIVITY",
            "data": {
                "type": "ACTIVITY"
            }
        }
    ],
    "activities": {
        "ACTIVITY": true
    },
    "data": {},
    "events": []
}

 
2

{
    "value": "test",
    "history": {
        "value": "test",
        "actions": [
            {
                "type": "xstate.start",
                "activity": "ACTIVITY",
                "data": {
                    "type": "ACTIVITY"
                }
            }
        ],
        "activities": {
            "ACTIVITY": true
        },
        "data": {},
        "events": []
    },
    "actions": [
        {
            "type": "xstate.stop",
            "activity": "ACTIVITY",
            "data": {
                "type": "ACTIVITY"
            }
        },
        {
            "type": "xstate.start",
            "activity": "ACTIVITY",
            "data": {
                "type": "ACTIVITY"
            }
        }
    ],
    "activities": {
        "ACTIVITY": false
    },
    "data": {},
    "events": []
}
```

In state 2, there are actions to stop and start ACTIVITY. But the resulting `activities` object shows `ACTIVITY: false`. I expected this to be `true`.

**Comment by adiun** [comment]
This is not just affecting self-transitions; even if an event transitions the machine to a _different_ state with the same activity the activity will be stopped. [Codesandbox](https://codesandbox.io/s/x2lwyjnmkw)

```
  states: {
    test: {
      activities: ["ACTIVITY"],
      on: {
        NEXT: [
          {
            // internal: true,
            target: "another"
          }
        ]
      }
    },
    another: {
      activities: ["ACTIVITY"]
    }
  }
```

After sending event `NEXT`, `ACTIVITY` is `false`. I'm also on xstate 3.3.2.

**Comment by karl** [comment]
I've just tested this on `4.0.0-12` and I believe it is still broken there. When transitioning to the state you are already in activities are stopped and then restarted. I would have expected them to just continue.

See a minimal recreation here:
https://codesandbox.io/s/xokop769kp?expanddevtools=1&module=%2Fsrc%2Findex.js&moduleview=1

If my findings are correct does it make sense to re-open this issue?

**Comment by davidkpiano** [comment]
It's actually working as expected, but I could make it more clear in the documentation (working on revising it now). 

To wit, by default, all transitions are **external** (according to the [SCXML spec](https://www.w3.org/TR/scxml/#transition)), meaning they will exit/reenter themselves, unless otherwise specified. So, in your example above:

```js
      on: {
        NEXT: 'first',
      },
```

resolves to:

```js
      on: {
        NEXT: {
          target: 'first',
          internal: false
        },
      },
```

which will exit/reenter. To get your desired behavior, set `internal: true`:

```js
      on: {
        NEXT: {
          target: 'first',
          internal: true
        },
      },
```

Or use the "targetless transition" shorthand (for internal transitions with no actions... basically a transition that does nothing):

```js
      on: {
        NEXT: ''
	    // or NEXT: undefined
      },
```

And you'll get the desired behavior.

**Comment by karl** [comment]
Ah that makes sense!

I had seen mention of internal transitions in the docs, but hadn't pieced together that I could use them on transitions to the same state.

Thanks for the, as always, detailed reply!
