### ISSUE TITLE
Tiny correction in the docs:  guides => #eventless-transitions 

### ISSUE THREAD

**Issue by eerrecalde** [davidkpiano/xstate#1327]
**Description**
I might be wrong, but I believe the example on: https://xstate.js.org/docs/guides/transitions.html#eventless-transitions
was supposed to have the 'always' array inside the 'on' object, and not as sibling. See below

**Expected Result**
```
on: {
  always: [
    { target: 'win', cond: 'didPlayerWin' },
    { target: 'lose', cond: 'didPlayerLose' }
  ],
  // Self-transition
  AWARD_POINTS: {
    actions: assign({
      points: 100
    })
  }
}
```

**Actual Result**
```
always: [
  { target: 'win', cond: 'didPlayerWin' },
  { target: 'lose', cond: 'didPlayerLose' }
],
on: {
  // Self-transition
  AWARD_POINTS: {
    actions: assign({
      points: 100
    })
  }
}
```

**Comment by davidkpiano** [comment]
The docs are correct; `always` is a sibling to `on`, similar to `onDone`, `after`, etc.

**Comment by eerrecalde** [comment]
@davidkpiano Not sure why I can't get it to work then :/

Mind quickly looking at the init state? (The very first one)
https://xstate.js.org/viz/?gist=b809941cd092c0358fb933c3d0e022e6

Thanks!

**Comment by Andarist** [comment]
The visualizer probably runs on an older version of XState.

**Comment by eerrecalde** [comment]
Ah that'd explain the issue.. Thanks
