### ISSUE TITLE
entry: send( ctx => ({/*...*/})) generates TypeError

### ISSUE THREAD

**Issue by EdmundsEcho** [davidkpiano/xstate#1347]
**Description**

In the machine configuration object the following generates an error:
```js
          entry: [
            log(
              (ctx) =>
                `Sending command to ui machine with purpose: ${JSON.stringify(
                  ctx.changes.purpose,
                )}`,
            ),
            send(
           // function expression that returns event
              (ctx) => ({
                type: 'GENERATE_UI',
                payload: { purpose: ctx.changes.purpose },  
              }),
              {
                // options
                id: 'generate_ui',
                to: 'ui-server',
                delay: 10,
              },
            ),
          ],
```

Configure the `send` action creeator with an event object instead (and fix the value of the payload)... no error. 

**Expected Result**

No error

**Actual Result**

```
TypeError: can't access property "indexOf", r.event.type is undefined
    sn StateChartAction.js:86
    React 25
    430 index.tsx:14
    i (index):1
    104 main.2b5d9a5b.chunk.js:1
    i (index):1
    a (index):1
    e (index):1
    <anonymous> main.2b5d9a5b.chunk.js:1
```
**Reproduction**

- [CodeSandbox template (JavaScript)](https://codesandbox.io/s/xstate-example-template-m4ckv)
- [CodeSandbox template (TypeScript)](https://codesandbox.io/s/xstate-typescript-template-s9kz8)
- ⚛︎ [CodeSandbox template (React)](https://codesandbox.io/s/xstate-react-template-3t2tg)
- ⚛︎ [CodeSandbox template (React + TypeScript)](https://codesandbox.io/s/xstate-react-typescript-template-wjdvn)
- 💚 [CodeSandbox template (Vue + Composition API)](https://codesandbox.io/s/xstate-vue-template-composition-api-1n23l)
- [XState Visualizer](https://xstate.js.org/viz/)

**Additional context**

xstate: "^4.11.0"

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by EdmundsEcho** [comment]
@Andarist thank you for your prompt reply. Your point is fair and I will do my best to get something up and running. 

In the meantime, have you seen this type of error code before? It comes from the online `viz` with my pasted code base. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davidkpiano** [comment]
The visualizer is running on an older version of XState, which could be the source of this error.

**Comment by EdmundsEcho** [comment]
Ah!! That explains soooo much. 

I was looking for a way to run the visualizer locally. Is that possible?  Is it on github so that I might also see how I might help... if helpful (I did do a first pass look and did not find anything).

Regarding the version online, is there legacy code that will break with an upgrade?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davidkpiano** [comment]
I'm currently working on the new visualizer, which is expected to be completed by the end of the month. It is a complete overhaul of the existing visualizer which is why we can't incrementally update the current one.

**Comment by EdmundsEcho** [comment]
@davidkpiano Thank you alround.  It's a great tool.  Clearly differentiating.   On a separate, but `viz`-related topic, is there a way to have one machine reference another machine specified in a different gist? So, ~ imports of gists?

**Comment by davidkpiano** [comment]
> @davidkpiano Thank you alround. It's a great tool. Clearly differentiating. On a separate, but `viz`-related topic, is there a way to have one machine reference another machine specified in a different gist? So, ~ imports of gists?

There will be! Sneak preview: see the _parent_ link?

<img width="943" alt="CleanShot 2020-07-20 at 00 03 05@2x" src="https://user-images.githubusercontent.com/1093738/89126330-ecc7b680-d4b2-11ea-9b7f-c96a437d14cd.png">

**Comment by EdmundsEcho** [comment]
Truly cool.
