### ISSUE TITLE
XState Visualiser does not accept the 'always' property on states

### ISSUE THREAD

**Issue by mattpocock** [davidkpiano/xstate#1355]
**Description**
Given this machine:
```js
const demoMachine = Machine({
  initial: 'idle',
  states: {
    idle: {
      always: 'neverReached'
    },
    neverReached: {}
  }
});
```

The machine will never reached the `neverReached` status when it's put into the visualiser.

**Actual Result**
![image](https://user-images.githubusercontent.com/28293365/89333168-85fdf500-d68c-11ea-8790-5b66ef304f1e.png)

No connecting link is placed between the two states, as usually happens on a transient transition.

**Additional context**
The XState Visualiser probably needs updating to a newer version of XState.

**Comment by davidkpiano** [comment]
> The XState Visualiser probably needs updating to a newer version of XState.

Yes; this is coming in late August.
