### ISSUE TITLE
can't use static value on assigner object using ts

### ISSUE THREAD

**Issue by idhowardgj94** [davidkpiano/xstate#1361]
**Description**

according to official website 

assign action creator can use like this: 

```ts
  actions: assign({
    // assign static value to the message (no function needed)
    message: 'Count changed'
  }),
```

but when i do this, ts show me error on `on` props:

```ts
// v error show here
 on: { 
      // .....
    // timeoutMsg is type string 
        TIMEOUT: { target: 'timeoutcode', actions: assign( timeoutMsg: 'foo'}) }
      }
```
change timeoutMsg to a function work fine.

**Expected Result**
no error 
**Actual Result**

```
The expected type comes from property 'on' which is declared here on type 'StateNodeConfig<RegisterContext, any, RegiserEvent>'
```

xstate ^4.11.0

**Comment by davidkpiano** [comment]
✏️ Please create a [CodeSandbox (XState TypeScript template)](https://codesandbox.io/s/xstate-typescript-template-6dsws) reproduction of this. Thanks!

**Comment by idhowardgj94** [comment]
https://codesandbox.io/s/xstate-typescript-template-forked-mb5vn?file=/src/index.ts:0-2706

error happen in line 40 and 45.

somehow this editor won't show the error msg.

maybe this error occur due to incompatible typescript version.

below is full msg occur to me on line 48:

```
The mapping of event types to their potential transition(s).

types.d.ts(289, 5): The expected type comes from property 'on' which is declared here on type 'StateNodeConfig<RegisterContext, any, RegisterEvent>'
``` 

other info

typescript: Version 3.8.2

ts config: 

```
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "isolatedModules": true,
    "jsx": "react",
    "lib": ["es6"],
    "moduleResolution": "node",
    "noEmit": true,
    "strict": true,
    "target": "esnext"
  },
  "exclude": [
    "node_modules",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js"
  ]
}

```

**Comment by idhowardgj94** [comment]
btw, use with react typescript.
tis seem not a prombleem of ts server ,
cause i upgrade ts to the latest stable version,
and still got the same problem 

ill check which dependecy conflict

**Comment by davidkpiano** [comment]
As the CodeSandbox shows, this shouldn't be a problem in newer versions of XState and TypeScript, so please double-check the versions.

If the error still occurs, you should pass in the context type as a type param:

```ts
actions: assign<RegisterContext>({
  timeoutMsg: "error happen here",
  payload: (c, e) =>
    ({
      email: "corelabstudent@gmail.com",
      password: "11111111",
      name: "test"
    } as typeof c.payload)
})
```

**Comment by idhowardgj94** [comment]
after some debug,

I find out that error happen when tsconfig.strict set to true.

I reduce the code to code bellow, and still got error:

```ts
import { Machine, assign, Event, EventObject, AnyEventObject } from "xstate";

export const test = Machine({
  id: 'registerMachine',
  initial: 'idle',
  context: {
    a: '',
    timeoutMsg: '',
    payload: undefined
  },
  states: {
    idle: {
      id: 'idle',
      on: {
       VALIDATE: [
         { target: 'idle', actions: assign({timeoutMsg: 'test'} )}
       ]
      }
    }
  }
});
```

and when I remove set the strict config to false, error gone:
```json
{
  "compilerOptions": {
    "module": "commonjs",
    "jsx": "preserve",
    "esModuleInterop": true,
    "sourceMap": true,
    "allowJs": true,
    "lib": [
      "es6",
      "dom"
    ],
    "rootDir": "src",
    "moduleResolution": "node",
    "strict": false // change this
  }
}
```

i'm not sure why codesandbox didn't have the same effect when set the strict mode on

**Comment by idhowardgj94** [comment]
pardon me to delete the codesandbox.

it has too many unnecessary info.

**Comment by davidkpiano** [comment]
I'll reopen this if it's reproducible with a CodeSandbox.

**Comment by idhowardgj94** [comment]
after digging, i think that types.d.ts host on codesandbox server is not the same with latest version of xstate on npm.
i try to clone the project and build again, and find out that the type.d.ts is the same with `npm install xstate ` version.

just a littile info, tks for reply and help .
