### ISSUE TITLE
devTools: true does not show state/events in redux dev tools

### ISSUE THREAD

**Issue by dustinknopoff** [davidkpiano/xstate#1382]
**Description**
When passing `{devTools: true}` to `useMachine` in React, the Redux Dev Tools appear but show no state/events, just `@@INIT`

**Expected Result**
The Redux Dev Tools display history, events, state

**Actual Result**
Nothing appears, just `@@INIT` as the most recent event

**Reproduction**
- [TodoMVC Forked from Docs](https://codesandbox.io/s/xstate-todomvc-4110-wdevtools-9m100):
    - Bumped xstate version to `4.11.0`
    - passed `{devTools: true}` to `useMachine` in `Todos.tsx`
   - Actual result mentioned above is what's seen
- [TodoMVC Forked from Docs 2](https://codesandbox.io/s/xstate-todomvc-433-b5rkm)
    - Downgraded version of xstate to before `devTools` argument was required.
    - Expected result is seen

**Comment by EdmundsEcho** [comment]
Is it possible that you are using `redux` in your app already?  

If so, you might think `devTools` would just "toggle" from one to the other.  Instead however, it behaves as you described it: only showing `@@INIT` when xstate `devTools:true`. 

\- E

**Comment by dustinknopoff** [comment]
I'm pretty sure that isn't what's happening. The code sandboxes I linked to showing the differing results both do not have `redux` as a dependency.

**Comment by dustinknopoff** [comment]
I've been unsuccessfully trying to see if I could narrow the scope. [Here's the Calculator example (no actors)](https://codesandbox.io/s/dreamy-sunset-6t91f) still with the `@@INIT` shown.

**Comment by davidkpiano** [comment]
It is recommended to use [the inspector](https://xstate.js.org/docs/packages/xstate-inspect) instead.
