### ISSUE TITLE
Hierarchical onExit Actions

### ISSUE THREAD

**Issue by shawnnosaurus** [davidkpiano/xstate#139]
> **Disclaimer:** This might be against state machine convention.

## Bug
Parent states don't expose the onExit actions of their nested children. 
This means that any possible cleanup of the child needs to currently happen on the parent state.

## Description:
Using the example of the [pedestrian traffic light](https://github.com/davidkpiano/xstate#hierarchical-nested-state-machines), on exit of the red state doesn't expose the exit actions of the current active pedestrian state.

## (Bug) Expected result:
On exit of a root lightMachine state(red), all onExit actions of the active pedestrian state(stop) will be passed up the tree.

## (Bug) Actual result:
On exit of a root lightMachine state(red), the active pedestrian state(stop) is unaware of the change.

## (Bug) Potential fix:
Same method as grabbing the initial states might possibly apply to the on exits of a transition.

**Comment by mogsie** [comment]
Hmm. I've tried reproducing this, but when I try a simple onExit on a child state it does fire.  Check out the [debugger](https://codepen.io/mogsie/full/YapZjZ/?sc=%0A%7B%0A%20%20initial:%20%27on%27,%0A%20%20states:%20%7B%0A%20%20%20%20on:%20%7B%0A%20%20%20%20%20%20on:%20%7B%0A%20%20%20%20%20%20%20%20flick:%20%27off%27%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D,%0A%20%20%20%20off:%20%7B%0A%20%20%20%20%20%20initial:%20%27A%27,%0A%20%20%20%20%20%20on:%20%7B%0A%20%20%20%20%20%20%20%20flick:%20%27on%27%0A%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20states:%20%7B%0A%20%20%20%20%20%20%20%20A:%20%7B%0A%20%20%20%20%20%20%20%20%20%20on:%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20flick:%20%27B%27%0A%20%20%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20%7D,%0A%20%20%20%20%20%20%20%20B:%20%7B%0A%20%20%20%20%20%20%20%20%20%20onExit:%20%22foo%22%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D&rd=) — click "parse" and then the "initial" button then "flick" three times.  It goes from "off.B" to "on" and triggers B's onExit.

**Comment by shawnnosaurus** [comment]
Oh wow, thank you so much, I logged this on my team's behalf and probably find we're on an older version. Will close this ticket and ensure it is updated.
