### ISSUE TITLE
Visualiser: in some cases the text area flashes when editing code in Firefox

### ISSUE THREAD

**Issue by mindrones** [davidkpiano/xstate#1392]
**Description**

In a couple of specific cases, when we want to edit code in the visualiser in Firefox, it goes black and redraws again everytime we edit, making it barely usable.

**Expected Result**

Editing code normally.

**Actual Result**

In the reported examples (see below), every time you press a key on the keyboard or click somewhere in the code area, it goes black and redraws again everytime we edit, maing it barely usable.

**Reproduction**

- Open [this](https://xstate.js.org/viz/?gist=912bbf1cfff6e58c9fa0af5179f20a0a) or [this](https://xstate.js.org/viz/?gist=9aae5aa5cea4ab0fb7ff211edfc507d1) in Firefox
- try to edit the code

**Additional context**

Firefox 79.0 (64-bit)

**Comment by davidkpiano** [comment]
There will be a new visualizer released in a couple weeks, completely different than this one.

**Comment by mindrones** [comment]
Ah that's nice, thanks!
