### ISSUE TITLE
Contributing to xstate

### ISSUE THREAD

**Issue by tomenden** [davidkpiano/xstate#1406]
Hi,

I followed the instructions [here](https://github.com/davidkpiano/xstate/blob/master/CONTRIBUTING.md) and attempted to create a PR, but I am unable to push due to permission issues. This is the message I get:
`ERROR: Permission to davidkpiano/xstate.git denied to tomenden.`

What is the right process to create a PR?

Thanks!

**Comment by brianespinosa** [comment]
@tomenden typically the best way to submit a PR into a Github repo like this is to fork the repository so you have your own copy, commit and push your changes to your fork, then submit a PR from your fork. Development is not usually happening with branches inside of a repository itself unless you are the owner of a repository or part of the organization.

**Comment by tomenden** [comment]
@brianespinosa 
Thanks for your response.
I get that, and it's perfectly fine, just that the Contributing Guidelines indicate otherwise. I will go ahead and fork, perhaps the Contributing guidelines should be updated to reflect that.

**Comment by brianespinosa** [comment]
Ah, yes. I see. Makes more sense to say "fork" instead of "clone" in step 1.
