### ISSUE TITLE
[@xstate/inspect] - Send expression breaks the viz

### ISSUE THREAD

**Issue by FMcIntosh** [davidkpiano/xstate#1428]
**Description**
Adding a send expression i.e. `send(() => ({ type: "NULL_EVENT" }))` breaks the inspector, although the machine works fine.

**Expected Result**
Send expressions should work in the inspector

**Actual Result**
The inspector shows `An unexpected error has occurred.`

**Reproduction**
[Codesandbox forked from the Vue example](https://codesandbox.io/s/xstate-vue-minute-timer-viz-forked-pyf05?file=/src/timerMachine.js:700-736)
Removing the send expression on line 30 fixes the inspector

Love the new tools by the way!

**Comment by davidkpiano** [comment]
This should be fixed - refresh soon!
