### ISSUE TITLE
This machine config crashes both old and new visualizer.

### ISSUE THREAD

**Issue by whitelizard** [davidkpiano/xstate#1437]
**Description**
This totally serializable machine config crashes both old and new visualizer.

It works fine with xstate and useMachine.

```
{
  id: 'app',
  initial: 'checking',
  context: {
    profile: {},
    documents: [],
    idps: [],
    verificationUrl: undefined,
    loginMessage: undefined,
  },
  states: {
    checking: {
      invoke: {
        src: 'checkToken',
        onError: { target: 'gettingIdps', actions: 'setLoginMessage' },
        onDone: [
          {
            cond: 'hasEmailVerification',
            target: 'verifyEmail',
          },
          { target: 'authenticated', actions: 'clearCodeParam' },
        ],
      },
    },
    verifyEmail: {
      entry: { actions: 'setVerificationUrl' },
      on: { LOG_IN: 'loggingIn' },
    },
    gettingIdps: {
      entry: { actions: 'clearTokens' },
      invoke: {
        src: 'getIdps',
        onError: 'login',
        onDone: { target: 'login', actions: 'setIdps' },
      },
    },
    login: {
      entry: { actions: 'setLoginMessage' },
      on: { LOG_IN: 'loggingIn' },
    },
    redirecting: { type: 'final' },
    loggingIn: {
      invoke: {
        src: 'logIn',
        onError: 'login',
        onDone: 'redirecting',
      },
    },
    authenticated: {
      initial: 'authedIdle',
      states: {
        authedIdle: {
          on: { INIT_DOCUMENTS: 'fetchingDocs', LOG_OUT: '#app.gettingIdps' },
        },
        fetchingDocs: {
          invoke: {
            src: 'fetchDocuments',
            onError: 'fetchFailed',
            onDone: { actions: 'setDocuments', target: 'initialized' },
          },
        },
        fetchFailed: {
          on: { RETRY: 'fetchingDocs', LOG_OUT: '#app.gettingIdps' },
        },
        initialized: {
          on: { INIT_DOCUMENTS: 'fetchingDocs', LOG_OUT: '#app.gettingIdps' },
        },
      },
    },
  },
}
```

**Expected Result**
Visualized mashine.

**Actual Result**
The new visualizer crashes with:
`TypeError: Cannot read property 'startsWith' of undefined`

The old visualizer crashes with:
`TypeError: Cannot read property 'indexOf' of undefined`

**Additional context**
Working fine with the following versions in React project:
xstate@4.13.0
@xstate/react@0.8.1

**Comment by davidkpiano** [comment]
✏️ Please create a [CodeSandbox (XState template)](https://codesandbox.io/s/xstate-example-template-qcwed) reproduction of this. Thanks!

**Comment by whitelizard** [comment]
Sure.

Here is the example with the machine that won't be visualized:

[https://codesandbox.io/s/xstate-example-template-vanilla-forked-2b6bh](https://codesandbox.io/s/xstate-example-template-vanilla-forked-2b6bh)

It works in code as I said, but not in any of your visualizers.

**Comment by davidkpiano** [comment]
The error was in the code:

```diff
      verifyEmail: {
-       entry: { actions: "setVerificationUrl" },
+       entry: { type: "setVerificationUrl" },
        on: { LOG_IN: "loggingIn" }
      },
```

And there's a couple other places where that typo was made. Remember: `entry` and `exit` properties represent _actions_, not transitions.

Here's a working example: https://codesandbox.io/s/xstate-example-template-vanilla-forked-1z3ch?file=/src/index.js

**Comment by whitelizard** [comment]
Damn. Thanks. Will at least never forget that again!
