### ISSUE TITLE
Invoke transitions rendered twice on new inspector

### ISSUE THREAD

**Issue by FokkeZB** [davidkpiano/xstate#1461]
**Description**
`invoke.onDone` and `invoke.onError` duplicated on https://statecharts.io/inspect.

**Expected Result**
Each transition displayed once.

**Actual Result**
Each transition displayed twice:

![](https://cdn.zappy.app/2ad485d26b6f5bb46a62d95ddcc6855a.png)

**Reproduction**

https://codesandbox.io/s/intelligent-hill-v8tds?file=/src/index.ts

**Comment by davidkpiano** [comment]
You're using an older version of XState. Upgrade to latest; this issue was fixed.
