### ISSUE TITLE
ModuleWarning: Cannot find SourceMap after adding @xstate/react

### ISSUE THREAD

**Issue by NathanKleekamp** [davidkpiano/xstate#1465]
**Description**
After adding `@xstate/react` to our project, which uses Webpack and the `source-map-loader`, we started getting the following warning at build time:

```
ModuleWarning: Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in 'node_modules\@xstate\react\lib'
ModuleWarning: Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'useActor.js.map': Error: Can't resolve './useActor.js.map' in 'node_modules\@xstate\react\lib'
```

**Expected Result**
There would be no warning related to source maps.

**Actual Result**
See Description

**Reproduction**
If you look at the distributed package, in `useActor.js.map`, there's a reference to a source map `useActor.js.map` that isn't included in the package. Likewise, for `index.js` and index.js.map`.

So to fix this, either include the source map or don't include the source map reference in the distributed package.

**Additional context**
`"@xstate/react": "^0.8.1",`
`"xstate": "^4.13.0"`

**Comment by davidkpiano** [comment]
Can you still reproduce this in version 1.x?

**Comment by davidkpiano** [comment]
Closing as not reproducible - if this still occurs in 1.x, we can reopen.
