### ISSUE TITLE
Set initial state dynamically at runtime anywhere in the hierarchy

### ISSUE THREAD

**Issue by jmakeig** [davidkpiano/xstate#147]
## Bug or feature request?

Feature, I think. (Or maybe a misunderstanding of the design of hierarchical states.)

## Description:

For testing, I need to be able to set the initial state to *any* state within a deeply nested hierarchy as a shortcut to avoid having to replay a series of events to test a particular state.

```js
const a = {
  "strict": true,
  "initial": "A",
  "states": {
    "A": {
      "states": {
        "C": {},
        "D": {}
      }
    },
    "B": {}
  }
};
```

For example, if I were testing events on the `C` state, in my test I'd like to be able to do something like:

```js
test('testing C', () => {
  // Set-up
  const fsm = Machine(Object.assign({}, a, {initial: '.A.C'}));  // or `A.C` or `C`
  const current  = fsm.initialState;
  // Assertions…
});
```
## (Bug) Expected result:

```
State({ A: 'C' })
```

## (Bug) Actual result:

```
TypeError: Cannot read property 'resolvedStateValue' of undefined
    at e.get [as resolvedStateValue] (main.fba6c9ef.js:1)
    at e.get [as initialStateValue] (main.fba6c9ef.js:1)
    at e.get [as initialState] (main.fba6c9ef.js:1)
    at new App (main.fba6c9ef.js:1)
    at constructClassInstance (main.fba6c9ef.js:1)
    at beginWork (main.fba6c9ef.js:1)
    at i (main.fba6c9ef.js:1)
    at a (main.fba6c9ef.js:1)
    at s (main.fba6c9ef.js:1)
    at w (main.fba6c9ef.js:1)
```

Even if this is the correct behavior, I’d suggest the code could be a little more defensive and provide a better error message.

## (Feature) Potential implementation:

I’d expect the `initial` property of a machine configuration to accept a fully qualified path to any state in the hierarchy. (Would this break encapsulation?) Or maybe there should be another parameter in the `Machine` factory function that allows you to set the initial state dynamically, independent of the static state configuration.

How are others isolating for testing?

**Comment by derek-duncan** [comment]
@jmakeig It looks like that error may be because "A" does not have an "initial" property defined? 

On a slightly unrelated note, it would be great to allow guards for initial states! For example, a dropdown component may accept an `defaultOpen` prop to open it by default. It would be great to dynamically change the initial state from "Closed" to "Open" in the statechart!

**Comment by jmakeig** [comment]
Argh. I think the problem is that I'm still trying to wrap my arms around the API and the fact that xstate is stateless. I think what I need is:

```js

import {Machine, State} from 'xstate';

const a = {
  "strict": true,
  "initial": "A",
  "states": {
    "A": {
      "states": {
        "C": {
          on: { d: "D"}
        },
        "D": {}
      }
    },
    "B": {}
  }
};

test('testing C', () => {
  // Set-up
  const fsm = Machine(a);
  const c = new State({A: 'C'});
  // Assertions…
  const d = fsm.transition(c, 'd');
  expect(d).toEqual({ A: 'D' });
  // …
});
```

The docs hint that you’ll likely only need to construct synthetic `State` objects for testing, which is exactly what I needed above.

*Note to self:* The initial state is just a default transition. There’s nothing special about it. The first parameter of `Machine.prototype.transition` specifies the “starting point”. This has nothing to do with the initial state.
