### ISSUE TITLE
[TypeScript] Generic types for `InvokeCallback`

### ISSUE THREAD

**Issue by larvanitis** [davidkpiano/xstate#1471]
**Description**

I believe the `InvokeCallback` type definition could be improved by adding generic types for its params.

**Expected Result**
Something like this:

```typescript
export type InvokeCallback<SEvent extends EventObject = any, REvent extends EventObject = EventObject> = ( 
  callback: Sender<SEvent>, 
  onReceive: Receiver<REvent> 
) => any; 
```

**Actual Result**

https://github.com/davidkpiano/xstate/blob/34a309717eff4ca04477a02c79e3d2ee3f142f8a/packages/core/src/types.ts#L205-L208

**Comment by Andarist** [comment]
In general, I think this makes sense - would you be willing to work on this improvement? Could you also include a real-life(-like) usage of this type?
