### ISSUE TITLE
Eventless transitions do not appears in visualizer

### ISSUE THREAD

**Issue by dminkovsky** [davidkpiano/xstate#1477]
**Description**

Eventless transitions do not appears in visualizer.

**Expected Result**

Eventless transitions appear in visualizer.

**Actual Result**

Eventless transitions do not appears in visualizer.

**Reproduction**

https://xstate.js.org/viz/?gist=d7aaaddc8e783bda1b05af66a75091de

**Additional context**

Please see `always` key in `updating` state in repro above.

Thanks so much for this library. It's beautiful!

**Comment by davidkpiano** [comment]
Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead. It is kept up-to-date with the latest XState.

**Comment by dminkovsky** [comment]
Awesome thanks a lot.
