### ISSUE TITLE
Semantics related to transient transitions

### ISSUE THREAD

**Issue by zarkomijailovic** [davidkpiano/xstate#1487]
## Bug or feature request?

Seems like a bug because the logic (or ordering) of execution of actions and guards seems wrong.

## Description:

Imagine the following simple statechart: it has two states 'a' and 'b' and one conditional eventless transition going from 'a' to 'b'. I would expect the abMachine to land in state 'b' after it is being started, but it stays in state 'a'. Seems like that eventless transitions's guard is executed before entry action of state 'a', which seems wrong to me, as it doesn't reflect the logic of the state machine. 

```javascript
  const abMachine = Machine({
    id: 'abMachine',
    initial: 'a',
    context: {
      value: 0
    },
    states: {
      a: {
        entry: ['aEntry'],
        on: {
          '': {
            target: 'b',
            cond: 'isReadyForB'
          }
        }
      },
      b: {
        entry: ['bEntry']
      }
    }
  }, {
    guards: {
      isReadyForB: (context) => {
        console.log('isReadyForB');
        return context.value > 0;
      }
    },
    actions: {
      aEntry: (context) => {
        context.value++;
        console.log('a');
      },
      bEntry: () => {
        console.log('b');
      }
    }
  });
```

## (Bug) Expected result:

After starting the abMachine I would expect it to land in state b, since the entry action of state 'a' increases the context value from 0 to 1, and then the eventless transition's guard should evaluate to true (since now the context.value is greater than 0) and move the machine to state 'b'.

## (Bug) Actual result:

The abMachine stays in the state a, since it seems like the eventless transition's guard is evaluated before the entry action of state 'a', which is semantically wrong. If we are leaving the state it is expected to be able to see the results of state's entry (and exit) actions in the guards that follow, right?

## (Bug) Potential fix:

Not really confident about the fix.

**Comment by davidkpiano** [comment]
You are mutating `context`, which you should not be doing. Please use `assign()` and see the docs on how to properly update context: https://xstate.js.org/docs/guides/context.html

If you still are having issues after making the above change, please create a [CodeSandbox (XState template)](https://codesandbox.io/s/xstate-example-template-qcwed) reproduction of this, and we can reopen.

Thanks!

**Comment by zarkomijailovic** [comment]
Thanks David, I've tried with updating the context using assign and it works nicely now. Would you be so kind to tell me why is context access (actually context mutation) designed this way, just curious...

**Comment by davidkpiano** [comment]
Why it is immutable? This prevents bugs (as you have seen), if that's what you were asking.
