### ISSUE TITLE
Hydrating a machine from localStorage doesn't work without an existing key

### ISSUE THREAD

**Issue by TheDutchCoder** [davidkpiano/xstate#1490]
**Description**

The guides show how to hydrate state from (e.g.) localStorage, however this will crash xstate if the key doesn't exist: https://github.com/davidkpiano/xstate/blob/master/docs/guides/states.md

**Expected Result**

The State to resolve to the machine's initial state

**Actual Result**

xstate crashes and throws this error:
```
// Code
const stateDefinition = JSON.parse(localStorage.getItem('auth-state'))
const previousState = State.create(stateDefinition)
const resolvedState = authMachine.resolveState(previousState)

// Thrown Error
State.js?2eb3:75 Uncaught TypeError: Cannot read property 'value' of null
    at new State (State.js?2eb3:75)
```

**Reproduction**
https://codesandbox.io/s/confident-waterfall-7linq?file=/src/index.js

**Additional context**
I think the docs should either be updated, or, ideally, the State should fall back to the machine's defaultstate (probably by passing it in?)

**Comment by TheDutchCoder** [comment]
One way around this, is to use the initial state of the machine as a fallback:
```
// Code
const stateDefinition = JSON.parse(localStorage.getItem('auth-state')) || authMachine.initialState
const previousState = State.create(stateDefinition)
const resolvedState = authMachine.resolveState(previousState)
```

**Comment by davidkpiano** [comment]
Feel free to open a PR updating the docs for this 🙏
