### ISSUE TITLE
Actions (fns) are not being executed

### ISSUE THREAD

**Issue by eth0lo** [davidkpiano/xstate#150]
## Bug or feature request?
Bug

## Description:
Actions that are a function does not get executed with the extState and the event (this is mentioned in the [documentation](http://davidkpiano.github.io/xstate/docs/#/api/actions) or at least that's what I infer from it).

Example

```js
const { Machine } = require('xstate')

const trackChange = (extState, event) => ({
  type: 'trackLightsChange',
  payload: {
    location: extState.location,
    event
  }
})

const lightMachine = Machine({
  key: 'lights',
  initial: 'green',
  states: {
    green: {
      on: { change: { yellow: { actions: [trackChange] } } }
    },
    yellow: { }
  }
})

const transition = lightMachine.transition(lightMachine.initialState, 'change', { location: [41.3896668, 2.1689342] })
console.log(transition.actions[0])
```

## (Bug) Expected result:

```js
{
  type: 'trackLightsChange',
  payload: {
    location: [41.3896668, 2.1689342],
    event: 'change'
  }
}
```

## (Bug) Actual result:

```js
[Function: trackChange]
```

### Notes

While the documentation says what I'm describing the tests actually point to the "error" is correct; so I don't know which one it is.

**Comment by davidkpiano** [comment]
Right, they're not meant to be executed:

> Actions in xstate represent the side-effects that transitioning from/to a state can produce. These actions are never executed in xstate...

What you're trying to do is dynamically send a new event. The `actions` property on the `State` object returns you an array of actions that your interpreter will then execute.

**Comment by eth0lo** [comment]
Why I don't understand is what the reason on imposing params on the function

> - function, a named function with two arguments (since 3.3):
>   - extState - the extended state
>   - event - the EventObject associated with the action

**Comment by davidkpiano** [comment]
> Is this meant to guide other projects for interpreters?

Yes. And the official xstate interpreter (coming in an upcoming version of xstate) will use that signature.
