### ISSUE TITLE
Visualizer: Cancelling a timer isn't properly visualized

### ISSUE THREAD

**Issue by tklepzig** [davidkpiano/xstate#1501]
**Description**
When a delayed transition is cancelled, the visualizer still proceeds with filling the progress bar. Furthermore, when the state is reached again (and so the timer starts again), the progress bar remains full and no animation is shown. 

**Expected Result**
I'd expect to stop the progress bar animation and if the state is entered again starting the animation again.

**Actual Result**
The progress bar animation completes until the end and no further timer iterations are visualized.

**Reproduction**
Visualizer Gist (When sending the event `ALIVE_PING` the delayed transition is cancelled and referring to itself to start the timer again.)
https://xstate.js.org/viz/?gist=3be59851512f44a340a4cd493a544308

**Comment by FredyC** [comment]
I recommend you try out a new Inspector tool. The Viz is old and won't be probably maintained anymore.

http://statecharts.io/

**Comment by davidkpiano** [comment]
> I suspect it should eventually replace current Viz for quick online machine showcase.

Yes, that's the eventual plan.
