### ISSUE TITLE
@xstate/react state is wrong in useService when the machine stops or reaches a final state

### ISSUE THREAD

**Issue by emanueleperuffo** [davidkpiano/xstate#1503]
I use `useService` to get the state of an interpreted machine. All works perfectly, but when the machine reaches one of its final states and stops, `useService` returns the initial state of the machine, and not the final state. In fact, when the interpreter stops, it sets `this.initialized = false`.

I would expect the state to be the last state the stopped machine had.

https://github.com/davidkpiano/xstate/blob/37d5ed8606833f900a87f2a7de8f3f5059cf4deb/packages/xstate-react/src/useService.ts#L20

https://github.com/davidkpiano/xstate/blob/37d5ed8606833f900a87f2a7de8f3f5059cf4deb/packages/core/src/interpreter.ts#L505

**Comment by FredyC** [comment]
It would be probably best to reproduce this with CodeSandbox, might be some mistake on your side as well.

**Comment by emanueleperuffo** [comment]
https://codesandbox.io/s/elegant-buck-b3kz8?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js

**Comment by Andarist** [comment]
I've prepared a fix for this issue: https://github.com/davidkpiano/xstate/pull/1504 . Out of curiosity - why do u render something based on service in its final state? 🤔 I would consider this usually to be a somewhat conceptual anti-pattern, but I don't have any strong arguments for this right now. So I'm just wondering what kind of service you are utilizing this way.

**Comment by emanueleperuffo** [comment]
In a Gatsby website (static, so no server-side code) I have a service that controls the *allow cookies* cookie.

I have some scripts listening to the transitions of this service that start tracking analytics when the state changes to `'allowed'`.

Another script listening saves a cookie when the state changes to `'allowed'` to remember the user decision.

I also have a *CookieBanner* React component that shows the cookie banner if the service state is not `'allowed'`. It hides the banner when the service state changes to `'allowed'`.

On the first page load, this service is started with state `'allowed'` if the cookie remembering the user decision is found, with `'unknown'` otherwise.

When this service reaches the `'allowed'` state it makes sense to me that it should stop there. That's why I've declared this state as final and found the issue.

I'm curious to know why rendering something for a service in its final state is considered an anti-pattern, what would be a use case for a service in its final state, and why *xstate* has the concept of a final state if it's not intended to be used.

:wink:

**Comment by Andarist** [comment]
> I'm curious to know why rendering something for a service in its final state is considered an anti-pattern, what would be a use case for a service in its final state, and why xstate has the concept of a final state if it's not intended to be used.

It was just my intuition - as I've said: I didn't have any strong arguments to back this claim. So I wasn't certainly trying to discourage this right now, was just wondering what was the actual use case so I could assess it myself and maybe discard my intuition or confirm it 😅 

Final states are useful, for example, for communication - as reaching a final state sends a `done.invoke.*` event to the parent machine (if there is any).

You could also always listen to the machine and proceed with some logic when it reaches a final state - but mostly I've always considered to sort-of a discrete event - happening in that single moment of time and not really a continuous state that can be just read freely.

My intuition comes from the fact that usually actors pop in and pop out of the system and before they appear in it you shouldn't quite access them (they don't exist up to that point in time, right?) and in a similar manner when they pop out (are stopped or have reached their final state) they probably shouldn't be accessible either.

That being said - your use case seems reasonable and this is certainly convenient in this case. The frontend techniques/needs also might differ from the backend ones, so this is probably fine.

**Comment by emanueleperuffo** [comment]
> You could also always listen to the machine and proceed with some logic when it reaches a final state - but mostly I've always considered to sort-of a discrete event - happening in that single moment of time and not really a continuous state that can be just read freely.

Correct. I guess that when the service reaches the final state it doesn't call the listeners anymore. But a listener doesn't need to know if a service reached its final state, it just needs the state.

That's because I think of services (with *service* I mean interpreted machines, those accessed with `useService`) as some sort of *global* machines, contrary to their *local* alternative (those accessed with `useMachine`). Does it make sense?

> My intuition comes from the fact that usually actors pop in and pop out of the system and before they appear in it you shouldn't quite access them (they don't exist up to that point in time, right?) and in a similar manner when they pop out (are stopped or have reached their final state) they probably shouldn't be accessible either.

I think I wasn't talking about actors here, or are actors and services the same thing?

**Comment by davidkpiano** [comment]
> I think I wasn't talking about actors here, or are actors and services the same thing?

They are (at least from a high-level view.)
