### ISSUE TITLE
entry for state with eventless transition called after next state is entered

### ISSUE THREAD

**Issue by dminkovsky** [davidkpiano/xstate#1508]
**Description**

If a state defines `entry` but also declares eventless transitions, upon entry into that state, the `entry` action is called after the eventless transition is taken and the system is already in the next state. 

**Expected Result**

If a state defines `entry` and also an eventless transition, its `entry` action is called at least before `entry` of the state taken due to the eventless transition.

**Actual Result**

`entry` in a state with eventless transitions is called after the transition to the next state.

**Reproduction**

https://codesandbox.io/s/always-entry-s5vlk?file=/src/App.tsx. The complete code listing copied here:

```
import * as React from "react";
import "./styles.css";
import { Machine, assign } from "xstate";
import { useMachine } from "@xstate/react";

interface Context {
  value: string;
}

const machine = Machine<Context>({
  id: "machine",
  strict: true,
  initial: "A",
  context: {
    value: ""
  },
  states: {
    A: {
      entry: assign({
        value: () => {
          console.log("called enterA");
          return "value";
        }
      }),
      on: {
        TRANSACTION: "B"
      }
    },
    B: {
      entry: () => console.log("called enterB"),
      always: "A"
    }
  }
});

export default function App() {
  const [state, send] = useMachine(machine);
  console.log("current state", JSON.stringify(state.value));
  return <button onClick={() => send("TRANSACTION")}>GO</button>;
}
```

In this example, the system starts in state `A`. The logs read:

```
called enterA 
current state  "A" 
```

Click the button to transition to state `B`, the new logs are:

```
called enterA 
called enterB 
current state  "A"
```

I would have expected them to be:

```
called enterB
called enterA 
current state  "A"
```

because `B` was entered due to the button click, which caused the transition back to `A`.

Perhaps this is because states with eventless transitions aren't actually "entered"? If so, maybe the entry for such states should never run at all? It was very unexpected for me that, instead, the run entry action runs after the transition to the next state. This example is contrived, but in my use-case, I was trying to use `entry` of a state with an eventless transition to set context before the state being transitioned to, which failed due to this behavior. 

**Additional context**

There are some similar-seeming issues but I wasn't sure if they were the same. Apologies if this is a dupe or if I missed something in the docs.

**Comment by Andarist** [comment]
I've described the issue that you are experiencing [here](https://github.com/davidkpiano/xstate/issues/1403#issuecomment-681858775).

**Comment by dminkovsky** [comment]
Thank you! Will take a look and close this.

**Comment by Andarist** [comment]
Keep in mind that it's just a description of **why** this happens now. This is something I'd like to explore fixing in the future though because it is highly unintuitive and we get reports about this being surprising.

**Comment by dminkovsky** [comment]
Thank you. 

Per the issue you linked: I got the behavior I wanted with `pure`, even though the function has a side-effect (but not in the state machine: it cancels a network request). I would prefer to keep this an `entry` action because I only need to specify it in one place, vs many if it's not an `entry` action.
