### ISSUE TITLE
Cyclical Dependencies when using Inspect in a complex environment

### ISSUE THREAD

**Issue by Blacktiger** [davidkpiano/xstate#1511]
**Description**
I have a complex plugin-based application. In this application I build multiple bundles and load them at runtime with a single bundle containing common dependencies. I tried using `@xstate/inspect` in the common plugin which loads before my other plugins, however I get a problem with `JSON.stringify(service.machine)`. It finds cycles and fails to serialize the machine.

**Expected Result**
I should be able to configure inspect before the rest of my application code runs without

**Actual Result**

**Reproduction**
Creating a reproduction in the sandboxes proved difficult. You can see the current version of our code at https://github.com/sonatype/nexus-public. `components/nexus-rapture` is the common plugin that loads first, `plugins/nexus-coreui-plugin` is the bundle where most of the application views are created. I tried adding the dependency and the inspect method to `nexus-rapture/src/frontend/index.js`.

**Workaround**
I finally figured out that if I add the dependency to the "child" plugin (nexus-coreui-plugin) that things would work as expected. This means any plugin that wishes to use the inspector must declare its own copy of the dependency and call the inspect method. I should still be able to extract the library to the common parent to reduce the bundle size, but I don't understand why I can't just call inspect from the parent. If this is expected feel free to close this issue.

**Comment by davidkpiano** [comment]
Thanks for reporting. This is a duplicate: #1497 we'll track it there. 👍
