### ISSUE TITLE
Action order wrong?

### ISSUE THREAD

**Issue by nicklas-delphai** [davidkpiano/xstate#1520]
**Description**
In the [docs](https://xstate.js.org/docs/guides/actions.html#action-order) it says the action order goes: "exit actions", "transition actions", "enter actions". Either I don't understand what that's supposed to mean or it's not working as intended.
Whenever I call a non-assignment action on a transition and an assignment action on entry, it seems the assignment action on entry is called first.

**Expected Result**
The order of  actions is like advertised in the docs, meaning the interpreter first calls the transition actions and then the entry actions.

**Actual Result**
Assignment action on entry gets called first and then the non-assignment transition action.

**Reproduction**
https://codesandbox.io/s/stupefied-cherry-1iccr?file=/src/machine.ts
```js
Machine({
  id: "machine",
  initial: "stateB",
  context: {
    someNumber: 1
  },
  states: {
    stateA: {
      entry: assign({ someNumber: 42 })
    },
    stateB: {
      on: {
        CLICK: {
          target: "stateA",
          actions: ({ someNumber }) => console.log(someNumber)
        }
      }
    }
  }
});
```
In this reproduction repo we have two states: `stateA`, `stateB`. We start off in `stateB`. On button click we transition to `stateA` logging `someNumber`. On Entry we assign 42 to `someNumber`. I'd expect the logged number to be 1 because of the order of actions according to the [docs](https://xstate.js.org/docs/guides/actions.html#action-order), but it actually is 42 proving that the entry action gets called first.

**I just want to take the chance to express my gratitude for this awesome library: Thanks!**

**Comment by Andarist** [comment]
I've explained this issue [here](https://github.com/davidkpiano/xstate/issues/1403#issuecomment-681858775). Please read this to understand why this happens. That being said - I believe we need to fix this in the next major version, but it will take some time until we release it.

**Comment by nicklas-delphai** [comment]
Good to know, that this is a known issue. Maybe it's worth mentioning this in the docs. I spent quite some time banging my head. For anyone who might encounter a similar issue, I "fixed" this problem like this:

```js
Machine({
  id: "machine",
  initial: "stateB",
  context: {
    someNumber: 1
  },
  states: {
    stateA: {
      entry: assign({ someNumber: 42 }),
    },
    stateB: {
      on: {
        CLICK: {
          target: "stateA",
          actions: [
            assign({ savedNumber: ({ someNumber }) => someNumber }),
            ({ savedNumber }) => console.log(savedNumber)
          ]
        }
      }
    }
  }
});
```
