### ISSUE TITLE
Introduce SCXML <final /> state

### ISSUE THREAD

**Issue by mattiamanzati** [davidkpiano/xstate#153]
# Feature request
## Description:
Once a machine ends its execution, it should enter in a "final" state. That means that no more actions can trigger any machine state change.
Also, for compound machines, when the child enters in the final state and executes the onEntry handlers of the final state, it will also internally emit state.done.{id}, where id is the name of the owning machine.
More details are available on the official documentation.

## Potential implementation:
There may be multiple final nodes, so it would be to have a boolean `final` to indicate that the state is final.

```javascript
{
  "key": "light",
  "initial": "green",
  "states": {
    "green": {
      "on": {
        "TIMER": "yellow"
      }
    },
    "yellow": {
      "on": {
        "TIMER": "red"
      }
    },
    "red": {
      "on": {
        "state.done.red": "green"
      },
      "initial": "walk",
      "states": {
        "walk": {
          "on": {
            "PEDTIMER": "wait"
          }
        },
        "wait": {
          "on": {
            "PED_TIMER": "stop"
          }
        },
        "stop": {
          final: true // <= addition here
        }
      }
    }
  }
}
```

This is part of the standard SCXML definition: [final](https://www.w3.org/TR/scxml/#final)

**Comment by davidkpiano** [comment]
Just a note to self:

> Immediately thereafter, if the parent <state> is a child of a <parallel> element, and all of the <parallel>'s other children are also in final states, the Processor must generate the event done.state.id where id is the id of the <parallel> element.

So the `"done.state.STATE_ID"` event will be generated for each state that reaches a final substate, and also for parallel states where all of its children have reached their final substates.

I'm wondering if an `onFinal: [...]` property would be appropriate as sugar for `on: { 'done.state.STATE_ID': ... }`.

**Comment by davidkpiano** [comment]
The syntax for this in V4 will be:

```js
const machine = Machine({
  // ...
  states: {
    foo: {
      type: 'final'
    }
  }
});
```
