### ISSUE TITLE
useActor Actor argument defaults to any TContext

### ISSUE THREAD

**Issue by webberwang** [davidkpiano/xstate#1547]
**Description**

The `useActor` does not pass generic into `Actor`

https://github.com/davidkpiano/xstate/blob/5fcc6c759365ab870db3dab834abe57ba8c05e50/packages/xstate-react/src/useActor.ts#L5-L7

So context defaults to `any`

https://github.com/davidkpiano/xstate/blob/5fcc6c759365ab870db3dab834abe57ba8c05e50/packages/core/src/Actor.ts#L13-L16

Shouldn't use `useActor` take a `TContext` so we can have better typing for `Actor`?

```
const actor = {} // <-- always default to TContext = any
const [] = useActor(actor)
```

<img width="723" alt="useActor_d_ts_—_codelab__Workspace_" src="https://user-images.githubusercontent.com/26264925/95665031-71f9c800-0b01-11eb-85d7-9902edb88c20.png">

**Expected Result**

I'm currently overriding it like this

```typescript
declare module '@xstate/react' {
  function useActor<TContext, TEvent extends EventObject, TEmitted = any>(
    actorRef: ActorRefLike<TEvent, TEmitted> | Actor<TContext, TEvent>,
    getSnapshot?: (actor: typeof actorRef) => TEmitted,
  ): [TEmitted, Sender<TEvent>]
}
```

**Comment by davidkpiano** [comment]
This is no longer an issue in the latest `@xstate/react`
