### ISSUE TITLE
Is it possible to define default (catch all) transition for a particular state?

### ISSUE THREAD

**Issue by chentsulin** [davidkpiano/xstate#155]
## Bug or feature request?

Question or feature request.

## Description:

In `switch...case`or [pattern-matching](https://github.com/tc39/proposal-pattern-matching) syntax:

```js
switch (value) {
  case 1:
    // 
  case 2: 
    //
  default:
    // .... 
}
```

There is a way to catch all of other unmatched values using `default` or `_`. Is there any approach to do this in xstate?

## (Feature) Potential implementation:

**Required!** If you would like to see a feature or enhancement make its way to xstate, please describe:
- What the API would look like

Use `_`  to catch all of non `SOMETHING` event:

```js
{
  states: {
    a: {
      on: {
        SOMETHING: 'b',
        _: 'c'
      }
    },
    b: {
      on: {}
    },
    c: {
      on: {}
    },
  }
}
```

or `'*'`:

```js
{
  states: {
    a: {
      on: {
        SOMETHING: 'b',
        '*': 'c'   // <- add quotes to avoid SyntaxError
      }
    },
    b: {
      on: {}
    },
    c: {
      on: {}
    },
  }
}
```

- If this is a breaking change

Probably No. If we do not name any events to `_` or `*`.

- If this is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)

Probably yes? As `*` event:

```
<state id=s">
   <transition event="e" cond="x==1" target="s1"/>
   <transition event="e" target="s2"/>
   <transition event="*" target="s3"/>
</state>
```

**Comment by davidkpiano** [comment]
I think (to follow with the SCXML spec) we should both support:

- `*` for any event without an explicit transition on the state node (explicitly defined events would take precedence)
- `foo.*` (`foo.bar.*`, etc.) for matching namespaced events

**Comment by elyzov** [comment]
What about partial wildcards support in XState? As I see, in PR #578 was added only global wildcard support. Is there any plans for this?

**Comment by Andarist** [comment]
@elyzov do you refer to the [event descriptors](https://www.w3.org/TR/scxml/#EventDescriptors) ending with `.*` (like `foo.*)?

**Comment by elyzov** [comment]
@Andarist Exactly! I think it's very useful ability to redirect bunch of events through one route.

**Comment by davidkpiano** [comment]
> What about partial wildcards support in XState? As I see, in PR #578 was added only global wildcard support. Is there any plans for this?

I think this should be supported, and it's now possible with TypeScript 🎉 

Want to create a new issue so we can track this?  It is an SCXML feature.

**Comment by elyzov** [comment]
> Want to create a new issue so we can track this? It is an SCXML feature.

I've created the idea #1716
