### ISSUE TITLE
Typescript Error When importing `createMachine` from `xstate/es` build, when using `@xstate/immer`

### ISSUE THREAD

**Issue by Ben52** [davidkpiano/xstate#1552]
**Description**
Using XState with XState-Immer's `createUpdater` function, I'm getting a type error from Typescript. 
After copying an pasting the Doc's example, and not getting the type error, I realized the difference is whether the import is `import {createMachine} from 'xstate'` vs. `import {createMachine} from 'xstate/es'`

**Expected Result**
I expected there to be no type error when using the es build, just as there is no type error when using the plain xstate build.

**Actual Result**
There was a type error

**Reproduction**
https://codesandbox.io/s/mystifying-raman-o9c89?file=/src/index.ts

**Comment by davidkpiano** [comment]
Not sure if this is valid - you should be using `'xstate'` rather than `'xstate/es'` in your TypeScript projects.
