### ISSUE TITLE
Please include LICENSE file in repo and distributions

### ISSUE THREAD

**Issue by RobertBorg** [davidkpiano/xstate#1557]
In order to properly apply the MIT license you need to actually have the license with copyright notice and year somewhere. This is usually included in a LICENSE file.

see https://opensource.org/licenses/MIT

**Comment by davidkpiano** [comment]
This is here: https://github.com/davidkpiano/xstate/blob/master/LICENSE

**Comment by RobertBorg** [comment]
Ah, you're right it is in the repo but missing from distributions.
see 
https://unpkg.com/browse/xstate@latest/
https://unpkg.com/browse/@xstate/react@latest/

**Comment by davidkpiano** [comment]
Would you mind making a PR adding the license there? Would be greatly appreciated 🙏
