### ISSUE TITLE
[@xstate/react] ...is not assignable to parameter of type 'Event<EventObject>' error when using useService(service)

### ISSUE THREAD

**Issue by zeekrey** [davidkpiano/xstate#1564]
**Description**
The current docs don't show me how to use **xstate** and **@xstate/react** in **typescript**. I used [https://xstate.js.org/docs/guides/typescript.html#using-typescript](https://xstate.js.org/docs/guides/typescript.html#using-typescript) to configure everything but still got type issues:

```
Argument of type '{ type: string; duration: number; }' is not assignable to parameter of type 'Event<EventObject>'.
  Object literal may only specify known properties, and 'duration' does not exist in type 'EventObject'.ts(2345)
```

This is what causes the error:

`const [state, send] = useService(service);`

And this works:

`const [state, send] = useService<LightContext, LightEvent>(service);`

**Expected Result**
If this `const [state, send] = useService(service);` could work with typescript (I'm still playing with typescript) then this should be implemented. Otherwise some hints in the docs would be cool.

**Actual Result**
```
Argument of type '{ type: string; duration: number; }' is not assignable to parameter of type 'Event<EventObject>'.
  Object literal may only specify known properties, and 'duration' does not exist in type 'EventObject'.ts(2345)
```

**Reproduction**
[https://codesandbox.io/s/frosty-worker-6tjjv?file=/src/Step.tsx](https://codesandbox.io/s/frosty-worker-6tjjv?file=/src/Step.tsx)

**Additional context**
xstate: 4.13.0
@xstate/rect: 1.0.1

**Comment by davidkpiano** [comment]
Your prop typings are too loose (that is, you didn't even provide any) for the `<Step>` component. This is what it should be:

```diff
-export function Step({ service }) {
+export function Step({ service }: { service: Interpreter<LightContext, any, LightEvent>}) {
  // const [state, send] = useService<LightContext, LightEvent>(service);
  const [state, send] = useService(service);
  return (
    <div className="App">
      <h1>Hello CodeSandbox</h1>
      <h2>Start editing to see some magic happen!</h2>
      <Step service={service} />
      <button onClick={() => send({ type: "PED_COUNTDOWN", duration: 1 })}>
        PED_COUNTDOWN
      </button>
    </div>
  );
}
```

**Comment by mwangaben** [comment]
import { assign, createMachine as MyBooking } from 'xstate';
      import { Seat } from 'src/Typings/Seat';
      import { fetchSeats } from 'src/stateMachines/BookingData';
      import { refetchSeats } from './BookingData';
    
        interface FetchContext {
          seats?: Seat[];
          error?: Error;
          slug?: string;
        }
        
        type InitialContext = FetchContext & {
          seats: undefined;
          error: undefined;
          slug: string;
        };
        
        type LoadingContext = FetchContext & {
          seats: Seat[];
          error: undefined;
          slug: string;
        };
        
        type ReadyContext = FetchContext & {
          seats: Seat[];
          error: undefined;
          slug: string;
        };
        type SuccessContext = FetchContext & {
          seats: Seat[];
          error: undefined;
          slug: string;
        };
        
        type FailureContext = FetchContext & {
          seats: undefined;
          slug: string;
          error: Error;
        };
        
        type InitialState = { value: 'initial'; context: InitialContext };
        type LoadingState = { value: 'loading'; context: LoadingContext };
        type SuccessState = { value: 'success'; context: SuccessContext };
        type ReadyState = { value: 'ready'; context: ReadyContext };
        type FailureState = { value: 'failure'; context: FailureContext };
        
        type FetchEvent =
          | { type: 'FETCH' }
          | { type: 'RETRY' }
          | { type: 'FRESH'; slug: string };
        
        type FetchState =
          | InitialState
          | LoadingState
          | SuccessState
          | ReadyState
          | FailureState;
        
        export const bookingMachine = MyBooking<FetchContext, FetchEvent, FetchState>({
          id: 'booking',
          initial: 'loading',
          context: {
            slug: '',
            seats: undefined,
            error: undefined,
          },
        
          states: {
            initial: {
              on: {
                FETCH: 'loading',
              },
            },
            ready: {
              on: {
                FETCH: 'loading',
                FRESH: {
                  target: 'refetch',
                  actions: assign({
                    slug: (_context, event) => event.slug,
                  }),
                },
              },
            },
        
            refetch: {
              invoke: {
                id: 'refetching',
                src: (context, _event) => refetchSeats(context.slug),
                onDone: {
                  target: 'success',
                  actions: assign({
                    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
                    seats: (_context, event) => event.data,
                  }),
                },
                onError: {
                  target: 'failure',
                  actions: assign({
                    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
                    error: (_context, event) => event.data,
                  }),
                },
              },
            },
        
            loading: {
              entry: assign({
                // eslint-disable-next-line @typescript-eslint/no-unused-vars
                seats: (context, _event) => context.seats || [],
                // eslint-disable-next-line @typescript-eslint/no-unused-vars
                error: (_context, _event) => undefined,
              }),
        
              invoke: {
                id: 'fetchSeats',
                // eslint-disable-next-line @typescript-eslint/no-unused-vars
                src: (_context, _event) => fetchSeats(),
                onDone: {
                  target: 'success',
                  actions: assign({
                    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
                    seats: (_context, event) => event.data,
                  }),
                },
                onError: {
                  target: 'failure',
                  actions: assign({
                    // eslint-disable-next-line @typescript-eslint/no-unsafe-return
                    error: (_context, event) => event.data,
                  }),
                },
              },
            },
            success: {
              after: {
                2000: 'ready',
              },
            },
            failure: {
              on: {
                RETRY: 'loading',
              },
            },
          },
        });
        `


When i do send event from the Vue component i get  this error 

![Screenshot 2022-04-05 at 20 21 38](https://user-images.githubusercontent.com/17113999/161814332-b95a55da-04e3-4c54-96ec-e084b60f0180.png)

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.
