### ISSUE TITLE
Can Visualizer be used with guards?

### ISSUE THREAD

**Issue by tastywheat** [davidkpiano/xstate#157]
The visualization tool seems to only accept JSON. If I decide to use guards or actions (as functions), is the Visualizer unusable?

**Comment by davidkpiano** [comment]
Right, but what you can do is have named guards:

```js
const lightMachine = Machine({
  // ...
  states: {
    green: {
	  on: { TIMER: { yellow: { cond: 'someCond' } } }
	}
  }
}, {
  guards: {
	someCond: (xs, e) => /* evaluate condition here */
  }
});
```

And then copy-paste the valid JSON configuration into the visualizer. The future visualizer will work with JS.

**Comment by iKethavel** [comment]
Hello, @davidkpiano! First of all - thanks for xState :)
Secondly, is it possible to visualize high-level guards like this  `guard: and(['cond1', 'cond2'])` in Visualizer or vscode extension? For now i receive  
<img width="476" alt="image" src="https://github.com/statelyai/xstate/assets/15525103/58b53929-5cad-4746-8dc0-ca9febc8f7cb">
