### ISSUE TITLE
Documentation - React example 

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#158]
## Bug
In the [react gallery app example](https://codepen.io/davidkpiano/pen/dJJMWE?editors=1010), line 82. If there are multiple actions that change the component's state, only the last 1's changes will be registered.

## Current:
```
const nextState = nextGalleryState.actions
      .reduce((state, action) => this.command(action, event) || state, undefined);
```

## Potential fix:
```
const nextState = nextGalleryState.actions.reduce(
            (state, action) => ({
                ...state,
                ...this.command(action, event)
            }), 
            undefined
        )
```

**Comment by bradwoods** [comment]
I forked the gallery app Codepen and added the potential fix [here](https://codepen.io/bradwoods/pen/OwoaEB?editors=0010). I also added an example of how to handle  any **onEntry** actions the initial state may have. Changes:

```
-- const nextState = nextGalleryState.actions
      .reduce((state, action) => this.command(action, event) || state, undefined);

++ const nextState = this.calcNextLocalState(nextGalleryState.actions)
```

```
++ calcNextLocalState = (actions) => 
    actions.reduce(
      (state, action) => ({
        ...state,
        ...this.command(action, event)
      }), 
      undefined
    )
```

```
++ componentDidMount() {
    const nextState = this.calcNextLocalState(galleryMachine.initialState.actions)

    this.setState({
      ...nextState,
    })
  }
```

**Comment by rdickert** [comment]
I was about to post the same thing, but it is already reported. Nice work, @bradwoods! My solution was the same but included a guard against a command returning `null`:

```
    const nextState = nextLoginStatus.actions.reduce(
      (state, action) => ({ 
        ...state,
        ...(this.command(action, event) || {})
      }),
      undefined,
    );
```

I also like the solution for initial state `onEntry`.

**Comment by davidkpiano** [comment]
Added a better React example: https://xstate.js.org/docs/examples/todomvc.html
