### ISSUE TITLE
Can't trigger two parallel actions simultaneously

### ISSUE THREAD

**Issue by felippenardi** [davidkpiano/xstate#16]
I'm trying to trigger two transitions like this:

```
  trigger = (action) => {
    this.setState(
      stateMachine.transition(this.state, action).value
    );
  }

 this.trigger('ACTION_1');
 this.trigger('ACTION_2');
```

But it will only execute the first, unless I wrap the second in a `setTimeout`.

Thing is: given that these two actions are not conflicting because they act in different paralleled states, is there a reason I should not be doing that or is it something that can be improved in xstate?

**Comment by davidkpiano** [comment]
What does the machine look like?

**Comment by mehdi-cit** [comment]
Interesting!
I was about to say that Finite State machine means the machine can be in exactly one state at anytime -me thinks- but you got me thinking... It might turn out interesting to have a way to automatically/programmatically alter the state machine (like listing all possible combinations of parallel states and adding each possible combination as its own state). That would go against @davidkpiano advise to use a pen and paper when designing your state machine!!

**Comment by davidkpiano** [comment]
A good solution for the original problem would be to have a single action that has transitions in both parallel states. So instead of doing two things at the same time, you do one thing that causes parallel transitions.
