### ISSUE TITLE
Question: How to specified a nested state in JSON

### ISSUE THREAD

**Issue by chungvle** [davidkpiano/xstate#161]
I'd like to load machine configuration from a JSON file, and have two questions:
1. Is there a handy way to do that other than writing my own XMLHttpRequest?
2. When a machine has a nested state like ...pedestrianStates as in the traffic light example, how should I specify that in JSON?
Many thanks.

**Comment by chungvle** [comment]
Thanks, David. I need to clarify my second question. In my JSON config for the light machine, I'd like to specify the fact that it includes a nested state, e.g. pedestrianStates. After the data is parsed, the resulting configuration in javascript should have the spread "...pedestrianStates" in it as in the code example. What is the expression in JSON to do that?

**Comment by avaragado** [comment]
You can’t do that in JSON. Spreads like “...pedestrianStates” are JavaScript syntax, not JSON.

**Comment by chungvle** [comment]
Thanks for pointing that out. What I am trying to figure out is how to specify nested states in a state configuration. Let me explain a workaround as an example.
In the state configuration for "red" in the light example, I replaced the spread ...pedestrianStates with nestedState: 'pedestrianStates':
         red: {
            on: {
              TIMER: 'green',
              POWER_OUTAGE: 'red'
            },
            onEntry: 'setLightRed',
            //...pedestrianStates
            nestedState: 'pedestrianStates'
          }
Then before passing the lightConfig to Machine, I replaced nestedState with the states in pedestrianStates using:
      nestedState = lightConfig.states.red.nestedState;
      delete lightConfig.states.red.nestedState;
      lightConfig.states.red = {...lightConfig.states.red, ...eval(nestedState)};
In the state config schema, is there a notion of nested state? and is it possible to do the above without writing the extra code? Thanks.

**Comment by mogsie** [comment]
I believe you're looking for the `states` key:

```
red: {
  on: {
    TIMER: 'green',
    POWER_OUTAGE: 'red'
  },
  onEntry: 'setLightRed',
  initial: 'walk'
  states: {
    walk: {
      on: {
        PED_COUNTDOWN: 'wait'
      }
    },
    wait: {
      on: {
        PED_COUNTDOWN: 'stop'
      }
    },
    stop: {}
  }
}
```

`states` indicates that there are nested states, and `initial` is required to tell xstate which one is the default state, when the parent is entered.

**Comment by chungvle** [comment]
Using "states", how do I specify that they're coming from a variable, e.g. pedestrianStates, and how do I get xstate to expand that out to the full states?

**Comment by chungvle** [comment]
Thanks, Avaragado. That was what I did in my prototype. I will now close this issue.
