### ISSUE TITLE
@xstate/inspect - local NextJS - stuck at Waiting for Connection

### ISSUE THREAD

**Issue by a-y-u-s-h** [davidkpiano/xstate#1616]
**Description**

I'm trying to use Xstate Inspect in a NextJS application but it gets stuck at 'waiting for connection'. This happens in any local NextJS project (but it **doesn't happen on codesandbox**). When using inspector, I've put `devTools: true` as an option for useMachine, and I have tried multiple ways (mentioned below) to run `@xstate/inspect` but none of them do the trick. Here are a few ways I tried calling `inspect({ iframe: false })` in `_app.js` which is the entry point of a NextJS app:

### **Outside of application component** 

This doesn't work because `window` is undefined at this point. So, have to keep it inside `React.useEffect` (this goes against what @davidkpiano mentioned in a [closed issue](https://github.com/davidkpiano/xstate/issues/1467) ([here's another related issue](https://github.com/davidkpiano/xstate/issues/1583)).

```jsx
import React from "react"
import Systems from "@/systems"
import theme from "@/settings/theme"
import { ThemeProvider as Theme } from "theme-ui"
import "@/settings/theme/global.css"

import { inspect } from "@xstate/inspect"

inspect({ iframe: false }) 

export const Application = props => {
  const { Component, pageProps } = props
  return (
    <Theme theme={theme}>
      <Systems>
        <Component {...pageProps} />
      </Systems>
    </Theme>
  )
}

export default Application

``` 

### Inside React.useEffect

These work halfway (there's no `window` is undefined error) but they show the `Waiting for connection` screen and errors about JS sourcemaps in developer tools console. There are multiple ways of getting this new bug, I've mentioned 2 of them below - 

```jsx
import React from "react"
import Systems from "@/systems"
import theme from "@/settings/theme"
import { ThemeProvider as Theme } from "theme-ui"
import "@/settings/theme/global.css"

export const Application = props => {

  React.useEffect(() => {
    import("@xstate/inspect").then(({ inspect }) => {
      inspect({ iframe: false })
    })
  }, [])

  const { Component, pageProps } = props
  return (
    <Theme theme={theme}>
      <Systems>
        <Component {...pageProps} />
      </Systems>
    </Theme>
  )
}

export default Application

``` 

```jsx
import React from "react"
import Systems from "@/systems"
import theme from "@/settings/theme"
import { ThemeProvider as Theme } from "theme-ui"
import "@/settings/theme/global.css"
import { inspect } from "@xstate/inspect"

export const Application = props => {
  React.useEffect(() => {
    inspect({ iframe: false })
  }, [])
  const { Component, pageProps } = props
  return (
    <Theme theme={theme}>
      <Systems>
        <Component {...pageProps} />
      </Systems>
    </Theme>
  )
}export default Application

``` 

**Expected Result**
Inspector should work fine.

**Actual Result**

Here's what you get with code above:

![2020-11-06_00-25-31_screenshot](https://user-images.githubusercontent.com/19586719/98284245-d7d55480-1fc6-11eb-9f4b-ccbc82e5240e.png)

![2020-11-06_00-25-51_screenshot](https://user-images.githubusercontent.com/19586719/98284262-dc9a0880-1fc6-11eb-83fa-8d78bd7993d0.png)

**Reproduction**
Codesandbox cannot be added because this issue happens on local NextJS applications. [Here's a demo repository](https://github.com/a-y-u-s-h/xstate.playground).

**Additional context**
Xstate version: 4.14.0
Xstate Inspect version: 0.2.0
Xstate React version: 1.0.2

**Comment by davidkpiano** [comment]
The way to do this in NextJS would be to [run the code client-side only](https://flaviocopes.com/nextjs-server-client-code/):

```js
if (typeof window !== 'undefined') {
  inspect({ iframe: false });
}
```

**Comment by a-y-u-s-h** [comment]
Thanks a lot!

**Comment by j-funk** [comment]
Just ran into this!

**Comment by davidkpiano** [comment]
> Just ran into this!

Are you currently having issues?

**Comment by j-funk** [comment]
> 

This solved it, I also since I posted this ran into the bit that's mentioned in the docs here:

https://xstate.js.org/docs/packages/xstate-inspect/#faqs

It may help to make this more prominent / searchable in the docs
