### ISSUE TITLE
npm i xstate @xstate/react does not work with react@17.0.1

### ISSUE THREAD

**Issue by titib** [davidkpiano/xstate#1635]
**Description**

npm i xstate @xstate/react does not work with react@17.0.1

**Expected Result**

Install @xstate/react

**Actual Result**

npm i xstate @xstate/react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: coucou@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from @xstate/react@1.0.2
npm ERR! node_modules/@xstate/react
npm ERR!   @xstate/react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Reproduction**

**Additional context**

I created from scratch a new project with React + Typescript (npx create-react-app)

**Comment by davidkpiano** [comment]
Seems like we need to support multiple peer dependencies (cc. @Andarist)
