### ISSUE TITLE
Question: How to restart FSM from a persisted state

### ISSUE THREAD

**Issue by laurentpierson** [davidkpiano/xstate#164]
Hi,

I need to be able to persist the current state of an FSM (including nested parallel FSMs) so that it can be restarted in the same state later in case of an application crash.

Is there any way to do that? I see there is an 'initialState' property on StateNode but it's readonly.

Thanks,

Laurent

**Comment by davidkpiano** [comment]
Can you give me more information on your use case? You should be able to do this manually if you're keeping the "current state" somewhere... just set the current state to that persisted state at the beginning instead of the initial state.

**Comment by laurentpierson** [comment]
I'm defining multiple FSMs that are nested together. Some are parallel, some are not.

Here's the xviz rendering of the first part of FSM to give you an idea: [xviz rendering](https://musing-rosalind-2ce8e7.netlify.com/?machine=%7B%22key%22%3A%22Flow%22%2C%22initial%22%3A%22ready%22%2C%22strict%22%3Atrue%2C%22states%22%3A%7B%22ready%22%3A%7B%22on%22%3A%7B%22onCreateCart%22%3A%22createCart%22%7D%7D%2C%22createCart%22%3A%7B%22key%22%3A%22cartCreation%22%2C%22initial%22%3A%22createCart%22%2C%22strict%22%3Atrue%2C%22states%22%3A%7B%22createCart%22%3A%7B%22onEntry%22%3A%22createCart%22%2C%22on%22%3A%7B%22onSuccess%22%3A%22fetchProductInfo%22%2C%22onFailure%22%3A%22failure%22%7D%7D%2C%22fetchProductInfo%22%3A%7B%22on%22%3A%7B%22onSuccess%22%3A%22success%22%2C%22onFailure%22%3A%22failure%22%7D%2C%22parallel%22%3Atrue%2C%22states%22%3A%7B%22fetchProductDescriptions%22%3A%7B%22initial%22%3A%22productDescriptionsRequesting%22%2C%22states%22%3A%7B%22productDescriptionsRequesting%22%3A%7B%22onEntry%22%3A%22requestProductDescriptions%22%2C%22on%22%3A%7B%22onSuccess%22%3A%22productDescriptionsRequested%22%7D%7D%2C%22productDescriptionsRequested%22%3A%7B%22on%22%3A%7B%22onProductDescriptionsProvided%22%3A%22productDescriptionsProvided%22%7D%7D%2C%22productDescriptionsProvided%22%3A%7B%22onEntry%22%3A%22saveProductDescriptions%22%7D%7D%7D%2C%22fetchProductPrices%22%3A%7B%22initial%22%3A%22productPricesRequesting%22%2C%22states%22%3A%7B%22productPricesRequesting%22%3A%7B%22onEntry%22%3A%22requestProductPrices%22%2C%22on%22%3A%7B%22onSuccess%22%3A%22productPricesRequested%22%7D%7D%2C%22productPricesRequested%22%3A%7B%22on%22%3A%7B%22onProductPricesProvided%22%3A%22productPricesProvided%22%7D%7D%2C%22productPricesProvided%22%3A%7B%22onEntry%22%3A%22saveProductPrices%22%7D%7D%7D%7D%7D%2C%22success%22%3A%7B%22onEntry%22%3A%22logSuccess%22%7D%2C%22failure%22%3A%7B%22onEntry%22%3A%22logError%22%7D%7D%7D%7D%7D).

 
We keep that FSM running in memory but we also want to be resilient in case of application crash. So, let's say we are in the states `productPriceRequesting` & `productDescriptionRequesting` of the parallel FSM called `fetchProductInfo` (as displayed in xviz):

`{
  "createCart": {
    "fetchProductInfo": {
      "fetchProductDescriptions": "productDescriptionsRequesting",
      "fetchProductPrices": "productPricesRequesting"
    }
  }
}`


But let's say our application crashes. How can I create a new instance of the FSM in these states instead of the typical initial state `ready` ?

Assuming I have initialized the machine using: `const machine = Machine(machineConfig)`, I wanted to manually set `machine.initialState` to the state(s) I had saved so that the FSM will start from these states, but the property is readonly.

How do you set the "current state" of the FSM then? 

KR,

Laurent

**Comment by laurentpierson** [comment]
Hi,

I have tested and it doesn't work because the initial state is a string so it can't contain a compound state like `{ "createCart": { "fetchProductInfo": { "fetchProductDescriptions": "productDescriptionsRequesting", "fetchProductPrices": "productPricesRequesting" } } }`.

Do you have any pointers as how to set the current state?

**Comment by davidkpiano** [comment]
Let's say your app looks like:

```js
// simplified - things like actions, etc. left out for brevity 

const initialState = machine.initialState;

let currentState = initialState;

function send(event) {
  currentState = machine.transition(currentState, event);
}
```

Then instead of `machine.initialState`, you would use your persisted state:

```js
const initialState = somePersistedStateValue
  ? State.from(somePersistedStateValue, someExternalState)
  : machine.initialState;

let currentState = initialState;

// ...
```

**Comment by laurentpierson** [comment]
Thanks a lot, it's working perfectly!
