### ISSUE TITLE
Visualizer: `always` transitions don't get rendered

### ISSUE THREAD

**Issue by mindrones** [davidkpiano/xstate#1640]
**Description**

`always` transitions don't get rendered in the visualizer

**Expected Result**

Be able to inspect guards in `always` transitions, like here: https://xstate.js.org/viz/?gist=7a144a4b8be8b3b9cf77ac3531f0f01a

<img width="466" alt="Screenshot 2020-11-18 at 23 01 16" src="https://user-images.githubusercontent.com/1309648/99598780-07865280-29f2-11eb-8203-c889b404d795.png">

**Actual Result**

No guards get rendered if within `always` transitions.

<img width="461" alt="Screenshot 2020-11-18 at 23 02 45" src="https://user-images.githubusercontent.com/1309648/99598915-3e5c6880-29f2-11eb-9e70-bd513d3b2e37.png">

**Reproduction**

https://xstate.js.org/viz/?gist=419c7ab6587378e52c94a44f78b44805

**Additional context**

Not sure where to read the Xstate version in the visualizer, we're using `"xstate": "^4.13.0"`.

**Comment by davidkpiano** [comment]
Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead.

More info: statecharts.io

**Comment by mindrones** [comment]
Hi @davidkpiano, how can I get a static link to a machine using the inspector?

Machines are first and foremost communication tools, so we need something like the visualizer to document things along the way without the need to run an app to see the machine: is this possible with statecharts.io?

Thanks!

**Comment by davidkpiano** [comment]
> is this possible with statecharts.io?

In the future, it will be - there will be a way to share and collaborate on machines and actor systems.

But for now, you can copy your machine to a CodeSandbox (no need to run an entire app) with the inspector set up: https://codesandbox.io/s/xstate-viz-template-f3dtr

**Comment by mindrones** [comment]
Thanks, am I right guessing the visualiser won't be maintained anymore?

**Comment by davidkpiano** [comment]
The visualizer will eventually be updated and become part of statecharts.io - the current visualizer is unmaintained.

**Comment by mindrones** [comment]
That's very useful info, thanks! 👍

**Comment by vuhrmeister** [comment]
Shouldn't be there a hint on the visualizer? I mean it's linked from the home page so this is the first place to look at. At least a banner telling me that this version is based on X.x would be nice to prevent confusion.

**Comment by mindrones** [comment]
I agree, visualising a machine and inspecting it at run time are two very different use cases  and inspection should never be prioritized over communication IMHO: before implementing a machine we discuss (sometimes at length) about the logic of the machines we are designing and we do this by sharing snapshots in the visualiser.

In the team there's also some disagreement about having a functionality that requires an external service to work and that takes a lot of screen estate: running the inspector on a laptop without an external screen is being quite problematic, if not impossible (you need to keep you app and the inspector open at the same times, which makes life quite difficult and using the inspector pointless). There are worries that statecharts.io would become a paid service in the future, causing vendor lock-in.

All in all the preferred solution would be a code editor addon so that the machine would be visualised locally, neas where you edit the code.
The visualiser code might be a separate, generic function that reads a machine object and generates a layout, so that you'd be able to render it where you want, with the technique you prefer.

If this is desirable we'd be glad to help :)

**Comment by davidkpiano** [comment]
@mindrones The inspector will always be free, and I am working on a solution to make it so that you can run it locally as well. That should solve the same use-case as the current visualizer.

Right now, the (outdated) visualizer already puts the machine into a "runtime" environment so that it can visualize it. The same thing can be accomplished with the inspector and code such as this:

```js
import { inspect } from '@xstate/inspect';
import { interpret, createMachine } from 'xstate';

inspect();

const machine = createMachine(/* ... */);
interpret(machine, { devTools: true });
```

Once I have the run-anywhere visualizer ready (currently it's baked into a Next.JS app), I'll update xstate.js.org/viz to essentially be the same as the above code.

**Comment by mindrones** [comment]
Ah that's great to hear, thanks for posting.
Also we have data visualisation skills in the team, can we help to improve the layout somehow?
Is it going to change or stay more or less the same?

**Comment by davidkpiano** [comment]
> Also we have data visualisation skills in the team, can we help to improve the layout somehow?

Absolutely. By the way, in `@xstate/graph`, there is a `toDirectedGraph(machine)` function that returns a friendly directed graph format (e.g., `{ children: ..., edges: ... }`) that allows you to more easily draw statecharts in any graph drawing library, like GraphViz, PlantUML, or ElkJS: https://xstate.js.org/docs/packages/xstate-graph/#api
