### ISSUE TITLE
Memory leak with stopped actor ?

### ISSUE THREAD

**Issue by lambda0xff** [davidkpiano/xstate#1642]
**Description**
after stopping a spawned actor and clearing its reference in context, `state.children` still retains the actor

**Expected Result**
the actor should be cleared from `state.children`

**Reproduction**
https://codesandbox.io/s/priceless-allen-ezjnd

**Comment by lambda0xff** [comment]
Using `actions.stop(ctx => { return ctx.refActor })` clears the actor from `state.children` but then `context` retains the actor.
Adding an action that assigns `null` to `ctx.refActor` causes a crash with an error message: `Uncaught TypeError: Cannot read property 'id' of null`

xstate: v4.14.0

**Comment by davidkpiano** [comment]
This cannot be fixed as-is for v4 because `assign(...)` actions are prioritized (wrongfully), which is fixed in v5.

However, you can use the `pure()` action creator as a workaround:

```js
    actions: {
      terminateActor: pure<Context, any>((ctx) => {
        return [
          assign({
            refActor: null
          }),
          actions.stop(ctx.refActor)
        ];
      })
    }
```
