### ISSUE TITLE
Top level entry/exit API issues

### ISSUE THREAD

**Issue by serhiipalash** [davidkpiano/xstate#1653]
Hi! We use XState for various state handling cases in our app. Each screen in the app has its own state machine. We would like to have a reliable way to do something on entering or exiting the screen. However it's not possible with XState.

1. If you add an "entry" property on top level of your machine and then use your machine with `useMachine` hook, "entry" will be fired twice (the bug is inside `xstate-react`)
2. If you add an "exit" property on top level of your machine, it does nothing (will not be fired on machine end)

It would be nice to have entry/exit working on top level as it seems to be logical.

**Comment by davidkpiano** [comment]
Hey @serhiipalash can you share code? Please create a [CodeSandbox (React template)](https://codesandbox.io/s/xstate-react-template-3t2tg) for this. Thank you!

**Comment by serhiipalash** [comment]
Hi @davidkpiano ! 

Here is a sandbox https://codesandbox.io/s/modest-gates-supxn

I tried again and `entry` works fine. It triggers actions twice only when it's an assign action, which is understandable as `useMachine` generates an initial state inside it (from code I saw). Sorry for misunderstanding. 

But top level `exit` still doesn't work. Check the sandbox. I think it should be fired on machine finish (on component unmount).

**Comment by serhiipalash** [comment]
We need `exit` API on machine itself to track analytics on screen close. 

We have settings screens in our app and they work very similar to iOS Settings, they don't have any "Save" button, user can toggle something and these changes are immediately applied. 

![Simulator Screen Shot - iPhone 8 - 2020-11-25 at 12 09 22](https://user-images.githubusercontent.com/14208343/100213263-151e6980-2f17-11eb-8105-63e8e6456118.png)

We want to track changed values on screen close. As we have a machine per screen, the correct place to have is `exit` node on machine itself. Attaching tracking on Close button press is not enough as the screen could be closed in another ways (swipe out on iOS and hardware back button on Android).

**Comment by Andarist** [comment]
This is related to the issue fixed by this PR: https://github.com/davidkpiano/xstate/pull/1566

The difference is that in there @davidkpiano has fixed calling exit handlers when reaching a final state (within private update method) and in here we deal with a slightly different situation because the machine gets canceled by something calling its `stop` method:
https://github.com/davidkpiano/xstate/blob/326b28d25535c8ce1520258b80a119f26847951b/packages/core/src/interpreter.ts#L489
which doesn't lead to an `update` call.

**Comment by serhiipalash** [comment]
Great! Thank you @Andarist !

**Comment by davidkpiano** [comment]
@serhiipalash The patch `4.14.1` should be released soon.

**Comment by serhiipalash** [comment]
@davidkpiano thank you! XState is a great library and the project feels really alive (comparing to some [other](https://github.com/tleunen/babel-plugin-module-resolver/issues/413) popular project your is the most alive 😄 ). 

We are migrating on XState in our RN app [Preggers](https://apps.apple.com/gb/app/preggers-pregnancy-baby/id1363479578), starting from screen level and later we want apply it on sub components level as well. We marked Hooks API as fully deprecated in favour of XState. We started 2 month ago and so far everything is fine in general. I'll try to share something from our experience in Discussions maybe next week. So far I found three minor "issues" in XState. If you are interested, here is the list

1. Naming in state config sometimes feels inconsistent
2. `useMachine` first render goes without resolved state. It's a small drawback comparing to `useSelector`.
3. State Definitions composability isn't high comparing to Robot, but that's a reasonable drawback for hight Declaratively and serialisation

**Comment by davidkpiano** [comment]
@serhiipalash Thanks, looking forward to your feedback! 

Also, for 3., note that since the config is just a plain JS object, you can create any composable API "layer" on top of it in user-land. But I'm curious to see what your ideal API would look like.

**Comment by serhiipalash** [comment]
> Also, for 3., note that since the config is just a plain JS object, you can create any composable API "layer" on top of it in user-land. But I'm curious to see what your ideal API would look like.

Yeah, it's possible, but you are right, State parts composability is not really needed in a standard app, especially mobile app with small view arias. View (components) is the main layer of app composability in 95% of apps, imho. Maybe if you are building an admin app with complex big screen where everything is connected to everything and in various complex ways, then State composability could be more important for you than View composability.
