### ISSUE TITLE
"always" not showing is the visualizer 

### ISSUE THREAD

**Issue by DEllement** [davidkpiano/xstate#1675]
## Bug
When specifying **always** in the state directly it work in app, but it doesnt show up in the visualizer, vice versa it doesnt work if always is set inside the **on** but it show in the visualizer. this concern : https://xstate.js.org/viz/

EDIT: Id like to mention that it work as expected in https://statecharts.io/

## Description: 

```
//Doesnt show in the visualizer, but work in app
...
{stateA:{
    always: [{ target:"stateB", cond:"guard1"} ]
    on: {
          EVENT1: "stateB"
    }
}}
...

//vs inside, it show in the visualizer but doesnt work in app

...
{stateA:{
    
    on: {
           always: [{ target:"stateB", cond:"guard1"}],
          EVENT1: "stateB"
    }
}}
....

```

## (Bug) Expected result:

It should show in the visualizer

## Possible Cause

im using "xstate": "^4.14.1", probably the visualizer is using an older version

**Comment by davidkpiano** [comment]
Duplicate: #1640 #1477 

I'll work on revamping the current visualizer to support it.
