### ISSUE TITLE
Interpretter clock.setTimeout method does not work in Firefox WebExtension content scripts by default

### ISSUE THREAD

**Issue by blimmer** [davidkpiano/xstate#1703]
**Description**

When an XState machine with [delayed events/transitions](https://xstate.js.org/docs/guides/delays.html#delayed-transitions) is used in a [Firefox WebExtension](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions) [content script](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts), the default implementation of `clock.setTimeout` and `clock.clearTimeout` throws this exception:

```console
TypeError: 'setTimeout' called on an object that does not implement interface Window.
```

**Expected Result**

I expected the machine, as defined, to work without throwing an exception.

**Actual Result**

An exception is thrown, and the state machine does not work properly.

**Reproduction**

Because this happens in a Firefox WebExtension, I couldn't use any of the recommended reproduction templates. Instead, I created a sample repository to show the issue: https://github.com/blimmer/xstate-webext-setTimeout-issue. There is information in the [Quick Start section of the README](https://github.com/blimmer/xstate-webext-setTimeout-issue#quick-start) that explains how to run the example.

**Additional context**

This issue seems to be caused by the default implementation of `setTimeout`/`clearTimeout` defined here: https://github.com/davidkpiano/xstate/blob/844c2c30d6160763ab164dc0592e33a942746361/packages/core/src/interpreter.ts#L125-L132

I believe the issue is with `thisArg` being `null`. I locally changed the default implementation to look like this (note the `global` `thisArg`) and the state machine started working with the default implementation.

```js
clock: {
  setTimeout: (fn, ms) => {
    return global.setTimeout.call(global, fn, ms);
  },
  clearTimeout: (id) => {
    return global.clearTimeout.call(global, id);
  }
},
```

I was looking at the history and noticed that @davidkpiano change the default `clock` behavior in [this commit](https://github.com/davidkpiano/xstate/commit/66c8cf2b20c11863fd388295a8ab382615d1fb4b) to use the `.call(null, ...args)` pattern. This makes sense since you want `setTimeout` bound to the `global` instance passed in, but I think Firefox is doing some additional checks on the `thisArg` which causes this error.

**Comment by davidkpiano** [comment]
@blimmer Thanks for the investigation! I'll fix this soon.

**Comment by blimmer** [comment]
No problem at all! Thank you so much for the quick response, I really appreciate it.

Does the `global` `thisArg` make sense as a fix? If so, I'd be happy to open a PR.

**Comment by davidkpiano** [comment]
> No problem at all! Thank you so much for the quick response, I really appreciate it.
> 
> Does the `global` `thisArg` make sense as a fix? If so, I'd be happy to open a PR.

Yes it does; I'd appreciate a PR!

For tests, this might be hard to test since it's a Firefox-specific thing, so as long as the existing tests pass, that's sufficient.

**Comment by Andarist** [comment]
It probably should be enough to just remove `global.` from those calls. I cant name any JS env in which those (setTimeout & clearTimeout) wouldnt be globally available.

**Comment by davidkpiano** [comment]
> It probably should be enough to just remove `global.` from those calls. I cant name any JS env in which those (setTimeout & clearTimeout) wouldnt be globally available.

I can't remember why, but there was a reason I used `global`, whereas `setTimeout`/`clearTimeout` wouldn't work.

**Comment by blimmer** [comment]
Yeah, I was wondering what the background was on why the `global` call was originally added. The commit message made it seem like there was something you ran into that required it.

https://github.com/davidkpiano/xstate/commit/66c8cf2b20c11863fd388295a8ab382615d1fb4b

>  Cleanup, fixing global setTimeout/clearTimeout issues

**Comment by blimmer** [comment]
For those linked here from the changelog, we decided to call the global methods directly as @Andarist recommended. More details available in the PR comments: https://github.com/davidkpiano/xstate/pull/1704
