### ISSUE TITLE
machine.getState() doesn't exist

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#171]
## Description:
Machine method *getState()* as listed in [docs](http://davidkpiano.github.io/xstate/docs/#/api/machine) doesn't exist. See [codepen](https://codepen.io/bradwoods/pen/yxJeQj?editors=0010).

## Expected result:
Return a stateNode.

## Actual result:
Uncaught error, message: `standardMachine.getState is not a function`

**Comment by carloslfu** [comment]
Hi @bradwoods , this feature was added [here](https://github.com/davidkpiano/xstate/commit/fe3b5fd74c08939ab0f964562018d14684ee2486) and is going to be released in 3.4 I guess.

**Comment by davidkpiano** [comment]
In V4 this will be:

```js
myMachine.getStateNode('foo'); // retrieves myMachine.states.foo
myMachine.getStateNode('#someStateID'); // retrieves (nested?) state with id: someStateId

// alternatively:
myMachine.getStateNodeById('someStateId'); // same as above

myMachine.getStateNodeByPath('foo.bar.baz'); // retrieves nested state with path ['foo', 'bar', 'baz']
myMachine.getStateNodeByPath(['foo', 'bar', 'baz']); // same as above
```

This is to disambiguate a "State" and "StateNode", which are two different things.

**Comment by davidkpiano** [comment]
This is now in `master` and the latest `xstate@next`.
