### ISSUE TITLE
Runtime Error: Converting circular structure to JSON

### ISSUE THREAD

**Issue by a-y-u-s-h** [davidkpiano/xstate#1718]
**Description**
Upon trying to insert a DOM node into a state machine as a payload to `send` event, following error occurs: 

```
TypeError
Converting circular structure to JSON
    --> starting at object with constructor 'HTMLDivElement'
    |     property '__reactInternalInstance$qksqu1uhyoc' -> object with constructor 'FiberNode'
    --- property 'stateNode' closes the circle
```

Not sure whether this happens in vanilla JS, but it definitely happens when I try to pass in `ref.current` value of some React node into `send` as payload.

**Expected Result**

Error should not occur.

**Actual Result**

![screenshot_20201212_221121](https://user-images.githubusercontent.com/19586719/101990238-d553d200-3ccb-11eb-9426-daccbdf229d4.png)

**Reproduction**
- [Codesandbox](https://codesandbox.io/s/xstate-bug-8nm2u?file=/src/index.js:138-250)

**Comment by davidkpiano** [comment]
Events should be serializable. Just like you can't serialize a DOM node in JSON (e.g., if you wanted to send it as a POST request), you can't serialize them in events, either.

Please reconsider how you're modeling this logic. For instance, you can create a unique string ID that maps to that DOM node, and pass _that_ ID to the event instead:

```js
const domNodeMap = new Map();

// ...
const id = 'abc123';
domNodeMap.set(id, someDomNode);

// ...

send({ type: 'SOME_EVENT', nodeId: id })
```

**Comment by a-y-u-s-h** [comment]
TIL. Thanks. Sort of takes away a whole class of encapsulat-able logic though (DOM manipulation), especially any logic that requires running functions or wrappers from other libraries that use a DOM element. 

Like I'm trying to use `fabric` inside state machines or P5 or any other canvas library and they all require a canvas DOM element, which gets stored somewhere and we do things with it, and I was pulling my hair out about why it was happening but now I finally know: all their variables which store the DOM element in one of their keys, I can't use them, makes sense. I'll remember it as: "anything related to DOM nodes are event emitters and event emitters lie outside of Xstate". Correct me if I'm wrong.

**Comment by davidkpiano** [comment]
There's other ways around this, too. You can create a custom object that avoids the circular ref:

```js
const domNodeRef = {
  node: someDomNode,
  toJSON() { return {} }
}

send('SOME_EVENT', domNodeRef)
```

**Comment by a-y-u-s-h** [comment]
On phone right now: Looks like that trick will work on any object that isn't serializable right, not just DOM nodes but also library wrappers which contain DOM nodes somewhere inside of them?

**Comment by davidkpiano** [comment]
I'm reopening this - I believe it can be fixed on our side as well.

**Comment by davidkpiano** [comment]
This should be fixed with `@xstate/inspect` 0.3.0

**Comment by a-y-u-s-h** [comment]
Oh I didn't even realize that it was an issue with inspector. I thought something changed in Xstate. So would that logic have not given me circular JSON error if I wouldn't have run the inspector?

**Comment by davidkpiano** [comment]
> Oh I didn't even realize that it was an issue with inspector. I thought something changed in Xstate. So would that logic have not given me circular JSON error if I wouldn't have run the inspector?

Right.

**Comment by a-y-u-s-h** [comment]
Just checked, inspector hangs now. Doesn't give any errors, and then chrome asks to kill the page. I suggest that instead of JSON strings, converting to compressed binary (with [notepack](https://www.npmjs.com/package/notepack.io) npm package) before passing data through websockets should perform a lot lot faster and it should be able to send DOM nodes as well. It's not a lot of code, just compressing before sending and then unpacking after recieving.

**Comment by davidkpiano** [comment]
Can you post that in the [Inspector feedback](https://github.com/davidkpiano/xstate/discussions/1430) so we can track it there?

In general, I'm not sure how useful sending DOM nodes over the wire is. Makes me think that there should probably be some custom "preprocessing" mechanism where you can format events before they're sent to the inspector.
