### ISSUE TITLE
"In the wild" docs section

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#172]
Would be cool to create such section and for the starters link to https://github.com/hashicorp/vault/tree/master/ui 😉

**Comment by davidkpiano** [comment]
Absolutely! I'm planning reworking the docs in prep for 4.0 and will definitely include this.

**Comment by davidkpiano** [comment]
> Do you have a planned release date for 4.0, or is this wholly dependent on how much time you can spare to work on it?

I'm working on it every day 😅 But `xstate@next` does reflect the latest version. I hope to have an official release by the end of the month, but feel free to use the `@next` version until then. I don't anticipate anything changing (more like adding/cleaning up types now, adding more tests, SCXML, etc.)

**Comment by rodinhart** [comment]
Grand. I'll try `xstate@next`, mostly to move actions from entry/exit to transitions.

**Comment by davidkpiano** [comment]
https://xstate.js.org/docs/about/showcase.html
