### ISSUE TITLE
Question - Xstate visualizer (beta) - how transition to the next state

### ISSUE THREAD

**Issue by eucaos** [davidkpiano/xstate#173]
Maybe this is a dumb question, but I don't know how to move to the next state in the  Xstate visualizer (beta).

For the first example  
![image](https://user-images.githubusercontent.com/6533163/44833593-3197a280-ac37-11e8-8e77-8071451f1df5.png)

I try to click in search arrow to go from Start to next state but nothing happens.
Thanks.

**Comment by davidkpiano** [comment]
If you click **INFO** on the right sidebar, you should see where you can trigger each event.
