### ISSUE TITLE
@xstate/react to be imported as a CDN dependency

### ISSUE THREAD

**Issue by dimitardanailov** [davidkpiano/xstate#1736]
## Feature request?
The current ticket is a feature request.

## Description:

I've been working on legacy project. The project doesn't have a build tool. The available option for us is CDN package import. 

What I found so far: 

The main library: `Xstate` can be used as a dependency package. The options are two: 
Option 1) XState core: https://unpkg.com/xstate@4/dist/xstate.js
Option 2) XState web: https://unpkg.com/xstate@4/dist/xstate.web.js

The window has a new property: Xstate. Xstate will be available globally: 
```javascript
const { Machine, actions, interpret } = XState; // global variable: window.XState
```

Documentation: https://xstate.js.org/docs/guides/installation.html#cdn

Unfortunately: `@xstate/react` can't be used as a CDN package. The unpkg package: [https://unpkg.com/browse/@xstate/react@1.1.0](https://unpkg.com/browse/@xstate/react@1.1.0) doesn't have `/dist` folder.

**Comment by Andarist** [comment]
This got implemented in https://github.com/davidkpiano/xstate/pull/1738
