### ISSUE TITLE
Documentation - React example (using state value for a transition) 

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#174]
## Description:
In the [react gallery app example](https://codepen.io/davidkpiano/pen/dJJMWE?editors=1010), `line 78`. When calling the transition method, the value being used for the current state is **stateValue**, not the **stateNode**. If you use this approach and try to access history, it will return the wrong state, see [here](https://codepen.io/bradwoods/pen/gdgrRa?editors=0010). 

## Potential fix:
Use `getState()` method (when made available) to calculate the current state for a transition.

**Comment by davidkpiano** [comment]
Refer to https://xstate.js.org/docs/recipes/react.html (will eventually rework React gallery example).
