### ISSUE TITLE
TypeError: this.config is not an Object.

### ISSUE THREAD

**Issue by Estournet** [davidkpiano/xstate#1799]
Good morning everyone ! I'm having an issue I can't resolve, maybe you can help me :) 

```
xstate 4.15.3
react 16.13.1
react-native 0.63.4
```

**Description**
Just before the app launches, an error is thrown. As it is just before launching, I don't have much log. Actually I only have this log. 
`TypeError: this.config is not an Object. (evaluating ''parallel' in this.config')`
 `Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication)`
I found it was because of xstate because when removing the package, I don't have the error anymore. But I can't figure what happens

**Expected Result**
The app laucnhes

**Actual Result**
The app crashes

**Additional context**
I'm doing an upgrade of react-native, from 0.59.x to 0.63.x

**Comment by Andarist** [comment]
If your app has worked on 0.59.x with `xstate` but is crashing after upgrading to 0.63.x then it's not a problem with `xstate`. We can't help you much here without you providing a repro case.

**Comment by Estournet** [comment]
Just in case someone has the same trouble, it was because I used  Parallel State Nodes in the wrong way

I had 
`
states: {
	pending: true,
	isAuthorized: true,
	isForbidden: true
},
`

instead of 
`
states: {
	pending: {},
	isAuthorized: {},
	isForbidden: {}
},
`
