### ISSUE TITLE
Remove state object mapping from the React Flickr Gallery example

### ISSUE THREAD

**Issue by carloslfu** [davidkpiano/xstate#181]
## Bug or feature request?
A bug
## Description
The React Flickr Gallery contains a state object mapping in the `loading` state on the `SEARCH_SUCCESS` and this is gonna be deprecated on `Xstate v4`.

Link to docs: http://davidkpiano.github.io/xstate/docs/#/examples/gallery

**Comment by davidkpiano** [comment]
Good catch! Updated.
