### ISSUE TITLE
Maintain code examples in this repo and show it through embedding

### ISSUE THREAD

**Issue by carloslfu** [davidkpiano/xstate#182]
## Bug or feature request?
Feature request
## Description:
The better way to maintain code examples is to have it in this repo, so anyone can modify it and submit a PR.
## Potential implementation:
The implementation might be to have all code examples in `docs/examples` folder. AFAIK Codepen doesn't have a way to import Github repos, so I recommend using Stackblitz or CodeSandbox for that, see:

[Stackblitz Github Import](https://stackblitz.com/docs#import-from-github)
[CodeSandbox Github Import](https://codesandbox.io/docs/importing)

I can contribute with this implementation, so let me know your thoughts.

**Comment by davidkpiano** [comment]
I'd love help with this. I'm planning on rewriting the docs using Gatsby + MDX.

**Comment by carloslfu** [comment]
Great! I'll start working on it this weekend.

**Comment by davidkpiano** [comment]
> I'd be keen to help rewrite documentation using Gatsby + MDX.

Currently wrestling with that now. I thought it was a good idea but MDX support doesn't seem mature in Gatsby yet.

**Comment by carloslfu** [comment]
See #184 , here a [live demo](https://xstate-docs.surge.sh/).

**Comment by bradwoods** [comment]
I'll have a go at setting up a small gatsby + MDX project over the weekend & see what it is currently capable of.

**Comment by davidkpiano** [comment]
Embedded examples through CodeSandbox: https://xstate.js.org/docs/examples/todomvc.html

You can open a pull request directly to `master` to add your own. 🚀

**Comment by carloslfu** [comment]
Wow! that's great 🔥

**Comment by davidkpiano** [comment]
They can use any interpreter.
