### ISSUE TITLE
Module not found: Can't resolve 'xstate' in '<Project dir>\@xstate\react\es'

### ISSUE THREAD

**Issue by hckhanh** [davidkpiano/xstate#1820]
I see this boy when try to upgrade @xstate/react from `1.2.1` to `1.2.2`

```bash
./node_modules/@xstate/react/es/useMachine.js
Module not found: Can't resolve 'xstate' in '<Project dir>\@xstate\react\es'
```

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by davidkpiano** [comment]
Closing until there is a reproduction.
