### ISSUE TITLE
Feature: design by contract

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/xstate#183]
## Bug or feature request?
Feature

## Description:
https://sismic.readthedocs.io/en/master/contract.html

## (Feature) Potential implementation:

- What the API would look like
Not sure yet, but it could model the above "design by contract" implementation in Sismic or behavior threads (a la Behavioral Programming)

- If this is a breaking change
It will not be.

- If this is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)
It is not.

**Comment by hendrul** [comment]
Behind DBC there is the idea of showing a "contract" view and an "implementation" view, to show/hide details, maybe the visualizer shall have this

**Comment by Andarist** [comment]
@hendrul could you illustrate with an example?

**Comment by hendrul** [comment]
I'm trying to make sense of DBC (which is an OOP approach) applied to xstate, but for this we need to make analogies with OOP to better understand the way DBC can be beneficial in the context of xstate (there's much overlap between DBC and xstate)... 

we know Actors are analogous to OOP classes/objects, and their behavior can be described by state machines; sending events between Actors is the analogous to "message passing" in OOP. In DBC, "contracts" take the shape of pre/post conditions (which are kind of "throwable" guards) which describe the responsabilities between two interacting parties or "Actors", and also "invariants" which describe conditions that must be meet in the "context" of an actor during its life span. 

What are the benefits?

1. Improves software verifiability by allowing developers formalize the specifications of Actors, effectively extending the semantic capabilities of automated interpreters/compilers to show us quickly when we break the specifications (complementing automated testing)

2. Improves software visibility by making explicit it's specifications and making it easy to visualize with the help of tools which can show a high level "contract" view of software, showing only it's actors with their events, transitions, and their specifications (pre/post conditions and invariants)

One of the main benefits offered by this approach is "formalization and visualization" of the specification. You can see DBC approach fully implemented in the [Eiffel Programming Language](https://www.eiffel.org/) created by the same author of DBC. [here](https://www.eiffel.org/doc/eiffelstudio/Class_views) is the docs about "class views".
