### ISSUE TITLE
[Hacktoberfest] Memoization of properties!

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/xstate#187]
## Bug or feature request?
Enhancement

## Description:
For [Hacktoberfest](https://hacktoberfest.digitalocean.com/), I would love help adding a memoization [decorator](https://www.typescriptlang.org/docs/handbook/decorators.html) to certain computed `get` properties in `StateNode`, such as:

- `.definition` 
- `.config`
- `.on`
- `.after`
- `.tree`
- `.delays`
- `.resolvedStateValue`
- `.initialStateValue`
- `.initialState`
- etc.

For some properties, caching is already done in an ad-hoc way (e.g., with `__cache` and `idMap`) but there's definitely better ways to do this.

## (Feature) Potential implementation:
Take a look at something like [`typescript-memoize`](https://github.com/darrylhodgins/typescript-memoize) to guide you.

**Comment by tarsir** [comment]
Is anyone working on this? I'd like to pick it up if it's available :)

**Comment by davidkpiano** [comment]
@tarsir It's yours if you want it! Would love the help.

**Comment by ivanportillo** [comment]
Is this issue already done @davidkpiano ?
In case it's not done, I'd like to take it.

**Comment by davidkpiano** [comment]
@ivanportillo It's not done yet, feel free to take it!
