### ISSUE TITLE
Would be better to declare context in MachineOptions

### ISSUE THREAD

**Issue by carloslfu** [davidkpiano/xstate#189]
## Bug or feature request?
Feature
## Description:
I think would be better to declare `context` in `MachineOptions` instead of the `MachineConfig` because `context` is global.

Right now you can declare `context` in child states without getting a type error and it seems wrong because it should be declared only in the root state. I think is more clear to have it in the machine options because it contains `actions` and `guards` that are both globals.

## (Feature) Potential implementation:

```javascript
Machine({ // pure statechart
  initial: 'a',
  states: {}
}, // global stuff
  context: {},
  actions: {},
  guards: {}
})
```

**Comment by carloslfu** [comment]
Another reason is that this way you can have a clear separation of the control state (finite) and the infinite state.

**Comment by davidkpiano** [comment]
Added docs to this: https://xstate.js.org/docs/guides/machines.html#initial-context
