### ISSUE TITLE
`onReceive` context is out of date

### ISSUE THREAD

**Issue by ilovett** [davidkpiano/xstate#1912]
Inside of an invoked service with 

```
(context, event) => (callback, onReceive) => {

   onReceive((evt) => {
      // if context has changed since this service was invoked
      // then the context appears to be from when closure was first created
      console.log('context', context);
   }

}
```

**Expected Result**
I am able to access the current context.  Why doesn't `onReceive` function have same structure as everything else? `(context, event)`

```
onReceive((context, event) => {
  console.log('context is up to date', context);
});
```

**Comment by ilovett** [comment]
Going off on a tangent, if you do decide to go forward with adding context to `onReceive` -- in the future, maybe 5.x, I would suggest a format of `({ context, event })` instead of `(context, event)` for backward compatibility

**Comment by Andarist** [comment]
The current `context` can only be used when creating an invoked service/actor. The communication between the parent and a child actor is done solely using events - context is treated as a private state of the actor and actors always isolate their state. If you want to share data with your child actor you should do it through events.

**Comment by ilovett** [comment]
OK fair enough, it makes sense since the service could be decoupled and used on other machines..., but I think warrants a caveat / warning on the documentation in the callback section of invoking services https://xstate.js.org/docs/guides/communication.html#listening-to-parent-events @Andarist @davidkpiano pinging since this is closed now

**Comment by davidkpiano** [comment]
> OK fair enough, it makes sense since the service could be decoupled and used on other machines..., but I think warrants a caveat / warning on the documentation in the callback section of invoking services [xstate.js.org/docs/guides/communication.html#listening-to-parent-events](https://xstate.js.org/docs/guides/communication.html#listening-to-parent-events) @Andarist @davidkpiano pinging since this is closed now

Feel free to make a PR, but the docs never imply that updated parent `context` is communicated; only events.
