### ISSUE TITLE
Assign actions are executed before other actions

### ISSUE THREAD

**Issue by carloslfu** [davidkpiano/xstate#193]
## Bug or feature request?
Bug
## Description:
Assign actions are executed before other actions.

```javascript
import { Machine } from 'xstate'
import { interpret } from 'xstate/lib/interpreter'
import { assign } from 'xstate/lib/actions'
 
const interpreter = interpret(Machine({
  initial: 'a',
  context: {},
  states: {
    a: {
      on: { EVENT: {
        actions: ['a1', 'a2', 'a3']
      } }
    }, 
    b: {}, 
  }
}, {
  actions: {
    a1: () => console.log('a1'),
    a2: assign(ctx => {
      console.log('a2')
      return {}
    }),
    a3: () => console.log('a3'),
  }
}))

interpreter.init()
interpreter.send('EVENT')
// logs: a2, a1, a3
```
Live example: https://codesandbox.io/s/8lk1k0m4qj

## (Bug) Expected result:
Actions should be executed in order.
## (Bug) Actual result:
Assign actions are executed first.

**Comment by davidkpiano** [comment]
This is working as expected. "Assign" actions are _raised_ as internal events, so that they are "executed" before any external events or actions.

Also, you should not depend on action order, since actions (side-effects) should be considered async.

What specifically is your real-life use case here?

**Comment by carloslfu** [comment]
I get it. My use case is a wizard with some questions in each step and many UI components, I am using `xstate` for the whole state management, machine states for the control-state and `assign` for the external-state. I was relying on action order but yeah it's wrong, right now I fixed it in a way in which action-order is not important and it seems much better to me. Thanks for the advice David.

**Comment by davidkpiano** [comment]
> right now I fixed it in a way in which action-order is not important and it seems much better to me

I'd love to see that, so I can add it to the documentation! 🙏
