### ISSUE TITLE
Delay - mainly after doesn't work using persistent state.

### ISSUE THREAD

**Issue by vinodKumarPula** [davidkpiano/xstate#1938]
**Description**
Hi,
I'm using Xstate machine npm module in server side. 
I have states configured as bellow
{
        "id" : "serviceMachine",
        "initial" : "ACTIVE",
        "context" : {
            "noTopUp" : "2021-02-18 10:34",
            "noUsage" : "2021-02-16 22:25"
        },
        "states" : {
            "ACTIVE" : {
                "after" : {
                    "NoTopUpToFree" : "checkTopup"
                },
                "on" : {
                    "SUSPEND" : "SUSPEND",
                    "SYNC" : "ACTIVE",
                    "TERMINATE" : "TERMINATE"
                }
            },
            "checkTopup" : {
                "invoke" : {
                    "src" : "checkTopUpDB",
                    "onDone" : "ACTIVE",
                    "onError" : {
                        "target" : "SUSPEND"
                    }
                }
            },
            "SUSPEND" : {
                "after" : {
                    "ActiveDelay" : "ACTIVE"
                },
                "on" : {
                    "TERMINATE" : "TERMINATE",
                    "RESUME" : "ACTIVE"
                }
            },
            "TERMINATE" : {}
        }
    }

all the delays are simple delays which return 10 ms or 12 ms. when we save data on each transition.delays work perfectly when server is up and start was started from init state.
but when i reslove the persistent state, I don't see actions of any delays. for resolving state i'm using **resolveState(State.create(<state>))**
 
**Expected Result**
Should trigger delay events .
**Actual Result**
No actions in state object.
**Reproduction**
Use the Machine  configuration as above, save each transition.  before NoTopUpToFree ends trigger SUSPEND event.once its suspended. close the server.
Restart it again, it should trigger RESUME on ActiveDelay done.(expected but not working)

Please let me know if its a bug or its not the right way @davidkpiano 

Regards,
Vinod Kumar Pula

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

And also while sharing the code please make sure that it's formatted well so people can actually read it.

**Comment by davidkpiano** [comment]
Based on the code you currently have, I assume you're missing the delays in the second argument: `createMachine(definition, { delays: { ... } })`.

I will reopen this if there is a full repro. Please create a [CodeSandbox (XState template)](https://codesandbox.io/s/xstate-example-template-qcwed) reproduction of this. Thanks!
