### ISSUE TITLE
interpreter.start(state) executes state.actions

### ISSUE THREAD

**Issue by amelon** [davidkpiano/xstate#194]
## Bug or feature request?
Bug - maybe

## Description:
When interpreter is restarted with previous state, `state.actions` are executed (without `eventObj` param) at restart.

````javascript
import { Machine, State } from 'xstate'
import { interpret } from 'xstate/lib/interpreter'

const machine = Machine({
  initial: 'here',
  states: {
    here: {
      on: {
        move: {
          actions: ['lookAtAMap'],
          target: 'elsewhere',
        },
      },
    },
    elsewhere: {},
  },
})

const interpreter = interpret(
  machine.withConfig({
    actions: {
      lookAtAMap(ctx, evObj) {
        console.log('lookAtAMap', { evObj })
      },
    },
  })
)

console.log('start interpreter')
interpreter.start()
let state = interpreter.send('move')
// console.log => lookAtAMap { evObj: { type: 'move' } }
interpreter.stop()

console.log('restart interpreter')
interpreter.start(state)
// console.log => lookAtAMap { evObj: undefined }

````

## (Bug) Expected result:
In my opinion (I'am not expert of statecharts) `interpreter.start(state)` should not react to `state.actions`.

## (Bug) Actual result:
`state.actions` are executed on restart.
`eventObj` parameter is undefined on restart.

I've found a workaround with `State.inert`
````
...
console.log('restart interpreter')
interpreter.start(State.inert(state))
````

**Comment by davidkpiano** [comment]
I feel like this is expected behavior, especially for the scenarios when initial states have actions that must be executed. @mogsie what do you think?

This is because `interpreter.start(initialState)` considers what's passed into it as the initial state, which must exhibit the on-entry-executing behavior.

But what we should probably consider instead is `interpreter.pause()` and `interpreter.restart()`. However, I don't think this is part of the SCXML specification or if it's even recommended functionality. If it seems okay, I would be fine adding it (interpreted statecharts would have their own internal state machines to represent this 😄 )

Another consideration: should we add an `inert` property to state instances? E.g.,

```js
// restart
interpreter.start(state.inert);
```

**Comment by davidkpiano** [comment]
Okay, let's go for the minimal change, since (unless I'm mistaken) your intention is:

> Start the `interpreter` again from this state, but don't execute the actions again

And "this state, but don't execute the actions again" is the same as `State.inert(state)` which we can make `state.inert`.

**Comment by davidkpiano** [comment]
The `state.inert` getter will be available in the next release.

**Comment by huan** [comment]
> this is expected behavior, especially for the scenarios when initial states have actions that must be executed.

I agree with you about the above and I'm trying to find a way to restore a state to the machine/interpreter with some actions _"that must be executed"_.

My use case is that once an `EVENT` happens and the `State` transitions to another, the new `State` will want to use `entry` to execute `actions` and deal with the `EVENT`.

If I restart the interpreter with a saved state, my machine needs the `EVENT` to be executed in the `entry`, or the logic will not be expected anymore.

@davidkpiano Is there any way to fulfill the above use case with the latest XState?

**Comment by davidkpiano** [comment]
> > this is expected behavior, especially for the scenarios when initial states have actions that must be executed.
> 
> I agree with you about the above and I'm trying to find a way to restore a state to the machine/interpreter with some actions _"that must be executed"_.
> 
> My use case is that once an `EVENT` happens and the `State` transitions to another, the new `State` will want to use `entry` to execute `actions` and deal with the `EVENT`.
> 
> If I restart the interpreter with a saved state, my machine needs the `EVENT` to be executed in the `entry`, or the logic will not be expected anymore.
> 
> @davidkpiano Is there any way to fulfill the above use case with the latest XState?

Can you file this as a separate issue? It should be possible already.

**Comment by huan** [comment]
@davidkpiano thank you very much for the reply, the new issue was created, appreciate you help!

**Comment by atido** [comment]
Hello @davidkpiano , I am in the same situation as @amelon but with error handling. I am persisting my state between request front / back and when invoking service, if an error occured, my actions for logging error are executed (logError and tellErrorMessage) and I go to a "WaitingForInfo" state, it's fine. 
But at the next request when I load my previous state and start the machine, the logging error actions are executed at the begining. Am I doing something wrong ? Are do I need to use the inert state too ?
Here is an extract of my machine.
Thank you in advance for your feedback.
`    
    WaitingForInfo: {
      on: {
        MESSAGE: {
          target: 'InfoCollected',
        },
      },
    },
InfoCollected: {
      invoke: {
        src: 'extractInfo',
        id: 'invoke-mgdk0',
        onDone: [
          {
            target: 'requestAssistance',
          },
        ],
        onError: {
          target: 'WaitingForInfo',
          actions: ['tellErrorMessage', 'logError'],
        },
      },
    },`

**Comment by davidkpiano** [comment]
> Hello @davidkpiano , I am in the same situation as @amelon but with error handling. I am persisting my state between request front / back and when invoking service, if an error occured, my actions for logging error are executed (logError and tellErrorMessage) and I go to a "WaitingForInfo" state, it's fine. But at the next request when I load my previous state and start the machine, the logging error actions are executed at the begining. Am I doing something wrong ? Are do I need to use the inert state too ? Here is an extract of my machine. Thank you in advance for your feedback. ` WaitingForInfo: { on: { MESSAGE: { target: 'InfoCollected', }, }, }, InfoCollected: { invoke: { src: 'extractInfo', id: 'invoke-mgdk0', onDone: [ { target: 'requestAssistance', }, ], onError: { target: 'WaitingForInfo', actions: ['tellErrorMessage', 'logError'], }, }, },`

In XState v4, make sure to delete `state.actions.length = 0` before restoring.

In XState v5 beta, actions are not persisted (they shouldn't be; they already occurred), so you won't run into this problem.

**Comment by atido** [comment]
OK thank you for your quick reply
