### ISSUE TITLE
@xstate/vue throws warnings when used with Vite

### ISSUE THREAD

**Issue by TheDutchCoder** [davidkpiano/xstate#1940]
**Description**

When using xstate in components in Vite, the `useMachine` method throws warnings from the compiler:
![image](https://user-images.githubusercontent.com/1668207/108256437-8bec8c80-712b-11eb-9b26-2e0d64aa7a5b.png)

It makes the state machine non-reactive. I'm not sure why this happens...

**Expected Result**
`useMachine` to not throw warnings and be reactive.

**Actual Result**
Warnings are thrown from the compiler.

**Reproduction**
I don't have a repro ready yet, because it's not very easy to set it up with Vite.

**Additional context**
Vite latest version, xstate and @xstate/vue latest version

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by TheDutchCoder** [comment]
I understand of course.

On the flip-side, it's sometime very, very time-consuming to reproduce the exact issue in a "new" environment and sometimes issues are more familiar to maintainers because they've encountered them before and/or they have more in-depth knowledge of their own code.

I'm not unwilling to try and replicate this (I normally do with smaller issues), I just don't always have hours to spend on it either.

**Comment by TheDutchCoder** [comment]
I can close this issue, as I have tracked down that this is actually a problem with the VitePress dev mode.
I isolated it into vue-cli, Vite, and VitePress. And only VitePress in dev mode (not prod) throws these warnings, so something's up over there.

I will make a reproduction and open an issue on their GH, thanks!
