### ISSUE TITLE
Be able to call assign actions with ActionObject notation

### ISSUE THREAD

**Issue by carloslfu** [davidkpiano/xstate#195]
## Bug or feature request?
Feature request
## Description:
Be able to call assign actions using the ActionObject notation, it's also needed to implement `<param>` and `<content>` which would be placed into the event (per the SCXML spec).

Example:
```javascript
onEntry: { type: 'myAction', foo: 'bar' }

// ...

actions: {
  myAction: (ctx, e) => {
    e.foo === 'bar'; // true
  }
}
```
Anything passed into the action object will be merged with the event object.

**Comment by davidkpiano** [comment]
Clarification with this after reading the spec: the extra fields passed into the action object will be merged with the resolved action object, not with the event:

```js
onEntry: { type: 'myAction', foo: 'bar' }

// ...
actions: {
  myAction: (ctx, e) => {
    e.foo === undefined;
  }
}
```

But when that action is returned as part of the `State`, it is returned as:

```js
{
  type: 'myAction',
  foo: 'bar',
  exec: (ctx, e) => { e.foo === undefined; }
}
```

Which makes me think that we should pass the action as a 3rd parameter to the action?

**Comment by carloslfu** [comment]
> Which makes me think that we should pass the action as a 3rd argument to the action?

Yes, I think it is a good solution.

**Comment by davidkpiano** [comment]
Added in the 3rd argument in the `actionMeta` property as of version 4.4. Docs: https://xstate.js.org/docs/guides/actions.html#declarative-actions
