### ISSUE TITLE
Visualizer does not work with always transitions

### ISSUE THREAD

**Issue by lanmonster** [davidkpiano/xstate#1956]
**Description**

https://xstate.js.org/viz/ cannot handle a machine that uses the `always` transition. it does not show that there is a valid transition and does not take it.

**Expected Result**

copy the machine from https://xstate.js.org/docs/guides/transitions.html#eventless-always-transitions into the visualizer
update
send the AWARD_POINTS event
go to the win state

**Actual Result**

no transition is taken

**Reproduction**

- [CodeSandbox template (JavaScript)](https://codesandbox.io/s/xstate-example-template-m4ckv)
- [CodeSandbox template (TypeScript)](https://codesandbox.io/s/xstate-typescript-template-s9kz8)
- ⚛︎ [CodeSandbox template (React)](https://codesandbox.io/s/xstate-react-template-3t2tg)
- ⚛︎ [CodeSandbox template (React + TypeScript)](https://codesandbox.io/s/xstate-react-typescript-template-wjdvn)
- 💚 [CodeSandbox template (Vue + Composition API)](https://codesandbox.io/s/xstate-vue-template-composition-api-1n23l)
- [XState Visualizer](https://xstate.js.org/viz/)

**Additional context**

**Comment by davidkpiano** [comment]
Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead.

More info: statecharts.io
