### ISSUE TITLE
Question: how to exit a nested FSM in a specific state

### ISSUE THREAD

**Issue by laurentpierson** [davidkpiano/xstate#196]
Hi David, I have a question regarding nested FSMs, let's start with this example:

```ts
const nestedFsm: MachineConfig<DefaultContext, any, EventObject> = {
    key: 'nestedFsm',
    initial: 'C',
    strict: true,
    states: {
        C: {
            on: {
                D_EVENT: 'D'
            },
            onEntry: 'ENTER_C',
            onExit: 'EXIT_C'
        },
        D: {
            on: {
                E_EVENT: 'E'
            },
            onEntry: 'ENTER_D',
            onExit: 'EXIT_D'
        },
        E: {
            onEntry: 'ENTER_E',
            onExit: 'EXIT_E'
        }
    }
};

const parentFsm = Machine({
    key: 'parentFsm',
    initial: 'A',
    strict: true,
    states: {
        A: {
            on: {
                B_EVENT: 'B'
            },
            onEntry: 'ENTER_A',
            onExit: 'EXIT_A',
            ...nestedFsm
        },
        B: {
            onEntry: 'ENTER_B',
            onExit: 'EXIT_B'
        }
    }
});
```

The nested FSM contains three sequential states `C`, `D` & `E` and I would like to ‘exit’ (move to parent state `B`) this FSM only when in state `{A: ‘E’}`. 

In theory I would only trigger a transition `B_EVENT` while in state `{A: ‘E’}`, but nothing is preventing us from triggering transition `B_EVENT` while in state `{A: ‘C’}` or `{A: ‘D’}` which would then put us in state `B` too soon and interrupt the workflow modelled in the nested FSM.

How can we model state `E` as an ‘exit state’ of the nested FSM so that we can make sure we won’t accept transition `B_EVENT` before?

The only way I could think of was to use a guard:

```
const nestedFsm: MachineConfig<DefaultContext, any, EventObject> = {
    key: 'nestedFsm',
    initial: 'C',
    strict: true,
    states: {
        C: {
            on: {
                D_EVENT: 'D'
            },
            onEntry: 'ENTER_C',
            onExit: 'EXIT_C'
        },
        D: {
            on: {
                E_EVENT: 'E'
            },
            onEntry: 'ENTER_D',
            onExit: 'EXIT_D'
        },
        E: {
            onEntry: 'ENTER_E',
            onExit: 'EXIT_E'
        }
    }
};

const parentFsm = Machine({
        key: 'parentFsm',
        initial: 'A',
        strict: true,
        states: {
            A: {
                on: {
                    B_EVENT: [{
                        target: 'B', cond: 'canMoveToB'
                    }]
                },
                onEntry: 'ENTER_A',
                onExit: 'EXIT_A',
                ...nestedFsm
            },
            B: {
                onEntry: 'ENTER_B',
                onExit: 'EXIT_B'
            }
        }
    },
    {
        guards: {
            canMoveToB: (extState: any, eventObject: EventObject, stateValue: StateValue) => {
                return (stateValue as any).A === 'E' ;
            }
        }
    });
```

That has various disadvantages:

- Such guard logic (`canMoveToB`) should be put inside the nestedFsm because only it should know what its ‘exit state’ is, not some parent FSM.
- But the `stateValue` variable contains the full chain of FSMs (in this case only `A` but if we use deeply nested FSMs, we can end up with something like `X.Y.Z.A`, which the nestedFsm shouldn’t be aware of. 
- In our project, we defined various FSMs in separate files, and we sometimes reuse an FSM as a nested FSM in other FSMs. With such approach, we unfortunately need to duplicate the guards because they each reference the path in which the nested FSM is used (in this case: `cartCreation` & `addProductToCart`):
```
private cartCreationCanMoveToSuccess(extState: any, eventObject: EventObject, stateValue: StateValue): boolean {
         return (stateValue as any)
                .cartCreation.fetchProductInfo.fetchProductDescriptions === 'productDescriptionsProvided'
            && (stateValue as any).cartCreation.fetchProductInfo.fetchProductPrices === 'productPricesProvided';
}

private cartUpdateCanMoveToSuccess(extState: any, eventObject: EventObject, stateValue: StateValue): boolean {
        return (stateValue as any)
                .addProductToCart.fetchProductInfo.fetchProductDescriptions === 'productDescriptionsProvided'
            && (stateValue as any).addProductToCart.fetchProductInfo.fetchProductPrices === 'productPricesProvided';
}
```
- More or less the same question applies to parallel FSMs. In the code example above, the guards are used in a parallel FSM where the two parallel FSMs try to fetch product prices & product descriptions, but I only want to accept a transition to 'exit' that FSM if both product prices & descriptions have been ‘provided’. 

Do you have another suggestion to handle the way we ‘exit’ an FSM?

**Comment by davidkpiano** [comment]
It seems you are using `xstate@next` (yay!) so the following solutions will apply, which I'm currently writing documentation for. I'll approach it in two different ways:

> How can we model state `E` as an ‘exit state’ of the nested FSM...

You can use **final states**, which is basically what you mean as an exit state (they're pretty much synonymous):

```js
const nestedFsm = Machine({
  // ...
  states: {
    // ...
	E: {
	  type: 'final' // indicates E as a final state node
    }
  }
});
```

Then, specify the `onDone` transition:

```js
const parentFsm = Machine({
  // ...
  states: {
  	A: {
	  // ...
	  onDone: 'B'
    },
	B: {
	  // ...
 	}
  }
});
```
  
That `onDone` transition will only be taken when the compound state node `A` has reached its final state, which in this case is `E` (but this is a good pattern because the parent can remain agnostic to what the final state is).

-------

> ...but nothing is preventing us from triggering transition `B_EVENT` while in state `{A: ‘C’}` or `{A: ‘D’}`...

This is a separate topic, but to forbid events from happening, make their transitions explicitly `undefined`:

```js
C: {
  on: {
    B_EVENT: undefined
  }
}
```

This is the same as defining an internal transition that has no actions (that is, we're telling the state machine to "do nothing").

Hope that helps!

**Comment by laurentpierson** [comment]
Thanks a lot David, that is exactly what I needed and it's also an elegant way to exit a parallel FSMs!

I just had an issue when an FSM is defined as strict, then transitions are rejected by the FSM.

I have joined a test reproducing the issue. If you remove `strict:true` in `parentFsm`, it works as expected, any idea why?

```
describe('parallel fsms with final state', () => {

    const nestedParallelFsm: MachineConfig<DefaultContext, any, EventObject> = {
        key: 'nestedParallelFsm',
        parallel: true,
        states: {
            parallel1: {
                initial: 'C1',
                states: {
                    C1: {
                        on: {
                            D1_EVENT: 'D1'
                        },
                        onEntry: 'ENTER_C1',
                        onExit: 'EXIT_C1'
                    },
                    D1: {
                        onEntry: 'ENTER_D1',
                        onExit: 'EXIT_D1',
                        type: 'final'
                    }
                }
            },
            parallel2: {
                initial: 'C2',
                states: {
                    C2: {
                        on: {
                            D2_EVENT: 'D2'
                        },
                        onEntry: 'ENTER_C2',
                        onExit: 'EXIT_C2'
                    },
                    D2: {
                        onEntry: 'ENTER_D2',
                        onExit: 'EXIT_D2',
                        type: 'final'
                    }
                }
            }
        }
    };

    const parentFsm = Machine({
        key: 'parentFsm',
        initial: 'A',
        strict: true,
        states: {
            A: {
                onEntry: 'ENTER_A',
                onExit: 'EXIT_A',
                onDone: 'B',
                ...nestedParallelFsm
            },
            B: {
                onEntry: 'ENTER_B',
                onExit: 'EXIT_B'
            }
        }
    });

    describe('parallel final state', () => {
        it('test parallel final states', () => {
            let nextState = parentFsm
                .transition(parentFsm.initialState, 'D1_EVENT');
            let actual = nextState.actions.map(a => `${a}`);

            nextState = parentFsm
                .transition({A: {parallel1: 'D1', parallel2: 'C2'}}, 'D2_EVENT');
            actual = nextState.actions.map(a => `${a}`);

            const expected = ['EXIT_C2', 'ENTER_D2', 'EXIT_D1', 'EXIT_D2', 'EXIT_A', 'ENTER_B'];
            assert.deepEqual(actual, expected);
        });
    });

});
```

The error is the following: `Error: Machine 'parentFsm' does not accept event 'done.state.parentFsm.A.parallel1'`

**Comment by davidkpiano** [comment]
Looks like a strict mode bug (which might be deprecated in V4, use `NODE_ENV=development` instead etc.), will take a look.
