### ISSUE TITLE
useSelector() needlessly requires a memoized selector

### ISSUE THREAD

**Issue by VanTanev** [davidkpiano/xstate#1965]
**Description**
`useSelector` requires the `selector` parameter to be wrapped in `React.useCallback()`. The [release notes of @xstate/react@1.3.0](https://github.com/davidkpiano/xstate/releases/tag/%40xstate%2Freact%401.3.0) do not stipulate such a necessity.

The selector itself will probably be a pure function in 99% of cases, so it should be OK to not update the `selected` data when the `selector` function changes.

**Expected Result**
Expected the following code to not rerender needlessly:
```typescript
const count = useSelector(someActor, state => state.context.count);
```

**Actual Result**
The selector `useEffect` is triggered constantly because the identity of the selector function changes on each rerender.

**Additional context**
```
xstate@4.16.2
@xstate/react@1.3.1
```

**Comment by davidkpiano** [comment]
It's not needless - the selector can change, which means that the selected value should change too (and cause a rerender).
