### ISSUE TITLE
Add absoluteId property to StateNode

### ISSUE THREAD

**Issue by carloslfu** [davidkpiano/xstate#198]
## Bug or feature request?
Feature request
## Description:
Right now `StateNode`s ids are automatically set if the configuration doesn't provide one. The automatic ids are absolute `ids`, i.e. `(machine).stateA.a1`. I realized these ids are very useful when you are visiting the nodes. But, the problem is that if a state configuration has an id, it is overwritten so you can't rely on it. Right now I populate `data` config property with the absolute ids to always have absolute ids. I propose to add a property to `StateNode`s called `absoluteId`, and this way we can rely on it.

**Comment by davidkpiano** [comment]
The `id` property is not overwritten:

```ts
// ...
    this.id =
      _config.id ||
      (this.machine
        ? [this.machine.key, ...this.path].join(this.delimiter)
        : this.key);
// ...
```

Am I missing something? Can you create a reproducible example where this is not the case? There is also a spec at `tests/id.test.ts` that ensures this behavior holds.

**Comment by carloslfu** [comment]
Sorry, I didn't explain right. What I mean is that the `_config.id` is used over the state path and sometime is very useful to have access to the state path. So I propose adding a property called `absoluteId` or `path` that always holds the state path. For instance:

```javascript
// ...
    this.absoluteId = this.machine
        ? [this.machine.key, ...this.path].join(this.delimiter)
        : this.key;
    this.id =_config.id || this.absoluteId;
// ...
```

**Comment by davidkpiano** [comment]
Ah, well `stateNode.path` will always hold the state path. Would that suffice?

**Comment by carloslfu** [comment]
Thanks David! This is what I'm searching for, I overlooked it.
