### ISSUE TITLE
Guard target with data

### ISSUE THREAD

**Issue by rudijs** [davidkpiano/xstate#199]
## Question

Hi,

When using a guard, I don't think it's possible to pass any arbitrary data with the target is it?

I read through the tests and experimented, but I thought I'd ask here to double check.

We can pass arbitrary data with the `.transition()` method to be used in the guard `cond` function.

Not sure if it makes sense or not with a data object in the target.

Here's an example of what I was trying to do, the `data` property after `target`:

## Description:

```
      on: {
        LOGIN: [
          {
            target: "active",
            cond: () => false
          },
          { target: "error", data: { details: "No permission" } }
        ]
      }
```

Thanks.

**Comment by davidkpiano** [comment]
Another note: if you want to refine your error states further (which allows you to model them properly and prevent impossible states, like two conflicting error types, etc.), the above pattern allows you to do that. For example:

```js
passwordError: {
  type: 'parallel', // v4 syntax
  states: {
    length: {
	  initial: 'valid',
	  states: { tooShort: {}, tooLong: {}, valid: {} }
    },
    chars: {
	  initial: 'valid',
	  states: { containsIllegal: {}, valid: {} }
	history: {
	  initial: 'valid',
	  states: { prevUsed: {}, valid: {} }
	}
  }
}
```

With the above, you can model your error states and say, for example:

- `'error.length.tooShort'` and `'error.history.prevUsed'` can both be `true` at the same time
- `'error.tooShort'` and `'error.tooLong'` **must not** both be `true` at the same time

**Comment by rudijs** [comment]
@davidkpiano Great stuff, thank you!

**Comment by rudijs** [comment]
@davidkpiano I'm on v3.3.3 - just using the version I get with `npm install`

Your first example I made two small changes, which I'll add here for documentation for the v3.3.3 case.

1. Add the `states` property to nested states - else it throws (I think just a typo in your example)
2. Use `data` else `meta` leave the `details` undefined (noted v3 and v4 differences)

```
{
  initial: "idle",
  states: {
    idle: {
      on: {
        LOGIN: [
          { target: "active", cond: () => false },
          // { target: "error.noPermission" }
          { target: "error.notEnabled" }
        ]
      }
    },
    active: {},
    error: {
      states: {
        noPermission: {
          data: { details: "No permission" } // 'meta' is v4, 'data' is deprecated (v3)
        },
        notEnabled: {
          data: { details: "Not enabled" }
        }
      }
    }
  }
}
```
