### ISSUE TITLE
@xstate/inspect should not bail in production

### ISSUE THREAD

**Issue by mattpocock** [davidkpiano/xstate#2020]
`@xstate/inspect` works when `process.env.NODE_ENV === 'development'`, but fails when `NODE_ENV === 'production'`. This is due to this line of code:

https://github.com/davidkpiano/xstate/blob/f3870f837e7d86bd4e3a1d28485e76b026579291/packages/core/src/devTools.ts#L43

Reproduction:

https://github.com/mattpocock/xstate-inspect-repro

Instead of bailing here, we should leave it up to the user whether or not they choose to have `devTools: true` in production

**Comment by Andarist** [comment]
Right, the integration with Redux DevTools is available in production (from what I see in the source code) so this should be too.

We probably should put a doc in place to explain to people how to configure stuff properly though so they don't start opening popups in production by accident 🤔

**Comment by SimeonC** [comment]
I too tracked it down to this. I raised an MR without thinking too deeply about it, this morning it occurs to me that we have 2 checks for this, as shown below. `IS_PRODUCTION` and (essentially) `window.__xstate__`.

https://github.com/davidkpiano/xstate/blob/f3870f837e7d86bd4e3a1d28485e76b026579291/packages/core/src/devTools.ts#L43-L47
https://github.com/davidkpiano/xstate/blob/f3870f837e7d86bd4e3a1d28485e76b026579291/packages/core/src/devTools.ts#L33-L35

I think we can just remove the `IS_PRODUCTION` check here and leave the check to whether the dev tools global has been set or not.

> We probably should put a doc in place to explain to people how to configure stuff properly though so they don't start opening popups in production by accident 🤔

I don't think we need anything extra to do this, the popup is triggered from @xstate/inspect and isn't actually checking for `IS_PRODUCTION` anyway so changing this shouldn't change whether the popup opens in production or not. All the dev tools code is doing in xstate core is dealing with that global `__xstate__` devTools object.

https://github.com/davidkpiano/xstate/blob/f3870f837e7d86bd4e3a1d28485e76b026579291/packages/xstate-inspect/src/browser.ts#L131

**Comment by SimeonC** [comment]
@Andarist what do you think about the above just removing the `is prod` flag?

**Comment by Andarist** [comment]
> I don't think we need anything extra to do this, the popup is triggered from @xstate/inspect and isn't actually checking for IS_PRODUCTION anyway so changing this shouldn't change whether the popup opens in production or not. All the dev tools code is doing in xstate core is dealing with that global __xstate__ devTools object.

You are right. I think it should be OK to remove this production check then - unless @davidkpiano doesn't think so.

**Comment by davidkpiano** [comment]
> > I don't think we need anything extra to do this, the popup is triggered from @xstate/inspect and isn't actually checking for IS_PRODUCTION anyway so changing this shouldn't change whether the popup opens in production or not. All the dev tools code is doing in xstate core is dealing with that global **xstate** devTools object.
> 
> You are right. I think it should be OK to remove this production check then - unless @davidkpiano doesn't think so.

That's fine. Just have to make a note in the docs that it's important to prevent the inspector from running in prod, if that is not desirable.
