### ISSUE TITLE
docs don't contain links to svelte package 

### ISSUE THREAD

**Issue by gjungb** [davidkpiano/xstate#2028]
**Description**
There are no obvious links to @xstate/svelte in the docs

**Expected Result**
Docs should contain links to svelte package

**Actual Result**
No link can be found pointing to @xstate/svelte in the docs

**Reproduction**
Go to https://xstate.js.org/docs/ and try to find a reference to the @xstate/svelte package

**Comment by davidkpiano** [comment]
Fixed in #2027

**Comment by gjungb** [comment]
👍
