### ISSUE TITLE
Not working with Svelte/kit beta

### ISSUE THREAD

**Issue by psyCodelist** [davidkpiano/xstate#2032]
Hi David,

When using svelt/kit (beta) with Vite (2.1.2) getting error:

[vite] Error when evaluating SSR module /node_modules/.pnpm/xstate@4.17.0/node_modules/xstate/es/interpreter.js:
SyntaxError: Unexpected token '.'
    at new Function (<anonymous>)
    at instantiateModule (/Users/nima/DeltaStream/node_modules/.pnpm/vite@2.1.2/node_modules/vite/dist/node/chunks/dep-efe32886.js:68893:9)

not sure if it's Vite or xState

**Comment by psyCodelist** [comment]
Ah seems it's vite ssr issue, closing...

**Comment by bwaidelich** [comment]
@psyCodelist were you able to work around this?

**Comment by psyCodelist** [comment]
@bwaidelich , They opened a new issue with Vite. it doesn't work for server less adapter until they fix it.
but if you are using node as your adapter and do not care about server-less stuff, this code in **svelte.config.cjs** will get you going:
vite: {
      ssr: {
        external: Object.keys(pkg.dependencies || {})
      }
    }
