### ISSUE TITLE
Typescript complaining about assign() to static value with multiple context entries

### ISSUE THREAD

**Issue by tivac** [davidkpiano/xstate#2040]
**Description**

When using TypeScript and there are more than a single property defined inside the `context` for a machine it becomes impossible to use a static value with `assign({ <field>: <value> })` without TS complaining. If I'm doing something obviously wrong in TS here I'm very sorry, still pretty new at it.

**Expected Result**

Just like [the guide for assign() says](https://xstate.js.org/docs/guides/context.html#assign-action) it should be totally fine to assign a field to a static value.

**Actual Result**

TS complains with the following error:

```
(property) EVENT?: SingleOrArray<string | StateNode<Context, any, {
    type: "EVENT";
}, {
    value: any;
    context: Context;
}> | TransitionConfig<Context, {
    type: "EVENT";
}>>
Type '{ actions: AssignAction<{ two: false; }, { type: "EVENT"; }>; }' is not assignable to type 'SingleOrArray<string | StateNode<Context, any, { type: "EVENT"; }, { value: any; context: Context; }> TransitionConfig<Context, { type: "EVENT"; }>>'.
```

**Reproduction**

https://codesandbox.io/s/admiring-lumiere-8krhn?file=/src/index.ts

There's comments in the code but if you remove the `one` field from both the `Context` type as well as the `context` machine definition than both forms of `assign({ <field>: ... })` work fine.

**Additional context**

[Discord Question I asked](https://discord.com/channels/795785288994652170/809564589880639548/825130495255904317) with a [response by @mattpocock](https://discord.com/channels/795785288994652170/809564589880639548/825131535845949501) that showed me a workaround.

**Comment by Andarist** [comment]
I believe that there is already some issue about this - and even if not then I'm very aware of this problem. I plan to address this but things take time.

The workaround is to either use an assigned function with `ctx` argument named (even if unused):
```ts
assign<Context>((_ctx) => ({
  sidebar: false
}))

```

 or to parameterized the context type for those manually:
```ts
assign<Context>({
  sidebar: false
})
```
