### ISSUE TITLE
Machine visualizer crashing with basic machine

### ISSUE THREAD

**Issue by JDansercoer** [davidkpiano/xstate#2049]
**Description**
When trying to input this machine into the visualizer, I get a white screen.

```
const clientMachine = Machine({
  id: "toggle",
  initial: "initial",
  context: {
    selectedProspect: null,
    selectedProperty: null
  },
  states: {
    initial: {
      on: {
        NEXT: {
          target: "client",
          actions: assign({
            selectedProspect: (context, event) => event.name
          })
        }
      }
    },
    client: {
      on: {
        NEXT: {
          target: "selected",
          actions: assign({
            selectedProperty: "Home"
          })
        }
      }
    },
    selected: {}
  },
  on: {
    RESET: {
      target: "initial",
      actions: assign({
        selectedProspect: null,
        selectedProperty: null
      })
    }
  }
});
```

This is the console.error that is likely causing the crash

```
TypeError: Cannot read property 'toString' of null
    at StateChartAction.js:75
    at Array.map (<anonymous>)
    at sn (StateChartAction.js:71)
    at Qi (react-dom.production.min.js:3274)
    at ka (react-dom.production.min.js:3899)
    at Vo (react-dom.production.min.js:5514)
    at zo (react-dom.production.min.js:5536)
    at Ns (react-dom.production.min.js:5958)
    at ws (react-dom.production.min.js:5925)
    at Ms (react-dom.production.min.js:6020)
```

As you can see from [this codesandbox](https://codesandbox.io/s/xstate-context-340re?file=/src/clientMachine.js:123-828) the machine appears to do its job.

This also made my XState Dev Tools stop working, but I guess it's related.

**Expected Result**
Have a working visualizer.

**Actual Result**
Visualizer is crashing

**Reproduction**
As stated before, [here is a sandbox with a working machine](https://codesandbox.io/s/xstate-context-340re?file=/src/clientMachine.js:123-828)

**Comment by davidkpiano** [comment]
Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead.

More info: https://xstate.js.org/docs/packages/xstate-inspect/

**Comment by JDansercoer** [comment]
Hi @davidkpiano, I have now updated [the codesandbox](https://codesandbox.io/s/xstate-context-340re?file=/src/clientMachine.js:123-828) with the inspect package. That appears to work.

However, this issue is more about the machine causing a crash in https://xstate.js.org/viz/. Is the online visualizer no longer supported? The same thing is happening in the Chrome Extension.

FWIW, if I were to remove the uppermost `on` key, the visualizer is working just fine. So this code does work

```
const clientMachine = Machine({
  id: "toggle",
  initial: "initial",
  context: {
    selectedProspect: null,
    selectedProperty: null
  },
  states: {
    initial: {
      on: {
        NEXT: {
          target: "client",
          actions: assign({
            selectedProspect: (context, event) => event.name
          })
        }
      }
    },
    client: {
      on: {
        NEXT: {
          target: "selected",
          actions: assign({
            selectedProperty: "Home"
          })
        }
      }
    },
    selected: {}
  }
});
```

But not sure why removing 
```
  on: {
    RESET: {
      target: "initial",
      actions: assign({
        selectedProspect: null,
        selectedProperty: null
      })
    }
  }
```
would somehow fix the machine.

Am I doing something wrong?

**Comment by JDansercoer** [comment]
Aha all right, perfecto! Thanks for the fast responses.
