### ISSUE TITLE
Cannot create actors in visualizer

### ISSUE THREAD

**Issue by blaadje** [davidkpiano/xstate#2072]
**Description**
I'm unable to create actors in the visualizer

**Expected Result**
I expect the `FETCH_PAYMENT_METHOD` event to change state to success in `paymentMethodMachine`

**Actual Result**
It doesnt seem to recognize the actor & I got this error 

```
[Error] Error: Unable to send event to child 'paymentMethod' from service 'fetch'.
	I (2.06c6d969.chunk.js:1:555610)
	Cn (2.06c6d969.chunk.js:1:582990)
	ks (2.06c6d969.chunk.js:1:651381)
	Fe (2.06c6d969.chunk.js:1:562848)
	wn (2.06c6d969.chunk.js:1:583472)
	(anonymous function) (2.06c6d969.chunk.js:1:662002)
	Ms (2.06c6d969.chunk.js:1:651606)
	Rn (2.06c6d969.chunk.js:1:583214)
	Rn
```

I am doing something wrong ? I was trying to follow the documentation cc https://xstate.js.org/docs/guides/actors.html#sending-events-to-actors

**Reproduction**
- [XState Visualizer](https://xstate.js.org/viz/?gist=bd3b1b1984d42fa6816202aa1fde165b)

**Additional context**

**Comment by davidkpiano** [comment]
Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead.

More info: https://xstate.js.org/docs/packages/xstate-inspect/

(The visualizer is running on an old version of XState)
