### ISSUE TITLE
Visualizer crashes when using named delay

### ISSUE THREAD

**Issue by jschaf** [davidkpiano/xstate#2095]
**Description**

When using a named delay, defined by `MachineOptions.Delay`, the visualizer crashes.
```
  states: {
    dirty: {
      after: {SOME_DELAY: {target: 'dirty'}},
    },
  },
```

**Expected Result**

The visualizer should work.

**Actual Result**

The visualizer crashes with:

```
TypeError: m is not a function
    at StateChartNode.js:191
    at Array.map (<anonymous>)
    at e.render (StateChartNode.js:176)
```

On this prettified code:

```js
      if (typeof delay === 'string') {
        var delayExpr = stateNode.machine.options.delays[delay];
        delay = typeof delayExpr === 'number' ? delayExpr : delayExpr(current.context, current.event);
      }
```

**Reproduction**

- [XState Visualizer](https://xstate.js.org/viz/) https://xstate.js.org/viz/?gist=e71e2f415fbc3a44c51913455f67f92b

**Additional context**

Workaround: replace `SOME_DELAY` with a number like 100.

**Comment by davidkpiano** [comment]
Please use the [XState inspector (CodeSandbox template)](https://codesandbox.io/s/xstate-viz-template-f3dtr) instead.

More info: https://xstate.js.org/docs/packages/xstate-inspect/
