### ISSUE TITLE
blocked events are available in the nextEvents array

### ISSUE THREAD

**Issue by AntonS86** [davidkpiano/xstate#2110]
```js
const formMachine = Machine({
  id: 'form',
  initial: 'firstPage',
  states: {
    firstPage: {
      on: {
        LOG: undefined
      }
    },
    secondPage: {
      /* ... */
    },
  },
  on: {
    LOG: {
      actions: 'logTelemetry'
    }
  }
});
const service = interpret(formMachine).start();
console.log(service.state.nextEvents)
// ["LOG"]
```

**Comment by davidkpiano** [comment]
This is working as intended. An `undefined` transition is still a transition; specifically, it's a self-transition with no actions.

The `state.nextEvents` property should avoid listing events where there are no transitions.

However, in the future we can add helpers that determine whether the machine is able to transition (and have the state changed) given an event and payload.
