### ISSUE TITLE
v3 get nested state data

### ISSUE THREAD

**Issue by rudijs** [davidkpiano/xstate#212]
## Question

Hi,

When using nested states in v3, is there an easy way to get the state data?

I was looking for a getData() method or something similar.

Below is a JSON format of a current state, the property `"(machine).inactive.noConnection"` has the data for this state.

Do I need to manually build up the property name, `"(machine).inactive.noConnection"`,  derived from the currentState to access the `details` property inside the `data` object?

Thanks.

## Description:

```
{
  "value": { "inactive": "noConnection" },
  "historyValue": {
    "current": { "inactive": "noConnection" },
    "states": { "inactive": { "current": "noConnection", "states": {} } }
  },
  "history": {
    "value": "loading",
    "actions": [],
    "activities": {},
    "data": {},
    "events": []
  },
  "actions": [],
  "activities": {},
  "data": {
    "(machine).inactive.noConnection": {
      "details": "Cannot connect to Scatter"
    }
  },
  "events": []
}
```

**Comment by davidkpiano** [comment]
That is the ID of the state node that provided the data. What you do with it is up to you; perhaps you can merge it:

```js
const allData = (state) => {
  return Object.keys(state.data).reduce((acc, datum) => {
    return Object.assign(acc, datum);
  }, {});
}

allData(state);
// { details: 'Cannot connect to Scatter' }
```

⚠️ Keep in mind that **in version 4 this property will be renamed to `meta`** because `data` has a special meaning in SCXML, and is used in final states.

**Comment by rudijs** [comment]
@davidkpiano Awesome, thanks!
