### ISSUE TITLE
How to handle parallel nested state

### ISSUE THREAD

**Issue by gilbarbara** [davidkpiano/xstate#22]
Hey David,

I'm playing with xtate and I'm wondering how to handle the parallel state below.

```js
{
  key: "machine",
  parallel: true,
  states: {
	lights: {
	  initial: "on",
	  states: {
		on: {
		  on: { TOGGLE: "off" },
		  initial: "green",
		  states: {
			green: {
			  on: {
				TIMER: "yellow"
			  }
			},
			yellow: {
			  on: {
				TIMER: "red"
			  }
			},
			red: {
			  on: {
				TIMER: "green"
			  },
			  initial: "walk",
			  states: {
				walk: {
				  on: {
					PED_TIMER: "wait"
				  }
				},
				wait: {
				  on: {
					PED_TIMER: "stop"
				  }
				},
				stop: {}
			  }
			}
		  }
		},
		off: {
		  on: { TOGGLE: "on" }
		}
	  }
	},
	animation: {
	  initial: "on",
	  states: {
		on: {
		  on: {
			TOGGLE: "off"
		  }
		},
		off: {
		  on: {
			TOGGLE: "on"
		  }
		}
	  }
	}
  }
}
```

Calling `machine.initialState` returns a shallow object: 
```
{ lights: 'on', animation: 'on' }
```

But subsequent calls to `machine.transition(...).value` returns nested objects.
```
{
  lights: {
     on: 'green'
  },
  animation: 'on'
}
```
and
```
{
  lights: {
     on: {
       red: 'walk'
    }
  },
  animation: 'on'
}
```

Shouldn't `initialState` returns `{ lights: 'on.green'}`?
And calling `.value` shouldn't return `{ lights: 'on.red.walk' }`

Is this the expected behavior?

**Comment by gilbarbara** [comment]
Btw, here's some code: https://codesandbox.io/s/myrp023zl8

**Comment by davidkpiano** [comment]
The nested objects are correct. I wanted to be consistent with the API, so that when you're in a deep state, you always get an object, since that is what that deep state represents.

In your code (awesome example btw!) you have: `lights === "on.red.walk"`, and in the future it's going to be much more type-safe to avoid stringly typed values and check it this way:

```js
if (lights.on && lights.on.red && lights.on.red.walk) { ... }

// or maybe in the future?
if (lights.on?.red?.walk) { ... }
```

However, there's a helper function for you (not documented yet, sorry!) Check it out:

```js
import { Machine, matchesState } from 'xstate';

// ...
if (matchesState('lights.on.red.walk', stateValue)) {
  // ...
}
```

You can check the usage in `tests/matches-state.ts`.

**Comment by gilbarbara** [comment]
Cool, I'm trying to refactor the example with `matchesState`. 

But don't you think it's weird for the `initialState` return a string and change to an object after a transition?
