### ISSUE TITLE
issue with assign - "No implementation found for action type"

### ISSUE THREAD

**Issue by amelon** [davidkpiano/xstate#220]
## Bug or feature request?
bug using version 4.0.0-4.0.1.

It worked previously on 4.0.0-13 and 4.0.0-15.

## Description:
using `assign` makes `action` "invisible".

## (Bug) Expected result:
`action` should be recognized

## (Bug) Actual result:
Here result with exemple on context documentation:

````
No implementation found for action type 'addWater'
````

Here is the  code

````javascript
const { Machine, actions } = require('xstate')
const { assign } = actions
const { interpret } = require('xstate/lib/interpreter')

// Action to increment the context amount
const addWater = assign({
  amount: (ctx, event) => ctx.amount + 1
})

// Guard to check if the glass is full
function glassIsFull(ctx, event) {
  return ctx.amount >= 10
}

const glassMachine = Machine({
  id: 'glass',
  // the initial context (extended state) of the statechart
  initial: 'empty',
  states: {
    empty: {
      on: {
        FILL: {
          target: 'filling',
          actions: 'addWater'
        }
      }
    },
    filling: {
      on: {
        '': {
          target: 'full',
          cond: 'glassIsFull'
        },
        FILL: {
          target: 'filling',
          actions: 'addWater'
        }
      }
    },
    full: {}
  }
})

const int = interpret(glassMachine.withConfig({
  actions: { addWater },
  guards: { glassIsFull }
}).withContext({
    amount: 0
  }))

int.onEvent((...args) => console.log(args))
int.start()

int.send('FILL')
````

You can find code [here](https://repl.it/@amelon/SecondaryLowDoom).

**Comment by davidkpiano** [comment]
The fix is in `master` and will be in the next release.

**Comment by davidkpiano** [comment]
@simlrh - Just pushed, can you pull and try again now?

**Comment by simlrh** [comment]
Yes, seems to be the expected result now, thank you very much. Regarding sending assignments as actions rather than events - the original reporter's code listing is doing it the correct way, is that right?

**Comment by davidkpiano** [comment]
Yes, it's correct, because `assign` is done through actions.

**Comment by davidkpiano** [comment]
Closing as this is fixed in `master`
