### ISSUE TITLE
Memory leak in interpret when using invoke

### ISSUE THREAD

**Issue by morrisis** [davidkpiano/xstate#2216]
**Description**
First, as a new user of xstate of only a month, please excuse my lack of knowledge of the xstate terminology.

When using 'invoke'd async javascript functions, there is a constant and persistent memory leak. This is being generated in the interpreter. Creating a small interpreter to invoke the same actions results in no memory leak.

**Expected Result**
No memory leak, resident memory size should return to normal when all machines and interpreters are no longer referenced.

I have not attached a link to a test area as I believe this needs to be reproduced locally. The code included below is self contained.

**Actual Result**
Memory usage constantly grows until node runs out of memory.

**Reproduction**
```
import { Machine, interpret } from "xstate";

// play with resolved values
const isFirstTimeUsage = async () => { console.log('isFirstTimeUsage invoked'); return true };

const sDef = { services: { isFirstTimeUsage } }
var mDef = {
	id: "main",
	initial: "idle",
	states: {
		idle: {
			on: {
				yes: {
					target: 'doInvoke'
				},
			},
		},
		doInvoke: {
			invoke: {
				src: {
					type: "isFirstTimeUsage",
				},
				onDone: 'intro',
				onError: 'talk'
			},
		},
		intro: {
		},
		talk: {},
	}
}
/**
 * create machine and make a transtion, calling 'invoked' async function
 */
function makeMachineAndTransition() {
	var m = Machine(mDef, sDef);
	var service = interpret(m)
		.onTransition(s => {/* console.log("on Transition", s.value, s.event) */})
		.start();
	service.send('yes')
}
/**
 * Run the machine builder/interpreter n times
 * @param {*} n 
 */
function runNmachines(n) {
	for (var i = 1; i < n; i++) {
		makeMachineAndTransition()
	}
}

function doCloops(c) {
	// global.gc() // enabled with --expose-gc
	console.log(c)
	runNmachines(100)
	var fn = () => doCloops(++c)

	if (c < 10) {
		setTimeout(fn, 10)
	} else {
		console.log('waiting 5 secs, c = ' + c)
		setTimeout(fn, 5000)
	}
}

var c = 0

doCloops(c)

```
**Additional context**

xstate 4.18

node.js 14.15.5

platform Ubuntu 20.04

**Comment by davidkpiano** [comment]
Hey @morrisis, thanks for the reproduction! For anyone curious (and hopefully I'm not doing this wrong), I'm running it by doing:

1. `node --expose-gc --inspect ./path/to/file.js`
2. Inspecting via Chrome dev tools: https://nodejs.org/en/docs/guides/debugging-getting-started/

I don't think the memory leaks are coming from the invoked promises. If you remove the invocation:

```diff
var mDef = {
  id: "main",
  initial: "idle",
  states: {
    idle: {
      on: {
        yes: {
          target: 'doInvoke'
        },
      },
    },
    doInvoke: {
-      invoke: {
-        src: {
-          type: "isFirstTimeUsage",
-        },
-        onDone: 'intro',
-        onError: 'talk'
-      },
    },
    intro: {
    },
    talk: {},
  }
}
```

You will see a similar "memory leak". The problem is here:

```js
function makeMachineAndTransition() {
  var m = Machine(mDef, sDef);
  var service = interpret(m)
    .onTransition(s => {/* console.log("on Transition", s.value, s.event) */})
    .start();
  service.send('yes')
}
```

When a `service` is started, it is registered to a "global registry", where it stays alive until it is stopped. Based on the machine you are using, these machines never get stopped, so they will continue being added to the registry indefinitely, creating an obvious memory leak.

However, if you change the transition to a final state:

```js
// ...
  intro: {
    type: 'final'
  }
// ...
```

There is no more memory leak, because the machines are stopped and removed from the registry.

Let me know if this is a valid assessment - try it out with that final state. If there's anything I missed, I'll reopen this issue. Thanks!

**Comment by morrisis** [comment]
David - Thanks for the followup. I see what you are doing. It makes sense. It is the "global registry" which is hurting me. In my scenario, I am building machines and interpreters for an accessed database record and all children (recursive as needed). Performance is good. It will be necessary to keep track of all the interpreters and manually "stop" them.

There is never a "final" state for this data.

 It never occurred to me that once I de-referenced them they would stick around. I rather expected that once I "lost" the parent machine/interpreter, all children would be "lost" too.

I added more logic to my .destroy() method to stop all children interpreters recursively.

Thanks again for the help.

Ian

**Comment by Andarist** [comment]
If you stop the parent then all children (recursively) should be stopped as well. If you just dereference the parent then this won't happen though - in a similar fashion as if you would dereference unresolved promise, if it ain't resolved then it continues to live in memory.

**Comment by davirbeiro-1** [comment]
Hello I have a question about the promises behavior in xstate. How to control a transition sent by `interpret.send(event),` when a promise didn't finished yet? The activities property indicates when the promise is over, turning its properties values to false. My idea is to always verify the activities property before sending the next event. Is this a good approach?

**Comment by VanTanev** [comment]
> Hello I have a question about the promises behavior in xstate. How to control a transition sent by `interpret.send(event),` when a promise didn't finished yet? The activities property indicates when the promise is over, turning its properties values to false. My idea is to always verify the activities property before sending the next event. Is this a good approach?

Not the place for this discussion, open a new one in the discussion tab.
But basically, there are better ways to handle this depending on constraints. 
You can have a guard on the event, and do the transition only if some condition is met. You can abandon the promise, that is usually also OK. Depends on the goal.
