### ISSUE TITLE
The TODO MVC VueJS Application does not save a change to a TODO item once created.

### ISSUE THREAD

**Issue by bernarma** [davidkpiano/xstate#2249]
Example from here: https://xstate.js.org/docs/examples/todomvc.html#todomvc-with-vue

**Description**
Open the CodeSandbox via the link above.
Add a new TODO Item.
Double click on the newly created TODO item and attempt to modify the name.
Press enter to save.

**Expected Result**
The TODO item should be updated with the newly entered name.

**Actual Result**
The TODO item name reverts back to the previously entered value.

**Reproduction**
https://codesandbox.io/s/blue-fire-zd796?from-embed (as linked from the website).

**Additional context**
No other context.

**Comment by santicros** [comment]
The current example of the todo-mvc for Vue has different problems and is outdated with Vue 2. It's currently not even working for me :(

In this PR I've created a new version of it with everything working and updated to Vue 3:
https://github.com/davidkpiano/xstate/pull/2351
