### ISSUE TITLE
Difficult to realize initial state is missing, due to unclear error message

### ISSUE THREAD

**Issue by robertpenner** [davidkpiano/xstate#2258]
**Description**
While defining a machine, I find it's quite easy to forget to define an initial state. This triggers a run-time error, which is good, but the error message doesn't help me pinpoint the problem. 

**Expected Result**
A clear error message diagnosing the initial state issue, e.g.: 
```
Initial state missing on [state node]
```

**Actual Result**
The error message reads:
```
Uncaught Error: Cannot retrieve initial state from simple state
```
(Secondarily, in XState Viz, this error doesn't pop up in the UI. Rather, the viz silently fails to update, so I have to open Console to see there's an error.)

**Reproduction**
I can't link to a saved XState Viz because omitting an initial state prevents saving, but here's the code:
```
const machine = Machine({
  states: {
    idle: {},
  },
});
```

**Additional context**
After filing this issue, I noticed that in Codesandbox with xstate 4.19.0, there is a better error message:
```
Warning: Compound state node '(machine)' has no initial state. 
```
So apparently this is about XState Viz being on an older version.

**Comment by davidkpiano** [comment]
> **Additional context**
> After filing this issue, I noticed that in Codesandbox with xstate 4.19.0, there is a better error message:
> 
> ```
> Warning: Compound state node '(machine)' has no initial state. 
> ```
> 
> So apparently this is about XState Viz being on an older version.

Yeah, when the visualizer is updated (still working on it), this problem will go away, so I'll close this as a duplicate (since there are other issues related to the visualizer being out-of-date) if that's okay.
