### ISSUE TITLE
Unable to use xstate in the browser

### ISSUE THREAD

**Issue by TimvdLippe** [davidkpiano/xstate#227]
## Bug or feature request?
Bug
## Description:
In `StateNode.ts`, there is a reference to `process`. Since a web browser does not have this variable, you can not load xstate using ES modules in a browser.
## (Bug) Expected result:
I can load xstate using ES modules in a browser
## (Bug) Actual result:
`process is not defined`
## (Bug) Potential fix:
This is a similar issue to https://github.com/reduxjs/redux/issues/2907 which I fixed in https://github.com/reduxjs/redux/pull/3143 that correctly generates an ES bundle.
I went ahead and did this locally, but I saw your `es/` folder output actually contains all `tsc` build targets. The fix would therefore be impossible if someone would directly use `es/StateNode.ts`.
I would propose to generate a new bundle called `es/index.mjs` just like Redux, but with the reference to `process` removed.

**Comment by davidkpiano** [comment]
Fix made in `master` - can you please test it out and see if it works for your use-cases?

**Comment by TimvdLippe** [comment]
@davidkpiano Finally had time to verify and yes it has been fixed :tada:
