### ISSUE TITLE
'Global' actions are overridden by state specific actions when both are triggered by the same event

### ISSUE THREAD

**Issue by el-dav** [davidkpiano/xstate#2273]
**Description**
'Global' actions are overridden by state specific actions when both are triggered by the same event

**Expected Result**
Both 'Global' and state specific actions should be triggered

**Actual Result**
Only the state specific action is triggered

**Reproduction**
- [CodeSandbox (JavaScript) reproduction](https://codesandbox.io/s/determined-bell-cic83?file=/src/App.js)

**Additional context**
In the following example when the `TEST` event is received only `IDLE` is logged. I would have expected both `Global` and `State Specific` to be logged. If the state specific action doesn't exist then `Global` is logged.
```
const testMachine = createMachine({
  id: "testMachine",
  initial: "IDLE",
  on: {
    TEST: {
      actions: log("global")
    }
  },
  states: {
    IDLE: {
      on: {
        TEST: {
          actions: log("State Specific")
        }
      }
    }
  }
});
```

There is no issue with parallel states responding to the same action so my current workaround is to create a parallel state which is always active and put any global actions there. E.g.: [CodeSandbox of workaround](https://codesandbox.io/s/admiring-hoover-8dsut?file=/src/App.js)

**Comment by with-heart** [comment]
I believe that's intentional although I couldn't find anything about it on Discord or in the docs. It allows more specific states to override the `actions` defined in outer states, sort of like overriding defaults.

I've run into situations where I wish I could specify that I wanted them both to happen though.

**Comment by davidkpiano** [comment]
> I believe that's intentional although I couldn't find anything about it on Discord or in the docs. It allows more specific states to override the `actions` defined in outer states, sort of like overriding defaults.

Yes, this is working as designed.

> I've run into situations where I wish I could specify that I wanted them both to happen though.

That's where parallel states come in handy. Otherwise, you can do this in user-land:

```js
on: {
  TEST: {
    // custom function
    actions: withGlobalActions(log('State specific')) // appends action to global actions
  }
}
```

**Comment by with-heart** [comment]
@davidkpiano Thanks for the info!

**Comment by el-dav** [comment]
Okay thanks, good to know!
