### ISSUE TITLE
transitioning in actions

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#232]
## Guidance

I've been looking through the docs & can't find any examples of calling a transition from an action. Example, if an action contacts a server for a user to sign in, I'd want to transition to ethier signedIn or error state based on the response:

```js
const signInMachine = Machine({
  id: 'signIn',
  initial: 'dataEntry',
  strict: true,
  states: {
    dataEntry: {
      on: { 
        SUBMIT: {
          target: 'awaitingResponse',
          actions: ['contactService']
        }
      }
    },
    awaitingResponse: {
      on: {
        SUCCESS: 'signedIn',
        FAIL: 'error'
      }
    },
    signedIn: {},
    error: {}
  }
}, {
  actions: {
    contactService: (ctx, evt) => {
      myContactServerFunc()
        .then(() => transition to signedIn state)
        .catch(() => transition to error state)
    }
  }
})
```

I have seen examples of pulling out a send method from the library:
```
import { Machine, actions } from 'xstate'
const { send } = actions;
```
However this does not work.

**Comment by davidkpiano** [comment]
Invoking promises example: https://xstate.js.org/docs/guides/communication.html#invoking-promises
