### ISSUE TITLE
Discord link on xstate.js.org is invalid

### ISSUE THREAD

**Issue by DexterShepherd** [davidkpiano/xstate#2336]
**Description**
It seems like the discord invite on xstate.js.org is invalid. Maybe it's expired? 

Thanks for the great library. Looking forward to getting into the community and learning more. 

**Expected Result**
Clicking the discord link on xstate.js.org/docs or the community link on xstate.js.org should link to a valid discord invite or community page.

**Actual Result**
Both links point to an invalid or expired discord invite

**Reproduction**
Navigate to xstate.js.org and click the "community" button, or xstate.js.org/docs and click the "discord" button in the top nav. Screen Recording: https://www.loom.com/share/9272f4c0fcc64edf96c1024428487837

**Comment by santicros** [comment]
Can you try to open the link on incognito? It's this one: https://discord.com/invite/xstate

For me it's working! Maybe its some chache or something

**Comment by DexterShepherd** [comment]
Interesting, it does in fact work in incognito mode. Must be something on my end then, feel free to close. 

Sorry for the false report, I'm not that familiar with discord and assumed these were just static links that either worked or didn't.

**Comment by davidkpiano** [comment]
For all others having trouble: https://discord.gg/xstate
