### ISSUE TITLE
Implementing types for configuration

### ISSUE THREAD

**Issue by valjusha** [davidkpiano/xstate#235]
## Description:
When updating the package, there were difficulties with the description of the types for `MachineConfig`.
You can set an example for enum fileds work.

```
const machineConfig = {
    strict: true,
    initial: S.pending,
    states: {
        [S.pending]: {
            on: {
                [E.NEXT]: S.working,
            }
        },
        [S.working]: {
            onEntry: [A.add_delay],
            on: {
                [E.NEXT]: S.pending,
            }
        }
    }
};
```
How to write an interface when working with Enums?
Thanks

**Comment by davidkpiano** [comment]
This is described here: https://xstate.js.org/docs/guides/typescript.html#using-typescript
