### ISSUE TITLE
Feature: In place action defintion

### ISSUE THREAD

**Issue by galliumstudio** [davidkpiano/xstate#238]
Can we define actions in-place along with the transition definition? Currently we can only put a name of the action, and then define the implementation of the action in a separate object name "actions".

It would be nice to define an anonymous function right in the transition. This would make it easier to follow the source code along with the graphical statechart. 

Thanks!

**Comment by davidkpiano** [comment]
Currently, you can use inline named functions for this. Having anonymous functions makes debugging and reuse more difficult.

**Comment by mikaelkaron** [comment]
You could add that quite easily yourself by generating a combination `context` and `stateSchema`:

```javascript
const actions = {};

const add = (name, action) => {
  if (action === undefined) {
    action = name;
    name = action.name;
  }

  actions[name] = action;

  return name;
};

const notifyActive = (ctx, event) => {
  console.log("active!");
};

const sendTelemetry = (ctx, event) => {
  console.log("time:", Date.now());
};

const context = {
  id: "trigger",
  initial: "inactive",
  states: {
    inactive: {
      on: {
        TRIGGER: {
          target: "active",
          // transition actions
          actions: [
            add(function activate(ctx, event) {
              console.log("activating...");
            }),
            "sendTelemetry"
          ]
        }
      }
    },
    active: {
      // entry actions
      onEntry: [add(notifyActive), "sendTelemetry"],
      // exit actions
      onExit: [
        add("notifyInactive", (ctx, event) => {
          console.log("inactive!");
        }),
        "sendTelemetry"
      ],
      on: {
        STOP: "inactive"
      }
    }
  }
};

const stateSchema = {
  actions: {
    // action implementations
    sendTelemetry
  },
  ...actions
};

console.log(context, stateSchema);
```

I'm not 💯 this was what you are looking for but it's a common pattern.

**Comment by mikaelkaron** [comment]
And I guess in _theory_ you _could_ add that as the default so you don't need `actions` and `add` but since it's so easy to add yourself I'm not sure it's worth trying to get it into the official API.

**Comment by galliumstudio** [comment]
Thanks for the reply. I tried it out and using an anonymous function for actions works already. For my purpose, this works better than specifying individual action functions separately. Please keep this feature!
