### ISSUE TITLE
Question: Reusing a generic machine

### ISSUE THREAD

**Issue by lorlab** [davidkpiano/xstate#239]
Hi! I would like to know what a good approach is for reusing a generic Machine.

Say I’m building a CMS, and in each component I make one or more requests to create/update entities. I would like to reuse a generic ‘network request’ machine to keep track of which request is pending, has succeeded or has failed in order to update the UI.

What I'm currently doing is creating a new service using the interpreter for each request I need to make, passing different machine configurations using ‘withConfig’

```js
import requestMachine from ‘./requestMachine’

const updateUserService = interpret(requestMachine.withConfig({
  actions: {
    performRequest: updateUser,
    requestSuccess: showSuccessMessage,
    requestFailure: showErrorMessage
  }
})).start()

const createBlogPostService = interpret(requestMachine.withConfig({
  actions: {
    performRequest: createBlogPost,
    requestSuccess: ...,
    requestFailure: ...
  }
})).start()
```

Am I on the right track or is there a better way? 
Thanks!

**Comment by davidkpiano** [comment]
What does the `requestMachine` look like?

**Comment by davidkpiano** [comment]
With `invoke`, you can model a request like this:

```js
const requestMachine = Machine({
  id: 'request',
  strict: true,
  initial: 'idle',
  states: {
	idle: {
	  on: { REQUEST: 'pending' }
	},
	pending: {
	  invoke: {
		src: (ctx, event) => fetchFromSomewhere(...),
		onDone: 'success',
		onError: 'failure'
	  }
	},
	// ...
  }
});
```

You can make a function that returns a machine:

```js
const createRequestMachine = (fetcher) => Machine({
  // ...
  invoke: {
	src: (ctx, event) => fetcher(ctx, event)
    // ...
  }
  // ...
});

const getUserMachine = createRequestMachine(fetchUser);
```

Lots of different ways you can approach this (it's just JS 😄)

**Comment by lorlab** [comment]
Ok thanks now I get it! 
I like the factory function approach to reuse and configure a machine.

Maybe it could be clearer in the docs that invoke is not only for "communicating between machines" (which is the title of the page), but it can also be used in situations such as this.

**Comment by houkagoweedtime** [comment]
@davidkpiano perhaps not entirely related to the question, but how would I add generic typings for typescript via `.withConfig`?

```tsx
interface RequestEvent{
  type: 'START'
}

const requestMachine = createMachine<{ ...stuff }, RequestEvent>(
  {
    initial: 'ready',
    states: {
      ready: {
        on: { START: 'loading' }
      }
    }
  }
)

// usage
const [state, send] = useMachine(
  requestMachine.withConfig({
    services: {
      // property "foo" does not exist on type "RequestEvent"
      saveFoo: (context, { foo }) => ...logic
    }
  })
)

<button onClick={() => send({ type: 'START', foo: 'bar' })}>save foo</button>
```
I tried something like
```tsx
interface RequestEvent {
  type: 'START'
}

const makeRequestMachine = <T>({ services }) => createMachine<Context, t & RequestEvent >(...)
```
this doesn't work though...is there some idiomatic way of doing this?

**Comment by davidkpiano** [comment]
> @davidkpiano perhaps not entirely related to the question, but how would I add generic typings for typescript via `.withConfig`?
> 
> ```tsx
> interface RequestEvent{
>   type: 'START'
> }
> 
> const requestMachine = createMachine<{ ...stuff }, RequestEvent>(
>   {
>     initial: 'ready',
>     states: {
>       ready: {
>         on: { START: 'loading' }
>       }
>     }
>   }
> )
> 
> // usage
> const [state, send] = useMachine(
>   requestMachine.withConfig({
>     services: {
>       // property "foo" does not exist on type "RequestEvent"
>       saveFoo: (context, { foo }) => ...logic
>     }
>   })
> )
> 
> <button onClick={() => send({ type: 'START', foo: 'bar' })}>save foo</button>
> ```
> 
> I tried something like
> 
> ```tsx
> interface RequestEvent {
>   type: 'START'
> }
> 
> const makeRequestMachine = <T>({ services }) => createMachine<Context, T & RequestEvent >(...)
> ```
> 
> this doesn't work though...is there some idiomatic way of doing this?

Can you ask this in the discussions?
