### ISSUE TITLE
Some thoughts & ideas

### ISSUE THREAD

**Issue by jayrbolton** [davidkpiano/xstate#24]
Hi @davidkpiano, I wanted to thank you for doing the node conf talk and leading the way with Harel Statecharts (I really enjoyed reading the book that you cited). Here I want to list some thoughts I've had to get some general feedback. I'll go ahead and close this issue after I open it. (I'm not saying any of these ideas should necessarily be part of this module)

One alternative API could be to separate out states and events into their own sections. Nested states could go in a "where" property. I think there are some intuitive advantages to this format, but the preference might be subjective. For example:

```js
const paymentMachine = Machine({
  initial: 'method',
  states: ['method', 'review', 'paid'],
  events: {
    NEXT: ['method', 'review'],  // [from, to]
    PAY: ['review', 'paid'],
    PREV: ['review', 'method.$history']
  },
  where: {
    method: {
      initial: 'cash',
      states: ['cash', 'check'],
      events: {
        SWITCH: [ ['check', 'cash'], ['cash', 'check'] ] // [ [from, to], [from, to] ]
      }
    }
  }
})
```

Also, an easy way to do parallel states would be to represent the `initial` value as an object of booleans: `initial: {notLoading: true, method: {check: true}}`. 

Have you thought about general approaches around tying these statecharts into your app data? A couple possibilities I've considered are:
* Use state machines as simple properties within your existing app data. Eg. you have a User object/model that has a state machine property for its registration/session/confirmation/etc statuses
* Use parameterized state machines where you store data inside the machine itself. You could have transition functions that take an argument and update the machine's data on a state transition. I think this is towards UML territory? :skull:

The two above approaches are inverses of eachother, and both put the state machine in your app data layer. I was also thinking that state machines may best belong in your presentation and layout layer. In this case, they could be built into your functions for generating DOM elements. A strange idea..

```js
const paymentProcess = elem('div', {
  machine: {
    initial: 'method',
    states: ['method', 'review', 'paid'],
    events: {
      NEXT: ['method', 'review'],  // [from, to]
      PAY: ['review', 'paid'],
      PREV: ['review', 'method.$history']
    }
  }
}, [ // children go here

 // Payment method selector
 elem('div', {
   class: {visible: 'method'}, // has this class when in this state
   machine: {
     initial: 'cash',
     states: ['cash', 'check'],
     events: {
       SWITCH: [ ['check', 'cash'], ['cash', 'check'] ] // [ [from, to], [from, to] ]
     }
   }
 }, [ 
   elem('p', state => 'selected ' + state),
   elem('button', {on: {click: 'SWITCH'}}, 'select cash'),
   elem('button', {on: {click: 'SWITCH'}}, 'select check')
 ]),

 // Review screen 
 elem('div', { class: {visible: 'review'} }, [
   elem('button', {on: {click: 'PREV'}}, 'go back'),
   elem('button', {on: {click: 'PAY'}}, 'pay!'),
 ]),

 // Paid
 elem('div', { class: {visible: 'paid'} }, [
   elem('p', "you're paid up!")
 ])
])
```

I'm unsure how the above would integrate with your app data. My ideal architecture would look something like:
- Write statecharts that describe your UI behavior -- this can map pretty closely to the layout of your page
- Write data types that describe your data layer (eg. a User) -- these should be totally unbound to your layout and need not be nested underneath any elements.
- Map statechart transitions from anywhere on the page to updates in your data layer. 
- Map values from your data layer to content anywhere on the page. 

To give some context, I have been working on a project called [Uzu](https://github.com/uzujs/uzu) where I've been thinking of working in Harel Statecharts as the primary event mechanism. As you can see, the current design uses a simple event emitting object and is very bottom-up and event-driven.

**Comment by davidkpiano** [comment]
Thanks for writing this up - lots of good ideas in here! 

In order to keep `xstate` as pure as possible (a "functional" statechart transition function of sorts), I want to avoid "keeping" data inside the state machine as much as possible, which is the major difference from other state machine libraries. I don't think it's a good idea to either 1) assume or 2) take complete control of how developers manage state, and by having `machine.transition(...)` be a pure function, we avoid both of those concerns.

That way, mapping values to UI/extended state is just a matter of using the result of the pure `transition` function to update state in whichever way you want.

Also, take a look at the guards (#10) proposal - those are going in soon and will be able to more easily deal with extended state.
