### ISSUE TITLE
Feature Request: Delays as timestamps rather than ms

### ISSUE THREAD

**Issue by waynerobinson** [davidkpiano/xstate#244]
There are situations where we might want to freeze and store a state machine and then load it again at a later date.

It would be useful if delays were stored as a future timestamp that is included in the state/context so that when a machine is loaded again, any pending delays that have already passed would be fired.

**Comment by davidkpiano** [comment]
What would this potentially look like, in code?

**Comment by waynerobinson** [comment]
You’re right, let me schedule in some time to get back to this with code examples. 

But at it’s core, it would allow the currently delayed actions to be part of the state so that if you import the state again elsewhere, the current executing timers would restart where they left off based on wall-time. 

Our use case is to allow us to have a series of redundant state machines running that each check out machines from a server and, if they go away for whatever reason (die, rebalancing, etc) that another machine can check out the most recent state and keep processing where the old executor left off.

**Comment by davidkpiano** [comment]
Thinking about this more, we can make this analogous to the `delayexpr` attribute in SCXML (see https://www.w3.org/TR/scxml/#send):

```js
// ⚠️ Tentative future API
const futureMachine = Machine({
  id: 'future',
  context: {
    // rehydrated 
    time: Date.now(),
    delayedTimestamp: /* some timestamp */
  },
  initial: 'active',
  states: {
    active: {
      after: [
        {
          // If delay <= 0, execute immediately
          delay: ctx => ctx.time - delayedTimestamp,
          target: 'otherState',
          actions: [/* ... */]
        }
      ]
    },
    otherState: {
      /* ... */
    }
  }
});
```

And some action would `assign` the `delayedTimestamp` based on the current time.

This also makes testing timed delays very straightforward:

```js
const futureTime = futureMachine.withContext({
  time: // time in past
  delayedTimestamp: // time in future
});

// did not transition yet
assert.equal(futureTime.initialState.value, 'after');

const pastTime = futureMachine.withContext({
  time: // time in future
  delayedTimestamp: // time in past (or equal to time)
});

// should transition
assert.equal(pastTime.initialState.value, 'otherState');
```

So the only change I'd have to make is support for `delayexpr`, which is just making `delay` accept a function expression that takes `context` and `event` (like all other expression-based properties) and returns the delay in milliseconds.

Thoughts?
