### ISSUE TITLE
Resolving promise within invoke triggers onError 

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#248]
## Description:
When using a promise as the value of `src` within `invoke`, if the promise resolves, onError is triggered. 

## Expected result:
`onSuccess` triggered

## Actual result:
`onError` triggered

## Potential fix:
Uncomment `function fromPromise` in `xstate/src/invoke.ts`

**Comment by davidkpiano** [comment]
Do you have a reproducible code example?

**Comment by bradwoods** [comment]
sure, [codesandbox](https://codesandbox.io/s/nr64o8wp1l)

**Comment by davidkpiano** [comment]
Funny enough, this is working as intended because **there is an error** ❌:

If you log out the event data from the error:

```js
        onError: {
          target: "failure",
          actions: (_, e) => console.error(e.data)
        }
```

You will see:

> `Error: Child state 'success' does not exist on 'user'`

And that's exactly what happened - you don't have a `success` state. Add it and it works 👍

---

I'm going to keep this open because I want to better handle what happens if you _don't_ have an `onError` handler and an error occurs anyway (the script should throw that exact error).

**Comment by bradwoods** [comment]
That makes sense. I may have messed up the example when moving it to code sandbox but the source of the problem I had was using the property `onSuccess` instead of `onDone`, which logs out this error: `Machine 'user' does not accept event 'done.invoke.promise'`. Not sure where I picked up the `onSuccess` property, I see in the docs example it is `onDone`.

**Comment by bradwoods** [comment]
I also made the assumption that`onDone` was synonymous with the JS promise method `.finally`, which triggers after success or error.

**Comment by davidkpiano** [comment]
The names `onDone` and `onError` come from the [SCXML Spec](https://www.w3.org/TR/scxml/#errorsAndEvents), which raises:

- `done.invoke.<id>` when the invoked service has reached its final state
- `error.execution` when errors occur during execution

**Comment by bradwoods** [comment]
Interesting, the onDone & onError syntax is quite nice though.

**Comment by davidkpiano** [comment]
Should be fixed in `master` thanks to @jjkola's work.
