### ISSUE TITLE
Feature: Custom evaluateGuard function

### ISSUE THREAD

**Issue by webstacker** [davidkpiano/xstate#249]
## (Feature) Potential implementation:

I'm working on a [module that allows rules to be serialized as JSON](https://github.com/webstacker/json-rules). It would be nice to do something like this so that I can use it to evaluate the conditions:

```js
const myMachine = Machine(
    {
        context: {
            foo: {
                bar: ['baz']
            }
        },
        initial: 'a',
        states: {
            a: {
                on: {
                    FOO: {
                        target: 'b',
                        // only transition to 'b' if ctx.foo.bar[0] === 'baz'
                        cond: ["==", "$.foo.bar.0", "baz"]
                    }
                }
            },
            b: {}
        }
    },  
    {
        evaluateGuard: (cond, ctx, eventObject, interimState) => {
            // cond: ["==", "$.foo.bar.0", "baz"]
            return jr.evaluate(cond, ctx);
        }
    }
);

myMachine.transition('a', 'FOO').value; // b
myMachine.transition('a', 'FOO', {foo:{bar:['bag']}}).value; // a
```

Is this something that would be considered? Thanks

**Comment by davidkpiano** [comment]
For sure - the lowest-common denominator is using a string-as-condition and mapping it to a real transition.

Some more discussion about this in #57, but I think that it would be reasonable to allow any JSON-serializable value, not just strings, in `cond: ...`.

**Comment by davidkpiano** [comment]
Added in 4.4: https://xstate.js.org/docs/guides/guards.html#custom-guards
