### ISSUE TITLE
Nested initial states

### ISSUE THREAD

**Issue by ferdinandsalis** [davidkpiano/xstate#25]
Hey David,

This project is really interesting. Great work! I have a question though.

With the following machine (example from the readme) the `machine.initialState` will be `method`.

```js
{
  initial: 'method',
  states: {
    method: {
      initial: 'cash',
      states: {
        cash: { on: { SWITCH_CHECK: 'check' } },
        check: { on: { SWITCH_CASH: 'cash' } }
      },
      on: { NEXT: 'review' }
    },
    review: {
      on: { PREVIOUS: 'method.$history' }
    }
  }
}
```

However I was expecting it to be `method.cash`. This is further solidified by the first transition you give in the example:
```
const checkState = paymentMachine
  .transition('method.cash', 'SWITCH_CHECK');
```

Can you explain why that is the case?

**Comment by davidkpiano** [comment]
The initial specified state is `'method'`, but the initial _resolved_ state is `'method.cash'`. The process for resolving the initial state (for non-parallel machines) is:
1. Find the specified initial state config (`'method'` in this case)
2. Recursively find the initial state of that state
3. If no initial state exists (leaf node), you're done.

Hope that answered your question!

**Comment by ferdinandsalis** [comment]
Yes it did, thank you!

**Comment by carloslfu** [comment]
Hey, @davidkpiano great work on this library! I think would be handy to have a small method for resolving the initial state inside this library, because is a very common task.

**Comment by davidkpiano** [comment]
@carloslfu That would be `machine.initialState`. Is that what you're asking? That gives you the `State` object that represents the initial state of the machine.

**Comment by carloslfu** [comment]
Oh, I'm sorry I was confusing `machine.initial` with `machine.initialState`. Thanks, @davidkpiano.
