### ISSUE TITLE
Documentation - Broken link to Machine Configuration

### ISSUE THREAD

**Issue by dance2die** [davidkpiano/xstate#253]
## Description: Broken Link for Machine Configuration

On the bottom of [Hierarchical State Machines](https://xstate.js.org/docs/guides/hierarchical.html) documentation, there is a following sentence.

> If neither a state nor any of its ancestor (parent) states handle an event, no transition happens. In strict mode (specified in the [machine configuration](https://xstate.js.org/docs/guides/api/config.html)), this will throw an error.

The link to the `machine configuration` is broken, which points to non-existent link https://xstate.js.org/docs/guides/api/config.html.

### Here is the demo.

![2018-11-25_10-56-40](https://user-images.githubusercontent.com/8465237/48981272-3dadc780-f0a1-11e8-8145-c45e169db90c.gif)

## (🐛) Expected result:

Takes you to the `Machine Configuration` documentation.

## (🐛) Actual result:

![image](https://user-images.githubusercontent.com/8465237/48981304-93826f80-f0a1-11e8-8f6b-732560be6c51.png)

## (🐛) Potential fix:

Create a new documentation `api/config.md`.

_(Search result [URL](https://github.com/davidkpiano/xstate/search?q=config.md&unscoped_q=config.md))._

_As I just started learning, not sure what's to be in it._

![image](https://user-images.githubusercontent.com/8465237/48981318-c88ec200-f0a1-11e8-963b-465cd1391198.png)

**Comment by davidkpiano** [comment]
Thanks for the detailed report! It is indeed linked to the wrong place. I'll fix it 🔜

**Comment by dance2die** [comment]
You're welcome & thank you XState~
