### ISSUE TITLE
Add support for actions with parameters

### ISSUE THREAD

**Issue by bedeho** [davidkpiano/xstate#26]

**Comment by davidkpiano** [comment]
Can you expand on what you mean by this?

**Comment by bedeho** [comment]
See  https://en.wikipedia.org/wiki/UML_state_machine#Events

> An event can have associated parameters, allowing the event instance to convey not only the occurrence of some interesting incident but also quantitative information regarding that occurrence. For example, the Keystroke event generated by pressing a key on a computer keyboard has associated parameters that convey the character scan code as well as the status of the Shift, Ctrl, and Alt keys.

**Comment by davidkpiano** [comment]
The API is already set up to handle actions with payload/parameters:

```js
machine.transition('green', {
  type: 'TIMER', // the action is determined on the object's `type` prop
  timestamp: Date.now()
});
```

When I add guard functions, they will be able to make use of action parameters.

**Comment by bedeho** [comment]
I see, I must have missed that in the readme examples, perhaps having standalone docs would be useful also? Closing.
