### ISSUE TITLE
Typescript: matchesState typed for StateValue, also works with State

### ISSUE THREAD

**Issue by craigglennie** [davidkpiano/xstate#260]
## Bug or feature request?

Maybe a bug?

## Description:

The type signature for `matchesState` does not support all the functionality available via vanilla JS.

The signature (in `utils.ts`) is

```
export function matchesState(
  parentStateId: StateValue,
  childStateId: StateValue,
  delimiter: string = STATE_DELIMITER
)
```

But the function implementation in practice also accepts a State object. You can see that in @carloslfu's [example code](https://github.com/carloslfu/use-machine/blob/master/README.md) for their `useMachine` library - if you look at the `App` function you'll see a line (in `render(...)`)

`{matchesState(machine.state, 'Off') ? 'Off' : 'On'}`

In this case `machine.state` is an instance of `State`. And this works fine. But if you convert this code to Typescript you'll need to change to using `machine.state.value`, or it won't compile.

## (Bug) Expected result:

Either `matchesState` supports both `State` and `StateValue` objects in both TS and JS (preferred)
OR 
`matchesState` doesn't accept `State` in JS, to make it consistent with the TS version.

## (Bug) Actual result:

`matchesState` only supports `StateValue` in TS.

## (Bug) Potential fix:

Change the signature of `matchesState` to accept either `StateValue` or `State`, if you think it's worthwhile to have this convenience (I think it probably is, especially as the function is named `matchesState` not `matchesStateId` or `matchesStateValue`. If you don't think this is a good change I'll suggest to @carloslfu that the example in the `useMachine` repo be changed to use `machine.state.value`.

I tried to create a PR for this, but as a TS newbie I wasn't sure whether `machineState` should accept `StateValue | StateInterface` or `StateValue | State`.

**Comment by davidkpiano** [comment]
Note: you can (and should) use `state.matches(...)` to match against an actual state. See here: https://xstate.js.org/docs/guides/states.html#state-methods-and-getters

**Comment by davidkpiano** [comment]
`matchesState` in JavaScript will actually resolve `State` instances to its state value. This will be an error in TypeScript, which is expected - you should use `state.value` or `state.matches(value)` instead.
