### ISSUE TITLE
Context not persisting after assign

### ISSUE THREAD

**Issue by jonlaing** [davidkpiano/xstate#272]
## Bug or feature request?
Bug? (Maybe?)

## Description:
I have an invoked machine for authentication. When I change the username, the password becomes blank, and vice versa. It seems like `assign` isn't taking old contexts into account when updating, and is instead merging with the initial context. (For the record, `sendStatus` is a custom thing I made for dealing with nested machines sharing context, I don't think it's the culprit, though). Also, I'm using the builtin interpreter.

### Base Machine

```typescript
/* ... */
auth: {
      on: {
       /* ... */
      },
      invoke: {
        id: "auth",
        src: Auth,
        forward: true,
        onDone: {
          target: "main",
          actions: [
            assign<MainContext>({
              auth: (ctx, evt) => ({ ...ctx.auth, ...evt.data.data })
            })
          ]
        }
      }
    },
  /* ... *./
```

### Auth Machine (invoked)
```typescript
/* ... */
  context: {
    email: "",
    password: "",
    error: null
  },
/* ... */
    enterInfo: {
      on: {
        [AuthEventType.EnterEmail]: {
          target: "enterInfo",
          actions: [
            assign<AuthContext, EnterEmailEvent>({
              email: (ctx, evt) => evt.email
            }),
            log(ctx => ctx, "login context (email)"),
            sendStatus("ChangeEmail", (ctx, evt) => ({ email: evt.email }))
          ]
        },
        [AuthEventType.EnterPassword]: {
          target: "enterInfo",
          actions: [
            assign<AuthContext, EnterPasswordEvent>({
              password: (ctx, evt) => evt.password
            }),
            log(ctx => ctx, "login context (password)"),
            sendStatus("ChangePassword", (ctx, evt) => ({
              password: evt.password
            }))
          ]
        }
    /* ... */
```

## (Bug) Expected result:

I have it logging with every update, and I would expect it to look something like this:

```
[1] [21:36:07] login context (email) Object {
[1] [21:36:07]   "email": "Asdfs",
[1] [21:36:07]   "error": null,
[1] [21:36:07]   "passcode": "",
[1] [21:36:07]   "password": "",
[1] [21:36:07] }
... Extra typing...
[1] [21:36:08] login context (password) Object {
[1] [21:36:08]   "email": "Asdfs", <== email is preserved
[1] [21:36:08]   "error": null,
[1] [21:36:08]   "passcode": "",
[1] [21:36:08]   "password": "asdfs",
[1] [21:36:08] }
```

## (Bug) Actual result:

```
[1] [21:36:07] login context (email) Object {
[1] [21:36:07]   "email": "Asdfs",
[1] [21:36:07]   "error": null,
[1] [21:36:07]   "passcode": "",
[1] [21:36:07]   "password": "",
[1] [21:36:07] }
... Extra typing...
[1] [21:36:08] login context (password) Object {
[1] [21:36:08]   "email": "", <== email is gone
[1] [21:36:08]   "error": null,
[1] [21:36:08]   "passcode": "",
[1] [21:36:08]   "password": "asdfs",
[1] [21:36:08] }
```

## (Bug) Potential fix:

I looked through the code, but I can't seem to find how the interpreter knows to merge the contexts, but I figure if this is legitimately a bug, and not user error, then the answer would be there.

**Comment by davidkpiano** [comment]
Can you put this example into https://codesandbox.io ?

**Comment by jonlaing** [comment]
Well, I put it into the code sandbox, but I'm not seeing the same error... but for the record, I'm seeing the error in react-native, so I'm not sure if it's an environment thing or what. I'm going to keep trying to bang on it and see if I can suss out where the problem is.

**Comment by davidkpiano** [comment]
>  I could generalize some of my code a little and post it up as an example of nesting machines in this way.

This would be extremely helpful, thanks!

**Comment by ClemensSahs** [comment]
@davidkpiano 

I have some similar result ... currently I think I miss something, but it looks similar to this problem

https://codesandbox.io/s/2o0w48m810?fontsize=14

```actionTest``` has not the last context

**Comment by davidkpiano** [comment]
@ClemensSahs This is working as expected. The context logged should be `test: null` which it is. What are you expecting? The `assign` change doesn't occur until after the action is executed.

**Comment by ClemensSahs** [comment]
in the function handleOnClick we have the right context on newState
the same value I expected in the actionTest. (in case the user has clicked) perhaps my expectation is wrong?

**Comment by davidkpiano** [comment]
The original issue is now explained here: https://xstate.js.org/docs/guides/context.html#action-order

In short:
1. `assign` actions are always batched and applied _first_ (i.e., raised in the microstep). This becomes a part of the next state.
2. The other actions follow, and are executed with regard to the resolved next state.

If it didn't work like that, there would be implicit "intermediate states" between each of the `assign()` calls, which is difficult to deterministically model and makes things very confusing and hard to test.

@ClemensSahs This is because React's `.setState(...)` calls are always async, so what's in React component state does not necessarily reflect the machine's state (though it does eventually!)

You can control that behavior and execute actions only after `.setState` has completed: https://xstate.js.org/docs/guides/interpretation.html#executing-actions
