### ISSUE TITLE
fetchMachine Example

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#276]
I've created a `fetchMachine` example with support for retries: https://codesandbox.io/s/82v7625nn8

I would like to add it to the examples section of docs.

**Comment by hnordt** [comment]
@davidkpiano I've also created `formMachine`: https://codesandbox.io/s/x314mk5zjo

It doesn't handle submitting, it's just lite form handling example.

![Preview](https://d.pr/i/dPI78m+)

**Comment by davidkpiano** [comment]
Similar machine featured in the visualizer: https://statecharts.github.io/xstate-viz/

I'll be making templates so that this can be updated to use `@xstate/react`, etc. if you want to resubmit! Closing for now for clean-up.

**Comment by pke** [comment]
@hnordt I like your machine! I wanted to build a machine like this myself for generic fetch handling with retries.
How would you add support for `Retry-After` server responses and have the machine retry after the server dictated timeout with the user having the ability to retry manually at any time? Manual retries should reset the retries count of course.

Similar to the `retry-after` handling the machine could also cope with `sunset` [header field](https://tools.ietf.org/html/rfc8594) and go directly to the fatal state.
