### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by ferdinandsalis** [davidkpiano/xstate#28]
Hi David,

Just watched your React Rally talk. Great talk and really liking `xstate`. I am already using it in an app of mine. Works like a charm. Also adopted the React Router like api for conditionally rendering of components from [this screencast on xstate](https://www.youtube.com/watch?v=MkdV2-U16tc). Do you have any thoughts on that? Anyway, just wanted to say thank you for this. Looking forward to see how this idea is going to evolve.

— Ferdinand

**Comment by davidkpiano** [comment]
Thanks @ferdinandsalis! I really appreciate messages like these, and am curious to see how you are using `xstate`. Version 2 is coming soon with a lot of extra features, especially to align it more closely with SCXML (the web standard for statecharts).

**Comment by MicheleBertoli** [comment]
I also want to take the opportunity to say THANK YOU VERY MUCH one more time to @davidkpiano.
Your [talk](https://www.youtube.com/watch?v=VU1NKX6Qkxc) at the React Rally was definitely one of the most inspiring talks of 2017, and I'm reading all the books/papers you recommended.
I'm so grateful for what I'm learning, and I'm super excited about statecharts and the future of `xstate`.

Also, thanks @ferdinandsalis for opening this issue - we should do this more often.
You might be interested in the [experiment](https://github.com/MicheleBertoli/react-automata) I'm working on, which is based on `xstate` (of course) and inspired by Ryan's [video](https://www.youtube.com/watch?v=MkdV2-U16tc) as well.
My goal is to get React components tested for free.

**Comment by hally9k** [comment]
I will add to this. The x-state and react-automata projects have just helped me reform what was a slightly embarrassing, fragile and hard to reason about component in our application. This component is a key stone in the critical feature set of our offering and has now been transformed into a self documenting, provably solid little gem; leading the way for some of the other complex areas of the application. Many many thanks for all the hard work guys!

**Comment by jjenzz** [comment]
I wanna add a little thanks here too. This has honestly got me really excited about dev again. I'm up stupid hours atm fiddling and learning this shizz in my spare time. I haven't felt this enthused for ages :heart:
