### ISSUE TITLE
Question: tooling for gradual statechart specification

### ISSUE THREAD

**Issue by PEZO19** [davidkpiano/xstate#287]
This project is really cool, however I think there is room for going one more abstraction level up.

Do you plan to create tools which help the user to develop (gradually specify) the state machines (/statecharts) themselves?
I am thinking about a solution where you can define some high level constraints (states, transitions, invariants) of your system, and with the exhaustive search on these existing high level constraints the user would be prompted to make further decisions about lower level constraints (states, transitions, invariants).
At the end you would be able to generate a statechart which fulfills the "requirements" (with high and low level states, transitions, invariants).
In my understanding this tool would really helpful to develop the orthogonal parts - which I think the hardest parts are to make them work together and not to forget about a single case (from the set of all cases in the cartesian product).

State machines are an old topic, I think there must be some information about that.
Do you have any idea / material on that?

**Comment by paul-f-maxson** [comment]
I use Sketch.systems to define the high level constraints, then pull the output of that into the xstate visualizer to refine the model. This isn't a foolproof workflow but it helps a lot with bootstrapping and allows a certain level of gradual development.

**Comment by PEZO19** [comment]
> Working on that as we speak (literally). It will be a visual + code platform for editing, visualizing, simulating, testing, analyzing, and sharing statecharts...

I was wondering about the some for years now, I am so glad you are pushing this project, thanks! The reason I did not start implementing my ideas is that I am not up to date with the current research and I am quite sure someone has already found it out; now I have some time to look around. 

> As far as fulfilling "requirements" (e.g., behaviors, invariants, etc.) there's a lot to be explored in this area.

I have checked the sismic link, thanks! As far I have seen its DbC implementation is based on runtime checks.
My main interest is to create a tool which helps analyzing & developing the states/transitions/invariants "compile" time. I have some ideas which could be used by this (or any other similar) project, and if I can't find anything better/similar I'll implement it soon in prolog.

If anyone has any idea on that topic I would be glad to hear about it, to me it seems like a problem of **safe async distributed programming**.

Did you hear about [P#](https://github.com/p-org/PSharp) ? At first glance it might worth to look at their approach. 

The other thing I am wondering about is creating statecharts in Idris language, because its type system and overall capabilities might be used to reason about half-baked statecharts as well.

**Comment by davidkpiano** [comment]
> ...to me it seems like a problem of safe async distributed programming.

This is why I'm also emphasizing the [Actor model](https://en.wikipedia.org/wiki/Actor_model) in XState's design and implementation.

I've heard about the related project [P](https://github.com/p-org/P) (https://github.com/p-org/P) which looks like a great DSL that's based on statecharts. I'll look into P# as well.

I'm also not sure how expressive Idris' types are to handle all statechart semantics.

**Comment by PEZO19** [comment]
@davidkpiano Are you familiar with existing [model checking tools](https://en.wikipedia.org/wiki/Model_checking) & [techniques](https://en.wikipedia.org/wiki/List_of_model_checking_tools)?
