### ISSUE TITLE
Question: XState FSMs as derived state.

### ISSUE THREAD

**Issue by phyllisstein** [davidkpiano/xstate#288]
:wave: Hey there! I hope you'll pardon me for dropping what's effectively a plea for tech support into the ole Issues here, but I'm a little perplexed about an implementation detail of integrating XState with React; and having pretty much exhausted my own ingenuity, I was hoping you might have some insight or guidance.

By way of light background, I'm building out the frontend for a content management system's editorial interface with React, Redux, and Redux Saga. I recently refactored its backend to use an FSM to manage posts' visibility lifecycle---draft/preview/published/etc.---and figured that meant I finally had an excuse to try XState in the editor. My thinking and hope was that it would be most handy for representing the set of possible next transitions to the UI components.

I threw together a super simple FSM...

```js
import { Machine } from 'xstate'

const visibilityMachine = Machine({
  id: 'postVisibility',
  initial: 'drafting',
  states: {
    drafting: {
      on: {
        PREVIEW: {
          actions: ['transitionPost'],
          target: 'previewing',
        },
        PUBLISH: {
          actions: ['transitionPost'],
          target: 'published',
        },
      },
    },
    pending: {
      on: {
        PREVIEW: {
          actions: ['transitionPost'],
          target: 'previewing',
        },
        PUBLISH: {
          actions: ['transitionPost'],
          target: 'published',
        },
      },
    },
    previewing: {
      on: {
        PUBLISH: {
          actions: ['transitionPost'],
          target: 'published',
        },
        UNPUBLISH: {
          actions: ['transitionPost'],
          target: 'drafting',
        },
      },
    },
    published: {
      on: {
        UNPUBLISH: {
          actions: ['transitionPost'],
          target: 'drafting',
        },
      },
    },
  },
})

export default visibilityMachine
```

...and, guided by the examples, started pulling it into React. I was imagining an API surface for the component that would mostly devolve on two props: `value`, which would take the value of `post.visibility` from Redux, and `onChange`, which would take a callback with a Redux action that triggered an API call and state transition on the backend.

But I quickly ran into some trouble here. XState wants very much to be the source of truth for visibility, whereas I was trying to dethrone it and treat it as derived state---it seemed as though I would need a more or less imperative way to force a change to the machine's state in case of, say, an API call failing.

I noticed that the TodoMVC example faced a not-altogether-dissimilar challenge, which it resolved by dispatching an event that trued up the FSM to the data in case of drift:

https://github.com/davidkpiano/xstate/blob/4cbb21a35ee9cc3e1f63004b34c217752d08d59b/docs/sandboxes/todomvc/Todo.jsx#L33-L42

...and while this makes sense, I'm uneasy with the fact that it would in my case fire the transition's actions, resulting in a redundant (and probably illegal) API call.

Having typed it out, I suspect that I'm overdesigning by bringing XState into the picture at all, and what this really wants is a static mapping between visibilities and transitions---which, if that's the answer, is totally fine. All the same, I'm curious whether there's a design angle I'm missing that would better accommodate XState, and whether this maybe represents a broader challenge in coordinating its view of the world with the world outside of it.

Thanks in advance for your thoughts! The code base has been a really lovely read. :sparkles:

**Comment by davidkpiano** [comment]
It's hard to tell what exactly the issue is here, but mixing Redux + Redux-Saga + XState sounds like 2 or 3 different things fighting to be the source of truth.

If you want to use XState purely as derived state, stick to `machine.transition(currentState, event)` and use it solely in reducers.

I can probably help more (and reopen this issue) if you reduce the problem to a minimal example. But the most useful pattern is:

```js
// Redux reducer
const visibilityReducer = (state = visibilityMachine.initialState, event) => {
  return visibilityMachine.transition(state, event);
}
```

That's all you should need for derived state.
