### ISSUE TITLE
Visualizer: Is it possible to pass stateChart JSON into visualizer as an argument?

### ISSUE THREAD

**Issue by famulus** [davidkpiano/xstate#293]
I would love to pass JSON into the visualizer as an argument. Is this possible?

**Comment by davidkpiano** [comment]
It will be soon! Making an updated editor right now.

**Comment by dakom** [comment]
"Fork me on XState" :D

**Comment by davidkpiano** [comment]
For now you can just copy-paste the JSON into `Machine(PasteJSONHere)`.

**Comment by davidkpiano** [comment]
Closing as this has a simple workaround.

**Comment by matthewp** [comment]
Are there plans for this? People have asked for support for JSON output in Lucy and I'd love to support it but don't want to do so until there's a JSON format that other tools use. See https://github.com/lucydsl/liblucy/issues/45

**Comment by davidkpiano** [comment]
> Are there plans for this? People have asked for support for JSON output in Lucy and I'd love to support it but don't want to do so until there's a JSON format that other tools use. See [lucydsl/liblucy#45](https://github.com/lucydsl/liblucy/issues/45)

Yes there are. The schema that will likely be used (subject to minor changes, if any) is here: https://github.com/davidkpiano/xstate/blob/main/packages/core/src/machine.schema.json
