### ISSUE TITLE
example seven-guis not work

### ISSUE THREAD

**Issue by qcgm1978** [davidkpiano/xstate#299]
## (Bug) Actual result: There's not public folder at all.
![image](https://user-images.githubusercontent.com/3024299/51083038-ce259180-174d-11e9-9f6a-a590e8205c51.png)

## (Bug) Potential fix:

index.html missing? How to generate it? Some npm command should execute firstly?

**Comment by kirkins** [comment]
Hello, I've cloned this repo after watching the talk on using state-machines with React.

I'd also like to try to example, any idea as to the problem here?

**Comment by davidkpiano** [comment]
I'm reworking the examples and we'll have these on the documentation pages.
