### ISSUE TITLE
Print-friendly docs

### ISSUE THREAD

**Issue by dakom** [davidkpiano/xstate#309]
Would it be possible to auto-generate a consolidated PDF from the docs, or have a print-friendly version that includes all the guides?

So far I've gotten bitten a couple times by being too excited and lazy to read through it all before diving in - would be good to just force myself to sit down and read it all. 

Personally, I prefer doing something like that with a hard copy.

**Comment by davidkpiano** [comment]
Related: https://github.com/vuejs/vuepress/issues/546

Also, note that you don't need to read through all the docs in order to get up and running. This should be sufficient to start: https://xstate.js.org/docs/guides/start.html

Do you have any specific projects in mind?

**Comment by dakom** [comment]
> Do you have any specific projects in mind?

Kinda sorta...

My history building UIs was many years in Flash/AIR, a few in Unity, a teensy bit in QML and other stuff, and now a couple years really focused full-on with the web.

So it's not so much a specific project, though there is one on the horizon with the dayjob, but more that the way UIs are built in the web just feels so brittle and hard to manage for larger applications. Coming into it made me feel like I was going _backwards_ 10 years.

React and related tech (Redux, FRP, etc.) combined with functional approaches (lenses, immutable, etc.) have made it _soo_ much better - I actually prefer doing the programming side in the web more than Flash/Unity now (not so much CSS) - and on the code level it makes _those_ look outdated imho (though not sure if I still remember how to code there hehe)... but it still feels like it's hard to go back into state-management code I wrote months ago and get what I was thinking at the time.

Short version - my latest approach used lenses and React Context and Typescript+enums (no Redux)... and it's not terrible, did pretty well on a biggish project, but it's not easily maintainable without being super careful to give everything types and write descriptive comments in key places.

In Flash/Unity this was managed more by the IDE. You could visually see how everything was connected and nested, and with Unity in particular you could expose dropdowns that are wired to enums and hook everything up that way. It was a jungle but an easy to navigate jungle. But on the web, what can we do?

So I'm looking at xstate more as an overall paradigm shift to be honest... yes I have a particular work job coming up that I want to be guinea pig, but on paper xstate (or statecharts in general) looks to be an extension of the move from imperative->declarative and as important a change as React etc. So I'm more excited about using it _everywhere_ for web UI's... maybe even for casual game logic and stuff like that (though tbh I'm dabbling in spare-time with Rust->wasm and looking more toward that for the more gamedev type things)

Not sure if this is really the info you were looking for, but I hope it helps!

I think a lot of ex Unity/Flash devs are going to be frustrated moving to the web, and xstate looks like an amazing tool to make that transition much more enjoyable and exciting.

**Comment by dakom** [comment]
I think that point about "in flash/unity we could visually see how everything was connected" is vastly under-estimated for web development in general.

I'm not really a fan of "visual coding" tools - but the ability to see a visual representation of the project, for discussion not just with UI designers but project managers, business interests, or even audio engineers, is a real benefit.

Otherwise so much of a project depends on translating code, designs, and everything into spoken language and then the "source of truth" is often some sprawling brief, but really it's each person's understanding of that brief, and so much gets lost in communication.

No doubt I'm preaching to the choir :)

**Comment by davidkpiano** [comment]
If you clone this repo, you can run `npm run docs:pdf` to generate a print-friendly PDF. The docs are also print-friendly now.
