### ISSUE TITLE
Registration and permalinks

### ISSUE THREAD

**Issue by dakom** [davidkpiano/xstate#312]
## Bug or feature request?
Feature

## Description:

Permalinks and an ability to fork would make it easier to share statecharts via the visualization tool

See for example codepen, jsfiddle, codesandbox, etc.

In order to provide editing features to the original author (and prevent guests from editing), an authentication/registration system would need to be built as well.

## (Feature) Potential implementation:

Would require backend services, database, etc. It's a significant effort and might not be part of the scope of `xstate` itself, especially since the visualization tool itself is open-sourced, but it would be nice as a user to have this feature available and it may help spread the word

**Comment by davidkpiano** [comment]
Done: http://xstate.js.org/viz/

**Comment by dakom** [comment]
wooohoo!
