### ISSUE TITLE
Invoking on self-transition

### ISSUE THREAD

**Issue by dakom** [davidkpiano/xstate#317]
The [docs](https://xstate.js.org/docs/guides/actions.html#actions-on-self-transitions) explain very well how self-transitions fire or do not fire `onEntry` / `onExit` depending on whether or not the self-transition is internal or external

However, it doesn't mention how this relates to invoking.

Might be helpful to clarify with a little more detail when exactly invocations are run

**Comment by davidkpiano** [comment]
Self-transitions have nothing to do with `invoke`.
