### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by dakom** [davidkpiano/xstate#324]
Ah, template is working for me again... that was weird! Anway...

## Bug or feature request?

Bug

## Description:

Tests are failing... seems like maybe there's a leaked timeout?

## (Bug) Expected result:

Test pass

## (Bug) Actual result:

Uncaught Error: Unable to send event "TIMER" to an uninitialized service (ID: light). Make sure .start() is called for this service.
Event: {"type":"TIMER"}
      at Interpreter.nextState (src/interpreter.ts:441:13)
      at Interpreter.send (src/interpreter.ts:386:28)
      at Timeout._onTimeout (src/interpreter.ts:480:14)

However, I think this is circumstantial, I don't think it's that specific test in the interpreter - rather, there's something funky happening at a higher level

## (Bug) Potential fix:

~~Not sure yet, I'll see if I can shake something out of the trees :)~~

Interpreter tests need SimulatedClock whenever they are started.

**Comment by dakom** [comment]
PR: https://github.com/davidkpiano/xstate/pull/325

**Comment by davidkpiano** [comment]
Great catch, thank you!
