### ISSUE TITLE
It shouldn't be this difficult - so a bug, enhancement, or documentation

### ISSUE THREAD

**Issue by SimonShapiro** [davidkpiano/xstate#333]
## Bug or feature request?

I am trying to send some of the context of a parent machine into a child.

```        ready: {
            invoke: {
                src: "fetcherMachine",
                id: "fetcher"
            },
            onEntry: xs.actions.send({type: "FETCH", resource: ???}, {to: "fetcher"},),
```

## Description:

In the above snippet, I am trying to replace the `???` with `context.resource`, which has been assigned in a previous step of the parent machine.  I have tried many variants - just guessing really because the documentation doesn't cover this.

## (Bug) Potential fix:

One would think that we could rely on some way of getting hold of the context object while in a machine rather than from outside of it only.

**Comment by SimonShapiro** [comment]
So it was a lack of detail in the documentation.  I solved it with a function that returns an event as follows:

`            onEntry: xs.actions.send((ctx, event) => {return {type: "FETCH", resource: ctx.resource}}, {to: "fetcher"},),
`

**Comment by davidkpiano** [comment]
There's literally an entire example for this 😉 

https://xstate.js.org/docs/guides/actions.html#built-in-actions

```js
import { actions } from 'xstate';
const { send } = actions;

// contrived example - reads from the `ctx` and sends
// the dynamically created event
const sendName = send((ctx, event) => ({
  type: 'NAME',
  name: ctx.user.name
}));

const machine = Machine({
  // ...
  on: {
    TOGGLE: {
      actions: sendName
    }
  }
  //...
});
```

Not sure where you're seeing the "lack of detail".

**Comment by SimonShapiro** [comment]
My apologies I was looking in wrong section.
