### ISSUE TITLE
Unexpected Event type inferred w/ TransitionConfig

### ISSUE THREAD

**Issue by leeyeh** [davidkpiano/xstate#338]
## Bug or feature request?

Bug

## Description:

The Event inference feature introduced in v4.3.0 is excellent. However when given a union event type, the Machine are not narrowing the event type down correctly for a TransitionConfig.

Consider a machine:

```ts
import { Machine } from "xstate";

type Event =
  | {
      type: "START";
      payload: string;
    }
  | {
      type: "END";
      payload: void;
    };

const machine = Machine<any, any, Event>({
  id: "game",
  initial: "waiting",
  states: {
    waiting: {
      on: {
        START: {
          target: "started",
          cond: (_, event) => event.payload === ""
        }
      }
    },
    started: {}
  }
});
```

## (Bug) Expected result:

The event param of `states.waiting.on.START.cond` is inferred as 

```ts
{
      type: "START";
      payload: string;
}
```

## (Bug) Actual result:

```ts
{
      type: "START";
      payload: string;
} | EventObject
```

## (Bug) Potential fix:

I'm not very familiar with the internal types of xstate, but I guess this is the result of this union type filter: https://github.com/davidkpiano/xstate/blob/0041c94f36d4ebff2e8f715eff8feb756d0ecb67/src/types.ts#L265

**Comment by timdeschryver** [comment]
I think this should work?

```ts
Extract<TEvent, { type: K }>
```

With my small example POCs, it's inferring correctly but I don't have a large/complex enough setup to be 100% sure 😅 .
