### ISSUE TITLE
accessing .changed getter throws error

### ISSUE THREAD

**Issue by geddski** [davidkpiano/xstate#340]
## .changed bug

```
this.interpreter.onTransition(async (stateNode, event) => {
  if (stateNode.changed === false){
    return;
  }
})
```

## Description:
Sometimes accessing the `.changed` getter throws this error:

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at keys (utils.js:45)
    at stateValuesEqual (State.js:36)
    at State.js:38
    at Array.every (<anonymous>)
    at stateValuesEqual (State.js:37)
    at State.get [as changed] (State.js:205)
```

## (Bug) Potential fix:
I wrapped my use of `.changed` in a try/catch. I supposed that could potentially work in the getter itself. Getters shouldn't throw IMO.

**Comment by davidkpiano** [comment]
Do you have a reproducible example?

**Comment by geddski** [comment]
I'll try to reproduce one apart from my game

**Comment by davidkpiano** [comment]
Any updates on this (reproduction)?

**Comment by davidkpiano** [comment]
This should no longer happen, as `.changed` is now a static pre-calculated property (no longer a getter) 😄

**Comment by geddski** [comment]
awesome thx!
