### ISSUE TITLE
TodoMVC Example Questions

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#345]
In `todosMachine.js` we have:

```js
states: {
    all: {},
    active: {},
    completed: {}
},
// ...
on: {
    // ...
    "SHOW.all": ".all",
    "SHOW.active": ".active",
    "SHOW.completed": ".completed",
    // ...
}
```

There is any specific reason they need to be internal transitions? They could be external transitions and it would work just fine. Am I missing something?

Same for `todoMachine.js`:

```js
  // ...
  on: {
    TOGGLE_COMPLETE: {
      target: ".reading.completed",
      actions: [assign({ completed: true }), "notifyChanged"]
    },
  },
  // ...
  states: {
    reading: {
      states: {
        completed: {
          on: {
            TOGGLE_COMPLETE: {
              target: "pending",
              actions: [assign({ completed: false }), "notifyChanged"]
            }
          }
        }
      },
  // ...
```

There is any specific reason that the transition to `reading.completed` needs to be internal? 

@davidkpiano I'm not asking that you change the TodoMVC example, I'm just trying to make sure I understand the purpose of internal transitions.

Thank you.

**Comment by davidkpiano** [comment]
Don't think of these as internal or external - it doesn't matter in this case.

For more information on the behavior of internal/external transitions when transitioning from a parent state node to its descendant state node, see ['Type' and Transitions (SCXML)](https://www.w3.org/TR/scxml/#N101D7).

Note: in SCXML, `type="internal"` refers to `internal: true` in XState.

**Comment by davidkpiano** [comment]
In other words, `"SHOW.active": ".active",` is just shorthand for the descendant state, instead of having to specify the full relative path.
