### ISSUE TITLE
Root transitions are not working properly

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#346]
Consider the following snippet:

```js
const wordMachine = Machine({
  id: 'direction',
  initial: 'left',
  states: {
    left: {},
    right: {},
    center: {},
    justify: {}
  },
  on: {
    LEFT_CLICK: 'left',
    RIGHT_CLICK: 'right',
    CENTER_CLICK: 'center',
    JUSTIFY_CLICK: 'justify'
  }
});
```

If you copy and paste it in the Visualizer (https://statecharts.github.io/xstate-viz/) you'll see that you can transition to `right` by clicking on `RIGHT_CLICK` event.

It shouldn't happen. `left` means "travel to my sibling left state", `direction` has no siblings.

The expected result would be a warning: `Target 'left' not found on 'direction'` (or something like that).

**Comment by Andarist** [comment]
This is explicitly allowed [here](https://github.com/davidkpiano/xstate/blob/0bd24b23f39a3971a2f879f918c032e5ff1c1285/src/StateNode.ts#L1960) so I'm wondering if it's indeed a bug or just a documentation issue?

**Comment by hnordt** [comment]
I think it's a bug. `left` means a transition to a sibling, not to a child.

**Comment by hnordt** [comment]
If you add a parent `foo` state, the machine will be interpreted correctly:

```
const wordMachine = Machine({
  id: 'direction',
  initial: "foo",
  states: {
    foo: {
      initial: 'left',
      states: {
        left: {},
        right: {},
        center: {},
        justify: {}
      },
      on: {
        LEFT_CLICK: 'left',
        RIGHT_CLICK: 'right',
        CENTER_CLICK: 'center',
        JUSTIFY_CLICK: 'justify'
      }
    }
  }
});
```

It won't allow you to transition from `left` to `right` on `RIGHT_CLICK` because there's no `right` sibling.

**Comment by Andarist** [comment]
That would mean that in example those machines are wrongly configured:
https://github.com/davidkpiano/xstate/blob/0bd24b23f39a3971a2f879f918c032e5ff1c1285/test/actions.test.ts#L620
https://github.com/davidkpiano/xstate/blob/0bd24b23f39a3971a2f879f918c032e5ff1c1285/test/deep.test.ts#L5

**Comment by hnordt** [comment]
Yes, I believe they are wrong.

Waiting @davidkpiano thoughts on it.

For me transitions without a dot always mean a transition to a sibling state, and it should not resolve to a child state in any case. 

If sibling transitions behave some way for the root state and then another way for children states, it's gonna be confusing.

**Comment by davidkpiano** [comment]
Yeah, they're wrong. Will fix.

**Comment by abhi18av** [comment]
Guys, does this issue still stand or perhaps it could be closed after the https://github.com/davidkpiano/xstate/pull/550 ?

**Comment by Andarist** [comment]
@abhi18av the issue still stands. It indeed got fixed in #550 but we couldn't merge it in, because it is a breaking change and we need to wait for the next major version for this to be fixed.

**Comment by abhi18av** [comment]
Cool 👍 

I'm trying to understand the standing issues and PRs - apologies for notifications 😅

**Comment by Andarist** [comment]
No problem, thanks for looking into them!
