### ISSUE TITLE
Update transition docs

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#347]
By reading the current docs you can't understand the difference between a self-transition, internal transition and "child transition" (I came with that name, not sure it's a good name).

Even statecharts.github.io made a mistake. In https://statecharts.github.io/glossary/local-transition.html#xstate they say:

> In XState, an internal transition is described by prefixing the target state with a dot.

So by reading that article you can think of `on: { RESET: '.A'  }` as being the same as `on: { RESET: { target: 'A', internal: true } }`. The dot prefix represents a "child transition" which happens to be an internal transition as well.

I would like to propose a couple changes to the docs:

1. Update `guides/transitions.md`
2. Remove `guides/internal.md`

# Self-transition

A self-transition is when a state transitions to itself. Self-transitions can either be internal or external, in which it may exit and then reenter itself.

Self-transitions are indicated by leaving the `target` as `undefined` or by explicitly setting the `target` to the self-transition's state node itself.

If you leave the `target` as `undefined` the self-transition will be internal. To be explicit, you can indicate the self-transition as internal with `{ internal: true }`. Setting `{ internal: false }` has no effect if you leave the `target` as `undefined`.

External self-transitions are indicated by setting the `target` to the self-transition's state node itself. To be explicit, you can indicate the self-transition as external with `{ internal: false }`. If you both define `target` and set `internal` to `true` the self-transition will be internal.

```js
const counterMachine = Machine({
  id: 'counter',
  initial: 'counting',
  states: {
    counting: {
      onEntry: 'enterCounting',
      onExit: 'exitCounting',
      on: {
        // self-transitions
        INC_BY_ONE: { actions: 'incrementByOne' }, // internal, implicit
        INC_BY_TWO: { actions: 'incrementByTwo', internal: true }, // internal, explicit
        DEC_BY_ONE: { target: 'counting', actions: 'decrementByOne' }, // external, implicit
        DEC_BY_TWO: { target: 'counting', actions: 'decrementByTwo', internal: false } // external, explicit
      }
    }
  }
});
```

# Internal Transition

An internal transition will not exit and reenter itself, so the state node's onEntry and onExit actions will not be executed again.

Internal transitions are indicated with `{ internal: true }`.

Please note that self-transitions will be internal by default if you define them by leaving the `target` as `undefined`.

# External Transition

An external transition will exit and reenter itself, so the state node's onEntry and onExit actions will be executed again.

All transitions are external by default. To be explicit, you can indicate them with `{ internal: false }`.

# Child Transitions

A child transition is when the state machine exit the current child state, handle the event from the parent state and internally transition to another child state. A child transition is also an internal transition, so parent state node's onEntry and onExit actions will not be executed again.

Child transitions are indicated with a dot prefix.

```js
const wordMachine = Machine({
  id: 'direction',
  initial: 'left',
  states: {
    left: {},
    right: {},
    center: {},
    justify: {}
  },
  on: {
    // child transitions
    LEFT_CLICK: '.left',
    RIGHT_CLICK: '.right',
    CENTER_CLICK: '.center',
    JUSTIFY_CLICK: '.justify'
  }
});
```

In the above example, `LEFT_CLICK: '.left'` translates to:
> Transition from currentState.currentChildState to currentState.newChildState:left

`LEFT_CLICK: 'left'` (without dot prefix) would translate to:

> Transition from currentState to siblingState:left

---

I would like to make a PR if you agree.

Closes #344.

**Comment by davidkpiano** [comment]
Transition docs updated: https://xstate.js.org/docs/guides/transitions.html
