### ISSUE TITLE
onExit Order

### ISSUE THREAD

**Issue by dodekeract** [davidkpiano/xstate#35]
Right now, `onExit` behaves slightly odd. If you have multiple nested states with `onExit` hooks, the first item in `exit` is the outermost state. I'd expect `xstate` to leave the innermost state first.

```javascript
const currentExit = ['OUTER_EXIT', 'INNER_EXIT']
const expectedExit = ['INNER_EXIT', 'OUTER_EXIT']
```

**Comment by davidkpiano** [comment]
Thanks for pointing that out! I'll have a fix soon.
