### ISSUE TITLE
State's event property is not working anymore

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#355]
Version: 4.3.1

```js
const lightMachine = Machine({
  id: 'light',
  initial: 'green',
  states: {
    green: {
      on: {
        TIMER: 'yellow'
      }
    },
    yellow: {
      on: {
        TIMER: 'red'
      }
    },
    red: {
      on: {
        TIMER: 'green'
      }
    }
  }
});


console.log(lightMachine.transition('green', 'TIMER').event) // undefined
```

By the way, we have also the `events`. What's used for?

**Comment by davidkpiano** [comment]
I cannot replicate this on version 4.3.1.

Don't worry about `events` - that's internal:

> Internal event queue. Should be empty with run-to-completion semantics.

It's a way for XState to keep track of raised events and properly execute the transitions until there are no more raised events in the internal event queue.

**Comment by hnordt** [comment]
@davidkpiano oh, I'm sorry. It's working.

I've used the [XState Visualizer](https://statecharts.github.io/xstate-viz/) to test. Possibly it's using an old version o XState.
