### ISSUE TITLE
Proposal for "selectors"

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#361]
I really love that I can hide the implementation details of my statecharts:

```js
{
  myState: {
    invoke: {
      src: "myService",
      onDone: {
        target: "nextState",
        actions: "doSomething"
      }
    }
  }
}
```

The diagram looks pretty awesome:

![Preview](https://d.pr/i/sLCmzX+)

I would like to propose a similar API for the `data` props:

```js
{
  myState: {
    invoke: {
      src: "myService",
      data: "getMyServiceContext", // data selector (or getter)
      onDone: "nextState"
    }
  },
  nextState: {
    type: "final",
    data: "getUser" // data selector (or getter)
  }
},
// ... machine options
{
  actions: ...,
  services: ...,
  selectors: {
    getMyServiceContext: context => ({ foo: bar }),
    getUser: context => ({ user: context.user }
  }
}
```

In the future, the Visualizer can also show the `data` getters description.

**Comment by davidkpiano** [comment]
Since this can be done in user-land and is not part of the SCXML spec, I think it makes sense to not include it in XState core.

The preferred pattern, by the way, will be equivalent and a bit more idiomatic: using named functions:

```js
const getUser = context => ({ user: context.user });

// ...
{
  nextState: {
    type: 'final',
    data: getUser
  }
}
```
