### ISSUE TITLE
Document interpreter options and include a warning in devTools option

### ISSUE THREAD

**Issue by carloslfu** [davidkpiano/xstate#372]
It would be helpful to document all the interpreter options. Also, I think it would be useful to add a note or warning to [devTools option](https://github.com/davidkpiano/xstate/blob/master/src/interpreter.ts#L68): "using Redux DevTools with large contexts might slow down your app". Yesterday, I figured out that because of the introspection or cloning that the extension does, my app was so slow on development (890ms - 400ms per update).

**Comment by davidkpiano** [comment]
Options documented: https://xstate.js.org/docs/guides/interpretation.html#options

Also, `devTools: false` is now the default. Use with caution!
