### ISSUE TITLE
How to use XState with TypeScript in service consumer?

### ISSUE THREAD

**Issue by christophercliff** [davidkpiano/xstate#377]
## Bug or feature request?

Question

## Description:

In a service consumer, e.g. a React component, there will be code to check current state and send events. For example:

```tsx
if (currentState.matches('myState')) {
    return <Button onClick={() => service.send({ type: 'myEvent' })} />
}
```

Is there anything in the XState API or general TypeScript patterns to ensure these types are in sync? For example, how could the above code be written so that it will not compile if `myState` or `myEvent` is removed from the machine definition, or if `myEvent` isn't valid for `myState`?

**Comment by henrikra** [comment]
I think you missed this: https://xstate.js.org/docs/guides/typescript.html#using-typescript
There is is saying how to type your events etc

**Comment by davidkpiano** [comment]
> how could the above code be written so that it will not compile if myState or myEvent is removed from the machine definition, or if myEvent isn't valid for myState?

This isn't possible with TypeScript, since TypeScript cannot match on partial strings.
