### ISSUE TITLE
Initial states aren't executed 

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#38]
If you have a statechart that defines an initial state, then when a machine "starts" it _enters_ the state.  This means that the _effects_ of that initial state should be able to get a hold of.

For a normal state transition, you pass in the current state, and an event, and you get back (among other things) the new state, and the side effects of any exits and entrys that happen.

However, when you are starting out, you haven't even entered that initial state.  There should be a way to get to that initial state, and any side effects.  Passing in 'undefined' as the current state might be a way, since there is no event, and no initial state. So perhaps `transition()` with no args should return that initial State instance.

**Comment by davidkpiano** [comment]
Since 3.0 is still in beta, I can probably have:

```js
myMachine.initialState;
// State { ... }
```

return a `State` rather than a `StateValue` (current behavior).

**Comment by mogsie** [comment]
That looks nice. It would include the necessary _effects_ of entering any initial states, right?

**Comment by davidkpiano** [comment]
Yep! I can close this; initial states from .initialState now return a State with all the appropriate onEntry actions.
