### ISSUE TITLE
Document how to access meta information for a given state

### ISSUE THREAD

**Issue by sbussard** [davidkpiano/xstate#380]
Inside of the state machine, meta information is defined like 
```js
{
  //...
  meta: {
    something: 'some value'
  }
}
```

but when you get state from an `interpreter` you get a different structure like

```js
{
  //...
  meta: {
    '(machineid).someState': {
      something: 'some value'
    }
  }
}
```

There are a lot of assumptions one could make about how to get the meta information, but there's no documentation about how to properly do so.

**Comment by davidkpiano** [comment]
This is done and will be published in the docs for 4.4.

**Comment by sbussard** [comment]
Amazing! Thank you!

**Comment by davidkpiano** [comment]
Here are the docs if you're curious/impatient:

-----

Meta data, which is static data that describes relevant properties of any [state node](./statenodes.md), can be specified on the `.meta` property of the state node:

```js
const fetchMachine = Machine({
  id: 'fetch',
  initial: 'idle',
  states: {
    idle: {
      on: { FETCH: 'loading' }
    },
    loading: {
      after: {
        3000: 'failure.timeout'
      },
      on: {
        RESOLVE: 'success',
        REJECT: 'failure',
        TIMEOUT: 'failure.timeout' // manual timeout
      },
      meta: {
        message: 'Loading...'
      }
    },
    success: {
      meta: {
        message: 'The request succeeded!'
      }
    },
    failure: {
      initial: 'rejection',
      states: {
        rejection: {
          meta: {
            message: 'The request failed.'
          }
        },
        timeout: {
          meta: {
            message: 'The request timed out.'
          }
        }
      },
      meta: {
        alert: 'Uh oh.'
      }
    }
  }
});
```

The current state of the machine collects the `.meta` data of all of the state nodes represented by the state value, and places them on an object where:

- The keys are the state node IDs
- The values are the state node `.meta` values

For instance, if the above machine is in the `failure.timeout` state (which is represented by two state nodes with IDs `"failure"` and `"failure.timeout"`), the `.meta` property will combine all `.meta` values and look like this:

```js
const failureTimeoutState = fetchMachine.transition('loading', 'TIMEOUT');

console.log(failureTimeoutState.meta);
// => {
//   failure: {
//     alert: 'Uh oh.'
//   },
//   'failure.timeout': {
//     message: 'The request timed out.'
//   }
// }
```

It's up to you for what you want to do with this meta data. Ideally, it should contain JSON-serializable values _only_. You might want to merge/aggregate the meta data differently; for instance, this function discards the state node ID keys (if they are irrelevant) and merges the meta data:

```js
function mergeMeta(meta) {
  return Object.keys(meta).reduce((acc, key) => {
    const value = meta[key];

    // Assuming each meta value is an object
    Object.assign(acc, value);

    return acc;
  }, {});
}

const failureTimeoutState = fetchMachine.transition('loading', 'TIMEOUT');

console.log(mergeMeta(meta));
// => {
//   alert: 'Uh oh.',
//   message: 'The request timed out.'
// }
```

**Comment by tanz645** [comment]
Is there any way we can update the meta information like 
```javascript
onDone:{
   target: 'next_state',
   actions: (ctx,evt) => 'some action',
   meta: assign({
     someKey: 'some value'
  })
}
```

**Comment by davidkpiano** [comment]
@tanz645 No, that's not what `meta` is for.

**Comment by tanz645** [comment]
Alright, thanks for the reply.

**Comment by jaetask** [comment]
Hi @davidkpiano , I see that meta was not supposed to be used like this but that was over a year ago. Is there any other mechanism for passing values to a state when a condition is met?

```
{ 
  target: 'error', 
  cond: (context, event) => event.name === undefined, 
  meta: { message: 'Must set a name' } 
},
```

**Comment by davidkpiano** [comment]
@jaetask You can use `assign()` for this.
