### ISSUE TITLE
Event label not displayed after migrating to v4?

### ISSUE THREAD

**Issue by coodoo** [davidkpiano/xstate#381]
## Bug or feature request?
Possibly a bug.

## Description:

`Event` label not displayed in chart?

## (Bug) Expected result:
![rqqmkjh](https://user-images.githubusercontent.com/325936/53620817-4c22f680-3c2f-11e9-8b29-d6e94e1d7324.png)

## (Bug) Actual result:
`Timer` is not displayed in chart

## (Bug) Potential fix:

Downgrade to `v3` has this fixed, maybe this is something configurable for `v4` somewhere but not documented?

**Comment by davidkpiano** [comment]
Is this for the old visualizer?

**Comment by coodoo** [comment]
Yep, the screencap was from `v3`,  but thought it would be great for `v4` to display the label too.

**Comment by davidkpiano** [comment]
The new visualizer displays events inline with the state. The design may change in the future, though, but this is currently working as intended.

**Comment by coodoo** [comment]
Wondering how does one display both `CLOSE` and `ESC` events on one state in `v4`? I tried the online editor but the second event will overlap the first one, hence not displaying two events at once.

Ps. The screencap below is from `v3`, as seen in the documentation.

<img width="771" alt="screen shot 2019-03-03 at 12 46 46 pm" src="https://user-images.githubusercontent.com/325936/53691117-823cb380-3db2-11e9-9fe5-c5c2c63a2ac9.png">
