### ISSUE TITLE
How to maintain the state across hot reload 

### ISSUE THREAD

**Issue by aislanmaia** [davidkpiano/xstate#382]
I'm using `create-react-app` and trying this `xstate` with `use-machine` hook and pretending to choose this combo for my next project. But developing with the state getting lost after each changing in the code is a pain, because my state get reseted all the time to the initial state. 

I ask if its possible to get the state working with hot reloads.

Thanks in advance.

**Comment by davidkpiano** [comment]
I'm not sure how hot reloading with `create-react-app` works but for rehydrating state, you can use a strategy here: https://xstate.js.org/docs/guides/states.html#persisting-state

**Comment by aislanmaia** [comment]
Okay, I have reached one solution. In this [gist](https://gist.github.com/aislanmaia/8b716b3411fa5b1b3195b199b7e9a73f#file-index-js) I just inject the App component root again when module hot-reloads.
