### ISSUE TITLE
Documentation for usage of React and sub components.

### ISSUE THREAD

**Issue by aislanmaia** [davidkpiano/xstate#389]
I've tried to use `xstate` (with use-machine hook, React Context, or just the default package [xstate]) and I always fall with problems like `unintialized machine` or unnecessary rerenders. 

Should be great a demo use and recommendations beyond usage with just a simple React root component.
The hot-reload seems to be a problem too.

**Comment by davidkpiano** [comment]
This is already documented: https://xstate.js.org/docs/recipes/react.html

Please post your problematic code so I can see what needs to be clarified. XState on its own does not cause unnecessary renders.
