### ISSUE TITLE
save state after each transition

### ISSUE THREAD

**Issue by belevtsev** [davidkpiano/xstate#390]
I want to save state after each transition.
async function saving state to DB. After successful save operation  just want to proceed to the next state.

```
interpret(machine)
  .onTransition(async...)
  .start();
```

**Comment by belevtsev** [comment]
I guess I can go with:
```
const service = interpret(machine, { execute: false });
service
        .onTransition(ctx => setTimeout(() => service.execute(ctx), 3000))
```

so `execute: false` seems do the trick

**Comment by davidkpiano** [comment]
Check out the strategies here: https://xstate.js.org/docs/guides/states.html#persisting-state

Also, just a nit: that'd be `.onTransition(state => ...)` because it's the entire `State`, not just the context.

**Comment by belevtsev** [comment]
Thanks. This will work for me. Already implemented, but with node.js
