### ISSUE TITLE
Async onEntry / onExit

### ISSUE THREAD

**Issue by pierreericgarcia** [davidkpiano/xstate#395]
## Bug

Hey 👋 I've been working with your library for 2 weeks and it's amazing ! However I encountered a problem when trying to use an async function on the `onEntry` hook of a `State`. 

## Description:

The problem is that it looks like the Machine doesn't await for the Promise to resolve.

## (Bug) Expected result:

The expected result would be that a state await his onEntry hook before jumping to the next one.

## (Bug) Actual result:

The machine jump to the next state without awaiting the onEntry function.

Hope it's clear ! Thank you very much for your help 🤞

**Comment by davidkpiano** [comment]
All actions (`onEntry`, `onExit`, `actions` in transitions) are "fire-and-forget" actions, which means they're executed and the machine shouldn't care what results from those actions: https://xstate.js.org/docs/guides/effects.html

If you want to do a sequence of dependent, async actions, that sounds like it would be better expressed as a single action:

```js
// State node config
onEntry: 'doSequence',

// ...

// Machine options
actions: {
  doSequence: async (ctx) => {
    await doFooThing(ctx);
    await doBarThing(ctx);
  }
}
```

If you actually wanted the result of those actions, that would be better placed in `invoke`:

```js
invoke: {
  src: 'fooBarSequence',
  onDone: // ...
},

// ...

// Machine options
{
  services: {
    fooBarSequence: (ctx) => async () => {
      const result1 = await foo(ctx);
      const result2 = await bar(result1);
      return result;
    }
  }
}
```

Hope that helps!
