### ISSUE TITLE
Interpreter start(state) throws exception in execute(state) when the starting state has no actions

### ISSUE THREAD

**Issue by Zenwolf** [davidkpiano/xstate#399]
## Bug or feature request?
Bug

## Description:
When calling `interpreter.start(machine.states.myState)` where `myState` has no actions property, `execute(state)` throws exception:

```text
TypeError: Cannot read property 'forEach' of undefined
    at Interpreter.push../node_modules/xstate/lib/interpreter.js.Interpreter.execute
```

Please note that `myState` is a sub-state of a hierarchical state.

I have a few questions regarding this:

1. Is it incorrect to pass in the `machine.states.myState` as the initial value for `interpreter.start`?
2. I noticed that the original `machine.states.myState.config` has an empty array `actions: []` even though I did not add any actions. However, the corresponding `machine.states.myState` object doesn't have an actions property at all.

## (Bug) Expected result:
When there are no actions on a state, it should _not_ attempt to execute any actions.

## (Bug) Actual result:
Interpreter `execute(state)` tries to iterate over non-existing actions array.

## (Bug) Potential fix:

There are two possible reasons that I can think of why this might be happening:

1. The `machine.states.myState` object is supposed to have an `actions: []` when the state never defined actions, and this step got missed somehow (note how the config for the state does have an empty actions array).
2. Or maybe the `machine.states.myState` is not supposed to have an actions property when there are no actions, and the `execute(state)` code is supposed to have a guard against calling `forEach` on a non-existent array.

**Repro steps:**

1. In Chrome, go to: https://codepen.io/anon/pen/BbvMZz.
2. After that pen loads, open the Chrome dev tools console to see the following error: `Uncaught TypeError: Cannot read property 'forEach' of undefined`

**Comment by davidkpiano** [comment]
I can't read your example in Chrome. `machine.states.*` is a `StateNode` instance, not a `State`. A `StateNode` is part of what ultimately determines the `State`. 

I think what you might be trying to do is start the machine at a specific state, such as `'foo'` or `{ bar: 'baz' }`. If so, just pass that into `.start(...)`:

```js
// Start at a specific state value
interpreter.start({ bar: 'baz' }); 
```

TypeScript would help a lot here, and show you that it is invalid to pass a `StateNode` into `.start(...)` (the docs also tell you this by specifying it must be a `State`: https://xstate.js.org/docs/guides/interpretation.html#starting-and-stopping)

**Comment by Zenwolf** [comment]
Thank you for the reply. Upon your suggestion, I looked at the TypeScript definition for `StateValue`, which is what is accepted by interpreter.start:

```TypeScript
/**
 * The string or object representing the state value relative to the parent state node.
 *
 * - For a child atomic state node, this is a string, e.g., `"pending"`.
 * - For complex state nodes, this is an object, e.g., `{ success: "someChildState" }`.
 */
export type StateValue = string | StateValueMap;
```

Given the example state Machine below, I tried both a string and a `{foo: 'bar'}` style object and got the same error I reported above with both. After reading the docs and looking at the typescript, I am still unsure how to get the interpreter to start is a non-default state:

```JavaScript
window.machine = XState.Machine({
  "key": "testmachine",
  "initial": "initializing",
  "states": {
    "initializing": {
      "on": {
        "ready": "paused"
      }
    },
    "playing": {
      "initial": "active",
      "states": {
        "active": {
          "on": {
            "inactivity": "inactive"
          }
        },
        "inactive": {
          "on": {
            "interaction": "active",
            "longwait": "passive"
          }
        },
        "passive": {
          "on": {
            "interaction": "active"
          }
        }
      },
      "on": {
        "close": "closed",
        "end": "ended",
        "error": "error",
        "pause": "paused"
      }
    },
    "paused": {
      "initial": "waiting",
      "states": {
        "waiting": {
          "on": {
            "inactivity": "inactive"
          }
        },
        "inactive": {
          "on": {
            "interaction": "waiting",
            "longpause": "idle"
          }
        },
        "idle": {
          "on": {
            "interaction": "waiting"
          }
        }
      },
      "on": {
        "close": "closed",
        "error": "error",
        "play": "playing",
        "timeout": "timedout"
      }
    },
    "ended": {
      "on": {
        "close": "closed",
        "play": "playing"
      }
    },
    "closed": {},
    "timedout": {},
    "error": {}
  }
});

const service = XStateInterpreter.interpret(machine);
```
I then tried to start the interpreter like this:

```JavaScript
service.start({ paused: 'waiting' });
// Also tried:
// service.start('paused');
// service.start('waiting');
```

Each time I got the following error:

```
Uncaught TypeError: Cannot read property 'forEach' of undefined
```

Do you have any documented code examples, or unit tests, that start the interpreter in a non-default state that I could take a look at to make sure I am not messing it up somehow?

I have really enjoyed using xstate, and am excited about replacing custom code with the new interpreter, but I can't seem to get it up and running yet.

Thank you!

**Comment by davidkpiano** [comment]
Try it on the `master` branch. Currently, you'd have to restore the state in version 4.3.3:

```js
service.start(State.from({ paused: 'waiting' }));
```
