### ISSUE TITLE
Vizualizer with functionality to generate xstate json

### ISSUE THREAD

**Issue by pwnreza** [davidkpiano/xstate#401]
As i read in a different issue there is a open source vizualizer (xstate-viz) for xstate machines.
https://github.com/davidkpiano/xstate/issues/306

My Question:
Is there a functionality in this vizualizer or another, to not only visualize (import) the xstate machine but also to edit inside the vizualizer and generate a new xstate json (export).

**Comment by davidkpiano** [comment]
It's a work in progress! It will be a separate package.

**Comment by pwnreza** [comment]
thanks for your quick answer dadash

**Comment by pwnreza** [comment]
Can you give an estimate when to expect the sperate package?
