### ISSUE TITLE
Is this a shortcut syntax for defining target state?

### ISSUE THREAD

**Issue by coodoo** [davidkpiano/xstate#406]
Just wondering is the [following code](https://github.com/davidkpiano/xstate/blob/master/docs/sandboxes/todomvc/todosMachine.js#L56-L58) from the `TodoMVC` is a shortcut for defining target state?

I had flipped through the doc a couple of times but didn't find where it mentioned what the `.` and the minimal syntax meant, hence the question.

```js
'SHOW.all': '.all',
'SHOW.active': '.active',
'SHOW.completed': '.completed',
```

**Comment by davidkpiano** [comment]
Added to docs, here's a preview:

-----

Child state nodes can be targeted relative to their parent by specifying a dot (`'.'`) followed by their key:

```js
const optionsMachine = Machine({
  id: 'options',
  initial: 'first',
  states: {
    first: {},
    second: {},
    third: {}
  },
  on: {
    SELECT_FIRST: '.first', // resolves to 'options.first'
    SELECT_SECOND: '.second', // 'options.second'
    SELECT_THIRD: '.third' // 'options.third'
  }
});
```

By default, relative targets are internal transitions.
