### ISSUE TITLE
[Feature] Shorthand for sending events to interpreter

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/xstate#408]
## Bug or feature request?
Feature

## Description:
This is purely an aesthetic, non-breaking change. The `service.send(...)` method can optionally take two arguments:

- Event type
- Payload object

Which looks like this:

```js
service.send('EVENT', { foo: 'bar' });

// equivalent to...
service.send({ type: 'EVENT', foo: 'bar' });
```

The payload argument must be an object (or undefined) and will be merged with the first argument, resolved to `{ type: eventType }`. 

This means that...

```js
service.send(
  { type: 'EVENT', meta: 'something', foo: 'original' },
  { foo: 'bar' });
```

would resolve to...
```js
service.send({
  type: 'EVENT',
  meta: 'something',
  foo: 'bar' // overwrites { foo: 'original' }
});
```

unless we should disallow that usage.

Prior art: [Vuex dispatching actions](https://vuex.vuejs.org/guide/actions.html#dispatching-actions)

**Comment by tivac** [comment]
I'm a :+1: on this proposal in general, though I think the 

```js
service.send(
  { type: 'EVENT', meta: 'something', foo: 'original' },
  { foo: 'bar' }
);
```

format is surprising and IMO kinda strange. I don't mind if it exists but I think it'd be weird to document it.

**Comment by davidkpiano** [comment]
Right, just thinking through the possibilities, given the args can be:

1. `string | object`
2. `undefined | object`

Gives us four possibilities:

1. `string` (resolves to `{ type: string }`)
2. `string, object` (resolves to `{ type: string, ...object }`)
3. `object` (resolves to itself)
4. `object, object` (resolves to `{ ...object, ...object }`)

The fourth one is the weird-looking one.

**Comment by tivac** [comment]
Were I building this I'd be sorely tempted to explicitly prevent 4 from working, because it's so strange-seeming.

Maybe there's a valid use-case for that though I dunno.
