### ISSUE TITLE
[feature] SCXML import?

### ISSUE THREAD

**Issue by aksonov** [davidkpiano/xstate#411]
Could I pass SCXML file to xstate?

**Comment by davidkpiano** [comment]
In the future, you will be able to. It will likely be in an `@xstate/scxml` package.

**Comment by aksonov** [comment]
@davidkpiano Thank you for your work. I started something similar three years ago (SCXML-based): https://github.com/aksonov/statem but didn't found any community interest...

I'm maintaining RNRF component (https://github.com/aksonov/react-native-router-flux) and want to integrate it with xstate to make app navigation independent from UI layer.

One issue I was not able to solve three years ago - how to support stacks with SCXML (typical push/pop operations)? Looks like it is not supported there...

**Comment by davidkpiano** [comment]
Do you mean simulating pushdown automata or simply maintaining a stack?

You can use a combination of `context`, `assign(...)`, and `cond: ...` (`<data>`, `<assign>`, and `<transition cond="...">` to simulate it, I believe.

**Comment by aksonov** [comment]
> You can use a combination of context, assign(...), and cond: ... (<data>, <assign>, and <transition cond="..."> to simulate it, I believe.

@davvidbaker Could you clarify? I want to use state machine for app navigation. For example, from Home account, user may go to own User Profile and to Friends List. From Friends List user may go to other's User Profile pages. The question how to implement 'pop' operation for User Profile, that should go to previous state from the stack (Home OR Friends List)

**Comment by aksonov** [comment]
More interesting situation will be if User Profile also contains "Friends List" tab. Then we could have indefinite sequence User Profile -> Friends List -> User Profile -> etc.

**Comment by kalutheo** [comment]
hey  ! great work ! any news about this feature ?

**Comment by sarimarton** [comment]
I'm also pretty interested in this feature. I find PUG as the most legible format for SCs, JSON/YAML is too verbose vertically, XML is also noisy with the closing tags. PUG would perfect, but it turns into XML, so we need xml import :)

**Comment by Andarist** [comment]
Conversion is partially supported by https://github.com/davidkpiano/xstate/blob/master/src/scxml.ts , it ain't 100% ready yet though - so stay tuned.
