### ISSUE TITLE
Array conditions

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#414]
## Bug or feature request?

Feature request

## Description:

Would be neat if `cond` could accept array of guards, without this I have to make multiple transient states when my logic is more complex.

## (Feature) Potential implementation:

It's not a breaking change and the API would be something like this:
```js
'': [
    { target: 'foo', cond: ['isOnline', 'hasForm'] }
]
```

**Comment by davidkpiano** [comment]
This seems like it would work well with [custom guards 📘](https://xstate.js.org/docs/guides/guards.html#custom-guards) - the tricky thing with "just allowing arrays" is that it's ambiguous whether it means `isOnline && hasForm` or `isOnline || hasForm`. But you can easily do this:

```js
const every = (...guards) => ({
  type: 'every',
  guards
});

const guards = {
  isOnline: ctx => ctx.status === 'online',
  hasForm: ctx => ctx.user.hasForm === true
};

// ...
'': [
  {
    target: 'foo',
    cond: every('isOnline', 'hasForm')
    // => { type: 'every', guards: ['isOnline', 'hasForm'] }
  }
]

// ...
// machine options
{
  guards: {
    ...guards,
    every: (ctx, event, { guard }) => {
      const { guards } = guard;
      return guards.every(guardKey => guards[guardKey](ctx, event));
    }
  }
}
```

What do you think about that for a solution? Much more flexible than having XState be opinionated (and potentially too magical/black-box like) about custom guards.

**Comment by Andarist** [comment]
I don't have much problem with the proposed solution, I've tackled the problem at hand in a similar fashion at the moment. My reasoning behind requesting this was that basically OR might be already represented by:
```
'': [ { target: 'foo', guard: 'a' }, { target: 'foo', guard: 'b' } ]
```
and that custom guards are harder to serialize.

**Comment by davidkpiano** [comment]
I'll consider it. Good to look at prior art too: https://states-language.net/spec.html#choice-state

**Comment by ooloth** [comment]
This feature would be really nice. An array of two strings (e.g. `cond: ['isOnline', 'hasForm']`) would be much easier to read and write than custom guards are.

I think an array would work as an assumed `&&` since the `||` alternative can already be implemented using an array of transitions (as @Andarist mentioned) and the pattern already exists with the `actions` arrays (i.e. every function in the array is fired).

🤞

**Comment by davidkpiano** [comment]
Good point. I'll implement it - it's on [the roadmap](https://github.com/davidkpiano/xstate/issues/742).

**Comment by ooloth** [comment]
> Good point. I'll implement it - it's on [the roadmap](https://github.com/davidkpiano/xstate/issues/742).

Thank you!

**Comment by cybervaldez** [comment]
> Good point. I'll implement it - it's on [the roadmap](https://github.com/davidkpiano/xstate/issues/742).
Any chance this would also show up for the choose action?

**Comment by davidkpiano** [comment]
@cybervaldez That will most likely look like:

```js
choose([
  { cond: and('cond1', 'cond2') }
])
```

Or something similar.

**Comment by AlCalzone** [comment]
> But you can easily do this

If anyone stumbles across this workaround, I had to make a few changes to the `every` guard to make it work:
```diff
- every: (ctx, event, { guard }) => {
- 	const { guards } = guard;
- 	return guards.every(guardKey => guards[guardKey](ctx, event));
  }
+ every: (ctx, event, { cond }) => {
+ 	const { keys } = cond;
+ 	return keys.every(guardKey => guards[guardKey](ctx, event));
  }
```

**Comment by joe2son** [comment]
> 
> If anyone stumbles across this workaround, I had to make a few changes to the `every` guard to make it work:
> 

This helped me, thanks!

**Comment by Enteleform** [comment]
@davidkpiano

I just implemented this following the `namespace.utility` convention of `actions` (*`actions.choose`, `actions.pure`, etc.*).

```ts
export namespace guards{
  export function every(...guards:string[]){
    return function guard(context:any, event:any, meta:any)
      {return guards.every(key => meta.state.machine.options.guards[key](context, event, meta))}
  }
  export function some(...guards:string[]){
    return function guard(context:any, event:any, meta:any)
      {return guards.some(key => meta.state.machine.options.guards[key](context, event, meta))}
  }
}
```

-----

This implementation allows me to reuse `guards` in any machine, without the boilerplate of the previously proposed solution (*target guards defined externally to MachineOptions, `every` guard defined in MachineOptions*).

Two questions:
- Are you aware of any potential pitfalls with this approach ?
- What do you think of using this approach for the `Array conditions` target of the roadmap?  
  (*the `namespace.utility` shape, not the exact implementation*)

**Comment by davidkpiano** [comment]
@Enteleform That actually seems like a great idea. Can you add it as an idea to a new discussion? I don't see much danger in exposing the machine configuration directly (which it already is, for `state.machine`) but we can support that more directly.

**Comment by eidan66** [comment]
@davidkpiano When this feature will be released? 🥺

**Comment by davidkpiano** [comment]
> @davidkpiano When this feature will be released? 🥺 

It is already in V5 alpha, although it looks slightly different to make guards much more flexible:

```js
guard: and(['isOnline', 'hasSomething'])
```
