### ISSUE TITLE
Multiple guards are first-come, first-serve

### ISSUE THREAD

**Issue by dakom** [davidkpiano/xstate#419]
This is just a documentation request. The page on [multiple guards](https://xstate.js.org/docs/guides/guards.html#multiple-guards) implies that they are followed in sequence and first-come, first-serve:

> For example, you can model a door that listens for an OPEN event, goes to the 'opened' state if you are an admin, or goes to the 'closed.error' state if alert-ing is true, or goes to the 'closed.idle' state otherwise.

Might be helpful to make an explicit mention of this in the docs

**Comment by davidkpiano** [comment]
I'm open to accepting a PR for this 🙏
