### ISSUE TITLE
Is there a way to fire actions without transitioning (i.e. when creating a new object)?

### ISSUE THREAD

**Issue by kurtmilam** [davidkpiano/xstate#42]
My team is using xstate to manage state transitions on the back end.

I have actions working well when transitioning between states, but I also need to trigger some side effects when creating new objects (usually one of the side effects that is already defined in my `actionMap`).

Assuming there's no built-in way to do this, I'm thinking it would make sense for us to add a dedicated `new` `initialState` to our machine, then create new objects in two steps:
1. Create an object with the `new` state.
2. Transition immediately to the actual desired state, using this transition to fire any necessary actions.

Side Note: It would be great if the project had a dedicated Gitter channel linked from the GitHub README and the doc site.

**Comment by davidkpiano** [comment]
Can you show some more example code so I have a better idea of what you're trying to achieve? Firing actions is entirely up to the developer - a statechart machine will simply map the event(s) from those actions to next states.

**Comment by kurtmilam** [comment]
Thanks for getting back to me quickly on this, and apologies for the delay in my response.

After putting a little more thought into the question, it became clear that our state machine was incomplete - we needed to add one more state and make it the initial state.

As I mentioned in the first post, we're using xstate on the backend, and two of the actions we trigger on state transition are:
1. Inserting a database record when a new object is created.
2. Updating the correct database record with the new state when a transition occurs.

When I asked the question, our machine had three de facto initial states, and I was trying to figure out whether we could trigger actions without first transitioning state. We now start all objects in the new, single `initialState` and transition them into one of the 3 states that had been our de facto initial states. This transition gives us a place to trigger actions that should occur when a new object is created (Inserting a database record).

If you'd like more info on our use-case, I'd be happy to provide it.
