### ISSUE TITLE
[@xstate/react] Remove immer dependency

### ISSUE THREAD

**Issue by DevSide** [davidkpiano/xstate#422]
## Bug or feature request?
Bug

## Description:
immer seems to be unused by @xstate/react by it is in its dependency list

**Comment by davidkpiano** [comment]
Interesting, `lerna` must have added it there. Want to make a PR?

**Comment by coodoo** [comment]
Wait, wouldn't it be a good idea to actually make the `context` immutable by default with `immer`?

**Comment by davidkpiano** [comment]
> Wait, wouldn't it be a good idea to actually make the context immutable by default with immer?

No, we don't want to prescribe a solution and want as minimal dependencies as possible.
