### ISSUE TITLE
Visualize statecharts tool

### ISSUE THREAD

**Issue by carlbarrdahl** [davidkpiano/xstate#44]
What do you use to visualize the statecharts?

**Comment by davidkpiano** [comment]
Currently this: https://codepen.io/davidkpiano/pen/ayWKJO

But I'm working on building a visualizer with more features 🔜

**Comment by carlbarrdahl** [comment]
This is awesome, thanks!
Looking forward to the new one.

**Comment by nenti** [comment]
Very nice. Thank you a lot. I hope the next version supports v3 state definition with actions and hierarchy.
