### ISSUE TITLE
Final states on substates can be transitioned from

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#441]
## Bug or feature request?

*I think* this is a bug.

## Description:

A final state on substate can be transitioned from:
```js
const fetchMachine = Machine({
  id: 'fetch',
  initial: 'idle',
  states: {
    idle: {
      on: { FETCH: 'substate'}
    },
    substate: {
      initial: 'done',
      states: {
        done: {
          type: 'final'
        }
      },
      on: { RESET: 'idle' },
    },
  },
});
```
where the same is not possible on the root state:
```js
const fetchMachine = Machine({
  id: 'fetch',
  initial: 'idle',
  states: {
    idle: {
      on: { FETCH: 'done'}
    },
    done: {
      type: 'final'
    },
  },
  on: { RESET: 'idle' },
});
```

It seems to me that both cases should work in a consistent manner - the transition should be disallowed (I was kinda surprised that we can exit something which is marked as **final**) or transition should be allowed in both scenarios and the behavior should be documented

## (Bug) Expected result:

Consistent behavior.

## (Bug) Actual result:

Slightly confusing one 😉

**Comment by avaragado** [comment]
I think there is a valid use case for being able to transition out of a final state - but if someone suggests a better way I’d be happy to change my mind. 

Imagine n independent on/off switches, each of which can transition between on and off at any time. But when all switches are on, and only then, something happens.

If transitions out of final states are permitted, you can model this with n parallel substates, where each “on” is a final state, with onDone on the parent to proceed. To me this feels natural.

(This doesn’t work if you only need, say, a majority of the switches to be on to trigger the action. I guess the alternative is to use context to count the on/off values, and a guard somewhere to decide whether to proceed.)

**Comment by alizbazar** [comment]
Final state is final only locally. Final state prevents transitioning from that state to other siblings. This should not prevent transitions to siblings of the parent(s).

For me, this sounds like a feature.

**Comment by davidkpiano** [comment]
This is as-expected. Only in top-level state nodes (direct children of the machine) can a `final` state node terminate the state machine: https://www.w3.org/TR/scxml/#final

The use-case for having a final state in a nested state node would be to transition from it when it is done:

```js
    substate: {
      initial: 'done',
      states: {
        done: {
          type: 'final'
        }
      },
      on: { RESET: 'idle' },
      onDone: 'anotherState' // transition out of this substate
    },
    anotherState: { ... }
```

**Comment by Andarist** [comment]
Thanks for the clarifications!
