### ISSUE TITLE
xstate should be a peerDep for @xstate/react

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#442]
`@xstate/react` includes `xstate` as a dep. I'm 99% sure nobody will ever use `@xstate/react` by itself.

I recommend removing `xstate` as a dep from `@xstate/react` so we can save 12kb from our bundles:

![Bundlephobia](https://d.pr/i/aR2y5u+)

**Comment by davidkpiano** [comment]
Good call. Want to make a PR?

**Comment by hnordt** [comment]
Sure, I’ll send tomorrow.

**Comment by Andarist** [comment]
Keep in mind though that it won't remove any kilobytes from your bundle, the very same xstate instance can still very much be shared between xstate & @xstate/react, unless you lock you somehow into having 2 versions which I think is rather unlikely.

Nevertheless - making it a peer dep is a good choice in this situation.

**Comment by hnordt** [comment]
I’m almost sure that without tree shaking it’s gonna result in twice the size even when xstate versions are equal.

A few building tools like CRA don’t have support for tree shaking yet.

**Comment by Andarist** [comment]
@hnordt it's not about tree-shaking. It's about node resolution algorithm. If you have a single copy of xstate in your dep tree (in the node_modules/xstate) then any xstate consumer would load exactly from the same place - resulting in no duplication.

Notice how peerDep thing doesn't event change that, you will still end up with single xstate directory in node_modules and your bundler doesn't even know what is a dep and what is a peer, it just cares about directory structure.

**Comment by hnordt** [comment]
Thanks for the clarification @Andarist.
