### ISSUE TITLE
Alternative assign() syntx not working with spawn(actor)

### ISSUE THREAD

**Issue by coodoo** [davidkpiano/xstate#448]
Not sure if this is by-design or really a bug, but both syntaxes should work?

This works:
```js
actions: assign({
  todoRefs: (ctx, e) => ({
    ...ctx.todoRefs,
    [e.id]: spawn(childMachine),
  }),
}),
```

This didn't:
```js
actions: assign((ctx, e) => {
  return { ...ctx.todoRefs, [e.id]: spawn(childMachine) }
}),
```

**Comment by coodoo** [comment]
Scratch that, ended up needing new `useMachine` to make it work, all's good now!

**Comment by davidkpiano** [comment]
Thanks for kicking the tires on `spawn(...)`! Keep in mind that until the minor release, the API isn't finalized.
