### ISSUE TITLE
[Feature] State metadata

### ISSUE THREAD

**Issue by davidkpiano** [davidkpiano/xstate#45]
Especially in testing and analytics, it can be useful for states to have associated metadata. Below is a simple proposal for what this can look like, analogous to [the `<datamodel>` specified in SCXML](https://www.w3.org/TR/scxml/#datamodel):

```js
const machineConfig = {
  initial: 'foo',
  states: {
    foo: {
      on: { ... },
      data: { ... } // metadata for 'foo' state
    },
    // ...
  },
  data: { ... } // metadata for machine (considered a state node)
}
```

And state objects will have the represented immutable metadata:

```js
machine.transition(...);
State {
  value: 'foo',
  history: ...,
  actions: [...],
  data: { ... } // state.data or undefined
}
```

The `data` property would be a record that can have any meta data in it that does not affect the transitions of the state machine (i.e., it is _internal_ to the machine). Examples include:

- passing heuristics for automatically generated tests to "know" when an externally-defined machine is in a certain state
- adding analytical data to states (useful for weighted state machines)
- static data useful for rendering any given state
- whatever you want!

Thoughts? The name `data` was chosen instead of `meta` to maintain consistency with SCXML. cc. @mogsie @michelebertoli

**Comment by mogsie** [comment]
How would you treat substate data?  And parallel state data?  Would they be aggregated, or would one be able to grab them all?  For parallel states it becomes difficult, because you could easily have to conflicting values for a property, both being "valid".

**Comment by davidkpiano** [comment]
@mogsie Good points - I wouldn't want to aggregate them naïvely, there could be conflicts (and definitely ambiguity as to which state the data relates to).

Hmm... since the way we're defining state values hierarchically (e.g., `{ foo: { bar: 'one', baz: 'two' } }`) is essentially an easier way of defining them by ID (e.g., `'foo.bar.one'`, `'foo.baz.two'`), we can use those unique IDs in the returned "datamodel":

```js
State {
  value: { foo: { bar: 'one', baz: 'two' },
  data: {
    foo: // data for foo
    'foo.bar': // data for foo.bar
    'foo.bar.one': // data for foo.bar.one
    'foo.baz': // data for foo.baz
    'foo.baz.two': // data for foo.baz.two
  }
}
```

It looks a little funny, but the strings are the exact IDs assigned to each of the state nodes and this would guarantee no conflicts, as well as quick data look-up time (we can always have a helper function/method for retrieving data based on state, e.g., `state.getData({ foo: 'bar' })`).

Thoughts on this approach?
