### ISSUE TITLE
the machine gives different results between normal mode and mode debugging (react native)

### ISSUE THREAD

**Issue by soufian97** [davidkpiano/xstate#469]
## Bug 

Description:

Expected result: for examples fetchMachine.initialState.nextEvents give me the different event in the state

Actual result: in the normal mode, he gives me just the first event of the State

**Comment by davidkpiano** [comment]
Not sure how this is possible. What version? Please check on the latest version of XState.

**Comment by davidkpiano** [comment]
Closing this as invalid - please provide a code reproduction if this is still the case after upgrading.
