### ISSUE TITLE
Feature request: Add `sideEffects` declarations

### ISSUE THREAD

**Issue by macbem** [davidkpiano/xstate#474]
In order to save a few kilobytes on bundle size, `xstate` could declare `sideEffects` in `package.json` so that Webpack will be able to tree shake its modules.

I'd be willing to send a PR for this, but I'm don't know the codebase yet and I'm not sure if there are any side effects or not.

**Comment by davidkpiano** [comment]
There are no side-effects 😄 Feel free to send a PR for this! It's been something I've been meaning to do for a while.

**Comment by macbem** [comment]
Great, I'll send a PR soon, hopefully today if I find some time.
