### ISSUE TITLE
convert sketch systems to xstate

### ISSUE THREAD

**Issue by david-raine** [davidkpiano/xstate#479]
I have been using sketch systems and I love the fact that I can use their text syntax to explain the states to "semi-technical" users.  I also like editing that text format and then running it through the sketch system site to produce xstate json.

I would love to be able to include this as part of my build process, so this is a cheeky request to see if anyone knows of any way to do this conversion in an automated way? Is there a CLI tool available? If not, how hard do you think it might be to write one?

**Comment by hnordt** [comment]
It would be very interesting if we also had an editor extension to read the machine definitions and allow us to see the visual representation while editing the code.

https://github.com/statecharts/xstate-viz could be the foundation for this.

**Comment by johnkazer** [comment]
Currently sketch.systems exports json in XState v3 format, it would be wonderful if XState had a conversion script (or we convince sketch.systems [to upgrade](https://talk.sketch.systems/t/support-for-xstate-v4-possible/193/2) :-) ).
I'm very keen on this work flow (expanded on a bit [here](https://dev.to/johnkazer/revist-the-waterfall-process-but-this-time-with-maths-27cn)), and the update would be a great improvement:

1. Creating the initial *design* with [Figma](https://www.figma.com/) and [sketch.systems](https://sketch.systems/ryanlucas/sketch/a58505b25ac114c6cec64922cb8fb325) (see the 'Export to clipboard' option) which informs, and is informed by;

1. State chart *maths* in XState.

1. UI via a *framework* (such as [React](https://reactjs.org/) or [Hyperapp](https://hyperapp.dev/)) is a side-effect of state chart behaviour.

1. Testing can be derived directly from the XState graph module and implemented with [Cypress](https://www.cypress.io/).

1. Requirement changes can quickly be incorporated into *design* and state chart *maths* updates, which (generally) require simple UI *framework* tweaks.

**Comment by coodoo** [comment]
@johnkazer Out of curiosity, how do you convert Figma format to xstate? Is there something like `Export to clipboard` for Figma as in sketch.systems?

**Comment by johnkazer** [comment]
Is a bit clunky, but sketch.systems defined a method in [this tutorial](https://sketch.systems/ryanlucas/sketch/a58505b25ac114c6cec64922cb8fb325)

**Comment by johnkazer** [comment]
PS, am investigating option of creating a Figma plugin to export a json list of URLs.

**Comment by johnkazer** [comment]
Here's a pretty raw [first go](https://github.com/johnkazer/Export-Figma-layer-IDs)
