### ISSUE TITLE
Static visualizer for Machine

### ISSUE THREAD

**Issue by dmitrynovik** [davidkpiano/xstate#500]
## Feature

It is nice that the xstate has the visualizer app where we can paste the code, however, if we decide to use xstate, we would not be able to do it manually with every state machine in the app.

I wonder if you plan a visualization to a static file feature, something like the javascript-state-machine has: https://github.com/jakesgordon/javascript-state-machine/blob/master/docs/visualization.md

Ideally, we would like to generate static diagram files in our CI/CD pipeline as a part of build process and dump them to file(s) in sort of open format (such as DotGraph) so that they can be viewed later, at any point in time. E.g something like `dump (fsm, path, format = "dotgraph")`

Is this something that is being considered?

Regards,
Dmitry.

**Comment by davidkpiano** [comment]
Let's merge this with #528
