### ISSUE TITLE
[question] is it possible to call entry action with payload?

### ISSUE THREAD

**Issue by DirkWolthuis** [davidkpiano/xstate#505]
Hi all, 

Really love the library! I've a couple of questions regarding guards, actions and reloading of a invoke service. 

1. Is it possible to call an action in an entry hook with some kind of payload that I can use in the action function to write something to the context. The code following code does not work:

```
   postNL: {
      entry: [{ type: "selectDeliveryMethod", payload: "POSTNL" }],
      on: {
        SELECT_PICK_UP: "pickUp",
        SELECT_DELIVERY: "delivery"
      }
    }
```
2. Is it possible to target a specific state when a guard fails (to let the user know why a specific state is not reachable? Are there other ways to get the same result?

3. If I use invoke service (promise) on a specific nested state and the parent state changes to something different and comes back to the state, the API request (promise) is invoked. Is there any way to check the context for data before firing again? (not a deal breaker but I'm curious)

**Comment by davidkpiano** [comment]
> Is it possible to call an action in an entry hook with some kind of payload that I can use in the action function to write something to the context. 

Yes, for the `{ type: "selectDeliveryMethod", payload: "POSTNL" }` action, the implementation can look like:

```js
// ...
{
  actions: {
    selectDeliveryMethod: (context, event, { action }) => {
      console.log(action.payload);
      // => "POSTNL"
    }
  }
}
```

> Is it possible to target a specific state when a guard fails (to let the user know why a specific state is not reachable? Are there other ways to get the same result?

Yes, if this is what you mean:

```js
{
  on: {
    SUBMIT: [
      { target: 'submitting', cond: formValid },
      { target: 'invalid' } // <-- default state when guard(s) fail
    ]
  }
}
```

> If I use invoke service (promise) on a specific nested state and the parent state changes to something different and comes back to the state, the API request (promise) is invoked. Is there any way to check the context for data before firing again? (not a deal breaker but I'm curious)

You can use a [transient transition 📖](https://xstate.js.org/docs/guides/transitions.html#transient-transitions) to determine which state to go to:

```js
checkForData: {
  on: {
    '': [
      { target: 'loaded', cond: (ctx) => ctx.data !== undefined },
      { target: 'loading' }
    ]
  }
},
loading: {
  invoke: { /* ... */ }
},
loaded: {}
```

**Comment by DirkWolthuis** [comment]
Wow thanks! This will help me a awful lot!

**Comment by DirkWolthuis** [comment]
Okay I can't seem to get usecase 1 working, tried a couple of things but how do I get access to the action variable inside the assign function? 

```
 selectDeliveryMethod: (_, __, action) => assign({
        selectedDeliveryMethod: (context, event) => {
          console.log(context, event, action);
          return " ssss";
  }
```

This does not seem to work and there is no action variable inside the assign function.

**Comment by davidkpiano** [comment]
One limitation of `assign()` right now is that it only gets the `context` and `event`. For now, one approach/workaround that I'd recommend is to just use JS:

```js
function assignDeliveryMethod(payload) {
  return assign({ deliveryMethod: payload });
}

// ...

{
  actions: assignDeliveryMethod('POSTNL')
}
```

> PS I don't really get why I can't return assign() from a other function.

You can; that's what the above pattern is doing.

**Comment by DirkWolthuis** [comment]
Okay just so I'm sure I understand correctly: there is no way to combine a state (to use state.matches) argument with the assign function? Can I add the feature request if there isn't already one to add the meta argument to the assisgn function?

**Comment by Andarist** [comment]
> Okay just so I'm sure I understand correctly: there is no way to combine a state (to use state.matches) argument with the assign function? Can I add the feature request if there isn't already one to add the meta argument to the assisgn function?

Could you describe what you are trying to do in more detail?

**Comment by petrdsvoboda** [comment]
@davidkpiano You mentioned that 

> One limitation of assign() right now is that it only gets the context and event. 

Would it be possible in the future to access state meta information inside assign function?

I'm trying to collect meta data from all the states that were passed in one event. Specifically add meta messages to context message array.

**Comment by davidkpiano** [comment]
> Would it be possible in the future to access state meta information inside assign function?

Yes, it will.

**Comment by davidkpiano** [comment]
Closing this as assigners/property assigners do get the state meta information:

```ts
export interface AssignMeta<TContext, TEvent extends EventObject> {
  state?: State<TContext, TEvent>;
  action: AssignAction<TContext, TEvent>;
  _event: SCXML.Event<TEvent>;
}
```
