### ISSUE TITLE
How to type xstate/react

### ISSUE THREAD

**Issue by EmirGluhbegovic** [davidkpiano/xstate#510]
## Bug or feature request?
Potential Bug else Documentation Request

I have the following code:

`const [state, send] = useService(AuthService);`

In another component I have:

```
interface TemplateProps {
  state: State<AuthContext, AuthEvent>;
  send: SendAction<AuthContext, AuthEvent>;
}
```

```
await actions.props.send({
  type: 'LOGIN',
  payload: { ...values },
});
```

Then I would get these errors:

For the send action I see this TS error:

`Cannot invoke an expression whose type lacks a call signature. Type 'SendAction<AuthContext, AuthEvent>' has no compatible call signatures.ts(2349)`

`return <Template state={state} send={send} />;`

For the send key I see this TS error:

`Type '(event: SingleOrArray<OmniEvent<EventObject>>, payload?: (Record<string, any> & { type?: undefined; }) | undefined) => State<Record<string, any> | undefined, EventObject>' is missing the following properties from type 'SendAction<AuthContext, AuthEvent>': to, event, id, typets(2739)`

**Comment by davidkpiano** [comment]
You mis-typed `send` - it's not a `SendAction`, but rather a `send` function/method for the service. Two different things.

Try this:

```ts
interface TemplateProps {
  state: State<AuthContext, AuthEvent>;
  send: Interpreter<AuthContext, AuthEvent>['send']
}
```

You should avoid doing this though and instead just pass the entire service down.

**Comment by EmirGluhbegovic** [comment]
I tried the following

```
interface FormProps extends WithStyles<typeof styles> {
	state: State<AuthContext, AuthEvent>;
	send: Interpreter<AuthContext, AuthEvent>['send'];
}
```
And I get the following errors:

For the AuthEvent inside the Interpreter

```
Type 'AuthEvent' does not satisfy the constraint 'StateSchema'.
  Type '{ type: "LOGIN"; data: any; }' has no properties in common with type 'StateSchema'.ts(2344)
```

And inside the Container component:
`
return <Template state={state} send={send} />;`

I see this error:
```

Type '(event: SingleOrArray<OmniEvent<AuthEvent>>, payload?: (Record<string, any> & { type?: undefined; }) | undefined) => State<AuthContext, AuthEvent>' is not assignable to type '(event: SingleOrArray<OmniEvent<EventObject>>, payload?: (Record<string, any> & { type?: undefined; }) | undefined) => State<AuthContext, EventObject>'.
  Types of parameters 'event' and 'event' are incompatible.
    Type 'SingleOrArray<OmniEvent<EventObject>>' is not assignable to type 'SingleOrArray<OmniEvent<AuthEvent>>'.
      Type 'string' is not assignable to type 'SingleOrArray<OmniEvent<AuthEvent>>'.ts(2322)
```

**Comment by davidkpiano** [comment]
✏️ Please create a [CodeSandbox (XState template)](https://codesandbox.io/s/xstate-example-template-qcwed) reproduction of this. Thanks!

**Comment by EmirGluhbegovic** [comment]
Look at the Template.jsx file

https://codesandbox.io/s/upbeat-goldwasser-k5k5j

**Comment by davidkpiano** [comment]
See the fixed version here: https://codesandbox.io/s/happy-satoshi-byrj1

When in doubt, look at the type definitions.

**Comment by haywirez** [comment]
Not sure if the best way, but this works for me:
```
  let [current, send] = useService<ServiceContext, AnyEventObject>(serviceRef);
```
