### ISSUE TITLE
Using XState with ReasonML

### ISSUE THREAD

**Issue by pedronauck** [davidkpiano/xstate#515]
## Bug or feature request?
Feature request

## Description:
Just to know, anyone using XState inside Reason? I tried to figure out some content about but didn't found anything. Would be awesome if we have some recipe for Reason inside the official documentation as we have for some frameworks/libs.

**Comment by nick-walt** [comment]
Does Elm also have the ability to track invalid states? I am currently exploring the combination of Svelte as View with Elm's Update and Model. Sending just data via Ports it occurred to me that I could explore using Xstate/FSM in between Svelte and Elm.

Elm has a philosophy of making impossible states impossible but to me that isn't the same as what Xstate is focused on, which seems to be a much more formalised system that would tie in to something like DDD's high level approach. Whereas Elm's mechanisms are low level and only code based. What do you think?

Should I pursue Xstate as in-between process manager for Svelte?

**Comment by davidkpiano** [comment]
This will hopefully happen one day but is outside the scope of this repo, sorry!
