### ISSUE TITLE
Unable to send events to arbitrary services

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#523]
## Description:

Not sure if I interpret this correctly, but in SCXML spec [here](https://www.w3.org/TR/scxml/#ExternalIntroduction) is stated that:
> The External Communications capability allows an SCXML session to send and receive events from external entities, and to invoke external services. 6.2 <send> provides "fire and forget" capability to deliver events and data to any destination, including other SCXML sessions.

## (Bug) Expected result:

I would expect that if unique ID of a sub-machine (or any other invoked service) is known  then it can be used to send events directly to it through the Interpreter instance (or using `<send>` element within invoked service)

## (Bug) Actual result:

Only immediate children are known to the interpreter and therefore it's not possible to send anything to a service which is nested anywhere deeper (or at any other location).

## Link to reproduction:

https://codesandbox.io/s/cool-hertz-9e00u

**Comment by davidkpiano** [comment]
I'm thinking we need to generate universally unique `sessionId` identifiers for each invoked session (this is different than the machine ID, and should not be known until a machine is started/invoked).

Then, the pattern would have to be that a child machine would `sendParent(...)` the `sessionId` of a grandchild machine, which the parent machine should be able to send events directly to.

**Comment by Andarist** [comment]
I was reading SCXML spec today quite a lot and I agree about the sessionId thing, according to the spec this has to be shared explicitly through events etc (although it's not quite explicitly stated in the spec, but that's what I read out of it).

> #_scxml_sessionid. If the target is the special term '#_scxml_sessionid', where sessionid is the id of an SCXML session that is accessible to the Processor, the Processor must add the event to the external queue of that session. The set of SCXML sessions that are accessible to a given SCXML Processor is platform-dependent.

Even though it's stated that what is known is platform-dependent I would be in favor of registering all nested sessions (no matter the depth) in owning interpreter automatically (without having to share this explicitly - the outer world still wouldnt know how to use those). That would allow for https://github.com/davidkpiano/xstate/issues/486 to be implemented as mentioned in the SCXML spec:
> origin. This is a URI, equivalent to the 'target' attribute on the <send> element. For external events, the SCXML Processor should set this field to a value which, when used as the value of 'target', will allow the receiver of the event to <send> a response back to the originating entity via the Event I/O Processor specified in 'origintype'.

Without central registry, it's not quite possible to just send a response back to the origin because the sender might be at arbitrary location.

**Comment by allforabit** [comment]
Could the origin be a path to the originating service? I.e. "/todos/todo-1", which would traverse down through the children of each service to find the target. This would be similar to akka's approach using path refs. https://doc.akka.io/docs/akka/current/general/addressing.html
