### ISSUE TITLE
Visualizer as a CLI tool

### ISSUE THREAD

**Issue by JasonNutmeg** [davidkpiano/xstate#528]
## Bug or feature request?

Feature request

## Description:

Have the visualizer as a CLI tool, where the state chart can be generated as an image. I think it would be nice to commit the state chart image into git so that it can be added to the documentation of the repository.

### What the API would look like

At the most basic level, something like this:
`visualizer filename_that_exports_the_machine --outputFile my_state_machine.png`

**Comment by NewAlexandria** [comment]
Was this ever referenced or moved to another issue?  It looks like this one referenced #500, and then that was closed, and then this was closed. 

Pardon that I don't have a suggestion for how to solve this one - but would love to make it part of our pipeline.  Some people are strongly-visual learners and readers, and the diagram is the only way they can grok what's happening.

**Comment by davidkpiano** [comment]
@NewAlexandria This would fit under https://github.com/davidkpiano/xstate/issues/90, which is in the roadmap.

**Comment by NewAlexandria** [comment]
I think I was confused about #90 because it also says it's closed.  For future reference, to others, [this seems to be the roadmaps indicated](https://github.com/davidkpiano/xstate/discussions/742).
