### ISSUE TITLE
Add ability to pass params to service declared as property

### ISSUE THREAD

**Issue by alfreema** [davidkpiano/xstate#529]
## Description:

This exchange in the chat best summarizes the request:

Q: Is there any way to pass hardcoded values to an invocation when the service is declared in a services property? 

A: Currently no, ...  Should be just like actions and guards

## (Feature) Potential implementation:

- What the API would look like

// future enhancement
```js
services: {
  fetchUser: (context, event, { service }) => {
    // service.params === { role, username, password }, etc.
  }
}
```

- If this is a breaking change

Should not be a breaking change

**Comment by hnordt** [comment]
Could you explain your use case?

I believe it can be handled easily with functions, no?

```js
function sendRequest({ method, path, body }) {
  // ...
}

function fetchUser() {
 let role = "foo"
 let username = "bar"
 let password = "baz"

  return sendRequest({ method: "get", path: "/user", body: { role, username, password } })
}

services: {
  fetchUser: (context, event) => fetchUser()
}
```

**Comment by Andarist** [comment]
I also don't see a value of this at the moment as this introduces new special API to cover a use case which can be **easily** covered by language itself.

**Comment by davidkpiano** [comment]
I see the utility of this now - this should come in the form of something like:

```js
invoke: {
  src: {
    type: 'customerAPI',
    method: 'GET',
    params: { user: 42 }
  }
}
```

Where the implementation details for `customerAPI` are provided.

**Comment by Andarist** [comment]
So would this just fill arguments of the given `customerAPI`?

**Comment by davidkpiano** [comment]
> So would this just fill arguments of the given `customerAPI`?

No, that's up to the implementation. (Contrived example below)

```js
services: {
  customerAPI: (context, event, { service }) => {
    return fetch(API.getCustomer + toQueryParams(service.params), {
      method: service.method
    });
  }
}
```

**Comment by CodingDive** [comment]
Will the third argument be a `"stateService"` object that not only has the extra `service` data like you demonstrated but also the current `state`?
I once had to dump the state (value) into an event just to use the state inside a service. This wasn't pretty at all, accessing it within a service would be really helpful!

**Comment by davidkpiano** [comment]
Yes, just like the third "meta" argument for actions and guards, it will have the current `state`.

**Comment by CodingDive** [comment]
> Also, please don't rely on state if you can avoid it. It's not an optimal pattern - you should already know which state you're in given the machine structure.

I agree. In my use case, I modeled some radio buttons as state nodes and needed to send their value to the server. Haven't ran into any other scenario where I needed state inside a service but it's useful to know  that it'll be possible.

**Comment by sateesh2020** [comment]
@davidkpiano will this feature be available in V5

**Comment by davidkpiano** [comment]
Yes it will.
