### ISSUE TITLE
Wrong error on invalid sibling transition

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#548]
## Description:

Invalid sibling transitions report a wrong error.

## (Bug) Expected result:

```
Invalid transition for state node '(machine).nested' on event 'RIGHT_CLICK':
Child state 'right' does not exist on '(machine)'
```

## (Bug) Actual result:

```
Invalid transition for state node '(machine).nested' on event 'LEFT_CLICK':
Child state 'left' does not exist on '(machine)'
```

## Link to reproduction:

https://codesandbox.io/s/zen-cache-01gk2

**Comment by davidkpiano** [comment]
This is not a "wrong error" per se; but rather, the `on` property is a getter that formats transitions when a state node is active. Since the transition for `'LEFT_CLICK'` appears first, it formats that first and realizes there's no sibling state `'left'` (should be `'.left'`, so it throws.

**Comment by Andarist** [comment]
Ok... I see. A more helpful message could be thrown here though.

 I still don't quite get all relations between those few classes XState has, maybe you would be able to write up few words about that as implementation notes, would help me (and others) a lot while exploring the codebase. I know the implementation is going to change, but then such notes could be adjusted - for now I'm trying my best to read between the code lines 😉 In particular, it would be good to bullet point responsibilities of classes and describe the overall approach of the algorithm.

When thinking about this now I suspect that this error is caused by lazy transition formatting which gets cached later on. Maybe we could evaluate lazy things in dev mode at initialization time to make it more apparent that the machine config itself is broken rather than it's something weirdly wrong with the transition which we attempt to make with our concrete event?

**Comment by davidkpiano** [comment]
> I still don't quite get all relations between those few classes XState has, maybe you would be able to write up few words about that as implementation notes, would help me (and others) a lot while exploring the codebase.

I'm working on a big simplification, and I'll add plenty of comments to make it more understandable.

> When thinking about this now I suspect that this error is caused by lazy transition formatting which gets cached later on.

Yep!

> Maybe we could evaluate lazy things in dev mode at initialization time to make it more apparent that the machine config itself is broken rather than it's something weirdly wrong with the transition which we attempt to make with our concrete event?

Good idea. I think we should prioritize adding development-only pre-execution analysis (which outputs to the console) for this.
