### ISSUE TITLE
[Feature] Support local transitions

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#55]
## Description:

A local transition is a transition from a state to its substate which sidesteps _exiting_ the source state, since (because the target is a child state) after the transition, the new configuration will include the source state.

The opposite, an external transition would be a transition to ones children that _exits_ the current state and _enters_ it again.

### What the API would look like

A transition can already be expressed as plain strings or objects, so I suggest these local transitions be specified in the object form only:

```js
on: {
  EVENT: { target: "foo", type: "local" }
}
```
The default would probably be an external event, as that's probably backwards compatible, however local events (where possible) do make sense to consider them being local by default.

Perhaps "internal" should be used to be more in line with SCXML?  Local stems form Wikipedia and UML.

This is not a breaking change

- This is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)

statecharts.github.io describes the concept: https://statecharts.github.io/glossary/local-transition.html  — It includes a workaround for xstate that more or less gives you the same result.

**Comment by davidkpiano** [comment]
(to provide some visuals) For a real life example, imagine a word editor with left, right, center, justify buttons:

<img src="https://imgur.com/FyB6MKx.jpg" width="300" />

This can be simplified with internal transitions:

<img src="https://imgur.com/7P1TV9K.jpg" width="300" />

And this could look like this:

```js
Machine({
  key: 'wordEditor',
  initial: 'left',
  states: {
    left: {},
    right: {},
    center: {},
    justify: {}
  },
  on: {
    // internal transitions
    LEFT_CLICK: '.left',
    RIGHT_CLICK: '.right',
    CENTER_CLICK: '.center',
    JUSTIFY_CLICK: '.justify',
  }
});
```

Prepending with a dot, e.g., `'.left'`, would signify that the state machine would exit the child state, handle the event from the parent state, which internally transitions to its child. 

From my understanding (in this example), the parent state `'wordEditor'` doesn't exit/enter, but its children do.

**Comment by davidkpiano** [comment]
Also, re: the above example, `LEFT_CLICK: '.left'` would be an **internal transition** (`wordEditor` never exits/reenters) whereas `LEFT_CLICK: 'wordEditor.left'` would be an **external transition** (following the same behavior as a self-transition) which would exit/reenter `wordEditor`. 

In real life, this would be like a `RESET` button, where you'd want the parent state to exit/reenter.

**Comment by mogsie** [comment]
I think that makes a lot of sense, since this dot prefix is only relevant when transition to child states.  It also fits well with e.g. `wordEditor.left` being a normal, _external_ transition, and `wordeditor` being a self transition.

**Comment by davidkpiano** [comment]
Local transitions are in! (see `localTransitions.test.ts`)

**Comment by jianzhongli** [comment]
> (to provide some visuals) For a real life example, imagine a word editor with left, right, center, justify buttons:
> 
> <img alt="" width="300" src="https://camo.githubusercontent.com/330b47f7fa42a603c3566969e893297bbfa0d500/68747470733a2f2f696d6775722e636f6d2f467942364d4b782e6a7067">
> 
> This can be simplified with internal transitions:
> 
> <img alt="" width="300" src="https://camo.githubusercontent.com/6946c0447150c7df3b8902647ccfee29ab790a90/68747470733a2f2f696d6775722e636f6d2f3750315456394b2e6a7067">
> 
> And this could look like this:
> 
> ```js
> Machine({
>   key: 'wordEditor',
>   initial: 'left',
>   states: {
>     left: {},
>     right: {},
>     center: {},
>     justify: {}
>   },
>   on: {
>     // internal transitions
>     LEFT_CLICK: '.left',
>     RIGHT_CLICK: '.right',
>     CENTER_CLICK: '.center',
>     JUSTIFY_CLICK: '.justify',
>   }
> });
> ```
> 
> Prepending with a dot, e.g., `'.left'`, would signify that the state machine would exit the child state, handle the event from the parent state, which internally transitions to its child.
> 
> From my understanding (in this example), the parent state `'wordEditor'` doesn't exit/enter, but its children do.

Need some help about concept clarification here: 

In the "word editor" example, transitions from superstate to substates can be treated as a simplication of the transitions in `Figure 6.12`. [Wikipedia](https://en.wikipedia.org/wiki/UML_state_machine#Local_versus_external_transitions) refer these transitions as "local transition" rather than "internal transitions", which is fine as long as "internal transition" has anothoer well-defined meaning.

![](https://upload.wikimedia.org/wikipedia/en/a/ac/UML_state_machine_Fig8.png)

But I found it hard to understand the transitions from substates to superstates. I think "superstates" are somewhat "abstract", which means a state machine can't be in any superstates, in fact, they should be exactly be one of the leaf substates of the superstates. 

Does transtions from a substate to its superstate means a internal transition from the substate to the default initial state of that superstate? But that will obviously trigger the exit/enter actions.

**Comment by Andarist** [comment]
> a state machine can't be in any superstates, in fact, they should be exactly be one of the leaf substates of the superstates.

1. When a machine is in a leaf state it is also in every ancestor state containing this leaf
2. If any ancestor is a parallel state then a machine can be in more than one leaf state (there is no restriction in how many leafs ot can be as you can create any number of parallel states)

> Does transtions from a substate to its superstate means a internal transition from the substate to the default initial state of that superstate? But that will obviously trigger the exit/enter actions.

Yes, this description seems to be accurate.

**Comment by jianzhongli** [comment]
![image](https://user-images.githubusercontent.com/5278523/85245681-f35a1b80-b47a-11ea-8e4c-c2c0016151d6.png)

Thanks! Now I get it, according to [wikipedia](https://en.wikipedia.org/wiki/UML_state_machine#Local_versus_external_transitions).

> In the top row, you see the case of the main source containing the main target. The local transition does not cause exit from the source, while the external transition causes exit and reentry to the source. In the bottom row of Figure 8, you see the case of the main target containing the main source. The local transition does not cause entry to the target, whereas the external transition causes exit and reentry to the target.

1. In the top row, we can interpret the transition as an internal transition as in `Figure 6.12`, hence "the local transition does not cause exit from the source".
2. In the bottom row, its actually an internal transition from a state to its parent's default initial state, hence "the local transition does not cause entry to the target".
