### ISSUE TITLE
Discussion around possible target patterns

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#554]
Current patterns are described at the bottom of [internal transitions](https://xstate.js.org/docs/guides/transitions.html#internal-transitions) and [external transitions](https://xstate.js.org/docs/guides/transitions.html#external-transitions).

This issue is not about discussing internal/external types - those are concepts well-defined by SCXML spec. I'd like to focus on currently supported "target patterns":
- `#<id>`
- `<id>`
- `.<path>`
- `<id>.<path>`

I kinda feel that those don't work in a cohesive way and are hard to understand, especially for beginners, because similar-looking patterns can't be mix & matched:
- `#<id>` pattern doesn't support paths
- `<id>` allow transitioning to ANY sibling, but `<id>.<path>` accepts only a "self-id" as ID, which makes it equivalent to `.<path>` (the only difference lies in implicit type - external/internal)

Additionaly - auto-generated IDs contain path delimiter in them (so i.e. `machine.state.child`), but IMHO explicitly IDentified states (currently) shouldn't accept delimiters in their IDs because it makes it even more confusing, after all auto-generated ones look like paths but you can type anything into explicit one.

And last - prepending auto-generated IDs with machine ID seems to be redundant. Especially considering that we've discussed in other issues that we should drop the possibility to specify `id` from the machine in favor of auto-generating sessionId and accepting only `name` which is "for purely informational purposes" ([per SCXML spec](https://www.w3.org/TR/scxml/#scxml)).

**Comment by davidkpiano** [comment]
The `<id>.<path>` pattern should be disallowed.

There should be only two target patterns:

- **ID**: `#foo`, `#bar.baz` would resolve to a state with `id: 'bar.baz'` (edge case, hopefully nobody does this) and NOT to `bar: { id: 'bar', states: { baz: {} }`
- **Relative**: no `#` prefix. Based on `<sibling | current>.<child>.<grandchild>` etc.

**Comment by Andarist** [comment]
> The <id>.<path> pattern should be disallowed.

Isn't this though what you describe later as the relative pattern?

> ID: #foo, #bar.baz would resolve to a state with id: 'bar.baz' (edge case, hopefully nobody does this) and NOT to bar: { id: 'bar', states: { baz: {} }

I can get behind that - I believe though that we should completely disallow specifying explicit IDs with path delimiter in it. I've proposed this in https://github.com/davidkpiano/xstate/pull/550 [here](https://github.com/davidkpiano/xstate/blob/ec8e017bb38a3fba690ff86149061db322697fc1/src/StateNode.ts#L258)

> Relative: no # prefix. Based on <sibling | current>.<child>.<grandchild> etc.

Should `<sibling | current>` part be optional to support `.child.grandchild` usage?

**Comment by davidkpiano** [comment]
> Isn't this though what you describe later as the relative pattern?

No; namely, this will be disallowed: `"#foo.bar"`, `"#foo.bar.baz"` etc.

(It will only be resolved if there is a state with an ID `"foo.bar"`, which as mentioned would be an edge case)

> Should `<sibling | current>` part be optional to support .child.grandchild usage?

Yes, these are valid: `"foo.bar"`, `".bar"` (resolves to `<current>.bar`).

**Comment by Andarist** [comment]
@davidkpiano I believe that your docs commit has only addressed the first part of the problem here - ID patterns not being matched at all against relative paths. 

This issue was also describing the possible expansion of relative targets to allow targeting "deep" descendants, which from what I remember is not supported yet. I've also mentioned confusion here around IDs allowing path delimiters right now and we could ban this in v5 altogether to avoid this.

**Comment by davidkpiano** [comment]
Adding this to #742
