### ISSUE TITLE
Guarding actor events

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#555]
For the same reason we shouldn't trust disabling an UI element to prevent users to send invalid events, we shouldn't listen to actor events without guarding them.

For example, when I invoke a `formMachine`, I want to be sure that only this child machine will be able to send `FORM.VALIDATED`, and not anyone else:

```js
{
  idle: {
    invoke: {
      src: formMachine
    },
    on: {
      "FORM.VALIDATED": {
        target: "loading",
        actions: assign({
          username: (_, e) => e.values.username,
          password: (_, e) => e.values.password
        })
      }
    }
  },
  loading: {
    invoke: {
      src: "login",
      onDone: "success",
      onFailure: "error"
    }
  }
}
```

I've been thinking on how to do it, and the most idiomatic way I could think of was a separated "on clause" for child services: 

```js
{
  on: {
    PARENT_EVENT: "foo"
  },
  onChild: {
    CHILD_EVENT: "bar"
  }
}
```

@davidkpiano, @johnyanarella, @Andarist thoughts?

**Comment by Andarist** [comment]
We could increase SCXML compliance by including sender~ in the event which you could validate then in your guard clause - https://github.com/davidkpiano/xstate/issues/486

**Comment by hnordt** [comment]
@Andarist that would be awesome:

```js
{
  invoke: {
    id: "form",
    src: formMachine
  },
  on: {
    "FORM.VALIDATED": {
      target: "loading",
      cond: (_, e) => e.meta.senderId === "form"
    }
  }
}
```

**Comment by davidkpiano** [comment]
Yep, #486 would be the answer to this.

**Comment by hnordt** [comment]
Closing this issue in favor of #486.
