### ISSUE TITLE
Actor event conflicts

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#556]
How can we avoid conflicts when two different actors send the same event to the parent?

Based on #486 I think we can do something like:

```js
on: {
  CHANGE: (ctx, e) => {
    switch (e.meta.sendId) {
      case "foo":
        // sent by foo
        break;

      default:
        // sent by someone else
        break;
    }
  }
}
```

So for example when a `formMachine` actor sends `CHANGE` I can respond in a different than when `inputMachine` sends `CHANGE`.

What's your thoughts on this?

**Comment by davidkpiano** [comment]
We definitely cannot have a function that defines a transition, because that makes it way too easy to introduce nondeterminism and much harder (if not impossible) to analyze. Example:

```js
// 🚫 counterexample
on: {
  CHANGE: (ctx, e) => {
    if (Math.random() < 0.5) {
      // do something
    } else {
      // do something else
    }
  }
}
```

Instead, use guards:

```js
// ⚠️ based on tentative syntax
// 'sendId' does not exist in the API yet

on: {
  CHANGE: [
    { target: 'foo', cond: (ctx, e, { sendId }) => sendId === 'foo' },
    { target: 'bar' }
  ]
}
```

**Comment by hnordt** [comment]
@davidkpiano sorry for the `on`. I was supposed to type `actions`. I meant an action implementation, not a transition.

But your response is also useful, we can implement the same idea for transitions.
