### ISSUE TITLE
Best practice on how to implement polling with xstate

### ISSUE THREAD

**Issue by aavelyn** [davidkpiano/xstate#567]
## Bug or feature request?
Feature request
## Description:

I want to implement a simple polling with Xstate. Currently I'm using the "after" delay to transition to a different a "loading" State, which handles the actual api call. When successful it enters the "polling" state again which, if no other allowed transition happens will go to the loading state after 10sec.

Below is a simple polling machine.
```js
const fetchMachine = Machine({
  initial: 'idle',
  states: {
    idle: {
       after: {
        TIMEOUT: 'pending'
      },
    },
    pending: {
      after: {
        TIMEOUT: 'idle'
      },
    },
  }
}, {
  delays: {
    TIMEOUT: 2000
  }
});

```

Since there is no official documentation, I would like ask for feedback is "after" is indeed intended for polling or if there are other best practices with xstate.

**Comment by davidkpiano** [comment]
That's one way to do it! Where is the actual API call being made? In `pending`?

**Comment by aavelyn** [comment]
Yep,

currently the api is still being called outside the machine in an anguar service using the rxjs recipe (https://xstate.js.org/docs/recipes/rxjs.html) 
and the format below to handle cancellation. Once cancellation is implemented I'm hoping to implement the api calls via "invoke" 

```
state$.pipe(switchMap( (state)=>handleState$(state)).subscribe()

function handleState(state){
currentState = getLastStateStrig(state)
switch(currentState){
    case 'pending':{
        return ap$(...).pipe(
            tap((payload)=>service.send('onIdle',{payload})),
            catchError(e=>{
                service.send('onError',{error})
                return of(false) <= this is to keep the subscription alive  
            })
        )
    }
}
return of(state)
}
```

**Comment by davidkpiano** [comment]
Ah, so you're listening for state changes externally to handle fetching/cancellation logic. Instead, you can try putting that in the machine itself:

```js
const fetchMachine = Machine({
  initial: 'fetching',
  states: {
    fetching: {
      invoke: {
        src: (ctx, e) => fetchFromAPI(...),
        onError: 'failure',
        onDone: 'success'
      },
      after: { TIMEOUT: 'fetching' } // retry fetching
    },
    failure: {
      after: {
        INTERVAL: 'fetching' // retry
      }
    },
    success: {}
  }
}, {
  delays: { INTERVAL: 2000, TIMEOUT: 10000 }
});
```

**Comment by aavelyn** [comment]
I tried your proposal with invoke. Beside the cancellation handling, the main issue was that we are using apollo for most of our data fetches. Passing an apollo instance or even an angular httpClient instance to context resulted into a mixture of difference frameworks. Hence I've implemented a "angular machine listener service", which handles api and framework calls and passes all the results as state data back to the machine.

You mentioned "That's one way to do it". Are there any other approaches you can recommend?

BTW: Love xstate, really helped me sorting out our client side state managment!

**Comment by davidkpiano** [comment]
> Passing an apollo instance or even an angular httpClient instance to context resulted into a mixture of difference frameworks.

Yeah, avoid doing that. The apollo instance and angular httpClient instances can be considered "services".

So you can instead do something like this:

```js
function apiService() {
  return (callback, onReceive) => {
    SomeAPIService.startRequest(...)
      .then(data => callback({ type: 'RESPONSE', data });

    onReceive(event => {
      if (event === 'POLL') {
        SomeAPIService.retryRequest(...);
      }
    });
  }
}

const fetchMachine = Machine({
  initial: 'fetching',
  states: {
    fetching: {
      invoke: {
        id: 'api',
        src: apiService
      },
      on: { RESPONSE: 'success' }
      initial: 'polling',
      states: {
        polling: {
          after: {
            INTERVAL: { actions: send('POLL', { to: 'api' }) }
          }
        }
      }
    },
    success: {}
  }
}, {
  delays: { INTERVAL: 2000 }
});
```

**Comment by aavelyn** [comment]
Thanks for the input!
