### ISSUE TITLE
pass actionMeta to assign action

### ISSUE THREAD

**Issue by geddski** [davidkpiano/xstate#581]
## Bug or feature request?
feature request

## Description:
when using the `assign` action, there's no way to get access to the `actionMeta` data like you can with your own custom actions.

## (Feature) Potential implementation:

```js
actions: assign({
  hints: (context, event, actionMeta) => {
    // use data from actionMeta, e.g. actionMeta.state
    ...
  }
})
```

Currently `context` and `event` are available when using `assign`, but `actionMeta` is not available. It would certainly be handy!

**Comment by davidkpiano** [comment]
What's your specific use-case for wanting to use `state`?

**Comment by geddski** [comment]
specifically, I put hints as metadata on the states like so:

```js
states: {
  open: {
    meta: {
      hint: "The Portal needs to be open."
    }
  }
}
```

and then display that hint when its state was **not** able to be transitioned to (using a guard that checks state values).

Currently I'm just using Object.assign to rewrite the context in my hint-gathering action, but I imagine xstate's `assign` does that and more.

**Comment by Andarist** [comment]
Should meta be available at runtime though? Ive always seen it as purely informational, a thing that can be leveraged by tools, like ie visualizer

**Comment by geddski** [comment]
@Andarist meta is available at runtime for the *current* state. I'm using it in the case when *not* in a specific state. Meta data can be useful for a lot of things.

**Comment by tivac** [comment]
We use meta at runtime constantly, we define our component hierarchy via xstate by using meta.

**Comment by davidkpiano** [comment]
This feature has been implemented.

⚠️ Please keep in mind that using `State.matches(...)`, etc. inside of an assigner is _definitely_ an anti-pattern, and you should always prefer the natural definition of the machine instead. Keep your assigners simple!

**Comment by geddski** [comment]
Noted. Thanks @davidkpiano!

**Comment by geddski** [comment]
@davidkpiano want to make sure I don't miss some of that wisdom - what do you mean by the natural definition of the machine?

**Comment by davidkpiano** [comment]
Basically, developers should avoid getting clever and remain idiomatic. Using `meta.state` should not be a common pattern.

**Comment by geddski** [comment]
gotcha
