### ISSUE TITLE
(hooks) state.changed not resetting between renders

### ISSUE THREAD

**Issue by geddski** [davidkpiano/xstate#611]
## Bug or feature request?
bug

## Description:
when using react hooks, `state.changed` stays set to `true` on every component re-render, causing infinite loops.

## (Bug) Expected result:
`state.changed` should go back to `false` when the component is re-rendered, right?

## (Bug) Potential fix:
somehow reset state.changed when the component is rendered...hmmm

Example of bug:
https://codesandbox.io/embed/confident-volhard-kzc1s

**Comment by davidkpiano** [comment]
Thankfully, this is not an `@xstate/react` issue (although I was worried for a split second).

This is invalid use of effects with hooks. You are calling `setState(...)` (which is an effect) outside of `useEffect`. That will synchronize with every single render, which is _not_ what your intention is.

Try this instead, synchronizing the effect only with `current`:

```diff
  // should only show as changed once, right?
  // but it shows as changed every time, causing infinite renders
- if (current.changed) {
-   // set state, causing a re-render of App
-   setTest("howdy");
- }
+ useEffect(() => {
+   if (current.changed) {
+     setTest("howdy")
+   }
+ }, [current])
```

**Comment by geddski** [comment]
@davidkpiano whew! You're right! Thx
