### ISSUE TITLE
Visualizer does not reset "after" delays visualization on self transitions

### ISSUE THREAD

**Issue by abierbaum** [davidkpiano/xstate#617]
## Bug or feature request?

Possible bug, but likely misunderstanding of usage of 'after' transitions

## Description:

I am trying to model a network heartbeat countdown.  So for example if our client doesn't receive a ping for 10 seconds, then attempt to reconnect to the server.

In the process of implementing this, I am trying to implement the resetting timer within the state machine.  I expected to be able to have a connected state ('running') and then have a substate that is counting down using 'after'.  When the timer expires then transition to a timedout state.  If we get the ping from the server, then reset the timer.

## (Bug) Expected result:

I tried modelling what I thought would work here:  https://xstate.js.org/viz/?gist=a3f87bc8653bbad4ea6c5cde4f9e2eea

```
  const countdown = Machine({
    id: 'count_down',
    initial: 'idle',
    states: {
      idle: {
        on: {
          START: 'running'
        }
      },
      running: {
        initial: 'waiting',
        states: {
          'waiting': {
            after: {
              5000: { target: '#timeout' }
            },
            on: {
              RESET: { 
                internal: false,
                target: 'waiting'
              }
            }
          }
        },
        on: {
          DISCONNECT: 'idle'
        }
      },
      timeout: {
        id: 'timeout',
        on: {
          CLEAR: 'idle'
        }
      }
    }
  });
```

The problem is that when I click to send the RESET event in the visualizer, the counter is not being reset.  I would have expected an external transition to for a restarting of the delay.

## (Bug) Workaround:

I found that I could work around the situation by introducing another state.  At first I thought I could use a transient transition, but that didn't work.  I had to add a delayed transition.  This doesn't seem optimal.  See: https://xstate.js.org/viz/?gist=c3d147ef294f6832582dc70abc5e8a45

```
  const countdown = Machine({
    id: 'count_down',
    initial: 'idle',
    states: {
      idle: {
        on: {
          START: 'running'
        }
      },
      running: {
        initial: 'start_count',
        states: {
          'start_count': {
            /*
            on: {
              '': 'waiting'
            }*/
            after: {
              1: 'waiting'
            }
          },
          'waiting': {
            after: {
              5000: { target: '#timeout' }
            },
            on: {
              RESET: { 
                internal: false,
                target: 'start_count'
              }
            }
          }
        },
        on: {
          DISCONNECT: 'idle'
        }
      },
      timeout: {
        id: 'timeout',
        on: {
          CLEAR: 'idle'
        }
      }
    }
  });
```

Am I missing something here?  Should delays for 'after' reset when transitioning back into the state with a self transition?

**Comment by davidkpiano** [comment]
In your first example, try clicking RESET near the end of that 5-second timer. You'll notice that even though the timeout is done, it will successfully reset and wait another ~5 seconds before transitioning.

So if I'm not mistaken, this isn't a bug with XState, but rather a glitch with the visualizer. Can you confirm this?

**Comment by Andarist** [comment]
I've debugged the first gist a little bit and this indeed seems like a glitch with the visualizer - upon clicking RESET both clearTimeout + setTimeout (for a new timer as we reenter `waiting`) are being called.

**Comment by abierbaum** [comment]
@davidkpiano @Andarist I confirmed what you suggested.  It appears to be an issue with the visualizer.  Feel free to close this issue or keep it open as a bug on the visualizer code.

**Comment by davidkpiano** [comment]
I'll keep it open for the visualizer issue. Can you rename the title, though? Thanks!

**Comment by abierbaum** [comment]
Sounds good.  Looks like there is already a bug over there about this issue: https://github.com/statecharts/xstate-viz/issues/11

**Comment by davidkpiano** [comment]
This is fixed in that repo and will be live when the visualizer is redeployed.
