### ISSUE TITLE
Add documentation about timing of transition execution

### ISSUE THREAD

**Issue by abierbaum** [davidkpiano/xstate#621]
Feature request from discussion with @davidkpiano 

## Description:

There was a gitter discussion starting Aug 13 16:19 about confusion around the order of evaluation related to transitions.  @davidkpiano clarified in summary as:

```
The order is:
  * Do all microsteps (handle raised events, assign actions, transient transitions)
  * Transition to next state
  * Execute actions
Even if that wasn't the order, you should always assume that actions are fire-and-forget and happen asynchronously. They're side-effects, after all
What do your actions look like? If it impacts the condition test, then it sounds like it should be assign(...) (if affecting the context) or raise(...) (if doing something else that might cause a state transition)
The solution is simple but might be a tiny more tedious: ➕ add another intermediate state
```

It was suggested this could be moved into a discussion in the documentation (possibly with the interpreter section) to make it clear to users what to expect.

Adding here at @davidkpiano 's request.

**Comment by lxcid** [comment]
I realise this when I wrote something like

```js
const machineOpts = {
  actions: {
    exitActive: (context, event) => {
      console.log('exitActive');
    },
    enterIdle: assign((context, event) => {
      console.log('enterIdle');
      return context;
    }),
  },
};
```

and the result when transiting from `active` to `idle` flipped because `assign()` is executed first, as shown on the console result.

```
enterIdle
exitActive
```

This doc above helped me.
