### ISSUE TITLE
Visualizer: XState.spawn is not a function

### ISSUE THREAD

**Issue by vuhrmeister** [davidkpiano/xstate#624]
## Description:

When I copy a statechart with some `spawn` call the console logs the following error:

```
XState.spawn is not a function
```

## Expected result:

`XState.spawn` is available and the Visualizer renders the chart properly.

Or does spawning actually does not (yet) work in Visualizer?

## Actual result:

```
XState.spawn is not a function
```

BTW: super awesome tool. But: why can't you expose all available functions directly? In my code my import statement looks like this:

```javascript
import { Machine, assign, sendParent, spawn } from 'xstate'
```

To be able to execute it in the visualizer I always need to prepend certain function calls with `XState.`. Imho that's unnecessary.

**Comment by davidkpiano** [comment]
Can you post a link to the visualization?

**Comment by vuhrmeister** [comment]
Oh … I was on the wrong URL: https://statecharts.github.io/xstate-viz/ (don't ask me how I got on this page). On the official page (https://xstate.js.org/viz/) it works 🥳

I already wondered where the "Login to save" button went …

**Comment by davidkpiano** [comment]
Let me know if there are further links to the old visualizer and I'll update them. Thanks!
