### ISSUE TITLE
TS fails to infer `event` for send actions 

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#632]
Like here - https://github.com/davidkpiano/xstate/blob/b6fcd4da50c4ff40b86d64679b24fbdbe80a02ea/test/actor.test.ts#L70

Ideally it should be inferred correctly, just like it happens for `assign` actions.

**Comment by davidkpiano** [comment]
Not sure when this was fixed, but it's properly inferred now:

<img width="320" alt="Screen Shot 2020-08-08 at 11 04 42 AM" src="https://user-images.githubusercontent.com/1093738/89713640-0790a400-d967-11ea-9345-2aacbc4977d0.png">
