### ISSUE TITLE
Question: log child machine transitions

### ISSUE THREAD

**Issue by andrejohansson** [davidkpiano/xstate#637]
I'm new to this library so sorry if I am asking something obvious here. 

This is what I want to do:

- I want to attach a simple log function to my state transitions. So that I can follow what is happens.
- I know there is a way to do this nicely when you interpret and launch your state machine this way:
```js
const promiseService = interpret(promiseMachine).onTransition(state =>
  console.log(state.value)
);
```

But I have two complications:

1. Using react hooks:
```js
const [current, send] = useMachine(parentMachine);
```
I can just log ``current`` using  ``console.log(current);`` and I will see the state transitions. Is this correct?

2. How do I attach ``onTransition`` to child machines using invoke?
Here I have a parent machine that is invoked using react hooks. The parent machine in turn invokes child machines. How can I attach a state transition logger in the best way so that I can follow the full flow (both parent machine transitions and child machine transitions)?

```js
configuring: {
      invoke: {
        id: 'childMachine1',
        src: childMachine,
        onDone: 'render'
      }
    },
```

I explicitly do __not__ want to attach "console log" actions to each state. I just want to follow the state transitions in one place globally for a hierarchical set tree of machines.

**Comment by andrejohansson** [comment]
For now: learning and logging yes. I am build a ui which I think will end up with a handful of machines. 

- one root machine
- one machine that handles initial setup (child of root)
- one machine that handles connectivity (connected, retry, error, disconnect). I guess this is parallel somehow
- one machine that handles rendering of the ui after inital setup is done (so this will be running as a child to root, in parallel with the connectivity machine I think).

So, in order to follow everything that is happening, I need some tool (console.log) to keep my sanity.

I might be going about this completely wrong though...so any hints/suggestions are welcome.

**Comment by davidkpiano** [comment]
The `service` created in `useMachine(machine)` can be referenced as the third returned value:

```js
//                  vvvvvvv
const [state, send, service] = useMachine(someMachine);
```

You can subscribe to that service's state changes with the [`useEFfect` hook](https://reactjs.org/docs/hooks-effect.html):

```js
// ...

useEffect(() => {
  const subscription = service.subscribe(state => {
    console.log(state);
