### ISSUE TITLE
getShortestPaths & getAdjacencyMap inference failing 

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#652]
Not sure why - maybe because of recent TS upgrade (?), but few things in tests don't compile because they have trouble with proper type inference. 

Mainly `TEvent` can't be inferred from concrete StateNode/StateMachine used in argument position.

Here:
https://github.com/davidkpiano/xstate/blob/9bdfe6d496ba81ef2ec0c17502fe9355565aaeee/packages/xstate-graph/test/graph.test.ts#L305

And here:
https://github.com/davidkpiano/xstate/blob/9bdfe6d496ba81ef2ec0c17502fe9355565aaeee/packages/xstate-graph/test/graph.test.ts#L171

**Comment by davidkpiano** [comment]
Closing as stale - type inference is correct and tests are passing 😄
