### ISSUE TITLE
Split StateMachine & StateNode

### ISSUE THREAD

**Issue by Andarist** [davidkpiano/xstate#655]
Just a place for discussing this potential but rly low priority refactor.

It's confusing at times that StateNode is also a StateMachine and I've started to believe that splitting those could result in slightly easier to follow code.

Many of the methods/properties of the StateNode seems to be exclusive for StateMachine, i.e. public `.transition` doesn't make much sense on a nested StateNode. And also vice-versa there are probably things needed only for "private" StateNode which wouldn't have to be kept on StateMachine.

Thoughts?

**Comment by davidkpiano** [comment]
Definitely want to do this. Just to outline the hierarchy:

Base class: `StateNode` (would be much smaller than the current `StateNode`

- `StateMachine` extends `StateNode`
- `AtomicStateNode` extends `StateNode`
- `CompoundStateNode` extends `StateNode`
- `OrthogonalStateNode` extends `StateNode`
- `HistoryStateNode` extends `StateNode`

How's that?

**Comment by Andarist** [comment]
Might be beneficial as well. My main concern is about StateMachine being combined with StateNode though - had no reasoning issues while reading/developing about different node types being the same class.

**Comment by davidkpiano** [comment]
Okay, that can be a good first step - having `StateMachine` extend `StateNode`.
