### ISSUE TITLE
how to get the list of transitions out of the current state. (out edges)

### ISSUE THREAD

**Issue by nmorse** [davidkpiano/xstate#663]
I would like to query the statechart graph for a list of transitions (out-edges) from the current state. Is this possible now or could it be a requested feature?

A use case is to enable/disable UI controls, so that a user is only offered buttons (controls) that can produce signals capable of transitioning from the current state.

**Comment by davidkpiano** [comment]
Great question - you can currently query `state.nextEvents` and see which events _might_ cause transitions from that state. Of course, guards play a role in determining whether the transition will actually take place.

You can also call `machine.transition(currentState, nextEvent)` and query whether that causes a state transition via the `state.changed` boolean.

**Comment by nmorse** [comment]
that works, thanks.

**Comment by Andarist** [comment]
As the question has been answered I'm closing this issue. If you have any more questions please create a new one.
