### ISSUE TITLE
How can i `invoke` promise within an event

### ISSUE THREAD

**Issue by Sunil6591** [davidkpiano/xstate#667]
## feature request?
Need to `invoke` a promise for a particular event
## Description:
E.g. 
```
...
loading: {
        on: {
          RESOLVE: {
            invoke: {
              src: somePromise,
              onDone: 'success'
            }
          },
          REJECT: 'failure'
        },
      },
...
```
Here is https://xstate.js.org/viz/?gist=7ce411c7e7bccf6df1474ce2b52bf968
I am aware of actions, but those are fire-n-forget, i wud like to have the promise resolved and then it moves to target state. So in above e,g, After firing `RESOLVE` event, I expect the machine to fire my `invoke` promise and after it resolves it shud move to targeted state.

**Comment by Andarist** [comment]
U have to split this into two states - make idle state which listens to RESOLVE, on RESOLVE move to loading which has invoke definition in it (directly on the loading state)

**Comment by Sunil6591** [comment]
Thanks for quick response!
