### ISSUE TITLE
React Flickr Gallery App Example Diagram: No path to SEARCH_SUCCESS

### ISSUE THREAD

**Issue by maniart** [davidkpiano/xstate#67]
## Bug or feature request?
Bug

## Description:
In the React Flickr Gallery App Example diagram, `SEARCH_FAILURE` and `CANCEL_SEARCH` actions are captured but `SEARCH_SUCCESS` is not.

## (Bug) Expected result:
`loading` state should transition to `gallery` state via `SEARCH_SUCCESS` action

## (Bug) Actual result:
`loading` state transitions to `gallery` state only via `CANCEL_SEARCH` action

## (Bug) Potential fix:
Re-draw the diagram, including the `SEARCH_SUCCESS` action.

**Comment by maniart** [comment]
I might be missing something here, as I'm new to this library. If so, apologies.
And thank you for this fantastic work. Very valuable.

**Comment by davidkpiano** [comment]
Seems to be captured here and working: 

```
      on: {
        SEARCH_SUCCESS: {
          gallery: {
            actions: ['updateItems']
          }
        },
```

Unless you mean in the actual diagram? Yeah, that's a mistake - it should have SEARCH_SUCCESS in there as well. The new version of the visualizer will remedy that.

**Comment by davidkpiano** [comment]
Remedied if you put it in bit.ly/xstate-viz
