### ISSUE TITLE
4.7.0 Actor/Service Feedback

### ISSUE THREAD

**Issue by derek-duncan** [davidkpiano/xstate#672]
## Bug or feature request?
Bug

## Description:
I've been playing more with xstate@next. It seems that both conceptually and in Typescript, the Actor/Service (Interpreter) distinctions are a little blurred, so I'm trying to understand when to use either. My primary question is what are the different purposes for Actors and Services/Interpreters?

Here are some more specific notes for `v4.7.0-rc3`:

It looks like `invoke` creates an Actor behind the scenes. Accessing it through `current.children.invokeId`, you get an Actor back. Accessing it through `service.children.get(invokeId)`, you get an Interpreter. Shouldn’t `invoke` always generate services/interpreters and not an actor? If invoking a “service” is really just an Actor behind the scenes, it’s be nice to always return an Actor so you consistently know what to expect from your `current.children`, `service.children` and `spawn`.

`spawn` also returns an Interpreter type in TS, but it looks like the actual object is an Actor. Why should `spawn` ever return an Interpreter if it’s an utility for spawning actors? Looks like the TS changed in #664

Also, a minor TS bug for `spawn`. It doesn’t accept a machine with custom event types since they clash with the generic EventObject.
```
spawn(new Machine<Ctx, Evt>())
// Type 'EventObject' is not assignable to type ‘Evt’
```

Finally, most of these concepts trickle out as confusing when you start to use the `useService` and `useActor` hooks. It seems that Actors are more locked down in state access, but it’s unclear as to why? It’s much easier to just use a `useService`, but as already noted, most of the Actors coming out of `current.children` and `spawn` aren’t accepted in `useService`. It’s unclear when comparing services to actors on why you’d ever want an Actor vs an Interpreter, or vice versa.

## (Bug) Potential fix:

I need more understanding of the conceptual model to propose a fix, but I'd be more than happy to after I understand distinctions between Actors and Services.

**Comment by coodoo** [comment]
I had those doubts earlier and after a quick digging up I came up with these notes, hope that helps.

- Main difference between `services` and `actors` - `services` need to be statically written in the machine definition to be `invoked`, whereas actors can be dynamically `spawned` by any action, multiple times (if you so wish).

- actors could spawn `sub-actors` and communicate with it's `parent` or other actors via event sending

- In short, `actors` are like `services` on steroid, allowing developers to more flexibly model complex application logics with multi-level of machine hierarchy interacting with each other.

- One of the biggest wins of having actors is now there's finally a way to totally encapsulate business logic within the `statechart` itself, without needing a ui layer (like react) to help gluing them.

- Another big win is with `useService` in place, it's super easy to make ui component and actors working together, hence making `one-machine-each-component` a reality, this will come in handy for large application.

Lastly, `actor` is just a pattern for making multiple `elements` working with each other nicely in a system, in this case those `elements` happened be one of { Promise | Callbacks | Observables | Machine },  yes, they are exactly the `services` already existing today, hence one could think `actor` is just a more flexible way of running `services`.

**Comment by derek-duncan** [comment]
Thanks @coodoo, that helps!

My feedback now is that when using xstate, it would be helpful to have spawned/invoked elements either always be an `Interpreter` or an `Actor`. e.g. the `spawn` helper sometimes returns an interpreter, but other times an actor; using invoke is always an interpreter; accessing these thorough `service.children` or `current.children` return different types.

Would it make sense to have both `invoke` and `spawn` refs always produce an `Actor`? I think that would be simpler to understand, especially so you don't have a `Actor | Interpreter` in `.children` you must guard against each time you access.

**Comment by Andarist** [comment]
It wouldn't allow you to unpack a "nested" spawned machine with eg `useService` hook and use that to match against its state etc which seems really useful. I agree though that the current situations is somewhat confusing, so maybe we'll discuss alternatives in the future - it will have to wait until next major version though.

**Comment by derek-duncan** [comment]
I haven't tried it yet, but doesn't `{ sync: true }` to `spawn` allow you to read state? Maybe `invoke`'d actors get `{ sync: true }` by default and other `spawn`'d actors are opt-in.

This way it'd be simple for the `useService` hook to merge with `useActor` and only provide `current` state when sync is available.

**Comment by Andarist** [comment]
`Sync` is just a convenience helper - explicit data passing is much more preferred in general. It also only works with machines, so you end up with a similar problem of not being able to differentiate machine actors and different type of actors - just at a different place.

**Comment by davidkpiano** [comment]
Marking this for documentation, as it is better resolved there. 

In V5, there will be no distinction between services/actors, so the implementation and usage will be much simpler. This also means that `{ sync: true }` will be better replaced with more intuitive, explicit patterns.
