### ISSUE TITLE
External self transitions are not being dispatched correctly for parallel states

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#673]
**Expected Result**

In the reproduction sandbox, "input updating..." should be printed twice.

**Actual Result**

"input updating..." is printing only once.

**Reproduction**

https://codesandbox.io/s/xstate-example-template-7xfg0

**Additional context**

Sandbox XState version: 4.6.7

The bug was introduced in `v4.6.0`. In `v4.5.0` "input updating..." is printed twice.

**Comment by davidkpiano** [comment]
This is expected and documented: https://xstate.js.org/docs/guides/transitions.html#internal-transitions

Always prefer being explicit if you want specific yet non-obvious (re-entry, in this case) behavior to occur.

> Summary of internal transitions:
> 
> - EVENT: '.foo' - internal transition to child
> - EVENT: { target: '.foo' } - internal transition to child (starts with '.')
> - **EVENT: { target: 'same.foo', internal: true } - explicit internal transition to child
>   This would otherwise be an external transition**
> - EVENT: undefined - forbidden transition
> - EVENT: { actions: [ ... ] } - internal self-transition
> - EVENT: { actions: [ ... ], internal: true } - internal self-transition, same as above
> - EVENT: { target: undefined, actions: [ ... ] } - internal self-transition, same as above

**Comment by Andarist** [comment]
Thanks for the report - gonna look into fixing this over this weekend.

**Comment by Andarist** [comment]
This is broken in 4.6.7 but fixed at least since 4.7.0-rc2. So this is not actionable right now unless we'd like to backport a fix to 4.6.x line. 

There are also some other fixes in 4.7, would be great to release it sometime soon as stable. What are the current blockers @davidkpiano ?

**Comment by davidkpiano** [comment]
@Andarist No current blockers. Just wanted to make sure it's stable since the core has changed quite a bit.

**Comment by Andarist** [comment]
Anything I could help with?

**Comment by hnordt** [comment]
I confirm it was fixed in `v4.7.0-rc3`. I wasn't able to use `v4.7.0-rc3` yet because it's breaking some machines that were used to work in `v4.6.0`.

**Comment by davidkpiano** [comment]
@hnordt Can you share those machines and report the bugs, if any?

**Comment by hnordt** [comment]
@davidkpiano I'll try to open the bug report on Monday, this weekend I need to finish a project milestone. 😅
