### ISSUE TITLE
[Doc] Is it `autoForward` or `forward` for invoked property?

### ISSUE THREAD

**Issue by coodoo** [davidkpiano/xstate#680]
Going through the docs right now and seemed `forward` had been renamed `autoForward` [as seen here](https://github.com/davidkpiano/xstate/blame/master/docs/guides/communication.md#L32), but later in the same doc the examples [were still using `forward: true`](https://github.com/davidkpiano/xstate/blame/master/docs/guides/communication.md#L683-L684), not sure if these are just leftovers not yet revised or by design?

**Comment by Andarist** [comment]
Seems like leftovers, `autoForward` is preferred (same as in SCXML) - but for the time being both works (`forward` being deprecated though).
