### ISSUE TITLE
Assign in typescript 

### ISSUE THREAD

**Issue by edgarjrg** [davidkpiano/xstate#681]
**Description**
Assign does not behaves as expected in typescript, it I assign the `Event` type to `assign` it becomes unassignable to the `machine`

**Expected Result**
Be able to type
```ts
const machine = Machine<Context, Schema, Event>({
  id: "machine",
  initial: "inactive",
  context: {
    count: 0
  },
  states: {
    inactive: {
      on: {
        TOGGLE: [
          {
            target: "active",
            actions: [
              assign<Context, Event>({
                //            ^ this is not possible
                count: (ctx, e) =>
                  e.type === "TOGGLE" ? ctx.count + 1 : ctx.count
              })
            ]
          }
        ]
      }
    },
    active: {
      on: {
        TOGGLE: [
          {
            target: "inactive"
          }
        ]
      }
    }
  }
});
```

**Actual Result**
`Type 'AssignAction<Context, Event>' is not assignable to type 'string'.`

**Reproduction**
https://codesandbox.io/s/xstate-typescript-error-with-assign-v18b4

**Additional context**
`"strict": true`
`xstate@4.6.7`

**Comment by davidkpiano** [comment]
What happens if you try this with `xstate@next`?

**Comment by edgarjrg** [comment]
could this be re-opened please 🙏 ?

I tried with `typescript@3.6.2` and `3.6.3` but nothing changed. It works ok without `strict`

**Comment by edgarjrg** [comment]
it works as expected with `xstate@4.7.0-rc3`
