### ISSUE TITLE
visualizer crashes on dynamic send actions

### ISSUE THREAD

**Issue by mikaelkaron** [davidkpiano/xstate#683]
**Description**

Visualizer crashes with [send action example from docs](https://xstate.js.org/docs/guides/actions.html#send-action):

```
// contrived example - reads from the `context` and sends
// the dynamically created event
const sendName = send((context, event) => ({
  type: 'NAME',
  name: context.user.name
}));

const machine = Machine({
  initial: 'initial',
  states: {
    initial: {}
  },
  // ...
  on: {
    TOGGLE: {
      actions: sendName
    }
  }
  //...
});
```

**Expected Result**

Visualizer to render dynamic `send` actions without `type` indicator in the UI and otherwise work as non-dynamic `send` actions.

**Actual Result**

White screen of death.

**Reproduction**

I've created [an example that illustrates the bug](https://xstate.js.org/viz/?gist=f747f04d0bd68338c437ac34c559e0e3) where you can change the `saveName*` to trigger the bug.

**Additional context**

**Comment by Andarist** [comment]
Special support of this has to be introduced here:
https://github.com/statecharts/xstate-viz/blob/c52424b79daa101e795925d452b68c668536f8fa/src/StateChartAction.tsx#L94

Shouldn't be that hard to handle this. Maybe you'd like to help with this? For starters, we'd have to render just some fallback values (function names or smth)

**Comment by chenxsan** [comment]
@Andarist Seems it's already fixed by https://github.com/statecharts/xstate-viz/commit/f476d17b30f84253de88c61cb80ca788bce51a52, but the fix is not pushed to production.

**Comment by davidkpiano** [comment]
Closing this in favor of using [the inspector](https://xstate.js.org/docs/packages/xstate-inspect) instead.
