### ISSUE TITLE
Child states without an "id" property and "#" prefix cannot be transitioned to across statechart boundaries

### ISSUE THREAD

**Issue by furiousOyster** [davidkpiano/xstate#685]
**Description**
The visualizer disallows transitioning to a non sibling state unless the following conditions are true:
1. The target has an "id" property
1. The target is prefixed with a "#" sign
This is not made clear in the error message from the visualizer, and appears nowhere in the otherwise very helpful 'gotchas' parts of the documentation.

**Expected Result**
I should be able to target any state across other statecharts regardless of whether they have an id property because the key name is the id, and the need for "#" should either be explained or removed.

**Actual Result**
When missing "#" prefix, the visualizer reports an error of: "Invalid transition for state node 'api' on event 'something':
Child state 'lib' does not exist on 'root'"

**Reproduction**
In this example: https://xstate.js.org/viz/?gist=fae5c024ce47204b425403416f451a90 simply add a "#" prefix to the first instance of the word "lib"

**Comment by davidkpiano** [comment]
In the docs, it gives clear examples that the default ID is its full path: https://xstate.js.org/docs/guides/ids.html

So `'lib'` wouldn't be the ID, it would be `'root.lib'`
