### ISSUE TITLE
Invoke Serially 

### ISSUE THREAD

**Issue by edgarjrg** [davidkpiano/xstate#688]
## Bug or feature request?
Feature Request
## Description:
I would like to have an option to run invokes serially, i've open a [stackoverflow question about it](https://stackoverflow.com/questions/57878908/xstate-chaining-multiple-promises-without-intermediary-states?noredirect=1#comment102755484_57936291)

## (Feature) Potential implementation:

- What the API would look like
```ts
// ...
invokeEach: [
  { id: 'service1', src: 'someService' },
  { id: 'service2', src: 'someService' },
  { id: 'logService', src: 'logService' }
],
// ...
```
`service1` would run first, and `service2` second, they do not need to share any data between steps, or could, like [Invoking Promises](https://xstate.js.org/docs/guides/communication.html#invoking-promises) 
> The resolved data is placed into a 'done.invoke.<id>' event, under the data property, e.g.:

- If this is a breaking change
Not, it should be separate from `invoke`

- If this is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)
Not sure

**Comment by Andarist** [comment]
U can build this yourself - without overcomplicating core APIs. https://codesandbox.io/s/brave-hopper-sxh2b 

Just remember about adding error handling 😉

**Comment by edgarjrg** [comment]
@Andarist Thank you for the example implementation 🙏 . 

Such *state factory* (as coined in [this comment](https://github.com/davidkpiano/xstate/issues/703#issuecomment-538918700) could be a nice pattern to have in another library, is there such utility library somewhere?

**Comment by Andarist** [comment]
> Either way, I guess my question goes more for "could this pattern be introduced into the lib according to philosophy or it's not and should be outside",

Not sure, we focus on the core APIs right now - I think helpers can be introduced, but it would require some more thought and designing. For now, I would be more in favor of creating a dedicated docs page describing that you can do stuff like this - if one wants to maintain library for such helpers then that's cool too.

> what its done its create with less handwriting intermediary states, but no invoke serially, is invoke serially a bad pattern for state charts?.

Not sure if I understand. The given example executes invokes serially - just to make this happen it puts each invoke on separate substate. And that's totally fine (answering your latter question) - if you need to make a series of waterfall requests then this is exactly what you need (or what is often good enough).

**Comment by davidkpiano** [comment]
XState is meant as a low-level library. Since it's all plain JS object syntax, you can easily build your own abstractions on top of it (as many have done).

**Comment by edgarjrg** [comment]
> just to make this happen it puts each invoke on separate substate

I guess this is the more appropriate approach, thank you for clarifying

> XState is meant as a low-level library. Since it's all plain JS object syntax, you can easily build your own abstractions on top of it (as many have done).

Thank you the answer 👏
