### ISSUE TITLE
matchesState returns true when unexpected

### ISSUE THREAD

**Issue by lmatteis** [davidkpiano/xstate#69]
Is it the intended behavior that `matchesState` returns true for this case?

```
matchesState('Main.Foo.Review.Publishing', 'Main.Foo.Review')
```

I would expect not or am I missing something?

**Comment by 0m15** [comment]
Yes, it's expected behavior:

https://github.com/davidkpiano/xstate/blob/972904c70b1b828c29c6d8cb5b187b5b894e0478/test/matchesState.test.ts#L34

**Comment by 0m15** [comment]
Test is marked as pending

https://github.com/davidkpiano/xstate/blob/972904c70b1b828c29c6d8cb5b187b5b894e0478/test/matchesState.test.ts#L63
