### ISSUE TITLE
[FeatureRequest] onTransition that get's every transition change

### ISSUE THREAD

**Issue by aughey** [davidkpiano/xstate#692]
**Description**
By design, onTransition is called only for the end state after all events are processed.  For a visualizer, it it useful to know what states it may have transitioned through on the way to its final state.  

**Expected Result**
Currently works as expected, would like a way to get all intermediate state transitions.

**Actual Result**
onEveryTransition

**Comment by Andarist** [comment]
Basically in the future, it should be the default behavior of the `onTransition` - as each intermediate transition is a transition, so skipping some seems counter-intuitive. 

For that to happen we would have to refactor quite a bit and make it a breaking change - so this is not a quick fix. Similarly adding a second hook like `onEveryTransition` for temporary backward compatibility is not that easy - those intermediate transitions happen inside pure Machine API, while Interpreter is responsible for handling callbacks.

What maybe could be explored right now is:
- adding smth like `.microstep` API to Machine
- rebuilding internals to actually handle `.transition` through series of `.microstep` calls
- use `.microstep` in the Interpreter

As mentioned - this is somewhat a big effort right now, maybe you would like to engage more with it and help us to achieve this goal?

**Comment by davidkpiano** [comment]
How about:

```js
// every microstep (intermediate transition)
service.onMicrostep(state => { ... });

// every macrostep transition (behavior unchanged)
service.onTransition(state => { ... });
```

And more manual control (these are not necessary):

```js
// queue an event
service.queue(event);

// dequeue an event and follow through (macrostep)
service.step();

// dequeue an event and follow through (microstep)
service.microstep();
```

No breaking changes necessary.

**Comment by Andarist** [comment]
Still - Machine internals have to be refactored quite a bit to support this as currently .transition is pure and “flattens” microsteps, so it’s currently not easy to hook into microstep processing to fire a callback
