### ISSUE TITLE
@xstate/test test plan strategy

### ISSUE THREAD

**Issue by Yuyz0112** [davidkpiano/xstate#694]
## Bug or feature request?
Maybe a feature.

## Description:
I've just started to try the @xstate/test package and wondering whether to generated test plans cover all things(or is that the intended strategy)?

For example, a simple machine:

```js
const machine = Machine({
  initial: "close",
  states: {
    close: {
      on: {
        FOCUS: "open"
      }
    },
    open: {
      on: {
        ENTER: "close",
        BLUR: "close"
      }
    }
  }
});
```

And then get test plans by setting the initial state to 'close' and 'open'.

## (Bug) Expected result:
I would expect the test plans contain the following test plans which cover all the paths and states, no matter the initial state is 'open' or 'close'.

```
close -> open via FOCUS
open -> close via ENTER
open -> close via BLUR
```

## (Bug) Actual result:
Actually, with an initial state 'close' I got:

```
-> close, via
close -> open, via FOCUS
```

and with an initial state 'open' I got:

```
-> open, via
open -> close, via ENTER
open -> close, via BLUR
```

## (Bug) Potential fix:

Before digging into the source code, I would like to know whether these are the intended result. If so, shall we implement some other test plan strategy to generate the paths I expect?

## (Feature) Potential implementation:

Same here.

**Comment by davidkpiano** [comment]
These are the intended results currently, as the tests focus on state coverage. I'll add a feature that focuses on transition coverage (not sure what this will look like yet).

Here is a workaround:

```js
const machine = Machine({
  initial: "close",
  context: { wasClosed: false },
  states: {
    close: {
      on: {
        FOCUS: "open"
      },
      exit: assign({ wasClosed: true })
    },
    open: {
      on: {
        ENTER: "close",
        BLUR: "close"
      }
    }
  }
});
```

**Comment by Yuyz0112** [comment]
Thanks for the feedback.
In my experience with states chart, transition coverage need more configurable strategy to avoid explosion.

Anyway, the test package is really useful and I started to using it in some complex UI component.

**Comment by cawabunga** [comment]
Hey, I'm new for the library, is there a solution (not a workaround above) for this issue?

**Comment by davidkpiano** [comment]
> Hey, I'm new for the library, is there a solution (not a workaround above) for this issue?

Yes, or at least soon - in the latest `@xstate/test@alpha`, state traversal is based on the state and previous event, by default, so the main issue is mitigated.
