### ISSUE TITLE
Support `devTools` on spawned machines

### ISSUE THREAD

**Issue by cogell** [davidkpiano/xstate#698]
**Description**
Enhance spawned machines to support `devTools: true`.

**Expected Result**
Allow spawned machines to log into redux dev tools.

**Actual Result**
NA as this is a request for enhancement

**Comment by tivac** [comment]
Spawned machines do log to the redux dev tools? There's a dropdown in the top-right that lets you choose the machine to inspect, all of our child machines are correctly listed there.

**Comment by cogell** [comment]
Oh nice! I see. I was just trying to turn on the `spawn`ed machine by itself. I can turn the top of the hierarchy on and get the spawned machine in redux dev tools 👌🏻
