### ISSUE TITLE
Babel plugin to avoid shipping the parser

### ISSUE THREAD

**Issue by gaearon** [davidkpiano/xstate#7]
As I understand the library currently includes a parser. What do you think about having a Babel plugin that precompiles state machine and replaces an import with the version that doesn’t ship a parser?

cc @threepointone

**Comment by davidkpiano** [comment]
Hey @gaearon I actually just updated the readme - the parser was based on a very old version of this library. Version 1 no longer requires parsing! I'll have examples up shortly.
