### ISSUE TITLE
Implement a proximity algorithm to use when finding a state

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#70]
## Feature request

Authoring statecharts is difficult enough without having to worry about unique names for each individual state.  Refactoring operations such as moving states to a substate becomes harder when predicates and link targets have to specify relative states.

Being able to use "the closest state with this name" in terms of hierarchy would make it easier to author statecharts, and would make re-use of statechart fragments (e.g. an on-off switch) easier.  It would also make visualizations more pleasing to the eye when `in` predicates can state the name of the state rather than a path relative to the starting state.

The proximity algorithm would prefer states in this order:
- siblings (as today's algorithm)
- children of any sibling (error if more than one match — ambiguous)
- grandchildren of any sibling (error if ambiguous) etc until no more child states exist
- parent state's siblings
- parent state's siblings children, grandchildren, etc.
- grandparent's state's siblings, then their children etc.

## Description:

A "smart" way of determining target state names from a context state, in order to resolve `in` predicates and `on` state targets, and possibly other uses of state names.

```
initial: A
states: {
  A: {
    states:
      one: {}
      two: {}
      three: {}
    }
  }
  B: {
    states: {
      one: {}
      two: {}
    }
    on: {
      a: "A.one" // unambiguous, resolves to A.one
      b: "one" // unambiguous, resolves to B.one
      b: "three" // unambiguous, resolves to A.three
    }
  }
  C: {
    on: {
      a: "A.one" // unambiguous
      b: "one" // ambiguous, would throw an error,
               // could resolve to either A.one or B.one, both are just "as close".
      c: "three" // unambiguous, resolves to B.three
      d: "two" // unambiguous, resolves to C.A.two
      e: "A.two" // unambiguous, resolves to C.A.two
      f: "A" // unambiguous, resolves to A (top level)
      g: "C.A" // unambiguous, resolves to C.A
    }
    states: {
      A {
        states: {
          two: {}
        }
      }
    }
  }
}
```

The contrived statechart above has one bug, an ambiguity: When in C, event `b` transitions to `one` but it is not defined in any substates, and two of C's siblings both have a `one` link. Creating a statechart with this would throw an error. The other states would be unambiguous, as described in the comments.

## Potential implementation:

I've done a spike implementation where the last line of the constructor of the StateNode checks if `parent` is defined, and if it isn't it assumes that it's the construction of a fully-fledged state machine.  It then proceeds to loop through the `this.state` recursively and "washes" the `this.on`, rewriting the target state of events to use a "proximity algorithm".

I haven't implemented this algorithm fully, but since the states already have a full "id", it shouldn't be hard replacing target states with fully qualified state IDs.

The algorithm would go something like this, for each target state in `in` or `on`.

0. Ignore state names that start with `^` or `#` or `.` as they have special meaning.
1. split the name up by STATE_DELIMITER (".")
2. Look for the current state's siblings to see if any of them match the first part of the target state name.  If any of them match, check if any of them have the remaining "path" of the state. If so this is a closest match.  Return the full state ID of the found state.  This is `matchesState`, I believe.
3. repeat step 2, but using the current state's direct children instead of siblings.  If this produces more than one positive match, throw an error, since the state name is ambiguous.  If exactly one positive match, return the full state ID of the found state, otherwise continue.
4. Repeat step 3 but for the state's grandchildren, checking all grandchildren in one go, and throwing an error if there is more than one match.
5. Repeat step 4 continuously deeper until there are no more generations of children.
6. Repeat steps 2 through 5, but starging at the state's _parent_ (check the parent state's siblings, then the parent state's children, etc).
7. Continue step 6 going up the "chain" of parents until a match is found or an ambiguity is detected, or there are no parents.
8. If you got here, then no states in the whole statechart match the target state, throw an error.

The resolution for history states, and initial states could use a subset of the algorithm that only looks at substates (since history and initial states cannot reference states outside their parent.

There are probably more efficient ways of doing this, e.g. by making lists of context + target IDs, sorting and filtering them in smart ways.  The algorithm is mainly intended to describe the required behaviour.

This *might* be a breaking change, but the implementation of the proximity algorithm would / should first check if there is a direct match with the current state's siblings, and since this is the most relevant match, it would not be a breaking change.  `.foo` (child) and `^foo` (uncle/aunt?)  syntax would remain unchanged, but there would be less need for them with the proximity algorithm in place.

This is not part of SCXML, being inspired from Harel's original drawings with `in` clauses only specifying a prefix when needed.

Will provide the spike implementation in my fork if needed, but I'd have to implement the algorithm for it to be meaningful.

## Downside

The only big downside is the additional overhead of other tools related to the xstate JSON file format itself; if this is adopted, it would require some tools (such as visualization tools) to implement the same algorithm in order to resolve state names in the same manner as xstate.  Other tools (such as debuggers) could simply piggyback on the xstate library itself to perform the disambiguation.  Thus it's useful for xstate to be able to provide the original label used when resolving state names, even though it's internally rewired to use full paths (or even direct object references to StateNode instances).

**Comment by davidkpiano** [comment]
Let's shelve this for now (since we support IDs which provide a stopgap for these use cases) and revisit it if we need to.
