### ISSUE TITLE
Sourcemaps point to non-existent source files

### ISSUE THREAD

**Issue by qtiki** [davidkpiano/xstate#707]
**Description**

The sourcemaps in `lib` and `es` directories point to source files that are not included in the npm package.

**Expected Result**

Using webpack with sourcemaploader should be able to import the sourcemaps.

**Actual Result**

Using webpack with sourcemaploader will throw a bunch of warnings like this:

```
WARNING in ./node_modules/xstate/es/Actor.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/Actor.ts': Error: Can't resolve '../src/Actor.ts' in 'xxx\node_modules\xstate\es'
 @ ./node_modules/xstate/es/interpreter.js 53:0-34 135:51-58
 @ ./node_modules/xstate/es/index.js
```

**Reproduction**

Setup a webpack project using typescript and sourcemaploader, then try to import xstate.

**Additional context**

`xstate@4.6.7`

**Suggested fixes**

I believe there are three possible fixes for this:

A) Include the source files in the npm package
B) Build the sourcemaps as standalone so that they include the whole source
C) Remove the sourcemaps

I'm not sure which one is the preferred one for you. In my mind option B is the best if you want to keep the package clean and have the sourcemaps "just work".

**Comment by davidkpiano** [comment]
Would be happy to accept a pull request for this 🙏 

cc. @Andarist

**Comment by Andarist** [comment]
I can easily prepare a PR - but not sure whats the expected result here. Most libraries dont ship sourcemaps - so maybe we should just ignore them?
