### ISSUE TITLE
Documentation - Broken link to more info about send

### ISSUE THREAD

**Issue by edgarjrg** [davidkpiano/xstate#710]
## Bug or feature request?
Bug
## Description:
Broken link in [documentation](https://xstate.js.org/docs/guides/communication.html#invoking-machines)

>The send(...) and sendParent(...) action creators do not imperatively send events to machines. They are pure functions that return an action object describing what is to be sent, e.g., { type: 'xstate.send', event: ... }. An interpreter will read these objects and then send them.

>[Read more about send](https://xstate.js.org/docs/docs/guides/actions.html#built-in-actions) <-- broken
## (Bug) Expected result:
Link to take me more info about `send`
## (Bug) Actual result:
404

**Comment by hcz** [comment]
@davidkpiano Looks like this was fixed but was not deployed in #568
