### ISSUE TITLE
Transient transition infinite loops when a default condition has no target

### ISSUE THREAD

**Issue by Ryan-McMillan** [davidkpiano/xstate#721]
When trying to check a condition upon entering a state and raise an action if the condition fails it infinite loops in the condition function.

Repro: Paste this into the visualizer https://xstate.js.org/viz/ and run the NEXT action with a balance <= 300 in the context.
```
  // Available variables:
  // - Machine
  // - interpret
  // - assign
  // - send
  // - sendParent
  // - spawn
  // - raise
  // - actions
  // - XState (all XState exports)
  
  const fetchMachine = Machine({
    initial: 'one',
    context: {
      balance: 0
    },
    states: {
      one: {
        on: {
          NEXT : 'two'
        }
      },
      two: {
        on: {
          "" : [
            {
              cond : ({ balance }) => {
                console.log("infinite loop")
                return balance > 300;
              },
              target : "success"
            },
            
            { actions : raise("INSUFFICIENTFUNDS") }
          ],
          INSUFFICIENTFUNDS : "bankrupt",
          SUCCESS           : "success"
        }
      },
      success: {
        type: 'final'
      },
      bankrupt: {
        type: 'final'
      }
    }
  });
  ```

I'd expect this to raise the INSUFFICIENTFUNDS action and transition to bankrupt.

**Comment by davidkpiano** [comment]
This is working as expected because:

1. all transitions are _external_ by default unless otherwise specified (`internal: true`)
2. transient transitions are always taken first.

Try adding `internal: true` to get the behavior you want... or you can transition directly to `'bankrupt'`.

**Comment by tivac** [comment]
In the real code it requires an id to jump to the target state, so raising an event would be way cleaner. I don't understand why the transient transition raising an event causes an infinite loop just yet. Is it possible for you to explain it in a slightly different way?

I tried adding some `internal : true` flags to the events, but I'm still getting an infinite loop.

https://xstate.js.org/viz/?gist=758f2c8511ac4b7849c708364698bbbe

**Comment by Andarist** [comment]
According to the `mainEventLoop` algorithm - https://www.w3.org/TR/scxml/#mainEventLoop - there is no difference in this for external/internal transitions. Basically `selectEventlessTransitions` happens after every `microtask` where `microtask` is a processing of an event (both from external queue and internal queue, it doesn't matter).

The solution here is not to use events in eventless transitions to jump to other states - just use target, like this:
https://codesandbox.io/s/great-cartwright-5fhwq

**Comment by tivac** [comment]
Hmm, that's unexpected.

That fact is probably worth calling out in the xstate docs around transient transitions since I don't think it's very likely that folks have read the SCXML spec.

**Comment by Andarist** [comment]
Do you have in mind which place could use a clarification around this?

**Comment by tivac** [comment]
Yes, see #727
