### ISSUE TITLE
State's onDone transition not executed after invokes finish

### ISSUE THREAD

**Issue by qtiki** [davidkpiano/xstate#724]
**Description**

State's onDone transition is not executed after the invokes finish. The onDone transition works for individual invokes but not for the state itself.

**Expected Result**

States onDone transition should be executed after all invokes finish.

**Actual Result**

States onDone transition is not executed after the invokes finish.

**Reproduction**

You can test by copy&pasting the following machines to the [xstate visualizer](https://xstate.js.org/viz/):

The onDone works for individual invokes, so this machine goes to the next state in 1 second after being reset:
```
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  });
}

Machine({
  id: 'onDoneTest',
  initial: 'invokeStuff',
  context: {
  },
  states: {
    invokeStuff: {
      invoke: {
        id: 'wait',
        src: () => wait(1000),
        onDone: 'next'
      }
    },
    next: {
    }
  }
});
```

If the onDone is set for the state however it does not work. This machine never goes to the next state:

```
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  });
}

Machine({
  id: 'onDoneTest',
  initial: 'invokeStuff',
  context: {
  },
  states: {
    invokeStuff: {
      invoke: {
        id: 'wait',
        src: () => wait(1000)
      },
      onDone: 'next'
    },
    next: {
    }
  }
});
```

Using the invoke's onDone is a decent workaround until you need multiple invokes which I think is the preferred way to split services into reusable chunks. This for example is not possible with the workaround since the individual onDone transitions are executed as soon as the particular invoke finishes:

```
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  });
}

Machine({
  id: 'onDoneTest',
  initial: 'invokeStuff',
  context: {
  },
  states: {
    invokeStuff: {
      invoke: [
        {
          id: 'wait1',
          src: () => wait(Math.random(5000))
        },
        {
          id: 'wait2',
          src: () => wait(Math.random(5000))
        }
      ],
      onDone: 'next'
    },
    next: {
    }
  }
});
```

**Comment by davidkpiano** [comment]
This is as expected, but I should clarify it in the docs.

The `onDone` on the state (not in each individual `invoke`) refer to the compound state node reaching a final child state, e.g.:

```js
loading: {
  invoke: {
    // ...
    onDone: {/* ... */} // refers to this invoke being done
  },
  initial: 'loadFoo',
  states: {
    loadFoo: {/* ... */},
    loadBar: {/* ... */},
    loadingComplete: { type: 'final' }
  },
  onDone: 'loaded' // refers to 'loading.loadingComplete' being reached
}
```

You can create a helper function to `Promise.all()` a set of invocations. Perhaps this should be done in userland rather than done in the library; not sure yet:

```js
const invokeAll = (invokeConfigs, onDone) => {
  return {
    id: invokeConfigs.map(c => c.id).join(', '),
    src: (ctx, e) => Promise.all(invokeConfigs.map(c => c.src(ctx, e))),
    onDone
  };
}

// ...
loading: {
  invoke: invokeAll([firstPromise, secondPromise], 'loaded'),
  // ...
}
```

**Comment by qtiki** [comment]
Thanks for the clarification. With the new information I was able to model my example with a machine without any need for helpers. However this results in a rather verbose configuration. On the bright side it looks pretty cool in the visualizer as you can see the individual wait states racing to the end 😅 :

```
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  });
}

Machine({
  id: 'onDoneTest',
  initial: 'invokeStuff',
  context: {
  },
  states: {
    invokeStuff: {
      type: 'parallel',
      states: {
        wait1: {
          initial: 'wait',
          states: {
            wait: {
            invoke: {
              id: 'wait1',
              src: () => wait(Math.random() * 5000),
              onDone: 'done'
            }           
            },
            done: {
              type: 'final'
            }
          }
        },
        wait2: {
          initial: 'wait',
          states: {
            wait: {
            invoke: {
              id: 'wait2',
              src: () => wait(Math.random() * 5000),
              onDone: 'done'
            }
            },
            done: {
              type: 'final'
            }
          }
        }
      },
      onDone: 'next'
    },
    next: {
    }
  }
});
```

I will probably need to make some form of a helper for my real-world case though. This is a bit clumsy to manually make for every case where I want to wait for multiple invokes.

**Comment by davidkpiano** [comment]
> However this results in a rather verbose configuration.

Yep, this is a clue that XState's config is meant to be low-level, and you're free to introduce abstractions on top of it. In the API design, I prefer flexibility (and conformance to the SCXML spec) over opinionated abstractions, as that's best for the majority of developers and gives the freedom to implement any opinionated parts in userland.

> On the bright side it looks pretty cool in the visualizer

You're right! https://xstate.js.org/viz/?gist=1a052c17151d53db88452feb7f9e543a

**Comment by qtiki** [comment]
I think the root of my confusion was not really understanding how the invokes work. I thought that invoking child machines was more or less the same as having the child machine's states copy&pasted in the parent, like this:

```
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  });
}

const waitMachineConfig = {
  initial: 'wait',
  context: {
  },
  states: {
    wait: {
      invoke: {
        src: () => wait(Math.random() * 5000),
        onDone: 'done'
      },
    },
    done: {
      type: 'final'
    }
  }
};

Machine({
  id: 'onDoneTest',
  initial: 'invokeStuff',
  context: {
  },
  states: {
    invokeStuff: {
      type: 'parallel',
      states: {
        wait1: waitMachineConfig,
        wait2: waitMachineConfig
      },
      onDone: 'next'
    },
    next: {
    }
  }
});
```

I can assign a child machine config like that and it works (as long as I don't use ids). But if I invoke a child machine I need an extra onDone callback with a separate final state.

Continuing this thought experiment further: since a promise is basically a machine with a final state it would be nice to be able to do something like this (could assign a child machine there too):

```
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  });
}

Machine({
  id: 'onDoneTest',
  initial: 'invokeStuff',
  context: {
  },
  states: {
    invokeStuff: {
      type: 'parallel',
      states: {
        wait1: () => wait(Math.random() * 5000),
        wait2: () => wait(Math.random() * 5000)
      },
      onDone: 'next'
    },
    next: {
    }
  }
});
```

Not sure if this would play nicely at all with the SCXML spec. I do agree that conforming to the specs is best for a generic library like this.

**Comment by Andarist** [comment]
> I think the root of my confusion was not really understanding how the invokes work. I thought that invoking child machines was more or less the same as having the child machine's states copy&pasted in the parent, like this:

Yeah, it's somewhat similar - only the context, events and IDs are not automatically shared between parent and invoked child.

**Comment by qtiki** [comment]
I just have to say that my last example for the wait states was pretty stupid. Obviously it'd need to be an object with type and other parameters. 😬

**Comment by qtiki** [comment]
Still wanted to clarify what I meant with the "extra onDone callback with a separate final state". In my above example where I assign the machineConfigs directly to the states the onDone is called. But if the states call the child machine with invoke it is not:

```
function wait(time) {
  return new Promise(resolve => {
    setTimeout(resolve, time);
  });
}

const waitMachine = Machine({
  initial: 'wait',
  context: {
  },
  states: {
    wait: {
      invoke: {
        src: () => wait(Math.random() * 5000),
        onDone: 'done'
      }
    },
    done: {
      type: 'final'
    }
  }
});

Machine({
  id: 'onDoneTest',
  initial: 'invokeStuff',
  context: {
  },
  states: {
    invokeStuff: {
      type: 'parallel',
      states: {
        wait1: {
          invoke: {
            id: 'wait1',
            src: waitMachine
          }
        },
        wait2: {
          invoke: {
            id: 'wait2',
            src: waitMachine
          }
        }
      },
      onDone: 'next'
    },
    next: {
    }
  }
});
```

**Comment by davidkpiano** [comment]
Add final states:

```js
        wait2: {
          invoke: {
            id: 'wait2',
            src: waitMachine,
            onDone: 'finished'
          },
          initial: 'pending',
          states: { pending: {}, finished: { type: 'final' } }
        }
```

**Comment by qtiki** [comment]
> Add final states:

Yes that was my point. When you use the child's configuration directly for the state then the child machine's final state is obviously included in the compound state - but when you use invoke you'll need to add a separate final state. I don't really have a problem with that, I just wanted to explain what was the cause of me misunderstanding how the invokes work. Invoke is not "inline include". 😅
