### ISSUE TITLE
Chalk dependency makes it impossible to execute tests inside a browser with @xstate/test

### ISSUE THREAD

**Issue by LevelbossMike** [davidkpiano/xstate#725]
Thanks so much for xstate!

**Description**
I'm trying to implement model based tests with `@xstate/test` in an ember.js project and the hard dependency on chalk breaks the test-suite as ember tests are executed in a browser environment.
Thanks for xstate!

**Expected Result**

Being able to execute model-based tests independent of node or browser environment - colorful output is nice but will most likely also be handled by the used test-runner. It might also be possible to create some kind of data structure that describes the error and then use that data-structure later on to optionally color the output of the error message.

**Actual Result**
My test breaks with
```
ReferenceError: process is not defined
```

as chalk is not designed to work in a browser environment.

**Reproduction**
I did not add a reproduction as I don't have a sandbox available that runs ember + xstate. I'll add a screenshot for reference though.

<img width="583" alt="xstate-test-error" src="https://user-images.githubusercontent.com/242299/66652599-5fbb2480-ec36-11e9-91e9-50c2f9be5982.png">

You can ignore the ember-auto-import part - the error message just tells us that the code breaks when requiring chalk.

**Additional context**
Removing `require('chalk')` and calls to `chalk` from the compiled code for `@xstate/test` gets rid of the errors and I can execute my test-suite.

**Notes**
Happy to fix this if you tell me how you can imagine getting rid of chalk in browser runs.

**Comment by Andarist** [comment]
Gonna prepare package tweaks a little bit later today to enable running them in browsers.
