### ISSUE TITLE
respond not a root export as per documentation

### ISSUE THREAD

**Issue by njdancer** [davidkpiano/xstate#730]
**Description**
https://github.com/davidkpiano/xstate/blob/master/docs/guides/communication.md suggests that ```respond``` should be a root export however looking at the current source this does not appear to be the case. It is currently exported as a value on the actions export.

**Expected Result**
```import { respond } from "xstate"``` should work.

**Actual Result**
Currently the following works:
```
import { actions } from "xstate"
const { respond } = actions
```

**Additional context**
Happy to submit a PR but not sure whether the code or documentation is incorrect. Personally I'd prefer ```respond``` to be a default export. While I'm at it would love ```log``` to be a default export as well. Understand you may wish to avoid polluting the export namespace however.

**Comment by Andarist** [comment]
Seems like we might want to export more than only `respond` - there are a bunch of actions that are currently not exported directly. 

@davidkpiano is there any rule of thumb here? should we just export all of them? or hide (under `actions` export) all of them in the future?

**Comment by davidkpiano** [comment]
We should export all of them, which I'll be doing before the release.

This also isn't public documentation, so I'll close this for now - the documentation on `master` has not been published yet 😅
