### ISSUE TITLE
Erroneous errors about transitions on transient states

### ISSUE THREAD

**Issue by njdancer** [davidkpiano/xstate#731]
**Description**
On 4.7.0-rc4 I'm receiving console warnings stating ```Warning: One or more transitions for the transient event on state 'session.loaded' are unreachable. Make sure that the default transition is the last one defined.```

**Expected Result**
```
loaded: {
  on: {
    "": [
      {
        cond: "isSessionValid",
        target: "session",
      },
      {
        target: "null",
      },
    ],
  },
}
```
shouldn't log warning.

**Actual Result**
```
loaded: {
  on: {
    "": [
      {
        cond: "isSessionValid",
        target: "session",
      },
      {
        target: "null",
      },
    ],
  },
}
```
logs warning.

**Reproduction**
https://codesandbox.io/s/xstate-react-template-yo5ui?expanddevtools=1&fontsize=14&module=%2Fpackage.json

**Additional context**
Receiving error on 4.7.0-rc4. Didn't get these errors on 4.6.7 which I previously was using.

**Comment by Andarist** [comment]
It has been fixed recently by https://github.com/davidkpiano/xstate/pull/728 but the fix has not been released yet. Sorry for the inconvience. Closing this for now as the fix is already merged in
