### ISSUE TITLE
useMachine logs warning about reading initial state from uninitialized service

### ISSUE THREAD

**Issue by njdancer** [davidkpiano/xstate#732]
**Description**
In 4.7.0-rc4 an warning is logged to the console when calling useMachine.

**Expected Result**
No warning.

**Actual Result**
```Warning: Attempted to read initial state from uninitialized service 'toggle'. Make sure the service is started first. ```

**Reproduction**
https://codesandbox.io/s/xstate-react-template-yo5ui?expanddevtools=1&fontsize=14

**Additional context**
Occurs on 4.7.0-rc4 but did not on 4.6.7.

**Comment by Andarist** [comment]
@davidkpiano is this warning even useful there? It just proxies to `machine.initialState` which is pure.

**Comment by davidkpiano** [comment]
> is this warning even useful there?

It is not, I'm going to be reworking this so that the warning no longer occurs.
