### ISSUE TITLE
Sending event `send()` after interpreter is stopped causes actions to be executed.

### ISSUE THREAD

**Issue by Baael** [davidkpiano/xstate#735]
**Description**
Sending event `send()` after interpreter is stopped causes actions to be executed.

**Expected Result**
After interpreter is stopped, sending event should not execute any action.

**Actual Result**
After interpreter is stopped, sending event executes entry action.

**Reproduction**
https://codesandbox.io/s/xstate-example-template-pubkk

**Additional context**
Maybe I am wrong and don't get something with start/stop/send functions.

**Comment by Baael** [comment]
@davidkpiano so it isn't bug, and this behavior is valid in this configuration, while it is working correctly in other configuration?

**Comment by davidkpiano** [comment]
@Baael It is a bug, that I just fixed.

**Comment by Baael** [comment]
I didn't noticed, you are too fast :D Good, cause client wasn't sure if use of this library is good idea. Now I have proof.

**Comment by davidkpiano** [comment]
> Good, cause client wasn't sure if use of this library is good idea.

Any other concerns? 😄

**Comment by Baael** [comment]
No, I have very strong argument now :)

**Comment by davidkpiano** [comment]
Keep in mind as well that most of the issues in this repo are discussions and/or questions, not bugs. And most of the bugs are small SCXML compatibility issues and edge-cases, not issues that you will run to in normal projects.

This also follows SCXML (an XState-SCXML converter will be released this year) so everything follows the spec, and nothing will be invented (no feature/scope creep) in this project, if that helps.
