### ISSUE TITLE
Send data to child actor

### ISSUE THREAD

**Issue by CodingDive** [davidkpiano/xstate#739]
I think this is probably a question not a feature request or bug.

How do we send data to child actors within a machine? 

Looking at the [example from the docs](https://xstate.js.org/docs/guides/actors.html#sending-events-to-actors), we can spawn an actor and send events to it but I'm not sure how to add data to the event. 

```
entry: assign({
  someRef: () => spawn(someMachine)
}),
on: {
  SOME_EVENT: {
    // I want to send some custom data (from either the SOME_EVENT data or the local context) to the PING event 
    actions: send('PING', {
      to: context => context.someRef,
    })
  }
}
```

With the sendParent API I can do the following:
```
actions: sendParent(context => ({
  type: 'UPDATE_FROM_CHILD',
  data: context
}))
```

Does a similar API exist for parent -> child 🤖 communication?

**Comment by davidkpiano** [comment]
Yes:

```js
actions: send({
  type: 'SOME_EVENT',
  somePayload: 'whatever you want'
}, { to: context => context.someRef })
```

**Comment by davidkpiano** [comment]
I'll add this to the docs too.
