### ISSUE TITLE
Interpreter replays actions when multiple batches of events are being sent

### ISSUE THREAD

**Issue by ikovic** [davidkpiano/xstate#741]
**Description**
When calling an interpreter with batches of events more than once, interpreter accumulates all the actions and executes them every time, replaying the previous actions. On every transition, all the actions from previous batches get executed as well.

My use case:

- developing a simple platformer game
- there's a game loop running on `requestAnimationFrame`
- in every step of the loop we create events based on user input and execute them in a batch using an interpreter

My workaround was accumulating events in every step of game loop in an array, and then calling `interpreter.send` event by event, looping over that array. I'd prefer to be able to use batching there.

Reading the docs, I didn't get an impression that this was by design. If that is true, I can open a PR with a change to interpreter so that it clears historic actions between running batches.

**Expected Result**
Calling an interpreter with an array of events more than once should have the same effect as if sending those events one by one.

**Actual Result**
Every time `interpreter.send` is called with an array of events, all the previously executed actions are executed again, with the latest actions being called last. Transition listener shows all the historic actions in `state.actions`, where I would expect only the actions from the current batch to be there.

**Reproduction**

- [CodeSandbox](https://codesandbox.io/embed/xstate-typescript-template-11lqz)

**Additional context**
xstate version: 4.6.7

**Comment by davidkpiano** [comment]
This no longer occurs in 4.7.3

<img width="520" alt="Screen Shot 2019-12-18 at 8 32 23 AM" src="https://user-images.githubusercontent.com/1093738/71090407-f513f100-2170-11ea-9b93-3d6d819a1a9f.png">

**Comment by ikovic** [comment]
Thank you!
