### ISSUE TITLE
Should actions be executed before or after updating the current state?

### ISSUE THREAD

**Issue by lorlab** [davidkpiano/xstate#75]
Hi! I'm really enjoying this library! I was wondering what the best strategy is for executing actions. In the example on the 'complete guide' page you execute actions before updating the value of currentState, however I'm running into a problem where I have an action that can change the current state, but because currentState is set after this action runs, the action has no effect. Any thoughts? Are there any side effects in executing actions after updating the state? Thanks!

**Comment by davidkpiano** [comment]
Do you have a project or some code you should point to?

In general, nothing should _ever_ modify the current **finite state** (e.g., `loading, success, etc.`) except from the result of calling `.transition()`.

I will be revising the guide (and coming up with a different set of complete examples), as you're right, the changed finite state should be reflected in the actions.

**Comment by lorlab** [comment]
I can post some code if you want but my question is more about how and when you think actions should be executed in general. If we take the dispatch function below (from the docs), any change in state caused by an action will be negated by the last line when the forEach loop ends, right? What I'm trying to understand is what the correct end state should be, the one which is initially assigned to nextState, or some state resulting from an action which recursively calls dispatch... I'm not sure I'm making much sense though :)

```javascript
dispatch (event) {
  const nextState = machine.transition(currentState, event)
  nextState.actions.forEach(actionKey => {
    const action = actionMap[actionKey]
    if (action) action(event, dispatch)
  })
  currentState = nextState.value
}
```

**Comment by davidkpiano** [comment]
That depends. So, an action isn't like a Redux "action" - those are more what are considered events in statecharts.

Here, an action can do one of two things:
- Modify external state (any state except for the finite `nextState`)
- Dispatch actions _asynchronously_

The async part is key there - as long as they're async, you won't run into the concurrency issues you're running into now. For most intents and purposes, just keep those two things in mind and you'll be fine.

----

However, if you want them to _synchronously_ queue up events from actions, then use a queue 😉 In SCXML, there's something called [`<send>`](https://www.w3.org/TR/scxml/#send) that formalizes this (worth reading). Here's what that might look like:

```js
dispatch (event) {
  let nextState = machine.transition(currentState, event)
  const queue = [];

  // assume object actions: { type: '...' }
  nextState.actions.forEach(action => {
	if (action.type === 'send') {
	  queue.push(action.event);
	} else {
	    const execAction = actionMap[action.type];
	    if (execAction) execAction(event, dispatch); // async dispatch only
	}
  });

  // run through the queued events
  while (queue.length) {
	nextState = machine.transition(nextState, queue.shift());
  }

  currentState = nextState.value
}
```

You can do this now. But there are two things coming soon that will help with this:
- In `xstate` 3.2, there's an official `actions.send(event, data)` creator
- The `xstate-interpreter`, which is not released yet, will handle queued events in a similar way.

**Comment by lorlab** [comment]
Thanks a lot for the explanation! I will experiment with your suggestions and I look forward to 3.2!

**Comment by MiChAeLoKGB** [comment]
Hi,

I am confused about the part of your code where you say it is asynchronous @davidkpiano 

When I use the function below, the order of execution is synchronous:
1. dispatch gets called
2. every action gets executed
3. current state from the first call of dispatch is changed 

```javascript
function dispatch(event) {
    var nextState = machine.transition(currentState, event);

    nextState.actions.forEach(function(actionKey) {
        var execAction = actions[actionKey];
        if (execAction) execAction(event, dispatch); // async dispatch only
    });

    currentState = nextState.value;
}
```

For the actions to be called asynchronously, the timeout has to be used, then the order of execution is as follows:
1. dispatch gets called
2. current state is changed 
3. every action gets executed

```javascript
function dispatch(event) {
    var nextState = machine.transition(currentState, event);

    nextState.actions.forEach(function(actionKey) {
        var execAction = actions[actionKey];
        if (execAction) {
            setTimeout(function (action) { 
                action(event, dispatch); 
            }.bind(null, action), 0);
        }
    });

    currentState = nextState.value;
}
```

Is your code indeed synchronous, or is the problem somewhere else?

I don't use arrow functions, because my code has to run in browser (IE 11 included :poop:). But even if I used them and tested it in Chrome, the execution was still synchronous.

Is there maybe some difference between node.js and chrome (even if node is chrome's js engine)?

Thank you.

**Comment by davidkpiano** [comment]
Execution is synchronous, but any events sent (dispatched) from inside an action must be assumed to be asynchronous.

**Comment by MiChAeLoKGB** [comment]
Ah, ok got it 😄 I was really confused there for a bit.
Thanks for an answer and for a great piece of code 👍 

I watched your JSConf presentation yesterday and today after some thinking I decided to re-write one module (similar to online bank contract application form, so it really needs FSA) from scratch, as I was tasked to do some extensive changes on it anyways.
I really hope it makes the code easier to understand and test.

Only thing I need to figure out now, is how (or when) to properly call actions like `showNextButton` when you go from `step1` to `step2`, mainly when `step1` has a 2 step validation (js and server side, but as they do the same thing, I think I will use server side only) which either changes the state back to `step1` or goes to `step2`.

TBH I don't know if my structure shouldn't be written differently. I am not sure if I should ask here, or on StackOverflow.

**Comment by davidkpiano** [comment]
You can ask here - it's helpful for knowing what to update in the documentation.

It seems like `step1` should have a `step1.pending` (or something similar) state where it's waiting for validation. Then validation will respond (from a promise or otherwise) and that event will determine if `step1.pending` transitions back to `step1.(some state)` or `step2`.

**Comment by MiChAeLoKGB** [comment]
This is my machine right now (its a bit simplified, real form has 6 tabs/steps), also I will probably drop the main `idle` state (I don't think its needed). The code just seems a bit too clunky to me.

Right now every step has 2 child steps `idle` and `validate`, where `idle` state can only call `validate`, which will either go back to `idle` state on `ERROR` or pass the even to the parent, which handles the `NEXT` and `PREV` events (except first and last step, which don't have `PREV` and `NEXT` states respectively).

Also depending on subject type (legal entity or not) you either go from `step1` to `step2` or `step3` and vice versa.

Also, right now, it always calls `hidePrevBtn` then `showPrevBtn` and then again `hidePrevBtn`...

```javascript
var contractMachine = xstate.Machine({
    key: 'contract',
    initial: 'idle',
    states: {
        idle: {
            on: {
                INIT: 'step1'
            }
        },
        step1: {
            initial: 'idle',
            states: {
                idle: {
                    on: {
                        NEXT: 'validate'
                    }
                },
                validate: {
                    on: {
                        ERROR: 'idle'
                    },
                    onEntry: ['validateStep1']
                },
            },
            on: {
                NEXT: {
                    step2: {
                        cond: function (extState, event) {
                            return event.subject !== 'SE';
                        }
                    },
                    step3: {
                        cond: function (extState, event) {
                            return event.subject === 'SE';
                        }
                    }
                }
            },
            onEntry: ['hidePrevBtn'],
            onExit: ['showPrevBtn']
        },
        step2: {
            initial: 'idle',
            states: {
                idle: {
                    on: {
                        NEXT: 'validate'
                    }
                },
                validate: {
                    on: {
                        ERROR: 'idle'
                    },
                    onEntry: ['validateStep2']
                },
            },
            on: {
                PREV: 'step1',
                NEXT: 'step3'
            }
        },
        step3: {
            initial: 'idle',
            states: {
                idle: {
                    on: {
                        NEXT: 'validate'
                    }
                },
                validate: {
                    on: {
                        ERROR: 'idle'
                    },
                    onEntry: ['validateStep3']
                },
            },
            on: {
                PREV: {
                    step1: {
                        cond: function (extState, event) {
                            return event.subject === 'SE';
                        }
                    },
                    step2: {
                        cond: function (extState, event) {
                            return event.subject !== 'SE';
                        }
                    }
                },
                NEXT: 'step4'
            }
        },
        step4: {
            initial: 'idle',
            states: {
                idle: {
                    on: {
                        NEXT: 'validate'
                    }
                },
                validate: {
                    on: {
                        ERROR: 'idle'
                    },
                    onEntry: ['validateStep4']
                },
            },
            on: {
                PREV: 'step3'
            },
            onEntry: ['hideNextBtn'],
            onExit: ['showNextBtn']
        }
    }
});
```

Ps.: I tried to use the code in your Statechart Visualizer on CodePen, but its not supporting the conditional transitions.
