### ISSUE TITLE
Login/signup without connecting to github to use visualizer

### ISSUE THREAD

**Issue by linus345** [davidkpiano/xstate#751]
## Bug or feature request?
Feature request
## Description:
Instead of having to authorize xstate to your github account it would be nice to have another option. For example: 
- logging in with email and password
- logging in with a google account

## (Feature) Potential implementation:
oauth

- What the API would look like
- If this is a breaking change
- If this is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)

**Comment by davidkpiano** [comment]
Added to roadmap!
