### ISSUE TITLE
"setCurrent is not a function" for @xstate/react immediate: true + initial state transient transition

### ISSUE THREAD

**Issue by johnyanarella** [davidkpiano/xstate#755]
**Description**

Given a machine whose initial state (ex. `bootstrapping`) contains a transient transition (i.e. immediate null event transition), if the `immediate: true` option is specified for `useMachine()`, a runtime error will occur.

**Expected Result**

The machine starts without incident.

**Actual Result**

The following error is thrown when `useMachine()` attempts to start the machine:

```
TypeError: setCurrent is not a function.
```

because the `onTransition()` handler (triggered by the transient transition during startup) registered a few lines earlier references `setCurrent()` from a `useState()` call that has not yet occurred.

**Reproduction**

Admittedly a contrived example, but the goal here was strip the problem down to its essence:

- [CodeSandbox](https://codesandbox.io/s/xstatereact-initial-transient-transition-immediate-option-fr0xb)

*NOTE:*

- Commenting `immediate: true` in the `useMachine()` call's options will resolve the runtime error but reveal the warning triggered when an event is sent by a descendant component before the service starts.
- Commenting out the `useMachine` import from `@xstate/react` and uncommenting the import for the local `useMachine` implementation will allow you to try out the proposed fix in the PR linked to this issue.

**Additional context**

Encountered in: `XState 4.7.0rc5`

Why am I enabling `immediate: true` anyway? Because the real machine in question (several of which are instantiated at a time) receives events dispatched by descendent components before the `useEffect()` inside `useMachine()` starts the machine, which results in tons of warnings like this in the dev console:

```
Warning: Event "FOO" was sent to uninitialized service "foo" and is deferred. Make sure .start() is called for this service.
```

Generally, I'd probably be fine with deferring these events, but the noisy dev console is problematic.

**Comment by Andarist** [comment]
fixed by https://github.com/davidkpiano/xstate/pull/756
