### ISSUE TITLE
@xstate/fsm version support for @xstate/react

### ISSUE THREAD

**Issue by sHooKDT** [davidkpiano/xstate#763]
Feature request

React bindings are now bounded to xstate internals and thus doesn't work with @xstate/fsm.
Common xstate is too large for me. 60KB of minified JS is incredible for me and I wanted to use fsm version, because I don't need too much features at this point.

Potential implementation:
I haven't dive deep into the code, but I think that maybe we can extract a common part of code into separate package, which react bindings can use internally. Or even completely get rid of xstate internals usage.

I can have a look at this myself a bit later, but I want to raise this issue up beforehand.

**Comment by sHooKDT** [comment]
@davidkpiano why did you close it?

**Comment by davidkpiano** [comment]
Because I just finished it 😉

**Comment by sHooKDT** [comment]
I'm kinda shocked 😮

Great job!
