### ISSUE TITLE
Remove "actions as strings" in @xstate/fsm

### ISSUE THREAD

**Issue by kyleshevlin** [davidkpiano/xstate#764]
## Bug or feature request?
More like removing a redundant feature (with the possibility of adding a feature instead)

## Description:

The source code for `@xstate/fsm` provides three places to add actions: on a transition's `actions` property, or on a state config's `entry` or `exit` property. There is no where to add an `options` object like in `xstate` that has an `actions` property for a string of an action type to reference. Thus, the only way to add actions is in function form.

With this determined, it doesn't make sense to document that an action can be represented as a string as this would have no effect. It would also reduce one case in `toActionObject` since we wouldn't have to check if it was a string. As is, that first check returns an object that wouldn't execute anything anyways.

The other option, if we wanted to keep the documentation and types the same, would be to add an ability to provide `actions` in an object like the bigger `xstate` library does.

**Comment by kyleshevlin** [comment]
That makes sense and is eerily close to what I was doing that tipped me off to this. If this is expected/wanted behavior, then I don't see a need to change the library, but it might be worth an example or a note somewhere about it. What do you think?

**Comment by davidkpiano** [comment]
For sure, this should be added to the documentation, as well as potentially a way to configure actions (which wouldn't add too much weight to the library, I'm guessing).
