### ISSUE TITLE
stale context, services, etc.

### ISSUE THREAD

**Issue by geddski** [davidkpiano/xstate#765]
**Description**
When using `useMachine` and configuring the machine inside of a react component based on props, things get stale on subsequent renders. The xstate context for example is not updated, causing actions to use stale context.

**Expected Result**
useMachine should keep the context, services, etc. up to date when they change. Possibly by providing an array of deps option like react's `useState` does. 

**Reproduction**
https://codesandbox.io/s/xstate-react-stale-xpd17

**Comment by Andarist** [comment]
As to `context` - it seems to me that this particular thing shouldn't be updated. I treat it like `initialValue` for useState/useReducer. The only way of manipulating these are events and assign actions associated with taken transitions.

Keeping this updated with the rendered value would even be rather impossible, imagine a simple counter:
```js
function Counter() {
  const [current, send] = useMachine(machine, {
    context: {
      count: 0
    },
  });

  return (
    <button
      onClick={() => {
        send("INCREMENT");
      }}
    >
      Increment
    </button>
  );
}
```

With what you propose this would just reset each time to `0` - thus having no effect on the app.

**Comment by geddski** [comment]
In that example sure. When xstate is managing the context it makes sense not to change it. But when the context is based on props then it makes sense to keep it up to date. Currently the integration of xstate and react is full of stale prop pitfalls. Just wanting xstate/react to be easier for people including myself. 

Maybe the lib could handle props specially? Using props in services (without context) has the exact same stale prop problem.

**Comment by geddski** [comment]
browsing the code it looks like `actions` are kept up to date, but that's all.

**Comment by Andarist** [comment]
> In that example sure. When xstate is managing the context it makes sense not to change it. But when the context is based on props then it makes sense to keep it up to date.

It's impossible for library code to determine what's your intention here. I just believe this is an integration point that cannot be automated because it would actually make the resulting code full of other pitfalls - context randomly updated etc. It's also from my point of view just the same as in the case of useState etc. Seems like you want to derive state (xstate context) from props here - maybe instead of doing that you should just hoist your machine so this is not needed? And if you can't do that - you have to "implement" `getDerivatedStateFromProps` semantics into your component.

> Maybe the lib could handle props specially? Using props in services (without context) has the exact same stale prop problem.

Yes, that most likely should be fixed 👍

**Comment by geddski** [comment]
> Yes, that most likely should be fixed 👍

@Andarist I only tried context after the stale props in services. If that's fixed I'm happy to use that, and leave context as is. 

Here's an updated example that shows the same problem but with services.
https://codesandbox.io/s/xstate-react-stale-8zx0p
