### ISSUE TITLE
@xstate/fsm: npm pkg missing es module

### ISSUE THREAD

**Issue by arjunyel** [davidkpiano/xstate#766]
**Description**

The package.json lists `"module": "es/index.js"` but that file seems to be missing from the final build: https://unpkg.com/browse/@xstate/fsm@1.0.3/

**Expected Result**

ES Module included on NPM

**Actual Result**

Missing file

**Additional context**

@xstate/fsm: 1.0.3

**Comment by davidkpiano** [comment]
Released as 1.1.0
