### ISSUE TITLE
Actor type missing (typescript)?

### ISSUE THREAD

**Issue by DirkWolthuis** [davidkpiano/xstate#768]
**Description**
I think the Actor type is missing, or I'm misunderstanding how to use the Actor type. 

**Expected Result**
I want to type my context ref attribute.

**Actual Result**
Can't find the Actor type. 

**Reproduction**
```typescript
import { Actor} from "xstate";

export type ProductOptionStepType = {
    step: string;
    ref: Actor;
    description: string;
    options: Array<ProductOptionType>;
    type: number;
};
```
**Additional context**
xstate 4.6.7

**Comment by davidkpiano** [comment]
Try this for now:

```ts
import { Actor } from 'xstate/lib/Actor';
```
