### ISSUE TITLE
[Docs] Clicking on a search link gives a 404 error

### ISSUE THREAD

**Issue by gustavo-depaula** [davidkpiano/xstate#773]
**Description, actual result and reproduction**
Suppose that I'm searching for guards:
![image](https://user-images.githubusercontent.com/732422/68045523-76462000-fcb8-11e9-83cc-4a3248414221.png)
When I click one of those options, I'm redirected to here:
![image](https://user-images.githubusercontent.com/732422/68045555-8a8a1d00-fcb8-11e9-871d-1410ebdf4173.png)
This problem happens because the URL has the path `docs/` duplicated: `https://xstate.js.org/docs/docs/guides/guards.html#guards`

**Expected Result**
I should've been redirected to this page:
![image](https://user-images.githubusercontent.com/732422/68045641-c3c28d00-fcb8-11e9-84e3-4884b8c500b9.png)
With the following URL:
`https://xstate.js.org/docs/guides/guards.html#guards`

**Comment by djkalmyk** [comment]
Clicking and also hitting Enter also produces the same problem

**Comment by davidkpiano** [comment]
Duplicate #744
