### ISSUE TITLE
@xstate/react, useService : Type Error Cannot read property 'context' of undefined

### ISSUE THREAD

**Issue by n8jadams** [davidkpiano/xstate#774]
**Description**
I am using a spawned actor as a prop, and then use that prop with the useService hook, similar to how the [Reddit example with actors](https://codesandbox.io/s/xstate-react-reddit-example-with-actors-5g9nu) does it.

**Expected Result**
The return array of the useService hook would be valid.

**Actual Result**
```
TypeError
Cannot read property 'context' of undefined
```

**Reproduction**
[Here is the code that is causing the error](https://codesandbox.io/s/black-tdd-n09u1)

**Additional context**
Love the library and the ideas. It's possible I'm doing something incorrectly here.

**Comment by davidkpiano** [comment]
Close! The `context` property doesn't work the same way as `assign`. Try this:

```js
// ...
		context: {
			flightTypeList,
			flightType: ONE_WAY_FLIGHT,
			firstFlightInput: undefined,
			secondFlightInput: undefined
		},
		entry: assign({
			firstFlightInput: () => spawn(createFlightInputMachine(), 'firstFlightInput'),
			secondFlightInput: () => spawn(createFlightInputMachine(), 'secondFlightInput')
		}),
// ...
```
