### ISSUE TITLE
createMachine function not found

### ISSUE THREAD

**Issue by cician** [davidkpiano/xstate#775]
I'm learning xstate and impatient as I am, I wanted to try out Typestates, but I cannot use the createMachine function as it doesn't seem to be present in the javascript code of 4.7.0-rc5 package, but present in its Machine.d.ts. Is this already fixed in master? Should I just wait for next RC or final release?
Thanks.

**Comment by davidkpiano** [comment]
Released as `4.7.0-rc6` - should work there.

**Comment by cician** [comment]
> Released as `4.7.0-rc6` - should work there.

Thank you!
