### ISSUE TITLE
restore from state: Child state 'actions' does not exist on

### ISSUE THREAD

**Issue by pke** [davidkpiano/xstate#789]
**Description**

Using the counter example state machine I persist it like described in the docs

```js
json = JSON.stringify(machine.state)`
```

Then later I want to load that state into my state machine

```js
const counterService = interpret(counterMachine)
.start(counterMachine.resolve(State.create(JSON.parse(json))))
```

**Expected Result**

I was expecting this work.

**Actual Result**

I am getting the error:

`Child state 'actions' does not exist on '(machine)'`

**Reproduction**

https://codesandbox.io/s/xstate-example-template-yk6yd

**Comment by alexdunne** [comment]
Looking at the [persisting state docs](https://github.com/davidkpiano/xstate/blob/master/docs/guides/states.md#persisting-state) it looks like you want `resolveState` rather than `resolve`.

So your example would go from:

```
interpret(machine).start(
  machine.resolve(
    State.create(
      JSON.parse(json)
    )
  )
);
```

to:

```
interpret(machine).start(
  machine.resolveState(
    State.create(
      JSON.parse(json)
    )
  )
);
```

**Comment by pke** [comment]
It certainly looks like it! Silly me. What is `machine.resolve` for then?

**Comment by davidkpiano** [comment]
> What is `machine.resolve` for then?

That is for resolving a state value, not a full state.

For example, `someMachine.resolve('a')` might return `{ a: { b: 'c' } }`.
