### ISSUE TITLE
Build warning missing *.map files

### ISSUE THREAD

**Issue by RainerAtSpirit** [davidkpiano/xstate#790]
**Description**
Projects that uses @xstate/react@0.8.1 (and earlier) throws warning during build:
`Cannot find SourceMap 'index.js.map': Error: Can't resolve './index.js.map' in 'C:\github\xstateactors\node_modules\@xstate\react\lib'`

**Expected Result**

*.map files should be included in npm packages.

**Actual Result**

*.map files are missing the npm package.
![image](https://user-images.githubusercontent.com/581644/68493446-c723be80-024c-11ea-805b-24fe572f7690.png)

**Reproduction**

**Additional context**

package.json has this files configuration:

```json
 "files": [
    "lib/**/*.js",
    "lib/**/*.d.ts"
  ],
```

According to https://docs.npmjs.com/files/package.json#files

> The optional files field is an array of file patterns that describes the entries to be included when your package is installed as a dependency.

Some other packages/xxx/package.json probably use the same settings. These should be most likely updated to look like

```json
 "files": [
    "lib/**/*.js",
    "lib/**/*.d.ts",
    "lib/**/*.map"
  ],
```

**Comment by Andarist** [comment]
We actually dont want to ship any referencea to source maps. Ill prepare a fix for this today

**Comment by RainerAtSpirit** [comment]
Ok, understood.
