### ISSUE TITLE
Add optional state type to Actor type

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#794]
Would there be any objections to adding an _optional State type_ to the _Actor type_. This would be helpful when spawning an Actor with syncing turned on? I can make the PR if it sounds like a good idea.

**Comment by davidkpiano** [comment]
Can you provide a CodeSandbox example demonstrating a use-case?

This should only be enabled for invoked machines.

**Comment by bradwoods** [comment]
Yep. The example shows a typescript error when attempting to access an actor's state via the parent's context. I'm assuming adding a State-type to the actor would fix the issue.

https://codesandbox.io/s/xstate-stateless-actor-problem-1v1r5

**Comment by davidkpiano** [comment]
This has been done in master, will be available in a RC soon
