### ISSUE TITLE
History state not working

### ISSUE THREAD

**Issue by fabiradi** [davidkpiano/xstate#796]
**Description**
I created a machine with a history state. The machine visualizer shows the history state with an H. so the definition should be correct.

**Expected Result**
Transitioning to the history state should forward to the last  state the machine was in.

**Actual Result**
Nothing happens. The history transition does not work. The machine does not even enter the history state.

**Reproduction**
https://xstate.js.org/viz/?gist=6628e561016cacaad4c246d7d35336d7

**Additional context**
I was trying to use a history state together with React, where it did not work. But in the visualizer, it does not work as well. So either I'm doing it wrong, or the lib has a bug?

**Comment by davidkpiano** [comment]
History state nodes don't mean "previous state", they mean "previously active child state node of this state".

See this thread for more clarification: https://spectrum.chat/statecharts/general/some-confusion-around-history-state-nodes~7323cbd5-7ad0-4d58-8bf6-b7cafab2a2a0
