### ISSUE TITLE
Question: can I rely on "state" as an argument in conditional transitions? Will it be removed at a later point?

### ISSUE THREAD

**Issue by 3plusalpha** [davidkpiano/xstate#798]
**Description**
In conditional transitions the function in the `cond` property receives `context, event, state` as arguments. Can I rely on `state` even though it's not mentioned in the docs?

**Expected Result**
The condition prop receives only `(context, event)`

**Actual Result**
The condition prop receives additionally state `(context, event, state)`

**Comment by davidkpiano** [comment]
Yes, it's available on `(context, event, { state })`. Try it out.

**Comment by 3plusalpha** [comment]
Great! Thanks a lot :)
