### ISSUE TITLE
[Feature] Add vue composition API functions

### ISSUE THREAD

**Issue by studnitz** [davidkpiano/xstate#807]
## Bug or feature request?
Feature Request
## Description:
I think with the upcoming release of Vue 3.0 and its [Composition API](https://vue-composition-api-rfc.netlify.com/) which is relatively similar in concept to React Hooks, it would be a great addition to port the current xstate-react Hooks to the Vue Composition API. At the moment the Composition API is [backported](https://github.com/vuejs/composition-api) (with a few caveats), so I could start working on a PR if it's wanted

**Comment by davidkpiano** [comment]
@studnitz I would love this. What would a Vue hook look like?

**Comment by Andarist** [comment]
Looking at Vue’s API - it would look exactly the same as existing useMachine 🚀. Only the implementation would differ. 

@studnitz is Vue’s `setup` called once per component’s instance?

**Comment by studnitz** [comment]
@davidkpiano As @Andarist said. :)
@Andarist The [documentation](https://vue-composition-api-rfc.netlify.com/api.html#setup) says:
> `setup` is called right after the initial props resolution when a component instance is created. Lifecycle-wise, it is called before the `beforeCreate` hook.

**Comment by Andarist** [comment]
Thanks for your answer! The last question - is it possible to track current props inside setup? Can't see (looking quickly through it though) any example of this. Are initial props received anyhow there? Can't see any example of receiving them as argument of the setup, nor available at `this`.

**Comment by studnitz** [comment]
Yes, that's possible.

> ## Arguments
>
>The function receives the resolved props as its first argument:
>
>```js
>export default {
>  props: {
>    name: String
>  },
>  setup(props) {
>    console.log(props.name)
>  }
>}
>```
>Note this props object is reactive - i.e. it is updated when new props are passed in, and can be observed and reacted upon using the watch function:

**Comment by AleksejDix** [comment]
I made a first Vue Composition API function today. Was inspired by the react useMachine
https://github.com/AleksejDix/vue-use/blob/master/src/compositions/useMachine.js

**Comment by AleksejDix** [comment]
Yeah I was too late for my PR.  @studnitz  great work.

**Comment by ChrisShank** [comment]
FYI the alpha for [`vue@next`](https://www.npmjs.com/package/vue/v/3.0.0-alpha.0) and  [`@vue/reactivity`](https://www.npmjs.com/package/@vue/reactivity) were released on NPM a couple of days ago.

**Comment by davidkpiano** [comment]
This was released as `@xstate/vue`! Currently version 0.1.x
