### ISSUE TITLE
@xstate/fsm Return config object from createMachine

### ISSUE THREAD

**Issue by ghengeveld** [davidkpiano/xstate#810]
I'd like to see @xstate/fsm expose the config object it was instantiated with. The most obvious way is by exposing a `config` property on the return value of `createMachine`.

**Comment by davidkpiano** [comment]
What is your use-case? Also, you can create a helper function that does this.

**Comment by ghengeveld** [comment]
The use case is being able to take a state machine defined by someone else and doing smart things with it based on its configuration. Technically you could just have the config in a separate variable but I don't want to ask people integrating with my library to provide both the config and the machine. If I can get the config from the machine that makes things easier for everyone.

The background to this request is I'm building a Storybook addon which takes an FSM and generates stories for each of the possible states. Because the context that's built up while transitioning from one state to the next is relevant, I can't just parse the config, I have to actually make the transitions. Therefore I crawl the FSM by starting from the initial state and transitioning to every other state by following the events and recording the context. That's why in my PR I also exposed config from the state object itself. That way it's much easier to know which events are available from a particular state (and follow each of them).

**Comment by ghengeveld** [comment]
The code to this is actually really simple:

```js
const variants = {}; // map of state key -> context

const crawl = state => {
  if (variants[state.value]) return;
  variants[state.value] = { ...state.context, events: {} };
  Object.keys(state.config.on || {}).forEach(event => {
    variants[state.value].events[event] = linkTo(kind, state.config.on[event]);
    crawl(transition(state, event));
  });
};

crawl(initialState);
```

This is depth-first, I should probably change it to breadth-first. `linkTo` is from `@storybook/addon-links` which is a callback that transitions to another story.
