### ISSUE TITLE
getSimplePathPlans getting into an infinite loop

### ISSUE THREAD

**Issue by mukeshsoni** [davidkpiano/xstate#812]
**Description**
I am trying to use @xstate/test to generate test plans for a simple machine i wrote. The machine can be found here - https://xstate.js.org/viz/?gist=502f835cd08540f84d15c3031c28f6b0

When i try to generate test plans for the machine using `getSimplePathPlans`, i get a maximum call size exceeded error. Looking at the `context` value when this happens it looks like `getSimplePathPlans` goes into an infinite loop. 

I can play with the machine alright in the visualizer though. 

**Expected Result**
A test plan which can be used to generate tests.

**Actual Result**
`getSimplePathPlans` throws a `maximum call stack size exceeded error`

```
Error: Unable to transition from state {"block_delete":"block_delete_active"} | {"selected_conv_count":4801} on event {"type":"SELECT_CONV"}: Maximum call stack size exceeded
    at findAdjacencies (https://ncrig.csb.app/node_modules/@xstate/graph/lib/graph.js:126:27)

    at findAdjacencies 
```

**Reproduction**
Here's a codesandbox link for reproducing the issue. I imported the test plan into the `src/index.js` file to reproduce it. The error can be seen in the console.
https://codesandbox.io/s/model-based-testing-for-chat-ncrig

Here's a link to XState Visualiser for the machine - https://xstate.js.org/viz/?gist=502f835cd08540f84d15c3031c28f6b0

**Additional context**
xstate vesion - 4.6.7
@xstate/test version - 0.1.0

**Comment by davidkpiano** [comment]
Please read here: https://xstate.js.org/docs/packages/xstate-test/#testmodel-getshortestpathplans-options. You need to add a `filter` to prevent runaway traversal scenarios like this.

**Comment by mukeshsoni** [comment]
Thanks a lot!

The documentation example shows the filter option to be passed to `createModel` but it's actually for the `getShortestPathPlans` function.

```
const todosModel = createModel(todosMachine, {
  // Tell the algorithm to limit state/event adjacency map to states
  // that have less than 5 todos
  filter: state => state.context.todos.length < 5
}).withEvents({
  // ...
});
```
