### ISSUE TITLE
Wildcard transitions not working correctly

### ISSUE THREAD

**Issue by 3plusalpha** [davidkpiano/xstate#813]
**Description**
Wildcard transitions not working for 4.6.x
According the docs wildcard transitions are supported, but it's not clear from which version.

**Expected Result**
State targets defined with a wildcard transition are reached on any unknown event.  

**Actual Result**
State will stay the same.

**Reproduction**
https://codesandbox.io/s/cocky-varahamihira-skh3p

**Additional context**
4.6.x - not working
4.7.0-rc6 - working

**Comment by Andarist** [comment]
If they dont work in 4.6 then this was introduced in 4.7 - this should be mentioned in the docs. Would u like to prepare PR for this?

**Comment by davidkpiano** [comment]
This is now reflected in the docs: https://xstate.js.org/docs/guides/transitions.html#wildcard-descriptors

**Comment by 3plusalpha** [comment]
@davidkpiano Thanks a lot! I also just figured out, that in strict mode the wildcard option doesn't work. Maybe that should be mentioned too :)

**Comment by Andarist** [comment]
@3plusalpha this actually seems like a bug - could you prepare a repro case and report it as a new issue?

**Comment by 3plusalpha** [comment]
@Andarist yes, just a sec

**Comment by 3plusalpha** [comment]
#816
