### ISSUE TITLE
Problem with typestates on rc6, solved in rc7 but not on npm

### ISSUE THREAD

**Issue by schpet** [davidkpiano/xstate#819]
**Description**

Typestate type narrowing does not narrow types as described in 
https://xstate.js.org/docs/guides/typescript.html#typestates-coming-soon

I was able to get this to working locally by building / linking from github master, but would be convenient if this was on npm. no worries if a release is already on the way, just wanted to drop an issue incase other folks run into this.

**Expected Result**
Typestate type narrowing to occur

**Actual Result**

![image](https://user-images.githubusercontent.com/921605/69501444-d85e0380-0eb9-11ea-9f81-b68efa7a5082.png)

**Reproduction**
https://codesandbox.io/s/optimistic-murdock-tx78u
(line 62)

**Additional context**

XState version: 4.7.0-rc6

**Comment by schpet** [comment]
oh! apologies: i realize now that xstate and @xstate/fsm are totally different, and that this works fine on @xstate/fsm. closing this.

another question: is it possible to use typestates with xstate (not @xstate/fsm) today?

**Comment by davidkpiano** [comment]
> another question: is it possible to use typestates with xstate (not @xstate/fsm) today?

Yes, `npm install xstate@next`

**Comment by schpet** [comment]
thanks for confirming this! 

with `xstate@next`  and the [tutorial example](https://xstate.js.org/docs/guides/typescript.html#typestates-coming-soon) i expect to see the types narrowed, but they don't seem to be:

![image](https://user-images.githubusercontent.com/921605/69547748-fa539680-0f4a-11ea-88e8-112e344fa66e.png)

(i expect this to be narrowed to `User` and not `User|undefined`)

https://codesandbox.io/s/awesome-tree-qom29 / src/index.ts

is there something i'm missing?

**Comment by davidkpiano** [comment]
@schpet I need to fix this. Can you open a new issue for it?

To illustrate, this will work (notice how it's not from `.subscribe()`)

```js
  const state = userMachine.initialState;

  if (state.matches("success")) {
    // from the UserState typestate, `user` will be defined
    console.log(state.context.user.name);
  }
```
