### ISSUE TITLE
Typestates not working as expected with xstate

### ISSUE THREAD

**Issue by schpet** [davidkpiano/xstate#820]
**Description**

not able to narrow typestate types when subscribing to a state machine service

**Expected Result**

within a `state.maches("foo") { ... }` condition, types to be narrowed to the appropriate State type

**Actual Result**

types are not narrowed, you get the Context type

![xstate-issue](https://user-images.githubusercontent.com/921605/69552997-3d663780-0f54-11ea-82e7-0d305f45f89b.png)

**Reproduction**

https://codesandbox.io/s/awesome-tree-qom29 (see `src/index.ts` L62)

**Additional context**

- https://github.com/davidkpiano/xstate/issues/819#issuecomment-558201650
- this problem is specific to xstate, works as expected with @xstate/fsm

**Comment by RafalFilipek** [comment]
Example: https://github.com/RafalFilipek/xstate-typestates-bug

**Comment by davidkpiano** [comment]
Fix for this coming 🔜 but for now, this should be general a workaround:

```ts
if (state.matches<any>('something')) {
  // ...
}
```

**Comment by RafalFilipek** [comment]
https://github.com/RafalFilipek/xstate-typestates-bug I've just updated my example. Still no luck. I think I'll wait for fix. I can live with that since we have optional chaining and nullish coalescing :)

**Comment by LookRain** [comment]
Having same issue with `useMachine` from `@xstate/react`

**Comment by davidkpiano** [comment]
Fix being released soon-ish: #868
