### ISSUE TITLE
Event was sent to uninitialized service

### ISSUE THREAD

**Issue by PaulRBerg** [davidkpiano/xstate#821]
**Description**

I have a `validating` state on which I invoke a Promise that perform some async checks. When I go from `pristine` to `validating`, things work well, but not when I go from `ready` to `validating`. I get these warnings and the context does not get updated:

> Warning: Event "UPDATE" was sent to uninitialized service "createStreamSidebar.amount" and is deferred. Make sure .start() is called for this service.
> Event: "UPDATE"

I also made sure that this is not similar to issue #403.

> Warning: Event "done.invoke.hasErrors:invocation[0]" was sent to uninitialized service "createStreamSidebar.amount" and is deferred. Make sure .start() is called for this service.
> Event: {"type":"done.invoke.hasErrors:invocation[0]"}

**Expected Result**

The input should behave as it normally does.

**Actual Result**

The input remains frozen after 1 character is typed.

**Reproduction**

Here's a [CodeSandbox](https://codesandbox.io/s/unitialized-service-6ntls).

**Additional context**

- xstate@4.6.7
- @xstate/react@0.8.1

**Comment by davidkpiano** [comment]
Try this with `xstate@next`

**Comment by PaulRBerg** [comment]
Just tried it and now the warnings are gone, yet the input still gets stuck in the "ready" state with 1 character. I added a lot of logs to ensure that there is no logical bug in my code. The machine sends the `UPDATE` event but it's not handled correctly, even if the `ready` state does have `UPDATE` defined as one of the transitions of the `on` property.

![Xstate Unitialized Service](https://i.imgur.com/KMsXEZP.png)

You can see above that that React properly fires the `onChangeAmount` event, which sends the `UPDATE` event to the machine, but that's where it breaks.

**Comment by Andarist** [comment]
That happens because your ready state is final. When you reach a final state which is a direct descendant of the machine then the machine gets stopped. This is described in SCXML spec in example here - https://www.w3.org/TR/scxml/#enterStates . Notice this part of the pseudo code:
```
        if isFinalState(s):
            if isSCXMLElement(s.parent):
                running = false
```

**Comment by PaulRBerg** [comment]
Oh I totally missed the `type: final` definition, I must've added it to see what it does but then forgot about it.

Thanks @Andarist! I also noticed that version 4.7.0 (the non-beta one) has a more intuitive warning:

> Warning: Event "UPDATE" was sent to stopped service "createStreamSidebar.amount". This service has already reached its final state, and will not transition
