### ISSUE TITLE
@xstate/graph not including final state 

### ISSUE THREAD

**Issue by drmikecrowe** [davidkpiano/xstate#823]
**Description**

Using the [hierarchical state machine example](https://xstate.js.org/docs/guides/hierarchical.html) example code with `@xstate/test`, I changed the stop state to be final in the code.

```
    stop: { type: "final" },
```

The core logic difference between the two machines is:

![Screenshot-20191125073405-1218x230](https://user-images.githubusercontent.com/90312/69589890-9f0dbc80-0fbb-11ea-9536-07b6f560abba.png)

- Test case 1: `machine.js`: Sub-state goes into final state. Parent uses event to move to next state (see [machine code here](https://github.com/drmikecrowe/xstate-test-lightmachine/blob/master/machine.js#L59))
- Test case 2: `machine-final.js`: Sub-state goes into final state. Parent uses `onDone` to move to the next state (see [machine-final code here](https://github.com/drmikecrowe/xstate-test-lightmachine/blob/master/machine-final.js#L60))

**Expected Result**
```
    reaches state {"red":"wait"} (undefined)
      ✓ via POWER_RESTORED → PED_COUNTDOWN
    reaches state {"red":"stop"} (undefined)
      ✓ via POWER_RESTORED → PED_COUNTDOWN → PED_COUNTDOWN (1ms)
```

**Actual Result**
```
    reaches state {"red":"wait"} (undefined)
      ✓ via POWER_RESTORED → PED_COUNTDOWN
```

**Reproduction**

I've created [a demo repo here](https://github.com/drmikecrowe/xstate-test-lightmachine.git)).

**Additional context**

The full `jest` output is:

```
 FAIL  ./machine.test.js
  LightMachine Test
    ✓ should have full coverage (1ms)
    reaches state "green" (undefined)
      ✓ via  (2ms)
    reaches state {"red":"blinking"} (undefined)
      ✓ via POWER_OUTAGE (1ms)
    reaches state {"red":"walk"} (undefined)
      ✓ via POWER_RESTORED
    reaches state "yellow" (undefined)
      ✓ via TIMER
    reaches state {"red":"wait"} (undefined)
      ✓ via POWER_RESTORED → PED_COUNTDOWN
    reaches state {"red":"stop"} (undefined)
      ✓ via POWER_RESTORED → PED_COUNTDOWN → PED_COUNTDOWN
  LightMachine Final Test
    ✕ should have full coverage (8ms)
    reaches state "green" (undefined)
      ✓ via 
    reaches state {"red":"blinking"} (undefined)
      ✓ via POWER_OUTAGE
    reaches state {"red":"walk"} (undefined)
      ✓ via POWER_RESTORED
    reaches state "yellow" (undefined)
      ✓ via TIMER
    reaches state {"red":"wait"} (undefined)
      ✓ via POWER_RESTORED → PED_COUNTDOWN

  ● LightMachine Final Test › should have full coverage

    Missing coverage for state nodes:
        light.red.stop

      68 | 
      69 |   it("should have full coverage", () => {
    > 70 |     return lightModelFinal.testCoverage();
         |                            ^
      71 |   });
      72 | });
      73 | 

      at TestModel.testCoverage (node_modules/@xstate/test/src/index.ts:300:13)
      at Object.it (machine.test.js:70:28)
```

**Comment by arturohernandez10** [comment]
I don't know. But in the case I reported. There is another state missing and it isn't final.

**Comment by hanyufoodles** [comment]
I've got the same issue. Final state on a sub-machine with onDone transition will be not be tested even if meta with test is specified.

**Comment by davidkpiano** [comment]
This can now be accomplished in the same way as #718 - by using the `filter` option in `model.testCoverage({ option: ... })` to disregard that state.

https://xstate.js.org/docs/packages/xstate-test/#testmodel-testcoverage-options
