### ISSUE TITLE
[TS] 4.7.0-rc7  Actor casting broken in rc7

### ISSUE THREAD

**Issue by semopz** [davidkpiano/xstate#828]
**Description**
I think we'll really benefit if the the  [Typescript example](https://github.com/davidkpiano/xstate/blob/master/docs/guides/typescript.md) was extended to include actors. I'm probably not doing it right, but the latest rc no longer likes how I cast my actors in my machine context.

**Expected Result**
Spawning actors should not cause TS errors

**Actual Result**

> Type 'ServiceActor<LightContext, LightEvent>' is missing the following properties from type 'Interpreter<LightContext, LightStateSchema, LightEvent>': machine, clock, options, scheduler, and 44 more.ts(2352)

**Reproduction**
1. Go to https://codesandbox.io/s/frosty-maxwell-66355
2. Wait for TS to init and observe the error on line 97 in index.ts
3. change xstate dep version to 4.7.0-rc6
4. **Important** reload the page
5. Wait for TS to init
6. There should be no error

**Additional context**
xsstate  - 4.7.0-rc7
TS - 3.3.4000
Notice that I've adapted the traffic light example by making the lightMachine a function that returns a machine. Also, added a dummy machine that spawns the lightMachine using said function.

**Comment by semopz** [comment]
This looks to be resolved in 4.7.2 so thank you for that. 

I see that the issue is tagged with `documentation` as well so I'll leave you @davidkpiano to decide when to close the issue (I assume you've left this ticket open as a reminder).

**Comment by davidkpiano** [comment]
No documentation needed since I've simplified the types so things should "just work".
