### ISSUE TITLE
Visualizer doesn't display all guarded transitions

### ISSUE THREAD

**Issue by hrafnkellpalsson** [davidkpiano/xstate#834]
**Description**
When multiple guarded transactions from an invoked promise lead _to the same state_, only one transition arrow is displayed in the visualizer.

**Expected Result**
I expect to see a transition arrow in the visualizer for every guarded transaction.

**Actual Result**
Only last guarded transaction shows an arrow in the visualizer.

**Reproduction**
[Bug in XState Visualizer](https://xstate.js.org/viz/?gist=76fdc4b698f40f649abaa7ba3700c57f)

**Additional context**
I realize the docs say don't overuse guarded transactions (https://xstate.js.org/docs/guides/guards.html#multiple-guards) but this looks like a bug nevertheless?

❤️XState❤️

**Comment by davidkpiano** [comment]
I'm reworking the visualizer and it will be updated by the end of the year.

**Comment by davidkpiano** [comment]
Closing this in favor of using [the inspector](https://xstate.js.org/docs/packages/xstate-inspect) instead.
