### ISSUE TITLE
[4.7] forwardTo is not exported

### ISSUE THREAD

**Issue by hnordt** [davidkpiano/xstate#840]
`forwardTo` action is documented at https://xstate.js.org/docs/guides/actions.html#forward-to-action, but it was not exported.

**Comment by davidkpiano** [comment]
Want to make a PR?

**Comment by toadslick** [comment]
Opened PR #844 to address this

**Comment by Andarist** [comment]
Fixed in https://github.com/davidkpiano/xstate/pull/844
