### ISSUE TITLE
[RFC] Re-implementation of DevTools integration in XState (#2)

### ISSUE THREAD

**Issue by amitnovick** [davidkpiano/xstate#848]
# Suggestion
Changing the `devTools` key from a boolean-type value to a function-type value (and optionally also an array of functions).

# Motivation
The service started by XState's `interpret` is currently tightly coupled to a specific DevTools interface (namely the Redux DevTools).

By externalizing this logic, and changing the value accepted by `devTools` key we can:
- ⬇ reduce bundle size of XState core
- 🔧 make XState interpreter easier to maintain (no need to keep track of how an external devtool is implemented)
- 🌟 enable features for other DevTools extensions (see: [XState DevTools](https://github.com/amitnovick/xstate-devtools)) such as removing stopped services
- 🐛 fix bugs with using multiple DevTools extensions: developers wouldn't have to disable an extension when working on different projects when XState itself is not relying on it being available on the Redux DevTools global value.

## What does it look like?
```js
// right now
interpret(machine, { devTools: true });

// after change
import { xstateDevtools, reduxDevtools } from '@xstate/devtools';

interpret(machine, { devTools: xstateDevtools });
interpret(machine, { devTools: [xstateDevtools, reduxDevtools] }); // or multiple
```

## How does it work?
```js
// packages/core/src/Interpreter.ts
class Interpreter {
  start() {
    if (this.options.devTools) {
      this.attachDev();
    }
  }
  attachDev() {
    if (typeof this.options.devTools === 'function') {
      this.options.devTools(this);
    } else if (Array.isArray(this.options.devTools)) {
      this.options.devTools.forEach(registerDevTool => registerDevTool(this));
    }
  }
}
```

### What are `xstateDevtools` and `reduxDevtools` from `@xstate/devtools`?
```js
export function xstateDevtools(service) {
  // will access the interface of the respective devtool directly from a global value
  const devtoolInterface = window.__XSTATE_DEVTOOLS_EXTENSION__;
  if (devtoolInterface) {
    service.onStart(() => { devtoolInterface.whatever(...) }) 
    service.onEvent(() => { devtoolInterface.whatever(...) })
    service.onSend(() => { devtoolInterface.whatever(...) })
    service.onStop(() => { devtoolInterface.whatever(...) })
    service.onTransition(() => { devtoolInterface.whatever(...) })
  }
}
```

```ts
export function reduxDevtools(service) {
  // will access the interface of the respective devtool directly from a global value
  const devtoolInterface = window.__REDUX_DEVTOOLS_EXTENSION__;
  if (devtoolInterface) {
    devtoolInterface.connect({
      name: service.id,
      autoPause: true,
      stateSanitizer: (state: State<any, any>): object => {
        return {
          value: state.value,
          context: state.context,
          actions: state.actions
        };
      },
      ...devToolsOptions, // various ways to implement passing these options
      features: {
        jump: false,
        skip: false,
        ...(devToolsOptions
        ? (devToolsOptions as any).features
        : undefined)
      }
    }, service.machine);

    service.onStart((state) => { devtoolInterface.init(state) }) 
    service.onEvent((event) => { devtoolInterface.send(event) })
    service.onSend((event) => { devtoolInterface.send(event) })
    // Redux DevTools doesn't expose a method for stopping a store so no need to listen to `onStop`
    service.onTransition(() => { devtoolInterface.whatever(...) })
  }
}
```

**Comment by amitnovick** [comment]
@davidkpiano It looks like you went ahead and implemented a slight variation of this in https://github.com/davidkpiano/xstate/blob/master/packages/core/src/devTools.ts

In your implementation
- only one devtools is registered (the one accessible from the global `__xstate__` binding)
- the `__xstate__` binding must have a method `register` with the signature (service) => void

I also notice that the `DevInterface` interface has a `services` property a method `onRegister`, which aren't being used, but I guess that you decided to add it as an example to what the interface could look like (although there is no requirement that they would be there).

It looks like a great approach, and it avoids two things:
- having to import a devtool instance in every `interpret` call site
- changing the existing `devTools` option syntax

**Comment by Andarist** [comment]
I like general idea of simplifying this and making XState more decoupled from devtools. 

I think we should also consider if it’s possible to remove any devtools-specific code from XState in favor of devtools integrating with XState using other, general-purpose APIs. Redux has approached this really nicely although they had it a little bit easier thanks to everything being built on top of middleware API and also that most of the time you have only a single store in your app. We shouldnt decrease ergonomics much with a chosen approach but I believe that some added boilerplate (on a consumer’s side) wouldnt be too terrible.

**Comment by davidkpiano** [comment]
I think the general approach of:

```js
if (options.devTools && window.__XSTATE__) {
  window.__XSTATE__.register(this);
}
```

is minimal enough to eliminate boilerplate even though there's a tiny bit of devtools-specific code.

**Comment by Andarist** [comment]
Yes - that wouldnt be too much extra code. Problem with this approach is different though - it somewhat ties internals to a specific implementation of devtools. This is something that Amit is proposing we dont do - and I also believe it would be better approach. Any devtools should be able to plug into XState (if only they satisfy interface/protocol), rather than XState registering into a single possible devtool.

**Comment by davidkpiano** [comment]
Okay, after rereading, I like this proposal. We can make it minimal:

```js
attachDev(attachFn = this.options.devTools) {
  attachFn(this);
}
```

If, for some reason, developers want to attach multiple dev tools, its their responsibility to compose the functions:

```js
interpret(machine, { devTools: compose(xstateDevTools, reduxDevTools) })
```

Which I'm fine with because that won't be a common use-case.

**Comment by amitnovick** [comment]
There's a tradeoff here between the attempt to remove complexity from the library and the ease of use for the user (ergonomics). 

The suggestion in my first post in this thread I valued the former, but after seeing @davidkpiano's version, I think that we would do best to take the (small) hit of complexity, for the benefit of the end-user.

Importing stuff can be really annoying for a user who just wants to inspect his app. Oh and if we really care about reducing complexity from `core`, then the functions for `xstateDevtools` and `reduxDetools` would have to come from external package(s). So now we would have to remind users to `npm i @xstate/devtools` before he can get to the good stuff.

I don't want that. I think users expect everything to be easy, otherwise they would not bother with it, or not stick with it for long term. So let's be user-centric.

And while we're doubling down on user-centric design, let's go ahead and remove the requirement for plugging in the `devTools` option at all. User is in development mode? i.e. `process.env.NODE_ENV !== 'production'`, so let's register to the devtools.

@Andarist not trying to dismiss your support for my suggestion, and feel free to disagree with me now, but when I think about what's best I would go with what @davidkpiano has done over mine.

**Comment by amitnovick** [comment]
Oh and about Redux Devtools support, I think we should keep the custom logic for it in there (currently in `attachDev`) **for the time being**, for the sake of users who rely on features only available in it.

I want to reach full feature parity in my XState DevTools, which right now as far as I can tell only means implementing the `context` diff view for every event in the Events tab (I expect this to be quite straightforward to implement, I could probably do it over the weekend).

So when the XState DevTools can do everything the Redux extension can (and more! e.g. Visualizer, stopping services etc.), we can go ahead and remove that custom Redux logic from `attachDev` and just tell users to switch to the official extension.

Other devtools can still work and if even 1% of users want to use a different devtool, the only interface they would have to implement is the `register` method, and expose the interface on the `window.__xstate__` binding.

**Comment by davidkpiano** [comment]
Redux DevTools support is staying in v4 for now - probably removed in v5 once we have the full-featured XState DevTools.

The default dev tools can be this: https://github.com/davidkpiano/xstate/issues/848#issuecomment-568270438 which gives it automatic support for XState.

In V5+, I don't believe there is any value to be gained by supporting the possibility of multiple dev tools, but of course we can make it easy to add an adapter if people want that.

Overall, the proposal is:

**Enable XState dev tools**

```js
const service = interpret(machine, { devTools: true });
```

**Enable other dev tools**

```js
import { devToolsAdapter } from '@xstate/redux'; // or similar

const service = interpret(machine, { devTools: devToolsAdapter });
```

~**Enable multiple dev tools**~

Don't support this for now. It doesn't make sense - why would you have more than one dev tool open for a single app, especially if one does the same thing as the other?

**Comment by amitnovick** [comment]
Gonna pitch this suggestion again, because I think it is the easiest for users and makes the most sense  @davidkpiano @Andarist 

- no `devTools` option required, but XState checks for `process.env.NODE_ENV !== 'production'` to register a single XState Devtools (assumed to be available on the `window.__XSTATE__`)
-  XState implementation:
```js
 if (process.env.NODE_ENV !== 'production' && window.__XSTATE__) {
  window.__XSTATE__.register(this);
}
```

**Comment by amitnovick** [comment]
(If there is no `window` object, use `global` for Node.js)

**Comment by davidkpiano** [comment]
Let's consider this closed now that [`@xstate/inspect`](https://xstate.js.org/docs/packages/xstate-inspect/) is out.
