### ISSUE TITLE
Control the entry of history

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#85]
## Description:

In Statecharts paper by Harel, history is denoted by way of `(H)` and `(H)*` markers for shallow and deep history, respectively.  In scxml, it is not possible to indicate this, only transition to a (magic) `$history` state.  In order to be able to provide things like default history and actions on the history transition, a state should be able to specify history notation.

## (Feature) Potential implementation:

Proposed API addition:

```typescript
export interace RequiredTransitionConfig {
  actions?: Action[]
  target: string | string[];
}
export interface StateNodeConfig {
  history?: boolean | string | RequiredTransitionConfig;
  deepHistory?: boolean | string | RequiredTransitionConfig;
}
```

All states referenced must be relative to the state where the initial property is defined.
Referenced states MUST be descendent states.

The boolean form of `history` and `deepHistory` would indicate that shallow (or deep) history _should_ be used.  If `true` then history is retained, but there is no default history, meaning that the _initial_ transition should be taken if a state does not have history.
The string form of `history` and `deepHistory`, this would be equivalent to `true` however, the string would denote the default state.
The complex form is also equivelent to `true` but allows specifying more than one default states (for targetting states in different regions of a parallel child state), and it would allow actions.

The `RequiredTransitionConfig` also fits to be used as the type of an `initial` state, this is why it's not called a _HistoryTransitionConfig_.

This should be possible to implement in a backwards compatible way, as it only specifies additions to the configuration; and does not change how you target the history state.  The idea is still to specify `$history` as the target for the shallow history, and introduce `$deepHistory` to target the deep history.  It might be that the boolean form of the `history` property is not needed; simply work as today, recording history for all states as today.

In case a transition is taken to a `$history` state, but there is no `history` defined, then a backwards compatible implementation would record history regardless.  Only a `history: false` would cause an error.  A future, backwards incompatible change could be that `$history` is only allowed when `history: true` (or truthy).

This is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/)

**Comment by mogsie** [comment]
As I wrote this I got some mixed feelings about what we want to achieve with respect to deep and shallow histories: The ability to (better) control the history entry.

I wonder if the following model would be better:

1. each state has a default history entry mode (shallow?)
2. It's possible to use the `$history` target to enter the states default entry mode.
3. It's possible to specify a state's default history mode, (e.g. by specifying `history: 'shallow'`).
4. It's possible to specify a default history by specifying `history: {shallow: 'foo' }`.
5. It's possible to specify actions or multiple default history states by specifying `history: {shallow: { target:['foo','bar'], actions:['a'] } }`.
6. If you really want two history states, you could specify `history: {shallow: 'foo', deep:'bar' }`.
7. If you have defined the two "modes" of history, then you _have_ to specify which type of history you're targetting in the transition:  `on: {something: 'foo.$history.deep'}` 

An example state would then be:

```js
history: (see below),
states: {
  A: {
    initial: 'B',
    states: {
      B: {
        initial: P,
        states: {
          P: {},
          Q: {}
        }
      }
      C: {
        initial: P,
        states: {
          P: {},
          Q: {}
        }
      }
    }
  }
}
```

| Example `history` | Meaning                                                                                 |
|-------------------|-----------------------------------------------------------------------------------------|
| undefined         | if $history is targetted, remember history or enter the initial state.  Shallow history |
| 'A.B.P'             | 'A.B.P' is the default history.  Retain shallow history.                                  |
| { deep: 'A.C' }   | 'A.C' is the default history, but retain deep history. |
| { shallow: true, deep: true } | Use initial states as defaults, but retain deep and shallow histories, require any transitions to target `.shallow` or `.deep` otherwise throw an Error |
| { deep: { targets: [ 'A.B.Q', 'A.C.Q'], actions: ['foo'] } } | (only if A is a parallel state), Specify that `$history` is deep, default targets, and actions to take. |

**Comment by davidkpiano** [comment]
Although I like the second proposal, after reading the spec, it seems we have to go with the first proposal, because `<history>` can occur 0 or more times.

That way, the developer can specify different history IDs that go to different default states, which makes sense (although I can't come up with a clear example right now... it's news to me too).

**Comment by mogsie** [comment]
That's just swell! but I guess it means a lot to align more closely with scxml and UML.

I think then we should put history states alongside normal state configurations, not even giving them magic identifiers.

I propose a new type `HistoryStateNodeConfig` which accepts `history: 'deep'` which transforms it into a history state:

* `StateNodeConfig` would have `history?: 'deep' | 'shallow' | undefined`
* `SimpleStateNodeConfig` would have `history: undefined`
* `HistoryStateNodeConfig` would have `history: 'deep' | 'shallow'`

The `HistoryStateNodeConfig` would have a new key for the default history, and null out everything else that isn't relevant:

```
export interface HistoryStateNodeConfig {
  history: 'deep' | 'shallow';
  default: RequiredTransitionConfig;
  states?: undefined;
  initial?: undefined;
  onEntry?: undefined; 
  // etc ensuring that only `default` is present.
}
```

The state machine from previous example would then be:

```js
states: {
  H1: {
    history: 'shallow'
  }
  H2: {
    history: 'deep'
  }
  H3: {
    history: 'deep',
    default: 'A.C.Q'
  }
  H4: {
    history: 'deep',
    // the following only if A is a parallel state
    default: { targets: [ 'A.B.Q', 'A.C.Q'], actions: ['foo'] } }
  }
  A: {
    initial: 'B',
    states: {
      B: {
        initial: P,
        states: {
          P: {},
          Q: {}
        }
      }
      C: {
        initial: P,
        states: {
          P: {},
          Q: {}
        }
      }
    }
  }
}
```

**Comment by davidkpiano** [comment]
Some modifications:

```typescript
export interface HistoryStateNodeConfig {
  history?: 'deep' | 'shallow'; // default: shallow per SCXML
  target: RequiredTransitionConfig; // instead of "default"
  actions?: Action[]; // because a history transition can have exec. content
}
```

We can maybe bikeshed `target` to `initial`, but that may be overloading the term. Thoughts? (the other state node config properties missing here are assumed to be `never` or `undefined`).

**Comment by mogsie** [comment]
Closing this issue.  Wrote a new issue, #86 which captures the updated requirements.
