### ISSUE TITLE
Calling batches event changes an actor

### ISSUE THREAD

**Issue by bradwoods** [davidkpiano/xstate#856]
Scenario 1: An event is called that triggers a state transition. When the new state is entered, an actor is spawned. In the console, you can see this actor is of type _Interpreter_.

Scenario 2: You call the same event as a batch. The actor is not of type _Interpreter_, rather it is an object. I'm also seeing a warning _Attempted to spawn an Actor (ID: "myActor") outside of a service. This will have no effect._ I'm not sure what is meant by this. 

See https://codesandbox.io/s/machine-spawn-playground-v1b0w

**Comment by Andarist** [comment]
Thanks for the report - gonna take a look at this today.

**Comment by Andarist** [comment]
I've prepared a fix for the second one - https://github.com/davidkpiano/xstate/pull/858 , but I'm not quite sure what a problem in scenario 1 is. Could you describe both actual & expected results?

**Comment by bradwoods** [comment]
I should have reworded. Scenario 1 wax the expected result. Sorry for the confusion.
