### ISSUE TITLE
Explicit history states

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#86]
## Description:

In Statecharts paper by Harel, history is denoted by way of `(H)` and `(H)*` markers for shallow and deep history, respectively.  In xstate, it is not possible to indicate this, only transition to a (magic) `$history` state.  In order to be able to provide things like default history and actions on the history transition, a state should be able to specify these.  Both UML and SCXML define a type of state called a 'history' state..

## (Feature) Potential implementation:

Proposed API addition:

StateNodeConfigs can be of type history, if the `history` property is specified, causing the state to be either a deep or shallow state.  Indeed the state looks more like a transition configuration.

```typescript
export interface HistoryStateNodeConfig (extends StateNodeConfig??) {
  history?: 'deep' | 'shallow'; // default: shallow per SCXML
  target: RequiredTransitionConfig; // instead of "default"
  actions?: Action[]; // because a history transition can have exec. content
}
```

History states could be allowed a 'key' to provide a unique machine-wide key to the state, like regular states.  

All states referenced must be relative to the state where the history is defined.
Referenced states MUST be descendent states.

The `RequiredTransitionConfig` also fits to be used as the type of an `initial` state, this is why it's not called a _HistoryTransitionConfig_.

The other states (outside the state in question) can target the history state as with any other state:

```
states: {
  H1: {
    history: 'shallow'
  },
  H2: {
    history: 'deep'
  },
  H3: {
    history: 'deep',
    target: 'A.C.Q'
  },
  H4: {
    history: 'deep',
    actions: ['foo'],
    // the following only if A is a parallel state
    target:[ 'A.B.Q', 'A.C.Q']
  },
  A: {
    initial: 'B',
    states: {
      B: {
        initial: P,
        states: {
          P: {},
          Q: {}
        }
      },
      C: {
        initial: P,
        states: {
          P: {},
          Q: {}
        }
      }
    }
  }
}
```

The H1 through H4 are essentially like any other state, when it comes to naming them

This should be possible to implement in a backwards compatible way, as it only specifies additions to the configuration;   It would still be possible to keep the behaviour of specifying `$history` as the target for the shallow history.  Removing this feature would be a breaking change but does not influence this proposal in any way.

This is part of the existing [SCXML specification](https://www.w3.org/TR/scxml/#history)

**Comment by davidkpiano** [comment]
Finished in 6d0cbc7

**Comment by AnimaLupi** [comment]
Hello, is this working in 3.3.0?

I just added "history: 'shallow'" to some of my states config but TS complains (lookings at interface definitions, the MachineConfig is defined with "history?: false | undefined").

It still compiles, but when I try to run the statechart I get a maximum stack calls exceeded.

Is it a bug, a work in progress or am I simply messing things up? :-)

**Comment by davidkpiano** [comment]
@AnimaLupi can you open a new issue for this? Maybe something broke (hopefully not!)

**Comment by AnimaLupi** [comment]
@davidkpiano opened issue #120 .
