### ISSUE TITLE
Typescript compilation error when assigning boolean

### ISSUE THREAD

**Issue by azixMcAze** [davidkpiano/xstate#863]
**Description**
When using a strongly typed state machine, using `assign()` with an object to update a boolean in the context results in a typescript compilation error.
Using `assign()` with a function assigner compiles without error.

**Expected Result**
Using an object or a function assigner should both work correctly

**Actual Result**
A compilation error on the `states` property.

**Reproduction**
Using this state machine declaration:
```typescript
import { assign, Machine } from 'xstate';

interface MachineSchema {
    states: {
        a: {};
    };
}

type MachineEvent = { type: 'A' };

interface MachineContext {
    val: boolean;
}

export const machine = Machine<MachineContext, MachineSchema, MachineEvent>(
    {
        initial: 'a',
        context: {
            val: false,
        },
        states: {
            a: {
                // entry: assign({ val: (ctx, event) => true }), // OK
                exit: assign({ val: true }), // not OK
            },
        }
    }
);
```
I get this compilation error:
```
src/testStateMachine.ts:21:9 - error TS2322: Type '{ a: { exit: AssignAction<{ val: true; }, MachineEvent>; }; }' is not assignable to type 'StatesConfig<MachineContext, MachineSchema, MachineEvent>'.
  The types of 'a.exit' are incompatible between these types.
    Type 'AssignAction<{ val: true; }, MachineEvent>' is not assignable to type 'string | ActionObject<MachineContext, MachineEvent> | ActionFunction<MachineContext, MachineEvent> | ... 4 more ... | undefined'.
      Type 'AssignAction<{ val: true; }, MachineEvent>' is not assignable to type 'AssignAction<Required<MachineContext>, MachineEvent>'.
        Types of property 'assignment' are incompatible.
          Type 'Assigner<{ val: true; }, MachineEvent> | PropertyAssigner<{ val: true; }, MachineEvent>' is not assignable to type 'Assigner<Required<MachineContext>, MachineEvent> | PropertyAssigner<Required<MachineContext>, MachineEvent>'.
            Type 'Assigner<{ val: true; }, MachineEvent>' is not assignable to type 'Assigner<Required<MachineContext>, MachineEvent> | PropertyAssigner<Required<MachineContext>, MachineEvent>'.
              Type 'Assigner<{ val: true; }, MachineEvent>' is not assignable to type 'Assigner<Required<MachineContext>, MachineEvent>'.
                Types of parameters 'context' and 'context' are incompatible.
                  Type 'Required<MachineContext>' is not assignable to type '{ val: true; }'.

21         states: {
           ~~~~~~

  ../node_modules/xstate/lib/types.d.ts:267:5
    267     states?: StatesConfig<TContext, TStateSchema, TEvent> | undefined;
            ~~~~~~
    The expected type comes from property 'states' which is declared here on type 'MachineConfig<MachineContext, MachineSchema, MachineEvent>'
```
The function assigner compiles correctly.
Using a `string` or a `number` in the context compiles correctly.

**Additional context**
xstate 4.7.2
typescript 3.7.3

**Comment by davidkpiano** [comment]
TypeScript inference is not perfect. The responsible thing to do is to specify the context as a generic:

```ts
exit: assign<MachineContext>({ val: true })
```

**Comment by CMCDragonkai** [comment]
I find that now we also need to specify exactly the event object as well:

```
actions: assign<BackupRestoreContext, {type: 'DELETE_RESTORE'}>({ backedUp: false }),
```

If I don't specify the exact event object, it will still result in a type error.

**Comment by Andarist** [comment]
@CMCDragonkai I have a pending fix in the pipeline for this as in - no explicit generics should be given to `assign` if it's being used "inline" within the first argument passed to the `createMachine`. I hope it will solve many cases like this - but we'll have to see how it plays out. Our types are quite complex so it's hard to test this without actually releasing this to the community. 

That potential fix is waiting for https://github.com/davidkpiano/xstate/pull/1543 to be merged as this is an enabler PR for that fix.

**Comment by dminkovsky** [comment]
Sorry to comment on this ticket as this is related to the Event type and not the Context type, but: what if not the assign is specified not inline but as a string? And if `TEvent` is an intersection of many types? Currently I am doing this:

```
interface Context {...}
type Event = EventA | EventB

...

useMachine(Machine<Context, Event>({...}), {actions: {action1}})

...

const action1 = assign<Context, Event>({
    field: (context, event) => {
        const eventA = event as EventA;
        ...
    }
})
```

Is this the best way to handle the non-inline case with events? Will this change going forward?

Thank you
