### ISSUE TITLE
[4.7.2] [TS] Spawn function returns incomplete Interpreter

### ISSUE THREAD

**Issue by DirkWolthuis** [davidkpiano/xstate#869]
**Description**
When using the spawn function on with a fully typed StateMachine, the returned Interpreter has the type of `Interpreter<SelectProductStateMachineContext, any, EventObject>`.

**Expected Result**
I expect that the returned Interpreter has the type: `Interpreter<SelectProductStateMachineContext, SelectProductStateSchema, SelectProductEvents>`. 

**Actual Result**
It returns `Interpreter<SelectProductStateMachineContext, any, EventObject>` and that value is not assignable to my typed context. 

**Additional context**
Workaround: 
```typescript
spawn(
    selectProductStateMachine.withContext({
        products: [],
        productDescription: null,
        productName: null,
        selectedProductId: null
    })
) as unknown as Interpreter<
SelectProductStateMachineContext,
SelectProductStateSchema,
SelectProductEvents
>;

```

**Comment by davidkpiano** [comment]
What do you need the schema for? Just curious.

**Comment by DirkWolthuis** [comment]
Hi @davidkpiano, I don't. I just thought this was the correct way of typing my context.

```typescript
  selectProductOptions: {
        ref: Interpreter<
            SelectProductOptionsStateMachineContext,
            SelectProductOptionsStateSchema,
            SelectProductOptionsEvents
        >;
    } | null;
```

The schema could be `any`, but I have it right there so why not use it I thought?

**Comment by davidkpiano** [comment]
I believe this is fixed. Check 4.7.8 and please report back if this is not working for you.
