### ISSUE TITLE
Allow ordering states consistently

### ISSUE THREAD

**Issue by mogsie** [davidkpiano/xstate#87]
## Description:

In SCXML, states have an implicit priority in the document order.  This document order is referenced in various edge cases:

- When equally "important" conflicting transitions exist, document order wins; the earliest transitions in the document wins.
- When parallel states are entered, they are entered in document order, and exited in reverse document order

## Potential implementation:

A simple priority field could be introduced to allow disambiguating the "order" of states within a compound and parallel states.

```js
{
  key: 'foo',
  states: {
    A: {
      priority: 1
    },
    B: {
      priority: 2
    }
  }
}
```

Either that, or an "order" key could be added to the compound or parallel state:

```js
{
  key: 'foo',
  order: ['A', 'B'],
  states: {
    A: {},
    B: {}
  }
}
```

**Comment by davidkpiano** [comment]
In V4, there will be an `order: number` property on the state.
