### ISSUE TITLE
Compose TypeStates

### ISSUE THREAD

**Issue by remkoboschker** [davidkpiano/xstate#870]
## Feature request

I like the TypeState interface to define the type of the context. I can specify a TypeValue and the type of the context, but if I have hierarchical states I do no see how I can continue along the same lines. For example: 

```
interface mainStateSchema {
   states: {
        user: {
            states: { 
                'idle': {},
                'loading': {}
             }
        },
        light: {
              states: {
                    'red': {},
                    'green': {}
              }
        }
}


type UserState =
  | {
      value: 'idle';
      context: UserContext & {
        user: undefined;
        error: undefined;
      };
    }
  | {
      value: 'loading';
      context: UserContext;
    }

type LightState = 
| { value: 'red' } | { value: 'green' }

type MainState = UserState | LightState 
// but where do I put the values?
```

## Potential implementation:

Perhaps the TypeState interface can be extended to 
```
type TypeState<T,V> = {
    value: string,
    context: T,
    substate?: V
} 
```
Where V is constrained to be a disjunctions of typestates.

**Comment by davidkpiano** [comment]
I'd love to see a PR for this, but to my knowledge, you can do this:

```ts
type SomeState = |
  // ...
  | {
    value: { nested: 'foo' },
    context: {/* ... */}
  }
```

**Comment by remkoboschker** [comment]
Can the nested have a context of a type as well?

**Comment by remkoboschker** [comment]
I thought I could only use a string as per https://github.com/davidkpiano/xstate/blob/a1d7414338b0e85cc4af2da107fe8bc817f4c37c/packages/xstate-fsm/src/types.ts#L102

**Comment by remkoboschker** [comment]
I am just starting out with xstate. Will revisit en perhaps write a pr when I get my bearings.

**Comment by remkoboschker** [comment]
I think what confused me is that I assumed that the context would be nested as well, but it seems that the machine has a singel context, that is used by all (sub)states.
