### ISSUE TITLE
How to represent events that have multiple possible new states

### ISSUE THREAD

**Issue by karl** [davidkpiano/xstate#88]
What is the best way to represent an event having multiple possible new states
(based on some external state).

For example consider the following state machine:

``` js
{
  initialState: 'app',
  states: {
    'closed': {
      on: {
        'open': 'opened',       // for admins
        'open': 'doubleCheck',  // for non-admins
      }
    },
    'doubleCheck': {
      on: {
        'confirm': 'opened',
        'cancel': 'closed',
      }
    },
    'opened': {
      on: {
        'close': 'closed',
      }
    }
  }
}
```

When the user clicks `open` we want to move them to a different state based
on whether or not they are an admin (state which is not encoded in our state
machine).

Is there a best practice for handling this?

Would it just be to use `cond` for each transition? I guess this requires the
developer to ensure that both conditions will never evaluate to true at the same
time.

Apologies if this question has been answered before! I had a search through the docs and issues but couldn't find an answer.

**Comment by karl** [comment]
Oh man, it looks like I've just found an example of this in the docs:

http://davidkpiano.github.io/xstate/docs/#/api/config (search for `cond`).

It looks like you would handle it like so:

```
{
  initialState: 'app',
  states: {
    'closed': {
      on: {
        'open': { 
          'opened': { cond: () => {} },
          'doubleCheck': {cond: () => {} }
        }      
      }
    },
    'doubleCheck': {
      on: {
        'confirm': 'opened',
        'cancel': 'closed',
      }
    },
    'opened': {
      on: {
        'close': 'closed',
      }
    }
  }
}
```

Although it isn't clear what would happen if both conditions evaluated to true. How does `xstate` know which state to move into?

**Comment by davidkpiano** [comment]
> Although it isn't clear what would happen if both conditions evaluated to true. How does xstate know which state to move into?

I have to add this to the docs, but they're evaluated in order. You can be more explicit about this by providing an array:

```
    'closed': {
      on: {
        'open': [
          { target: 'opened', cond: (extState) => { extState.user.type === 'admin' } },
          { target: 'doubleCheck', cond: () => {} },
		  { target: 'someDefaultTarget' }
        ]
      }
    },
```

Which will evaluate each candidate transition in order, until it finds one where the `cond` is satisfied.

**Comment by karl** [comment]
Just a couple more questions if I may!

* Would it be helpful if I added an example of this to the docs? If so should I just make a PR for this file (https://github.com/davidkpiano/xstate/blob/gh-pages/docs/guides/guards.md) or is there more to a docs change?

* It looks like conditional transitions are not supported by the Statechart Visualizer (https://codepen.io/davidkpiano/full/ayWKJO/). Is there some way I can help out and add support for them?

**Comment by karl** [comment]
One more question that I couldn't find an answer for in the docs:

* What happens if an error is thrown in a `cond` function? Does it just cause an error to be thrown when calling `machine.transition`?

**Comment by davidkpiano** [comment]
> Would it be helpful if I added an example of this to the docs?

Yes! Just make it to `gh-pages` and you're good.

> It looks like conditional transitions are not supported by the Statechart Visualizer 

They'll be supported in the next version of the visualizer, which will be released as a separate package in a couple weeks.

> What happens if an error is thrown in a cond function? Does it just cause an error to be thrown when calling machine.transition?

I'd think so. It'd be up to the interpreter on how to handle that error (whether you make the interpreter yourself or use a pre-made one, which will also be released in a couple weeks).

**Comment by karl** [comment]
I've created a first PR which adds an interactive example of how to use conditional guards:

https://github.com/davidkpiano/xstate/pull/89

**Comment by karl** [comment]
I've had a moment to create a PR to update the docs with support for an array of state transition mappings:

https://github.com/davidkpiano/xstate/pull/92

**Comment by davidkpiano** [comment]
Thanks so much @karl! Tiny comment but otherwise looks 👍

**Comment by karl** [comment]
Closing this as docs have been updated to reflect what I've learnt 😀
