### ISSUE TITLE
[Visualizer] Visualize variables of custom guards

### ISSUE THREAD

**Issue by CodingDive** [davidkpiano/xstate#881]
**Description**
I'd love to be able to see the variables and values passed to custom guards directly within the visualizer.

**Expected Result**
Either when hovering or clicking on the custom guard name next to an event, show the variables and their respective values.

**Actual Result**
No variables are shown.

![image](https://user-images.githubusercontent.com/28842311/71011550-e46e6700-20ed-11ea-87c5-1e4a70fd3bcf.png)

**Reproduction**
- [XState Visualizer](https://xstate.js.org/viz/?gist=1d5b003a354ece91b145e3e5454a738c)

**Comment by davidkpiano** [comment]
Added to roadmap: https://github.com/davidkpiano/xstate/issues/742
