### ISSUE TITLE
[Help needed] Async/Await for the resulting context after the state machine finishes

### ISSUE THREAD

**Issue by seeseesky** [davidkpiano/xstate#883]
Is there any way to get the resulting context after the state machine finishes by using async/await? Currently, I can only get the lastest context by using onTransition callback.

**Comment by Andarist** [comment]
State machine’s transition is always synchronous, there is nothing to be awaited because you can just read state/context immediately after the call.

**Comment by seeseesky** [comment]
Sorry maybe my question is a little bit unclear, what I mean is that how can I get the latest context after the state machine reached the final state and stop running due to completion
```
// vehicleMachine contains some async action and null events for auto state hopping
const service = interpret(vehicleMachine)
  .onTransition((state) => {
    console.log(`==============${state.value}=================`);
    console.log(state.context);
  })
  .onDone((event) => {
    console.log('service onDone', event);
  });
service.start();
console.log(`resulting context: ${vehicleMachine.context}`); // Not the latest context
```

**Comment by Andarist** [comment]
You should be able to read that from within onDone callback

**Comment by seeseesky** [comment]
> You should be able to read that from within onDone callback

Thanks a lot
