### ISSUE TITLE
(4.7.2) Conditional transitions break `after` delayed transition.

### ISSUE THREAD

**Issue by MatrixNorm** [davidkpiano/xstate#886]
(sandbox: https://codesandbox.io/s/determined-volhard-ke3dt)

Consider this simple machine. If event `FOO` is received within 1.5 seconds state X should be re-entered and delayed `after` transition resetted. Even if state X is re-entered many times, `after` transition should be fired only once. Sure enough all works as expected here.

```javascript
const machineGood = Machine({
  id: "someMachine",
  initial: "X",
  states: {
    X: {
      on: {
        FOO: "X"
      },
      after: {
        1500: {
          target: "Y"
        }
      }
    },
    Y: {}
  }
});
```

But if conditional transitions are added to the `after` things get wrong. The following machine should exhibit the same behavior but in fact it is different. In this case delayed transition is fired multiple times. 

```javascript
const machineBug = Machine({
  id: "someMachine",
  initial: "X",
  states: {
    X: {
      on: {
        FOO: "X"
      },
      after: {
        1500: [
          {
            target: "Y",
            cond: () => 1 > 0
          },
          {
            target: "Z"
          }
        ]
      }
    },
    Y: {},
    Z: {}
  }
});
```

Here is the code to run tests:

```javascript
function sleep(period) {
  return new Promise(r => setTimeout(r, period));
}

async function demo(machine) {
  // expected outcome in the comments
  const service = interpret(machine).onTransition(state =>
    console.log(state.value)
  );
  service.start();
  //X
  await sleep(1000);
  service.send({ type: "FOO" });
  //X
  await sleep(1000);
  service.send({ type: "FOO" });
  //X
  //...after 1500 ms
  //Y
}
```

demo(machineGood);
//correct:
//X
//X
//X
//Y
demo(machineBug);
// incorrect:
//X
//X
//Y
//Y
//Y

**Comment by Andarist** [comment]
Please prepare a runnable repro case - for example on CodeSandbox. It can significantly speed up us finding a time to evaluate your issue.

**Comment by MatrixNorm** [comment]
https://codesandbox.io/s/determined-volhard-ke3dt

**Comment by Andarist** [comment]
I can confirm a bug and diagnosed the problem. Gonna think about it (and hopefully fix it) tomorrow.

**Comment by Andarist** [comment]
Here you go - https://github.com/davidkpiano/xstate/pull/888
