### ISSUE TITLE
@xstate/react 1.0.0-rc.1 useLayoutEffect warning

### ISSUE THREAD

**Issue by RafalFilipek** [davidkpiano/xstate#894]
Hi,

`useLayoutEffect` from bc40dc826ce3176ed8faa3e0b5e77cc9e7e462d7 throws warning on server.

Demo: https://codesandbox.io/s/xstate-uselayouteffect-warning-cjqf6

```
Warning: useLayoutEffect does nothing on the server, because 
its effect cannot be encoded into the server renderer's output format. 
This will lead to a mismatch between the initial, non-hydrated UI and 
the intended UI. To avoid this, useLayoutEffect should only be used in 
components that render exclusively on the client. 
See https://fb.me/react-uselayouteffect-ssr for common fixes.
```

More info about warning can be found [here](https://medium.com/@alexandereardon/uselayouteffect-and-ssr-192986cdcf7a).

Simple solution:

```
# useIsomorphicLayoutEffect.ts

import { useEffect, useLayoutEffect } from 'react';

export const useIsomorphicLayoutEffect = typeof window !== 'undefined' ? useLayoutEffect : useEffect;
```

thanks

**Comment by Andarist** [comment]
Yeah - I’ve already created a PR reverting this change https://github.com/davidkpiano/xstate/pull/892
