### ISSUE TITLE
xstate version 3.3.3 failure when using TypeScript >3.7

### ISSUE THREAD

**Issue by miroshSa** [davidkpiano/xstate#899]
**Description**
It fail to TS check:
`../node_modules/xstate/lib/types.d.ts(1,10): error TS2440: Import declaration conflicts with local declaration of 'StateNode'.`

**Expected Result**
no TS error

**Actual Result**
TS error

**Additional context**
typescript@3.7.4
xstate@3.3.3

**Comment by Andarist** [comment]
Im afraid that we wont be able to provide bug fixes to v3, given the fact that v4 is out for quite some time already and we have even started to work on v5.

Please consider upgrading your codebase to v4.

**Comment by davidkpiano** [comment]
Please look at the migration guide here: https://github.com/davidkpiano/xstate/blob/master/migration.md

Let us know if you have any questions.
