### ISSUE TITLE
Vue integration example

### ISSUE THREAD

**Issue by BrockReece** [davidkpiano/xstate#9]
This is an awesome lib.

I have just built a quick [codepen demo](https://codepen.io/BrockReece/pen/EvdwpJ) for Vue.js if that is of any use to anyone?

Cheers
Brock

**Comment by davidkpiano** [comment]
This is awesome! I'll add a link to it on the README.

**Comment by BrockReece** [comment]
Thanks 👍 , I am going to do some experiments with Vuex today, do you want me to share those with you too?

**Comment by davidkpiano** [comment]
Yes please!

**Comment by BrockReece** [comment]
Ok, [here](https://codepen.io/BrockReece/pen/ZJqgpO) is what I have so far, it appears to be working as expected, looks fairly neat too.

**Comment by davidkpiano** [comment]
Vue integration docs: https://xstate.js.org/docs/recipes/vue.html
