### ISSUE TITLE
Autoforwarding on invoked machine can't be used with strict: true

### ISSUE THREAD

**Issue by mrjogo** [davidkpiano/xstate#903]
**Description**
When invoking a machine with `autoforward: true`, if the parent machine has `strict: true` it will throw an error for events only accepted by the child machine. If the child machine has `strict: true`, it will throw an error for events only accepted by the parent machine.

**Expected Result**
An error should only be thrown if BOTH the parent and child machine cannot handle the event.

**Actual Result**
Errors are thrown if EITHER the parent or child machine cannot handle the event.

**Reproduction**
https://codesandbox.io/s/gallant-margulis-csk2u

**Additional context**
I'm writing a complex hierarchical state chart controlled through RPC, and I'm using the errors from strict mode to send error responses to callers of that RPC if they're called when not allowed. I would like to use invoked machines to separate concerns (primarily to isolate context, but also for ease of development), and currently it seems that if I use strict mode on the parent I will have to manually forward every event the child could accept, and the child will not be able to use strict mode. I'm sure the current behavior is technically correct based on how autoforward and strict mode work individually, but the effect is to essentially exclude them from working together.

**Comment by Andarist** [comment]
Question - why do you want to use strict mode? We are considering removing it in the next major release so your feedback on that would be really valuable on that.

**Comment by mrjogo** [comment]
Well, for one I just realized it doesn't actually work the way I had thought: I thought it would cause an error if an event was sent that did not have a transition in the current state (ie, not in the `on` property). However it seems to only throw an error if an event is sent that is not defined **anywhere** on the machine.

As I mentioned above, some of the transitions in my state machine are triggered by events from RPC calls (I'm using xstate on the backend). These calls have responses that indicate if they were successful, and I was defining successful as "the RPC triggered a transition on the machine". The caller also subscribes to state changes, so I could change to fire-and-forget, but that decouples the cause and effect of any unexpected behavior, making it harder for the client to handle. Another way I considered checking for RPC "success" was verifying that the state returned from the `send()` call was the expected state, but that is more brittle since a successful transition could (theoretically) trigger additional transitions, such that the final state is not the expected state, even though the RPC call did what it was supposed to. If the response from `send` had some sort of log of what (if any) transitions had been performed, that would also work, but that doesn't seem to be the case.

All in all, I'm sure I can find a way around using strict mode (especially since it doesn't actually do what I need), but it seemed to be a handy shortcut.

**Comment by Andarist** [comment]
>  I thought it would cause an error if an event was sent that did not have a transition in the current state (ie, not in the on property). 

I think you can achieve this by using a wildcard transition on the root of your machine. If such a transition gets triggered it means that it wasn't handled by your current state and this seems like what you were after here.

**Comment by mrjogo** [comment]
I'd expect that wouldn't work with the invoked child machines (ie, if the invoked machine transitions but the parent does not, I would expect that wildcard to still be called).

However, I looked closer at the state object returned from `send()` and discovered `state.changed` reports what I want for the top level machine, and `state.children` allows me to recurse into any invoked machines and check their `state.changed` properties as well. I will note that I passed `sync: true` to the invoked machine, which is undocumented for invoked services (https://xstate.js.org/docs/guides/communication.html#the-invoke-property), but nosing through the code seems like it should behave the same as on Actors (https://xstate.js.org/docs/guides/actors.html#syncing-and-reading-state)

**Comment by davidkpiano** [comment]
I'm changing this to "Working as intended" - strict mode is behaving as expected, and if you don't want errors to be thrown for events sent to a machine that's intended for a child machine, the parent machine _still_ needs to handle those events explicitly in strict mode.
