### ISSUE TITLE
Question: machine.transition state parameter

### ISSUE THREAD

**Issue by KeitIG** [davidkpiano/xstate#91]
## Bug or feature request?
Question

## Description:

I am fairly new to final state machine, but if I understand well, every time I want to know the next state of my FSM, I need to pass it the current state. 

But is not `Machine` supposed to know the current state "It's in"? 

What is the point of having an initial state then? Is it a concept rule? or a deliberate API choice? And if so, why? :)

**Comment by davidkpiano** [comment]
If I asked you, "How many apples do I have right now?", that wouldn't be an easy question to answer, right?

If instead I asked you "I had 10 apples but I just ate 3. How many apples do I have right now?" then the answer is _deterministic_ - we can know for certainty that the answer is 7.

That's the power of pure functions. There is never any unknown or ambiguous context; you provide all the information up front and get a deterministic return value. This is very powerful for testing and managing state.

It also leaves the flexibility to you, the developer, for storing that "current state" in whichever method you may like (Redux, MobX, something else, etc. etc.)

As for why there's an initial state, that follows both SCXML and the original Statechart semantics and specification -- after all, everything has to start somewhere, right? Please refer to the original paper for more details.

**Comment by KeitIG** [comment]
Thank you for the explanations!
