### ISSUE TITLE
Visualizer sometimes crashes in a unrecoverable way

### ISSUE THREAD

**Issue by victorb** [davidkpiano/xstate#912]
Was playing around with the visualizer, especially around actions and context. When I modified the actions and clicked "Update", the visualizer crashed in a way that made me loose all the progress I had written in. Seems the only reliable way to use it right now, is to copy-paste from a proper editor, in order to not loose all the data.

This is how it looked once crashed:

![image](https://user-images.githubusercontent.com/459764/71619901-058f8700-2bc7-11ea-8aef-0446a45c0003.png)

One possible fix would be to decouple the editor from the viewer, so the editor won't crash if there is errors in the code people use. Basically some global error handler.

I tried to find the source for the visualizer myself but I wasn't able to, so can't triage the issue better at the moment.

**Comment by jeremy-deutsch** [comment]
I have a reproducing case here: https://xstate.js.org/viz/?gist=bd607e804535bb3a659a9baec634a533

It doesn't crash on its own, obviously, but try replacing
```
assign({ value: () => null })
```
with
```
assign({ value: null })
```
and hitting "UPDATE". This might be an error in XState, but even so, it's probably a good idea to find out why this also causes the whole page to crash.

**Comment by davidkpiano** [comment]
Closing this in favor of using [the inspector](https://xstate.js.org/docs/packages/xstate-inspect) instead.
