### ISSUE TITLE
Why useConstant?

### ISSUE THREAD

**Issue by AjaxSolutions** [davidkpiano/xstate#913]
I'm curious why [useConstant](https://github.com/davidkpiano/xstate/blob/8930df82b7b71124eb5cdafd4892a3354c396ce9/packages/xstate-react/src/useConstant.ts) is used as opposed to just using useMemo?

Looks like they both cache the return value of a function(?)

**Comment by davidkpiano** [comment]
cc. @Andarist

**Comment by Andarist** [comment]
https://reactjs.org/docs/hooks-reference.html#usememo

> You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.

We can't allow forgetting created service - we need it to be the same throughout the whole lifetime of a component.
