### ISSUE TITLE
@xstate/fsm: actionMeta as param to actions, to access current state

### ISSUE THREAD

**Issue by damooo** [davidkpiano/xstate#914]
## Bug or feature request?
FEATURE
## Description:
it would be helpful to provide actionMeta as param to actions. an usecase will be that, when we exit from a state, we may want to cleanup, based on next state reached.. in my case i want to clear retry counter of an action within that state, when state actually changed, instead of transitioning to itself.

**Comment by davidkpiano** [comment]
For now, this is covered in `xstate`, as we want to prevent feature creep in `@xstate/fsm`, which is intentionally meant to be small (and feature-light).
