### ISSUE TITLE
When using a custom clock and a transition with a delay of 0, the clock setTimeout function is called but xstate transitions to the next state despite the sent continue function not having been called.

### ISSUE THREAD

**Issue by tanishalfelven** [davidkpiano/xstate#923]
**Description**
When interpreting a machine and using a custom clock, if you have an `after` with a `delay: () => 0` then the transition will be taken even when the clock hasn't yet called for the statechart to continue.

**Expected Result**
The statechart should not continue until the function sent to `clock.setTimeout` is called.

**Actual Result**
The statechart transitions to the next state without the function argument that is sent to `clock.setTimeout` being called.

**Reproduction**
[codesandbox](https://codesandbox.io/s/xstate-custom-clock-delay-transitions-5o4c4)

**Additional context**
Working in codesandbox with most recent xstate version.

**Comment by Andarist** [comment]
I've just checked by forking your codesandbox and updating XState version there and this is working as expected by you. It had to be some bug in the older version of XState.
