### ISSUE TITLE
@xstate/react: integrate `useService` with @xstate/fsm

### ISSUE THREAD

**Issue by lucat1** [davidkpiano/xstate#929]
## Bug or feature request?
feature-request

## Description:
Similarly to #763 and 5f0e33992c48b464d13a7324fb487e6a0660b74c it would be cool if we could use the same `@xstate/react/lib/fsm` import and have `useService` without the overhead of the main `xstate` library. I have taken a look at the source code and it looks like the only funciton used from `xstate` inside the `useService` function is `interpret` which is also available inside `@xstate/fsm`.

I tried using a webpack resolve alias but it didn't work, unfortunately(😢). The `useService` function returns an undefined state but what seems to be an okay `send` function:

```javascript
const [state, send] = useService(service)
console.log(state, send) // undefined, function
```

## Expected result:
```javascript
import { useService } from '@xstate/react/lib/fsm'
```
## Actual result:
```javascript
// including the whole xstate library and creating the Machine with
// xstate instead of @xstate/fsm
import { useService } from '@xstate/react'
```

**Comment by Andarist** [comment]
You are right, we can't quite reuse the same useService for both. I'm gonna prepare a PR providing `useService` in `@xstate/react/fsm`

**Comment by lucat1** [comment]
Sorry to bring this up again, but a minor release would be appreciated as I need this feature asap.

**Comment by Andarist** [comment]
We plan to release this within a week.
