### ISSUE TITLE
Missing Typestates support in @xstate/react

### ISSUE THREAD

**Issue by RafalFilipek** [davidkpiano/xstate#934]
Hi,

`Typestates` support introduced in 4.7.6 is super cool and works great. Is it possible to make it work with `@xstate/react` and `useMachine`. I tried to add `TTypestate` here and there in `index.d.ts` but without luck.

Here you can find repro: https://github.com/RafalFilipek/xstate-react-typestates-bug

```
xstate: 4.7.6
@xstate/react: 0.8.1 / 1.0.0-rc.1
TS: 3.7.4
```

Thank you

**Comment by davidkpiano** [comment]
Fixed here and will be available in the next release: https://github.com/davidkpiano/xstate/pull/940
