### ISSUE TITLE
Machine Config given in TodoMvc example is not working in visualizer

### ISSUE THREAD

**Issue by amanmavai** [davidkpiano/xstate#942]
**Description**
Machine Config given in TodoMvc example is not working in visualizer

**Expected Result**
It should work in visualizer

**Actual Result**
Machine Config given in TodoMvc example is not working in visualizer

**Reproduction**

- [CodeSandbox Link](https://codesandbox.io/s/xstate-todomvc-33wr94qv1?from-embed)

**Comment by davidkpiano** [comment]
That machine config depends on other machines working together (spawned) and won't work as-is, until the new visualizer is released.
