### ISSUE TITLE
Two vizualiser packages?

### ISSUE THREAD

**Issue by PetrSnobelt** [davidkpiano/xstate#948]
**Description**
Hi, there are two visualizer packages:
https://github.com/davidkpiano/xstate/tree/master/packages/xstate-viz
and
https://github.com/statecharts/xstate-viz

first report error after `yarn start` 
`semantic error TS2300: Duplicate identifier 'useState'.`

I think the second package is correct and used on web, but it takes me some time to realize it.

Can you plz clarify the situation or at last add some info to readme of https://github.com/statecharts/xstate-viz

Thanks

**Comment by PetrSnobelt** [comment]
So then it is also unclear where to add issue for a fix like this
https://github.com/statecharts/xstate-viz/pull/47

**Comment by davidkpiano** [comment]
Add current visualizer issues to https://github.com/statecharts/xstate-viz/issues/new
