### ISSUE TITLE
The @xstate/vue package is marked private in its package.json

### ISSUE THREAD

**Issue by morgancmartin** [davidkpiano/xstate#955]
**Description**
The @xstate/vue package is marked private in its package.json and therefore inaccessible from the npm and yarnpkg registries or when attempting `yarn add @xstate/vue` or `npm install @xstate/vue` commands.

[package.json](https://github.com/davidkpiano/xstate/blob/master/packages/xstate-vue/package.json) can be seen with `private: true`

The [documentation](https://xstate.js.org/docs/packages/xstate-vue/#quick-start) implies this is not intentional.

Thanks very much for the very interesting library!

**Comment by Andarist** [comment]
The package is meant to be private for some more time because it ain't ready for a final release yet. Its docs probably shouldn't be published just yet, @davidkpiano anything that we could do easily to take those docs down for the time being? Or maybe we should just "under development" banner or smth?

**Comment by davidkpiano** [comment]
@Andarist We can probably release a 0.x version for now.

**Comment by josephfh** [comment]
When you do release a 0.x version it would be great to add any known issues to the documentation. I will be trying it out as soon as the package is public :)

Thanks!

**Comment by davidkpiano** [comment]
@josephfh Your wish is our command, try it out: https://www.npmjs.com/package/@xstate/vue

**Comment by RomainLanz** [comment]
Nice!

I'll move my current application that use raw XState & Vue to this and see if I find any issue. 👍 
With the raw version of XState I had some caching issue between view, I'll check if it's fixed in this.
