### ISSUE TITLE
When using global/context events, the machine should only apply the desired action and keep on the same state

### ISSUE THREAD

**Issue by filipemonteiroth** [davidkpiano/xstate#966]
**Description**
When using global/context events, the machine should only apply the desired action and keep on the same state, but that's not what happens.

**Expected Result**
When an event is received and only actions are applied, it should apply the actions and keep on the same state.

**Actual Result**
It takes the machine back to the very initial state.

**Reproduction**
The statemachine below is just the basic example we got when we open the xstate viz app and I add one more event at the top. Click on the fetch event and then click back on the `TEST` event. It takes you to the very initial state instead of keeping you on the loading state.
- [XState Visualizer](https://xstate.js.org/viz/?gist=ff46ef1fc474024633efeba932d64acb)

**Additional context**
No more context needed.

**Comment by davidkpiano** [comment]
Can you try this in XState 4.7? Use CodeSandbox: https://codesandbox.io/s/xstate-example-template-m4ckv

**Comment by filipemonteiroth** [comment]
Hey, just tested that now and it seems fixed! Thank you. Maybe we can close that issue?
