### ISSUE TITLE
TS Question: What type is needed in the context for the parent machine to reference the child machine?

### ISSUE THREAD

**Issue by mastermike501** [davidkpiano/xstate#969]
## Bug or feature request?
Question

## Description:
In the [docs](https://xstate.js.org/docs/guides/actors.html#spawning-machines) relating to spawning child machines, the value assigned to the context value that holds the child machine is `null`. 

![image](https://user-images.githubusercontent.com/9069099/73424637-634ff400-436a-11ea-9670-b7aa46a0bffb.png)

However I'm using TS and my context is typed so I'm wondering what type should I use? 
~~EDIT: I've tried copying the type from the TS inferrer system (Interpreter type) but that doesn't seem to play nicely with the null value. I'm wondering if using a Union type between Interpreter and null is the way to go?~~
EDIT: Seems that the Union type solution doesn't work:
`Type 'Interpreter<OutputMachineCtx, any, OutputMachineEvents, any> | null' is not assignable to type 'Interpreter<OutputMachineCtx, any, OutputMachineEvents, any>'`

![image](https://user-images.githubusercontent.com/9069099/73424804-d9545b00-436a-11ea-84a8-d93fe36c31f3.png)

**Comment by davidkpiano** [comment]
Try `Interpreter<...>`.

**Comment by mastermike501** [comment]
Hey David, thanks for the response. 

I tried that but it just says `Type expected`. It's also the first time I've seen the spread operator being used inside a generic, but I can't find any documentation on that. 🙂

![image](https://user-images.githubusercontent.com/9069099/73502853-5502e600-4405-11ea-8feb-7e809f77edc9.png)

**Comment by davidkpiano** [comment]
🤦‍♂ Haha, what I meant was try `Interpreter<SomeContext, SomeEvent>`. Not literally those... fill those in.

**Comment by mastermike501** [comment]
Hmm that kind of leads back to square one since I did try with `Interpreter` before but that doesn't allow me to assign `null`.

> EDIT: I've tried copying the type from the TS inferrer system (Interpreter type) but that doesn't seem to play nicely with the null value. I'm wondering if using a Union type between Interpreter and null is the way to go?

**Comment by semopz** [comment]
Have you tried using string identifiers instead of object getters? I don't use object getters as I just can't get them to work with TS.

**Comment by davidkpiano** [comment]
Can you put this in a CodeSandbox?

**Comment by CodingDive** [comment]
@semopz use string identifiers where? 

@mastermike501 you can try
`localOne: Interpreter<Context, Event> | undefined` then set the value to undefined when you define the initial context. Like David said, would need to look at a sandbox why null isn't working.

**Comment by semopz** [comment]
@CodingDive, yep my comment can be ignored. I don't know what I was looking at.

**Comment by davidkpiano** [comment]
New answer:

```ts
import { ActorRefFrom } from 'xstate';
import { remoteMachine } from '../path/to/remoteMachine';

interface SomeContext {
  localOne: ActorRefFrom<typeof remoteMachine>
}
```
