### ISSUE TITLE
Relative vs ID transition? Docs...

### ISSUE THREAD

**Issue by tehnorm** [davidkpiano/xstate#98]
## Bug (Question)?

Fairly certain this is more of a question...  I think this is likely a documentation (or lack there of / clarity issue).

`xstate: 3.2.0`
`node: v8.9.3`

## Description:

First things first - cool lib! Very handy and prefer it over the other state(ish) libs because of the simplicity. Please, please, please for the love of Cthulhu aim to keep it simple. `</2-cents>`

I'm attempting to transition to a child state and having all sorts of unexpected (at least with how I believe a transition should work) challenges. 

First challenge:
```js
const {Machine} = require('xstate');

const stateTree = {
	initial: 'idle',
	states: {
		connecting: {
			id: 'connecting',
			onEntry: ['attemptConnection'],
			onExit: ['exitConnecting'],
			on: {
				GOINNER: 'inner'
			},
			states: {
				inner : {
					id: 'inner',
					onEntry: ['enterInner'],
					actions: ['innerAction'],
				}
			}
		},
		idle: {
			id: 'idle',
			on: {
				START: 'connecting'

			}
		}
	}
};

let state = Machine(stateTree);
let currentState = state.initialState;


console.log('idle -> START -> connecting');
currentState = state.transition(currentState, 'START');
console.log(currentState.actions);


console.log('connecting -> GOINNER -> inner');
currentState = state.transition(currentState, 'GOINNER');
console.log(currentState.actions);
```
#### Based on the docs, examples and tests I would expect:
```
idle -> START -> connecting
[ 'attemptConnection' ]
connecting -> GOINNER -> inner
[ 'enterInner', 'innerAction']
```

#### Instead I get this:
```js
idle -> START -> connecting
[ 'attemptConnection' ]
connecting -> GOINNER -> inner
/Users/norm/Projects/blue-white/test/xstate/node_modules/xstate/lib/StateNode.js:463
                    throw new Error("Event '" + event + "' on state '" + currentPath + "' leads to undefined state '" + nextStatePath.join(_this.delimiter) + "'.");
                    ^

Error: Event 'GOINNER' on state 'connecting' leads to undefined state 'inner'.
    at /Users/norm/Projects/blue-white/test/xstate/node_modules/xstate/lib/StateNode.js:463:27
    at Array.forEach (<anonymous>)
    at /Users/norm/Projects/blue-white/test/xstate/node_modules/xstate/lib/StateNode.js:431:27
    at Array.forEach (<anonymous>)
    at StateNode.next (/Users/norm/Projects/blue-white/test/xstate/node_modules/xstate/lib/StateNode.js:424:26)
    at StateNode.transitionStateValue (/Users/norm/Projects/blue-white/test/xstate/node_modules/xstate/lib/StateNode.js:257:39)
    at StateNode.transition (/Users/norm/Projects/blue-white/test/xstate/node_modules/xstate/lib/StateNode.js:154:36)
    at Object.<anonymous> (/Users/norm/Projects/blue-white/test/xstate/test.js:41:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
```
Ok... well, maybe we need to give it a bit more help on how to find the child state, let's try the ID syntax.

```js
const {Machine} = require('xstate');

const stateTree = {
	initial: 'idle',
	states: {
		connecting: {
			id: 'connecting',
			onEntry: ['attemptConnection'],
			onExit: ['exitConnecting'],
			on: {
				GOINNER: '#inner'
			},
			states: {
				inner : {
					id: 'inner',
					onEntry: ['enterInner'],
					actions: ['innerAction'],
				}
			}
		},
		idle: {
			id: 'idle',
			on: {
				START: 'connecting'

			}
		}
	}
};

let state = Machine(stateTree);
let currentState = state.initialState;


console.log('idle -> START -> connecting');
currentState = state.transition(currentState, 'START');
console.log(currentState.actions);


console.log('connecting -> GOINNER -> inner');
currentState = state.transition(currentState, 'GOINNER');
console.log(currentState.actions);
```

#### Here I would expect:
```
idle -> START -> connecting
[ 'attemptConnection' ]
connecting -> GOINNER -> inner
[ 'enterInner', 'innerAction']
```

#### Instead this is what happens:
```
idle -> START -> connecting
[ 'attemptConnection' ]
connecting -> GOINNER -> inner
[ 'exitConnecting', 'attemptConnection', 'enterInner' ]
```

Wait. WAT. Yeah... lost me on that one. 

It's like it went all the way back out of `connecting` re-entered `connecting` and then entered `inner`, but also didn't pick up the actions on `inner`.

Any clarification as to what the behavior should be here would be greatly appreciated. Again, fairly certain this is an issue with my understanding of how xstate is intended to work.

**Comment by tehnorm** [comment]
Alright! Seems the solution was a bit more very detailed reading around the `initial` property. The starwars example helped highlight this subtlety. On a state is __very important__ to have an `initial` state.  

For someone that might find this later here is a working example:

```js
const {Machine} = require('xstate');

const stateTree = {
	initial: 'idle',
	states: {
		idle: {
			id: 'idle',
			on: {
				START: 'connecting'
			}
		},
		connecting: {
			id: 'connecting',
			initial: 'idle',
			onEntry: ['attemptConnection'],
			onExit: ['exitConnecting'],
			states: {
				idle: {
					on: {
						GOINNER: 'inner'
					},
				},
				inner : {
					id: 'inner',
					onEntry: ['enterInner'],
					actions: ['innerAction'],
				}
			},

		},
	}
};

let state = Machine(stateTree);
let currentState = state.initialState;

console.log('idle -> START -> connecting');
currentState = state.transition(currentState, 'START');
console.log(currentState.actions);

console.log('connecting -> GOINNER -> inner');
currentState = state.transition(currentState, 'GOINNER');
console.log(currentState.actions);
```

#### Output:

```
idle -> START -> connecting
[ 'attemptConnection' ]
connecting -> GOINNER -> inner
[ 'enterInner' ]
```

Food for thought - should `Machine({state})` throw an error if there are missing `initial` states in the tree since you will pretty much always have a bad time?

Another detail that was also subtle: actions apply along a transition path, not a state.

**Comment by davidkpiano** [comment]
> Food for thought - should Machine({state}) throw an error if there are missing initial states in the tree since you will pretty much always have a bad time?

Yes, it should. Good thought.

> Another detail that was also subtle: actions apply along a transition path, not a state.

Yep, I should make that clear in the docs too (Mealy vs. Moore model - statecharts employ both)

> Please, please, please for the love of Cthulhu aim to keep it simple. 

Of course! The three goals for this are:
- Simplicity
- Declarative-ness (functional, pure)
- Adherence to the SCXML spec (no inventing novel/sugary things)
