### ISSUE TITLE
@xstate/test .getShortestPathPlans() doesn't run all event cases

### ISSUE THREAD

**Issue by tivac** [davidkpiano/xstate#980]
**Description**

I've been experimenting with `@xstate/test` and trying to use it to test events that should be run with multiple `cases`.

**Expected Result**

Whether I use `.getShortestPathPlans()` or `.getSimplePathPlans()` all of the `cases` for each event would be taken into account.

**Actual Result**

If I use `.getSimplePathPlans()` all the event `cases` are used, as expected. If I use `.getShortestPathPlans()` only the first case is ever used.

**Reproduction**
https://codesandbox.io/s/blissful-wind-f75ux

<details>
  <summary>Repro + Output</summary>

**Repro Code**
```js
const { Machine: createMachine } = require("xstate");
const { createModel } = require("@xstate/test");

const machine = createMachine({
  id: "menu",
  initial: "booting",
  states: {
    booting: {
      on: {
        EVENT: "ready"
      }
    },

    ready: {}
  }
});

const model = createModel(machine).withEvents({
  EVENT: {
    exec: (test, ev) => console.log(ev),
    cases: [{ id: "one" }, { id: "two" }, { id: "three" }]
  }
});

const execute = async plans =>
  plans.forEach(plan => {
    plan.paths.forEach(async path => {
      await path.test({ ctx: "foo" });
    });
  });

(async function() {
  console.log("getSimplePathPlans()");
  await execute(model.getSimplePathPlans());

  console.log(".getShortestPathPlans()");
  await execute(model.getShortestPathPlans());
})();
```

**Repro Output**
```
getSimplePathPlans() 
> Object {type: "EVENT", id: "one"}
> Object {type: "EVENT", id: "two"}
> Object {type: "EVENT", id: "three"}

.getShortestPathPlans() 
> Object {type: "EVENT", id: "one"}
```
</details>

**Additional context**

`xstate@4.7.8`
`@xstate/test@0.3.0`

**Comment by davidkpiano** [comment]
As discussed on Gitter - this is as expected, because the events need to result in different states, and the reproduction always results in the same state, regardless of the event cases.
