### ISSUE TITLE
Documentation on invoking a service for TypeScript insufficient

### ISSUE THREAD

**Issue by jaqmol** [davidkpiano/xstate#988]
Referring to https://github.com/davidkpiano/xstate/issues/986

## Bug or feature request?
Request for better documentation about how to write service invocations in TypeScript. This is not sufficient: https://xstate.js.org/docs/guides/communication.html#the-invoke-property

## Description:
It's not clear how one would need to apply custom context and event types to get an invoke service to work together with TypeScript.

**Comment by jaqmol** [comment]
Update: I just removed all the typing of my service and applied "any" to all contexts and events. Under this conditions TypeScript is swallowing the service. With the ugly side effect that I need to do manual type-checking for any- and everything. If a type-safe solution to this problem exists, it would be worth mentioning it in the documentation.

**Comment by davidkpiano** [comment]
I can't help the verbosity of the TypeScript errors. Can you please share the code (preferably in a CodeSandbox) that currently is giving you issues?

Again, do _not_ use `async () => ...` as a `src`.

**Comment by jaqmol** [comment]
It'll take me some time to rebuild the core of the issue without the whole complexity of my use-case. Please don't close the issue.

**Comment by jaqmol** [comment]
Just lost 2 hour of work on CodeSandbox after it went into a save-error 502 frenzy. Sorry but I have to try again tomorrow. Please keep the issue open.

**Comment by jaqmol** [comment]
I think I'm just giving up on Xstate. I'm utterly incapable of reproducing the issue in smaller scale and completely drowning in TypeScript error messages in my full project. To give you as taste of it:

```ascii
No overload matches this call.
  Overload 1 of 2, '(config: MachineConfig<AppMachineContext, any, AnyEventObject>, options?: Partial<MachineOptions<AppMachineContext, AnyEventObject>> | undefined, initialContext?: AppMachineContext | undefined): StateMachine<...>', gave the following error.
    Type '{ signedOut: { on: { FAIL: { target: string; actions: AssignAction<AppMachineContext, EventObject & ErrorEvent>; }; SIGNIN: { ...; }; UPDATE_ENTRIES: { ...; }; }; }; updatingUser: { ...; }; signedIn: { ...; }; failure: { ...; }; }' is not assignable to type 'StatesConfig<AppMachineContext, any, AnyEventObject>'.
      Property 'updatingUser' is incompatible with index signature.
        Type '{ invoke: { id: string; src: (ctx: AppMachineContext, { app, user }: EventObject & InitAndUpdateUserEvent) => Promise<{ app: firebase.app.App; user: User; }>; onDone: { ...; }; onError: { ...; }; }; }' is not assignable to type 'StateNodeConfig<AppMachineContext, any, AnyEventObject>'.
          Types of property 'invoke' are incompatible.
            Type '{ id: string; src: (ctx: AppMachineContext, { app, user }: EventObject & InitAndUpdateUserEvent) => Promise<{ app: firebase.app.App; user: User; }>; onDone: { ...; }; onError: { ...; }; }' is not assignable to type 'StateMachine<any, any, any, any> | { id?: string | undefined; src: string | StateMachine<any, any, any, any> | InvokeCreator<any, any>; ... 4 more ...; onError?: string | ... 2 more ... | undefined; } | InvokeConfig<...>[] | undefined'.
              Type '{ id: string; src: (ctx: AppMachineContext, { app, user }: EventObject & InitAndUpdateUserEvent) => Promise<{ app: firebase.app.App; user: User; }>; onDone: { ...; }; onError: { ...; }; }' is not assignable to type 'undefined'.
  Overload 2 of 2, '(config: MachineConfig<AppMachineContext, any, AnyEventObject>, options?: Partial<MachineOptions<AppMachineContext, AnyEventObject>> | undefined, initialContext?: AppMachineContext | undefined): StateMachine<...>', gave the following error.
    Type '{ signedOut: { on: { FAIL: { target: string; actions: AssignAction<AppMachineContext, EventObject & ErrorEvent>; }; SIGNIN: { ...; }; UPDATE_ENTRIES: { ...; }; }; }; updatingUser: { ...; }; signedIn: { ...; }; failure: { ...; }; }' is not assignable to type 'StatesConfig<AppMachineContext, any, AnyEventObject>'.
      Property 'updatingUser' is incompatible with index signature.
        Type '{ invoke: { id: string; src: (ctx: AppMachineContext, { app, user }: EventObject & InitAndUpdateUserEvent) => Promise<{ app: firebase.app.App; user: User; }>; onDone: { ...; }; onError: { ...; }; }; }' is not assignable to type 'StateNodeConfig<AppMachineContext, any, AnyEventObject>'.
          Types of property 'invoke' are incompatible.
            Type '{ id: string; src: (ctx: AppMachineContext, { app, user }: EventObject & InitAndUpdateUserEvent) => Promise<{ app: firebase.app.App; user: User; }>; onDone: { ...; }; onError: { ...; }; }' is not assignable to type 'StateMachine<any, any, any, any> | { id?: string | undefined; src: string | StateMachine<any, any, any, any> | InvokeCreator<any, any>; ... 4 more ...; onError?: string | ... 2 more ... | undefined; } | InvokeConfig<...>[] | undefined'.
              Type '{ id: string; src: (ctx: AppMachineContext, { app, user }: EventObject & InitAndUpdateUserEvent) => Promise<{ app: firebase.app.App; user: User; }>; onDone: { ...; }; onError: { ...; }; }' is not assignable to type 'undefined'.
```

Sorry, but this kind of complexity is nothing a can deal with on a tight schedule.

**Comment by davidkpiano** [comment]
@jaqmol That's fine (you're free to use something else), but for the record, the last two lines are what you need to look at:

> Type '{ id: string; src: (ctx: AppMachineContext, { app, user }: EventObject & InitAndUpdateUserEvent) => **Promise<{ app: firebase.app.App; user: User; }>**; onDone: { ...; }; onError: { ...; }; }'
> 
> is not assignable to type:
> 
> 'StateMachine<any, any, any, any> | { id?: string | undefined; src: string | StateMachine<any, any, any, any> | InvokeCreator<any, any>; ... 4 more ...; onError?: string | ... 2 more ... | undefined; } | InvokeConfig<...>[] | undefined'.

Like I said, do _not_ use an async function. Refactor it.

**Comment by jaqmol** [comment]
> The `src` is probably where the problem lies. Don't try to be too strict with types for that for now.

I thought so too. Unfortunately it was more complicated. I rebuilt the complete machine from the ground up, diligently taking care of any little change in compiler outputs with every thing added. There where 2 things going south: 1st me overlooking what the onError-callback delivers, I didn't expect a "data" property in the error-handler. The 2nd thing where my union-types in the src. They where causing false positives together with the 1st error. I redesigned them to take their arguments from the context instead. It seems to work now. At least I learned something ;-)

**Comment by davidkpiano** [comment]
Awesome! V5 will have more helpers and better type safety for this. I'll be sure to add additional documentation around this.

**Comment by haywirez** [comment]
> Again, do _not_ use `async () => ...` as a `src`.

Had a similar error since a few days, started after a `^4.8.0` and typescript `3.8.3` update. I was surprised to learn this, my code had a lot of async fn services before, and somehow everything was fine 🤔 

Refactoring to callback-hell style functions fixed the compiler error (but also not the root cause yet 😄...)

But is theoretically possible to make it work with async functions in the future? Is there any reason the types don't pan out that way?

**Comment by davidkpiano** [comment]
@haywirez It is possible... it's just that the return value is expected to be a cleanup function, and not a Promise. But you can open a new issue to track this.
