### ISSUE TITLE
Warning when spawning actor within an assign action

### ISSUE THREAD

**Issue by Blacktiger** [davidkpiano/xstate#991]
**Description**
When spawning an actor within an assign action, I'm getting a warning about attempting to spawn an actor outside of a service.

**Expected Result**
No warning printed.

**Actual Result**
"Warning: Attempted to spawn an Actor (ID: "(machine)") outside of a service. This will have no effect."

**Reproduction**
https://codesandbox.io/s/tender-leavitt-mv9le

**Comment by davidkpiano** [comment]
How are you spawning this?

Also, this will be solved more holistically in V5.

**Comment by Blacktiger** [comment]
I've tried a few different methods, but the failing case is using this:
```
function spawnFieldMachine(name, validators) {
  return spawn(
    FieldMachine.withContext({
      name: name,
      pristineValue: "",
      currentValue: "",
      validators: validators
    }),
    { name, sync: true }
  );
}
//...
      assign(() => {
        return {
          field: spawnFieldMachine("field", {
            isRequired: ({ currentValue }) => !!currentValue
          })
        };
      })
```

I can of course pull the spawn call outside of the helper function and into the assign action directly but that doesn't remove the warning.

**Comment by CodingDive** [comment]
Try this

```javascript
assign(
  {
     field: (/* you were missing this callback*/ ) => spawnFieldMachine("field", {
       isRequired: ({ currentValue }) => !!currentValue
      })
  }
)

**Comment by Blacktiger** [comment]
@CodingDive https://codesandbox.io/s/awesome-rhodes-c42u9  uses your suggested syntax but it also throws the warnings.

**Comment by davidkpiano** [comment]
This is solved in V5. Is it making your code not work?

**Comment by Blacktiger** [comment]
I think the code might be working correctly. If so I should be ok to just ignore it for now. I was mainly just prototyping different ways to work with forms in my system to try to come up with an easy way to share as much code as possible between them as I have quite a few different configuration forms in my application.

**Comment by davidkpiano** [comment]
Don't worry about the warning; it can be ignored for now.

**Comment by Andarist** [comment]
@Blacktiger your latest sandbox is not working properly, because it's using an older version of XState - if you upgrade it to the latest one then it works as expected and you receive no warnings of this kind. 

There is another warning related to `sync` option though. It might be that your child actor gets actually spawned when reading `.initialState`, which would definitely be not a good thing. A further investigation has to be done though to check if that's true.

**Comment by Blacktiger** [comment]
Correct, with this setup I'd need to skip most of the component's logic during the initial state. I don't really see any other way to handle it though unless I want to spawn the field machines outside the form machine and inject them as initial context.

**Comment by Andarist** [comment]
I believe that ideally, you should be able to do exactly what you do and there is a small problem on our side, which we need to figure out.

**Comment by Blacktiger** [comment]
Nice catch, if I just update to xstate 4.7.8 it appears that the warning is fixed. In that case this issue can be closed.
