### ISSUE TITLE
Visualizer crashes with `assign({ foo: null, bar: undefined })`

### ISSUE THREAD

**Issue by simonflk** [davidkpiano/xstate#997]
**Description**

`assign()` accepts an `object` whose values are either plain values or functions that return new values. Visualizer is ok with plain values as long they are not `null` or `undefined`

**Expected Result**

Visualizer should not crash

**Actual Result**

Visualizer crashes with one of these errors:
```
TypeError: Cannot read property 'toString' of null
    at StateChartAction.js:75
```
or 
```
TypeError: Cannot read property 'toString' of undefined
    at StateChartAction.js:75
```

**Reproduction**
```
  const fetchMachine = Machine({
    id: 'fetch',
    initial: 'idle',
    context: {
      retries: 0
    },
    states: {
      idle: {
        on: {
          FETCH: { target: 'success', actions: assign({ foo: null }) }
        }
      },
      success: {
        type: 'final'
      },
    }
  });
```

**Comment by davidkpiano** [comment]
Closing this in favor of using [the inspector](https://xstate.js.org/docs/packages/xstate-inspect) instead.
