### ISSUE TITLE
onDone is not fired anymore for parent nodes starting from 4.7.1

### ISSUE THREAD

**Issue by pandomic** [davidkpiano/xstate#999]
**Description**
Starting from `4.7.1` `onDone` is not fired for the parent node. This happens for transitions and actions (in the example below you may find two versions).

**Expected Result**
When reaching a final state, `onDone` should be triggered for the parent node.

From the example below, the output should include either `ENTERING "WORLD", DONE` or `ENTERING WORLD, ENTERING "LITTLE"` depending on the `onDone` version.

**Actual Result**
After reaching a final state `onDone` is ignored.

From the example below, the output only includes either `ENTERING "WORLD"` ignoring `onDone`.

**Reproduction**
- https://repl.it/@VladGramuzov2/TestXstate
- https://codesandbox.io/s/inspiring-dhawan-6ygom

**Additional context**
That worked in `4.7.0` and doesn't in XState >= `4.7.1`

**Comment by davidkpiano** [comment]
This is expected and specced behavior:

> When the state machine reaches the <final> child of an <scxml> element, it must terminate.
> 
> https://www.w3.org/TR/scxml/#final

In this case, the machine is that top-level `<scxml>` element. When a machine reaches its final state, it is terminated (hence "final").

You probably didn't mean to use `type: 'final'` here.
